[documentation]: Getting started
Vonage/vivid-3 pull request #1007
Opened 2023-02-06 10:37 UTC by rachelbt

as we talked about:
![image](https://user-images.githubusercontent.com/7512792/216950221-a22f2976-77bc-47da-8c6d-695e7c14a875.png)

for mirroring content we can open a separate issue

2023-02-06 13:11 UTC, yinonov requested changes

2023-02-06 13:11 UTC, yinonov commented on libs/components/README.md
> +### Local Installation
```suggestion
### Installation
```

2023-02-06 13:11 UTC, yinonov commented on libs/components/README.md
> +### CDN - Quickstart
this is, really, a side note as it introduces nothing new in terms of Vivid. it can be practiced with any library. in the diagram it is extracted to "advanced" and is optional. but even there I'd say it's redundant

2023-02-06 13:11 UTC, yinonov commented on libs/components/README.md
>  For a full list of components and API, explore the [components docs](https://vivid.deno.dev/components/accordion/) 📚.
```suggestion
For a full list of components and API, explore the [components docs](https://vivid.deno.dev) 📚.
```

2023-02-06 13:15 UTC, yinonov requested changes

2023-02-06 13:15 UTC, yinonov commented on docs/starting/extra-features.md
> +```
there are so many ways to include assets. let's avoid this tutoring by a generic guidance

https://github.com/oddbird/popover-polyfill/blob/4d711dba644d3dff6fd2535e029922b7fafc96f9/README.md?plain=1#L29-L33

2023-02-06 13:20 UTC, yinonov requested changes
look for _"We publish a next release on every successful merge to main, so you never need to wait for a new stable version to make use of any updates"_. it is no longer a valid statement

2023-02-06 13:20 UTC, yinonov commented on libs/components/README.md
> +#### Vonage users:
```suggestion
#### Vonage authors:
```

2023-02-06 13:23 UTC, yinonov requested changes

2023-02-06 13:23 UTC, yinonov commented on libs/components/README.md
> +- Core styles
```suggestion
```

2023-02-06 13:23 UTC, yinonov commented on libs/components/README.md
> +For further information check our [docs : Advanced Usage](link)
```suggestion
For further information on **core application styles** & **scoped elements** check out [advanced usage](link)
```

2023-02-06 13:25 UTC, yinonov requested changes

2023-02-06 13:25 UTC, yinonov commented on libs/components/README.md
> +#### Vonage users:
this section should be extracted to the vonage authors page. simply reference vonage authors to it from here

2023-02-06 14:20 UTC, rachelbt commented on libs/components/README.md
> +### CDN - Quickstart
I followed the pattern in shoelace and other libraries. 
maybe we should put it at the end as it was.

2023-02-06 14:22 UTC, rachelbt commented on docs/starting/extra-features.md
> +```
I agree there are a lot - but I find it so much helpful and these are the common. 
If one want to do it differently that he can

2023-02-06 16:00 UTC, yinonov commented on libs/components/README.md
> +### CDN - Quickstart
I don't see a reason to add documentation on industry best (or opinionated) practices

2023-02-06 16:38 UTC, rachelbt commented on libs/components/README.md
> +#### Vonage users:
not sure I understand. This is what I did.
Under the headline comes this line:

> For further information check our [docs : Advanced Usage](https://vivid-s12dtrwn7950.deno.dev/link)

2023-02-08 12:09 UTC, YonatanKra requested changes
`What's on our plate` is quite unclear. Maybe we should write it like:

`Want to see our sprint plan? Here's what's on our plate`

2023-02-08 12:09 UTC, YonatanKra commented on libs/components/README.md
> +#### include the tokens
```suggestion
#### Include the tokens
```

2023-02-08 12:09 UTC, YonatanKra commented on libs/components/README.md
> +### Tokens
Maybe we should defer the explanation to after the "quick start" instructions?
I mean - most people don't really care about reading a book - they just want to know what they need to import.

2023-02-08 12:09 UTC, YonatanKra commented on libs/components/README.md
> +Require a `vvd-root` class selector to be present on a wrapping element (advisably the `:root`).
```suggestion
The `vivid` styles require a `vvd-root` class selector to be present on a wrapping element (advisably the `:root`).
```
In addition, what does `:root` mean?

2023-02-08 12:13 UTC, YonatanKra commented on docs/starting/extra-features.md
> +When set on the `:root` (html element), typeface sizes are able to descend from the root font-size, thus comply with the [WCAG 1.4.4](https://www.w3.org/WAI/WCAG21/Understanding/resize-text)).
I do not understand this whole paragraph.
`vvd-root` is not extra - it is already mentioned in the core docs.
Is mentioning that setting the class not on `html` might cause an a11y issue?

2023-02-08 12:20 UTC, YonatanKra commented on docs/starting/extra-features.md
> +Custom elements, by browsers limitations, are registered globally, and thus may conflict when multiple versions of the library are used in the same application as all custom elements register under t
```suggestion
Custom elements are registered globally by the browser. When two custom elements with the same tag name are registered on the same document, it creates a conflict that results in an error. Loading multiple versions of `vivid` is likely to cause this error as vivid elements are named the same.
```
We should try to avoid long sentences.

2023-02-08 12:24 UTC, YonatanKra commented on docs/starting/extra-features.md
> +Even though custom elements can be registered under different namespaces, as many as needed, this approach lets you enjoy the benefits of [npm dedupe](https://docs.npmjs.com/cli/v8/commands/npm-dedup
```suggestion
In addition to avoiding namespace collision and customizing elements' tag names, this approach lets you enjoy the benefits of [npm dedupe](https://docs.npmjs.com/cli/v8/commands/npm-dedupe). With [npm dedupe](https://docs.npmjs.com/cli/v8/commands/npm-dedupe), only the least needed versions of the library are used in the application.
```
Not sure about the change but I think my text is clearer. In any event, `Even though` does not fit here because it is not something that happens `despite` - it happens in `addition`.

2023-02-08 13:11 UTC, rachelbt commented on docs/starting/extra-features.md
> +Even though custom elements can be registered under different namespaces, as many as needed, this approach lets you enjoy the benefits of [npm dedupe](https://docs.npmjs.com/cli/v8/commands/npm-dedup
It was on the homepage - I only cut-past from there to here :)

2023-02-08 13:12 UTC, rachelbt commented on libs/components/README.md
> +### Tokens
The quick start was here... @yinonov asked to move it further down.

2023-02-08 16:27 UTC, yinonov requested changes

2023-02-08 16:27 UTC, yinonov commented on libs/components/README.md
>  npm install @vonage/vivid # or yarn add @vonage/vivid
```suggestion
npm install @vonage/vivid
```

2023-02-09 11:06 UTC, yinonov requested changes

2023-02-09 11:06 UTC, yinonov commented on libs/components/README.md
> +```
I still think this is wrong. the previous section explicitly state

> As the task of loading css is not trivial, and may vary from project to project, this library does not provide any way to load the css. It is up to the author to load the css in the most appropriate manner for their project.

sharing opinions can only backfire if authors follow one of the suggestions and fail

2023-02-09 11:09 UTC, yinonov requested changes

2023-02-09 11:09 UTC, yinonov commented on libs/components/README.md
> +The `vivid` styles require a `vvd-root` class selector to be present on a wrapping element (advisably the `:root`).
```suggestion
The Vivid tokens require a `vvd-root` class selector to be present on a wrapping element (advisably the `:root`) for it to apply its css custom properties to.
```

2023-02-09 11:13 UTC, yinonov requested changes

2023-02-09 11:13 UTC, yinonov commented on libs/components/README.md
>  ## Support
```suggestion
## Support Matrix

This library is supported on 2 recent versions of major browsers (Chrome, Firefox, Safari, Edge).

## Support
```

2023-02-09 11:18 UTC, yinonov requested changes

2023-02-09 11:18 UTC, yinonov commented on apps/docs/_data/extra.json
> +    "title": "extra-features",
```suggestion
    "title": "Advanced",
```

2023-02-09 11:18 UTC, yinonov commented on apps/docs/_data/extra.json
> +    "markdown": "./docs/starting/extra-features.md",
```suggestion
    "markdown": "./docs/starting/advanced.md",
```

2023-02-09 11:18 UTC, yinonov commented on apps/docs/_data/extra.json
> +		"markdown": "./docs/starting/vonage-users.md",
```suggestion
		"title": "vonage-authors",
		"markdown": "./docs/starting/vonage-authors.md",
```

2023-02-09 11:18 UTC, yinonov commented on apps/docs/_includes/navigation.njk
> +    </vwc-nav-disclosure>
these are just simple docs, the might not need all the components conditions at this point. use same approach as _Design System_

2023-02-09 11:18 UTC, yinonov commented on docs/starting/extra-features.md
> +# Extra Features
rename file and heading to _Advanced_

2023-02-09 11:18 UTC, yinonov commented on docs/starting/vonage-users.md
> +# Vonage Users
rename file and heading to Vonage Authors

2023-02-09 12:05 UTC, YonatanKra commented on libs/components/README.md
> +### Tokens
I know how important explanations are but to 95% of devs it doesn't matter. 
@yinonov?

2023-02-12 09:37 UTC, rachelbt commented on apps/docs/_includes/navigation.njk
> +    </vwc-nav-disclosure>
they *are* like the design system category :)

2023-02-12 10:41 UTC, rachelbt commented on apps/docs/_includes/navigation.njk
> +    </vwc-nav-disclosure>
removed from both :)

2023-02-13 16:32 UTC, yinonov requested changes

2023-02-13 16:32 UTC, yinonov commented on libs/components/README.md
> +Vivid uses `Montserrat` and `Roboto Mono` Google fonts.
```suggestion
Vivid uses `Montserrat` and `Roboto Mono` Google fonts.
```

2023-02-13 16:32 UTC, yinonov commented on libs/components/README.md
> +Unless explicitly stated otherwise, *Vonage products* should use the brand specified `Spezia` font families.
```suggestion
Unless explicitly stated otherwise, *Vonage* products should use the brand specified font families by `Spezia`.  
```

2023-02-13 16:37 UTC, yinonov requested changes

2023-02-13 16:37 UTC, yinonov commented on docs/starting/advanced.md
> +## Core (Optional)
```suggestion
## Styles (Optional)
```

2023-02-14 07:52 UTC, rachelbt commented on libs/components/README.md
> +### Tokens
not sure I understand what to put where :)

2023-02-14 07:52 UTC, rachelbt commented on libs/components/README.md
> +```
then I'll revert to what was before

2023-02-14 20:53 UTC, yinonov commented on libs/components/README.md
> +Require a `vvd-root` class selector to be present on a wrapping element (advisably the `:root`).
The :root [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) [pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) matches the root element of a tree representing the document. In HTML, :root represents the [<html>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html) element and is identical to the selector html, except that its [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) is higher.

2023-02-14 20:54 UTC, yinonov commented on libs/components/README.md
> +Require a `vvd-root` class selector to be present on a wrapping element (advisably the `:root`).
@rachelbt if you think we should link to root's explanation then use the following
https://developer.mozilla.org/en-US/docs/Web/CSS/:root

2023-02-15 11:34 UTC, yinonov requested changes

2023-02-15 11:34 UTC, yinonov commented on docs/getting-started/advanced.md
> +### vivid class
```suggestion
### Setting Vivid class
```

2023-02-15 11:34 UTC, yinonov commented on docs/getting-started/advanced.md
> +*require* a `vvd-root` class* selector to be present on a wrapping element (advisably the `:root`.
now this is an extension. add something like
```suggestion
"[As in tokens](/README.md), styles *require* a `vvd-root` class* selector to be present on a wrapping element (advisably the `:root`.  
```

2023-02-15 11:38 UTC, yinonov requested changes

2023-02-15 11:38 UTC, yinonov commented on docs/getting-started/advanced.md
> +```
sorry to return to this again but what's the verdict?
now that this is added the docs reflect an inconsistent approach.
in tokens it says

> As the task of loading css is not trivial, and may vary from project to project, this library does not provide any way to load the css. It is up to the author to load the css in the most appropriate manner for their project.

but here we provide ways to load the css in opposed to what is stated in tokens

2023-02-15 18:46 UTC, rachelbt commented on docs/getting-started/advanced.md
> +```
I'll change it

2023-02-15 20:15 UTC, yinonov approved these changes
excellent work. this will absolutely return dividends

2023-02-16 06:29 UTC, merged