chore: arrange 11ty in folders
Vonage/vivid-3 pull request #101
Opened 2022-01-03 13:44 UTC by YonatanKra

2022-01-03 16:59 UTC, yinonov requested changes
remove __site_ from `.gitignore`

2022-01-03 16:59 UTC, yinonov commented on .github/workflows/_gh-pages.yml
> +          publish_dir: ./dist/vvd-docs
this was really hard working against as the job deleting the _dist_ kept messing with ongoing development

2022-01-03 16:59 UTC, yinonov commented on apps/vvd-docs/.eleventy.js
> +    "vivid-logo.svg": "assets/images/vivid-logo.svg",
typo?
```suggestion
    "assets/images/vivid-logo.svg": "assets/images/vivid-logo.svg",
```

2022-01-03 16:59 UTC, yinonov commented on apps/vvd-docs/.eleventy.js
> +    [ASSETS_DIR]: "assets"
ASSETS_DIR = 11ty's reserved name? what is this referencing?

2022-01-03 16:59 UTC, yinonov commented on apps/vvd-docs/.eleventy.js
> +  eleventyConfig.addWatchTarget(`${INPUT_DIR}/assets`);
INPUT_DIR = 11ty's reserved name? what is this referencing?

2022-01-03 16:59 UTC, yinonov commented on package.json
> +    "docs:serve": "eleventy --config=./apps/vvd-docs/.eleventy.js --serve",
is this prep for monorepo?

2022-01-03 18:09 UTC, YonatanKra commented on .github/workflows/_gh-pages.yml
> +          publish_dir: ./dist/vvd-docs
Will be taken care of in the next phase I guess
The components will have their own folder and not the whole `dist` folder.

2022-01-03 18:12 UTC, YonatanKra commented on apps/vvd-docs/.eleventy.js
> +    "vivid-logo.svg": "assets/images/vivid-logo.svg",
I'm actually taking the logo from the main folder.  Do we want a `single source of truth` for this logo?

2022-01-03 18:12 UTC, YonatanKra commented on apps/vvd-docs/.eleventy.js
> +    [ASSETS_DIR]: "assets"
It's a const from the top of the file. A magic string :)

2022-01-03 18:14 UTC, YonatanKra commented on package.json
> +    "docs:serve": "eleventy --config=./apps/vvd-docs/.eleventy.js --serve",
You might say that. Currently it's more ordering what needs ordering.
Dist will hold all of our artifacts.
Apps will hold the demo apps (or later on if we have more - for instance, angular/react/vue integrations examples we'd like to make public).
Libs will hold anything "reusable" or "publishable".

2022-01-03 19:22 UTC, yinonov commented on .github/workflows/_gh-pages.yml
> +          publish_dir: ./dist/vvd-docs
I think that was intended but we kept the _site for that interim so that we keep working on site improvements without breaking our heads.
restoring monorepo is on our plan and I've even fiddled with it on #93
Can we postpone that change?

2022-01-03 19:23 UTC, yinonov commented on apps/vvd-docs/.eleventy.js
> +    "vivid-logo.svg": "assets/images/vivid-logo.svg",
_always bet on SSOT_ 🤓

2022-01-03 19:25 UTC, yinonov commented on package.json
> +    "docs:serve": "eleventy --config=./apps/vvd-docs/.eleventy.js --serve",
should we put all our _dot files_ in a _dot files_ folder maybe?

2022-01-04 15:53 UTC, yinonov approved these changes

2022-01-04 16:04 UTC, merged