fix(documentation): repeated icon note
Vonage/vivid-3 pull request #1027
Opened 2023-02-13 11:23 UTC by olaf-k

there's an a11y for using only an icon in several components, this PR replaces them with a small include.
+ it has been added to `accordion-item` and the `option`.
+ it corrects the `badge` note (which was truncated) and the card one (which was wrong).
+ it removes the "Icon only" paragraph of `nav-disclosure` for consistency (we don't do it for other widgets).

2023-02-13 13:39 UTC, rachelbt commented on apps/docs/_includes/icon-note.md
> +Note: An icon on its own doesn't make a discernible text. An `aria-label`, `aria-labelledby` or `title` must be provided to ensure that the user can understand the component's purpose.
When the icon is followed by with text and has no real need for screen readers than authors should add `aria-hidden="true"`

2023-02-13 13:41 UTC, rachelbt reviewed
nice docs maintaining touch-up!
How come there are new snapshots for the nav-discloser? seems not relevant to this PR...

2023-02-13 14:20 UTC, olaf-k commented on apps/docs/_includes/icon-note.md
> +Note: An icon on its own doesn't make a discernible text. An `aria-label`, `aria-labelledby` or `title` must be provided to ensure that the user can understand the component's purpose.
true, but that's valid for every bit of text in an app, not just when using an icon.

2023-02-13 14:22 UTC, olaf-k commented
> nice docs maintaining touch-up! How come there are new snapshots for the nav-discloser? seems not relevant to this PR...

you're right, this should have been a doc only PR. but since I updated the `nav-disclosure` doc to *remove* a paragraph, it shows in the ui tests!

2023-02-14 08:27 UTC, rachelbt commented on apps/docs/_includes/icon-note.md
> +Note: An icon on its own doesn't make a discernible text. An `aria-label`, `aria-labelledby` or `title` must be provided to ensure that the user can understand the component's purpose.
not sure I understand..

2023-02-14 08:29 UTC, rachelbt commented
> > nice docs maintaining touch-up! How come there are new snapshots for the nav-discloser? seems not relevant to this PR...
> 
> you're right, this should have been a doc only PR. but since I updated the `nav-disclosure` doc to _remove_ a paragraph, it shows in the ui tests!

why did you removed it? don't we have an icon-only option?

2023-02-14 08:41 UTC, olaf-k commented
> why did you removed it? don't we have an icon-only option?

this was the `nav-disclosure` comment for the paragraph I removed:
![image](https://user-images.githubusercontent.com/1153034/218682630-2860acde-8070-4481-ad2e-ab18bcf69478.png)
as I wrote, I did it for consistency purposes: there are other widgets that allow authors to inject an icon while not providing text/label (accordion-item, badge, button, etc.) and we don't provide a specific example for them.

2023-02-14 09:13 UTC, yinonov commented on apps/docs/_includes/icon-note.md
> +Note: An icon on its own doesn't make a discernible text. An `aria-label`, `aria-labelledby` or `title` must be provided to ensure that the user can understand the component's purpose.
For SVG, If no explicit role/aria set, it's hidden by default. Is it not?

2023-02-14 09:18 UTC, yinonov commented
> Is this supported in GH markdowns?

No
![image](https://user-images.githubusercontent.com/15140652/218692101-aeaab413-0e52-44b2-a913-9cd3fd43a6d4.jpeg)

2023-02-14 12:04 UTC, rachelbt commented on apps/docs/_includes/icon-note.md
> +Note: An icon on its own doesn't make a discernible text. An `aria-label`, `aria-labelledby` or `title` must be provided to ensure that the user can understand the component's purpose.
no.....

2023-02-14 14:29 UTC, yinonov commented
> > > Is this supported in GH markdowns?
> 
> > 
> 
> > No 
> 
> 
> 
> of course, that's nunjucks syntax, markdown is not a templating language. is that a dealbreaker? do you expect users to read the doc on GH?
> 
> 

Yes. Otherwise we would have wrote directly in 11ty templates

2023-02-14 15:33 UTC, olaf-k commented
> Yes. Otherwise we would have wrote directly in 11ty templates

that's (partly) the point of this PR: we have repeating information and a templating engine, why not take advantage of it?

2023-02-14 15:55 UTC, yinonov commented on apps/docs/_includes/icon-note.md
> +Note: An icon on its own doesn't make a discernible text. An `aria-label`, `aria-labelledby` or `title` must be provided to ensure that the user can understand the component's purpose.
> When the icon is followed by with text and has no real need for screen readers than authors should add `aria-hidden="true"`

the sentence starts with _"An icon on its own..."_

2023-02-14 16:01 UTC, yinonov commented
> > Yes. Otherwise we would have wrote directly in 11ty templates
> 
> that's (partly) the point of this PR: we have repeating information and a templating engine, why not take advantage of it?

because you lose documentation in GitHub. the closest you can get to mirroring content in GH is via permalinks. where in 11ty this type of url should be intercepted and replaced with the actual mirrored content. but that windowed content can still be somewhat confusing

https://github.com/Vonage/vivid-3/blob/ec2e81920b18d39d982492f76856390bf4fb0be0/docs/design/design-tokens.md?plain=1#L6-L12

2023-02-15 08:27 UTC, olaf-k commented
![tigger-sad](https://user-images.githubusercontent.com/1153034/218973138-d3c11682-5dd1-419f-8455-b92c97b29d76.gif)

2023-02-15 10:18 UTC, olaf-k commented
include reverted and replaced by copy/paste, first post updated.

2023-02-15 12:13 UTC, yinonov requested changes
this caveat would make more sense when the documentation flow in this order

1. text / label section
2. icon section (showing icon only without text / label). in the icon section it makes sense to explain about the caveat sense it's a real case
3. icon with text / label

also bear in mind to apply those same rules in the code snippet

2023-03-22 14:39 UTC, closed without merging