chore(option): add value example
Vonage/vivid-3 pull request #1045
Opened 2023-02-28 11:08 UTC by rinaok

2023-02-28 14:25 UTC, olaf-k commented
ok, documenting `value` is a good initiative indeed, but for the sake of consistency I'd have 2 comments:
1. only add one example with `value`, as we do in other pages (1 attribute <-> 1 example), not in all of them.
2. extend the PR to make sure all form elements are covered (I'm thinking `checkbox` and `radio`; `switch` already has an entry, maybe I'm missing others?)

2023-02-28 15:45 UTC, rinaok commented
> ok, documenting `value` is a good initiative indeed, but for the sake of consistency I'd have 2 comments:
> 
> 1. only add one example with `value`, as we do in other pages (1 attribute <-> 1 example), not in all of them.
> 2. extend the PR to make sure all form elements are covered (I'm thinking `checkbox` and `radio`; `switch` already has an entry, maybe I'm missing others?)

@olaf-k done

2023-02-28 16:58 UTC, olaf-k commented
> @olaf-k done

you missed the `slider`, it was a test 
![SasEvilGIF](https://user-images.githubusercontent.com/1153034/221923546-e41a7d2f-9333-4503-85ab-343b307f5fa0.gif)

2023-03-01 09:43 UTC, olaf-k reviewed
👍

2023-03-01 09:44 UTC, olaf-k approved these changes

2023-03-01 09:45 UTC, olaf-k requested changes

2023-03-01 09:45 UTC, olaf-k commented on libs/components/src/lib/slider/README.md
> +```
```suggestion
Use `value` in order to set the value of the slider.

- Type: `string`
- Default: `on`

```html
<vwc-slider value="5"></vwc-slider>
```
```

2023-03-01 10:48 UTC, olaf-k requested changes

2023-03-01 10:48 UTC, olaf-k commented on libs/components/src/lib/slider/README.md
> +- Default: `on`
```suggestion
- Default: `5`
```
(missed that earlier)

2023-03-01 13:00 UTC, olaf-k approved these changes

2023-03-01 15:13 UTC, merged