feat(select): add label handling to option component
Vonage/vivid-3 pull request #1047
Opened 2023-02-28 16:03 UTC by YonatanKra

Opened an issue for the missing feature in fast: https://github.com/microsoft/fast/issues/6651

2023-02-28 16:55 UTC, olaf-k requested changes

2023-03-01 08:00 UTC, YonatanKra commented on libs/components/src/lib/select/select.spec.ts
> +	});
Acutally it does not. I did not touch the option. You can use a `div` and it'll work.

2023-03-01 08:05 UTC, YonatanKra commented on libs/components/src/lib/select/select.ts
> +	}
I'm afraid `label` is not documented (a.k.a. not tested) on the `option` component.

Even in `fast`, they do not describe what it does.

I've raised the bug on their end.

That's a good point - because `label` should just reflect `label` in `option`.

2023-03-01 08:34 UTC, olaf-k commented on libs/components/src/lib/select/select.spec.ts
> +	});
it shouldn't. `label` is not a global attribute, but it is an `option` attribute.
also, it is literally an `option` attribute in your code and the sample.

2023-03-01 08:35 UTC, olaf-k commented on libs/components/src/lib/select/select.ts
> +	}
why?
<img width="576" alt="image" src="https://user-images.githubusercontent.com/1153034/222086490-a88dca26-153f-48e5-9495-3ecfa8965ca9.png">

2023-03-01 09:40 UTC, olaf-k commented on libs/components/src/lib/option/option.ts
> +		return this.getAttribute('label') ?? this.value;
https://github.com/Vonage/vivid-3/pull/1047#discussion_r1121345926
(FAST's code as you reported it seems all right)

2023-03-01 09:53 UTC, YonatanKra commented on libs/components/src/lib/select/select.ts
> +	}
Where do you see that?

Oh - you are looking at Fast@next, right?

Cause it doesn't exist in our Fast version...

2023-03-01 09:57 UTC, YonatanKra commented on libs/components/src/lib/option/option.ts
> +		return this.getAttribute('label') ?? this.value;
The fact is it doesn't work :) 
Looking at their code shows they do not take the `label` attribute but the `value` only.

2023-03-01 13:19 UTC, YonatanKra commented on libs/components/src/lib/select/select.ts
> +	}
Oh - so I meant `fast` which we are extending.

I believe it is a bug on their end and the issue mentioned in the PR's description relates to that.

This is fixed in this PR for `vivid`.

2023-03-01 13:24 UTC, olaf-k commented on libs/components/src/lib/select/select.ts
> +	}
yeah my bad, I read `this.label` instead of `this.label` 🤦‍♂️

2023-03-01 14:32 UTC, olaf-k commented on libs/components/src/lib/option/README.md
> +Note that you cannot set `label` programmatically like this: `option.label = 'new label'`. You can only set it via the attribute.
sorry to be a PITA but this is still bothering me. why this limitation? FAST code?

2023-03-01 14:49 UTC, yinonov submitted a review, later dismissed

2023-03-01 14:49 UTC, yinonov commented on libs/components/src/lib/option/README.md
> +`label` will return the the `label` attribute's value. If not set, it will revert to the `text`.
```suggestion
`label` will return the `label` attribute's value. If not set, it will revert to the `text`.
```

2023-03-01 14:52 UTC, yinonov commented
See https://github.com/microsoft/fast/issues/6642

2023-03-01 15:25 UTC, olaf-k commented
> See [microsoft/fast#6642](https://github.com/microsoft/fast/issues/6642)

the main difference being that we don't use the default slot content but the `text` attribute, so we should have more flexibility, right?

2023-03-02 08:09 UTC, YonatanKra commented
> See [microsoft/fast#6642](https://github.com/microsoft/fast/issues/6642)

I saw it. It is not the same issue. Looks similar, but you are looking at an external label element. 

The label property/attribute is not according to the HTML spec.

2023-03-02 08:11 UTC, YonatanKra commented on libs/components/src/lib/option/README.md
> +Note that you cannot set `label` programmatically like this: `option.label = 'new label'`. You can only set it via the attribute.
Yes it is indeed.
Do we want to fix this too?

2023-03-03 16:18 UTC, olaf-k requested changes

2023-03-06 10:01 UTC, olaf-k approved these changes
👍

2023-03-08 09:05 UTC, merged