chore(button): migrate to vivid next
Vonage/vivid-3 pull request #107
Opened 2022-01-06 06:32 UTC by yinonov

2022-01-11 07:05 UTC, rachelbt commented on src/components/button/README.md
> +```
```suggestion
```## States
### Disabled
```html preview
<vwc-button label='ghost' appearance='ghost' disabled></vwc-button>
<vwc-button label='filled' appearance='filled' disabled></vwc-button>
<vwc-button label='outlined' appearance='outlined' disabled></vwc-button>
```
```

2022-01-11 07:05 UTC, rachelbt commented on src/components/button/button.template.ts
> +	[`size-${size}`, Boolean(size)],
disabled class is needed and style as well :)

2022-01-11 07:50 UTC, yinonov commented
@jshenkman should we support loading "state"?

2022-01-11 10:54 UTC, yinonov commented
@jshenkman are `tonal` buttons in consideration? should they replace `ghost`? maybe `tonal` only apply in **toggle-buttons**?

2022-01-11 13:27 UTC, yinonov commented
tests fail when running both _badge_ and _button_.
tests pass when removing `badge.spec.ts`.
@YonatanKra anything u can think of?

2022-01-13 07:14 UTC, yinonov commented
@jshenkman FYI
meetings sign in button loading state

https://user-images.githubusercontent.com/15140652/149282886-2526ff80-1816-4f92-aa4d-df8f450e3d21.mov

2022-01-16 13:09 UTC, YonatanKra commented on src/components/button/button.spec.ts
> +			expect(control).toBeInstanceOf(Element);
What does this test mean?

2022-01-16 13:11 UTC, YonatanKra commented on src/components/button/button.spec.ts
> +			const control = element.shadowRoot.querySelector('.control.icon-only');
What's the other alternative? If I don't set an icon, what happens then?

2022-01-16 13:12 UTC, YonatanKra commented on src/components/button/button.ts
> +	/**
As a side note - these comments in the code are driving me nuts!

2022-01-16 13:15 UTC, YonatanKra requested changes
See the comments

2022-01-16 13:49 UTC, yinonov commented on src/components/button/button.spec.ts
> +			const control = element.shadowRoot.querySelector('.control.icon-only');
it won't set `icon-only` class on `control`

2022-01-16 13:49 UTC, yinonov commented on src/components/button/button.ts
> +	/**
JSDoc / TSDoc?

2022-01-16 14:02 UTC, YonatanKra commented on src/components/button/button.ts
> +	/**
I know - I don't like them :)
Not critical. Just leaving on the table :)

2022-01-16 14:05 UTC, YonatanKra commented on src/components/button/button.spec.ts
> +			const control = element.shadowRoot.querySelector('.control.icon-only');
Might need to check before and after.

2022-01-16 14:14 UTC, YonatanKra commented on src/components/button/button.spec.ts
> +			const control = element.shadowRoot.querySelector('.control.icon-only');
```
const hasIconOnlyBefore = checkIconOnly(element);
element.icon = 'home';
await elementUpdated(element);
const hasIconOnlyAfter = checkIconOnly(element);
expect(hasIconOnlyBefore).toEqual(false);
expect(hasIconOnlyAfter).toEqual(true);
```

2022-01-16 15:58 UTC, yinonov commented on src/components/button/button.spec.ts
> +			expect(control).toBeInstanceOf(Element);
don't we prefer repeat the same structure?
won't it be incoherent to have unique naming for each test?
it's the same pattern

2022-01-16 16:17 UTC, yinonov commented on src/components/button/button.ts
> +	/**
"this is all over the town"

2022-01-18 12:40 UTC, yinonov commented
icon figure element does not respond well to
```css
display: flex;
width: 1em;
height: 1em;
```
in safari, flex doesn’t set the flow to be blocked (in opposed to chrome / firefox)
it results in a “non-sized” element

if set to **block** instead of **flex**, the `<figure>` element is, again!, not vertically aligned to exact middle

![image](https://user-images.githubusercontent.com/15140652/149939026-6031aa3e-b70d-43fb-b09b-b7d1c05322ce.png)

2022-01-18 18:27 UTC, YonatanKra approved these changes

2022-01-18 18:28 UTC, merged