feat(avatar): duotone appearance and deprecate outline
Vonage/vivid-3 pull request #1074
Opened 2023-03-15 10:02 UTC by rachelbt

2023-03-15 16:11 UTC, olaf-k requested changes

2023-03-15 16:11 UTC, olaf-k commented on libs/components/src/lib/avatar/README.md
```suggestion
- Type: `'filled'` | `'duotone'` (`outlined` is deprecated since v3.4.0)
- Default: `'filled'`

```

2023-03-16 06:51 UTC, rachelbt commented on libs/components/src/lib/avatar/README.md
waiting for designers final say if we will keep it or make it deprecated.

2023-03-23 10:29 UTC, rachelbt commented on libs/components/src/lib/avatar/README.md
was decided to keep both outline + duotone

2023-03-23 11:40 UTC, olaf-k requested changes

2023-03-23 11:40 UTC, olaf-k commented on libs/components/src/lib/avatar/README.md
> +<vwc-avatar connotation="accent" appearance="outlined"></vwc-avatar>
```suggestion
<vwc-avatar connotation="accent" appearance="outlined"></vwc-avatar>
<vwc-avatar connotation="cta" appearance="outlined"></vwc-avatar>
```
<ocd>let's keep a consistent order</ocd>

2023-03-26 08:37 UTC, rachelbt commented on libs/components/src/lib/avatar/README.md
> +<vwc-avatar connotation="accent" appearance="outlined"></vwc-avatar>
you mean cdo ...
![image](https://user-images.githubusercontent.com/7512792/227764688-c96ca574-3913-4705-a399-11a95861458d.png)

2023-03-27 08:07 UTC, olaf-k approved these changes

2023-03-27 08:13 UTC, merged