feat(select): add icon
Vonage/vivid-3 pull request #1076
Opened 2023-03-19 11:36 UTC by rachelbt

2023-03-26 12:16 UTC, AyalaBu commented
@rachelbt 
Looks great!

2023-03-26 13:45 UTC, rinaok commented on libs/components/src/lib/select/README.md
> +  }
@rachelbt Why not with a custom property?

2023-03-26 19:02 UTC, rachelbt commented on libs/components/src/lib/select/README.md
> +  }
because there's no need - it is set on the host and effect all the rest.
We use css-variables when we want to infect a dipper element in the shadow-dom that the consumer can't get to.
There's no need for setting a width, but it can be uses to set as a narrow select or set as 100%

2023-03-27 07:59 UTC, rinaok submitted a review, later dismissed

2023-03-27 14:15 UTC, olaf-k requested changes

2023-03-28 13:35 UTC, olaf-k requested changes

2023-03-28 13:35 UTC, olaf-k commented on libs/components/src/lib/select/README.md
> +<vwc-select label="phone" icon="search-line">
```suggestion
<vwc-select label="choose one option" icon="search-line">
```

2023-03-28 13:35 UTC, olaf-k commented on libs/components/src/lib/select/README.md
> +### Select-width
```suggestion
### Width
```

2023-03-28 14:11 UTC, rachelbt commented on libs/components/src/lib/select/README.md
> +### CSS Variables - Select-height
but in our docs we point out if its css-variable...

2023-03-28 14:12 UTC, rachelbt commented on libs/components/src/lib/select/README.md
> +<vwc-select label="phone" icon="search-line">
```suggestion
<vwc-select label="country code" icon="search-line">
```

2023-03-28 14:49 UTC, olaf-k requested changes

2023-03-28 14:49 UTC, olaf-k commented on libs/components/src/lib/select/README.md
> +### CSS Variables - Select-height
I find
> Use `--select-height`

sufficiently clear, but we can drive the nail farther with

> Use the `--select-height` CSS variable

2023-03-28 14:49 UTC, olaf-k commented on libs/components/src/lib/select/README.md
> +<vwc-select label="country code" icon="search-line">
why not stick with "choose one option"? these options are not country codes + consistency.

2023-03-28 15:19 UTC, rachelbt commented on libs/components/src/lib/select/README.md
> +<vwc-select label="country code" icon="search-line">
because the label breaks when we set a width on the select :rolling_on_the_floor_laughing:

2023-03-28 15:21 UTC, rachelbt commented on libs/components/src/lib/select/README.md
> +### CSS Variables - Select-height
I want to stick to pointing out that this is a variable - how about  "height - CSS Variables"

2023-03-29 07:24 UTC, olaf-k approved these changes
👍

2023-03-29 07:32 UTC, merged