docs(components): VIV-952 Add `@slot` attribute to Vivid 3 components.
Vonage/vivid-3 pull request #1092
Opened 2023-03-31 12:45 UTC by acelletti

2023-03-31 13:34 UTC, RichardHelm approved these changes

2023-03-31 14:00 UTC, olaf-k commented on libs/components/src/lib/calendar/calendar.ts
> + * @slot day-6 - Assign elements to corresponding day column using this slot.
note (to self) the calendar template appears to also have a default slot, which is 1) not documented and 2) useless, to be investigated.

2023-03-31 14:52 UTC, olaf-k requested changes
missing:

- menu-item > lacks the undocumented `expand-collapse-indicator` (maybe undocumented on purpose? to be checked)
- popup > lacks `default` (underlying component but since elevation is documented...)

2023-03-31 14:52 UTC, olaf-k commented on libs/components/src/lib/calendar/calendar.ts
> + * @slot day-6 - Assign elements to corresponding day column using this slot.
there's also a default slot to embed calendar-event components.

2023-03-31 14:52 UTC, olaf-k commented on libs/components/src/lib/header/header.ts
> + * @slot - Default slot.
```suggestion
 * @slot - Default slot.
 * @slot action-items - Nodes assigned to action-items slot will be set at the end of the header.
 * @slot app-content - Content vertically aligned with header.
```

2023-03-31 14:52 UTC, olaf-k commented on libs/components/src/lib/tabs/tabs.ts
> + * @slot - Default slot.
not exactly. `tabs` will process children elements as long as they are slotted as `tab` and `tabpanel`.

2023-03-31 14:52 UTC, olaf-k commented on libs/components/src/lib/text-anchor/text-anchor.ts
> + * @slot - Default slot.
no such slot + underlying component

2023-03-31 15:07 UTC, acelletti commented on libs/components/src/lib/tabs/tabs.ts
> + * @slot - Default slot.
This is fine, but the default slot still needs declaring so it can be added in the wrappers.

2023-03-31 15:07 UTC, acelletti commented on libs/components/src/lib/calendar/calendar.ts
> + * @slot day-6 - Assign elements to corresponding day column using this slot.
Added.

2023-03-31 15:07 UTC, acelletti commented on libs/components/src/lib/header/header.ts
> + * @slot - Default slot.
Done.

2023-03-31 15:08 UTC, acelletti commented on libs/components/src/lib/text-anchor/text-anchor.ts
> + * @slot - Default slot.
I was looking at the underlying component https://www.fast.design/docs/components/anchor/ and it looks like this does provide a default slot.

2023-03-31 15:56 UTC, olaf-k commented on libs/components/src/lib/text-anchor/text-anchor.ts
> + * @slot - Default slot.
looking at the Fast components may be misleading as our templates use fewer slots and rely more on attributes.

2023-04-03 07:26 UTC, olaf-k commented on libs/components/src/lib/tabs/tabs.ts
> + * @slot - Default slot.
that's my point: there is no default slot, there are two named slots (`tab` and `tabpanel`).

2023-04-03 08:38 UTC, olaf-k approved these changes
The tabs TSDoc change is wrong and describes the wrapper's API rather than the Vivid component's. Approving on @acelletti 's request.

2023-04-03 08:41 UTC, merged