feat(accordion-item): add size condensed (VIV-883)
Vonage/vivid-3 pull request #1093
Opened 2023-04-02 08:43 UTC by rachelbt

2023-04-02 09:52 UTC, rinaok requested changes
@rachelbt Looks good :)
I know that it's not connected to your PR, but all the accordion-items examples should be inside an accordion, like in other components (tab, nav-item, option, tree-item)

2023-04-02 10:32 UTC, rachelbt commented
> @rachelbt Looks good :) I know that it's not connected to your PR, but all the accordion-items examples should be inside an accordion, like in other components (tab, nav-item, option, tree-item)

added :)

2023-04-02 10:51 UTC, rinaok commented on libs/components/src/lib/accordion-item/README.md
> +	<vwc-accordion>
```suggestion
<vwc-accordion>
```

2023-04-02 10:51 UTC, rinaok commented on libs/components/src/lib/accordion-item/README.md
> +</vwc-accordion>
```suggestion
<vwc-accordion>
	<vwc-accordion-item heading="normal accordion item" meta="meta-data" icon="chat-solid">
		Lorem Ipsum is simply dummy text of the printing and typesetting industry.
	</vwc-accordion-item>
		<vwc-accordion-item heading="condensed accordion item" size="condensed" meta="meta-data" icon="chat-solid">
		Lorem Ipsum is simply dummy text of the printing and typesetting industry.
	</vwc-accordion-item>
</vwc-accordion>
```

2023-04-02 11:26 UTC, rachelbt commented on libs/components/src/lib/accordion-item/README.md
> +</vwc-accordion>
I dont want them to be together because this is bad practice to use both dense and regular together.

2023-04-02 11:26 UTC, rachelbt commented on libs/components/src/lib/accordion-item/README.md
> +</vwc-accordion>
I dont want them to be together because this is bad practice to use both dense and regular together.

2023-04-02 11:28 UTC, rinaok approved these changes

2023-04-02 17:29 UTC, YonatanKra requested changes

2023-04-02 17:29 UTC, YonatanKra commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(accordionRegion).toBeInstanceOf(Element);
This needs to be revised

2023-04-03 13:27 UTC, YonatanKra approved these changes

2023-04-03 13:29 UTC, merged