feat(tag): migrate tag component (VIV-944)
Vonage/vivid-3 pull request #1100
Opened 2023-04-03 16:59 UTC by rinaok

2023-04-10 13:53 UTC, YonatanKra requested changes
Mostly test semantics :)

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +				.toBeInstanceOf(Element);
I'd expect this to be more explicit:
```suggestion
			const baseElementContainsConnotationClass = getBaseElement(element).classList.contains(`connotation-${connotation}`;
			expect(baseElementContainsConnotationClass)
				.toBeTruthy();
```

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +				.toBeInstanceOf(Element);
Same as in `connotation`.

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +				.toBeInstanceOf(Element);
Same as in `shape`

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +			expect(base).toBeInstanceOf(Element);
Same :)

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +		it('should not update selected to true when not selectable', async () => {
Better to be "positive" when writing test descriptions :)
```suggestion
		it('should leave selected unchanged when not selectable', async () => {
```

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +		it('should not update selected to true when removable', async () => {
```suggestion
		it('should leave selected unchanged when removable is true', async () => {
```

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +				.toBeInstanceOf(Element);
Consider making more explicit.

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +		it('should not remove tag on keydown when disabled', async () => {
Positive description

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +		it('should not fire removed event', async () => {
Positive

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +		it('should update selected to true when keydown', async () => {
```suggestion
		it('should update selected to true when Enter is pressed', async () => {
```

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +		it('should remove tag on keydown when removable', async () => {
```suggestion
		it('should remove tag on Escape press and removable is true', async () => {
```

2023-04-10 13:53 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +		it('should not remove tag on keydown when not removable', async () => {
```suggestion
		it('should still show tag after Escape press when removable is false', async () => {
```

2023-04-10 13:56 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.ts
> +	select = (): void => {
Is this API explicitly tested?

2023-04-11 09:06 UTC, rachelbt reviewed
not sure that the active color.
Also - if the tag is selected it needs to have a different color and not only the V.
Check with @AyalaBu abut the design - I understand that is is still in process :woman-facepalming::skin-tone-2:

2023-04-11 09:06 UTC, rachelbt commented on libs/components/src/lib/tag/README.md
> +
We should add to the docs that the tag can be either selectable or removable.
What if someone sets both - which of them will "win"?

2023-04-11 10:21 UTC, rinaok commented on libs/components/src/lib/tag/README.md
> +
`Notice that it works only if the tag is selectable, not disabled and not removable.`

2023-04-11 11:43 UTC, olaf-k commented on libs/components/src/lib/tag/tag.ts
> +		if (e.key === 'Escape') {
I'm no UX expert but I expect <kbd>esc</kbd> to **close** (popups/dialogs/modals), not to **remove** (<kbd>delete</kbd> feels more appropriate).
@AyalaBu ?

2023-04-11 11:49 UTC, rinaok commented on libs/components/src/lib/tag/README.md
> +- Type: `'subtle'` | `'duotone'`
This is a question for @AyalaBu. 

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=21462-145817&t=y8RHSy0BGrByqo1f-0

2023-04-11 11:51 UTC, rinaok commented on libs/components/src/lib/tag/tag.ts
> +		if (e.key === 'Escape') {
@olaf-k I agree, can update it. @rachelbt @YonatanKra What do you think?

2023-04-13 08:16 UTC, YonatanKra approved these changes
See one suggestion. Other than that, fine by me :)

2023-04-13 08:16 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.spec.ts
> +				.toBeInstanceOf(HTMLElement);
```suggestion
			await toggleRemovable(element, true);
			expect(element.shadowRoot?.querySelector('.dismiss-button'))
				.toBeTruthy();
```

2023-04-13 08:16 UTC, YonatanKra commented on libs/components/src/lib/tag/tag.ts
> +	};
I like this solution even better than writing tests for it!
![Uploading image.png…]()

2023-04-13 10:13 UTC, rachelbt commented on libs/components/src/lib/tag/README.md
> +- Type: `'subtle'` | `'duotone'`
@olaf-k filled is different in its color shades.

2023-04-13 10:13 UTC, rachelbt commented on libs/components/src/lib/tag/ui.test.ts
> +	const template = extractHTMLBlocksFromReadme(
```suggestion
	const template = `<style>#wrapper{height: 180px; width: 260px;}</style>' +extractHTMLBlocksFromReadme(
```

2023-04-13 10:13 UTC, rachelbt commented on libs/components/src/lib/tag/ui.test.ts
> +	const template = extractHTMLBlocksFromReadme(
you'll also need to generate new ui-png

2023-04-13 10:18 UTC, rinaok commented
@AyalaBu Found the original design from vivid-2
https://github.com/Vonage/vivid/pull/1016
Are you sure we don't need sizes?

2023-04-13 12:00 UTC, rachelbt approved these changes
LGTM - lets see it inside tag-group :)

2023-04-13 12:05 UTC, merged