feat(components): add a way to manually set text-field in error state (VIV-970)
Vonage/vivid-3 pull request #1103
Opened 2023-04-04 15:11 UTC by olaf-k

There are two ways to go about this:
- a purely cosmetic approach that simply styles the component and displays the message.
- a cleaner way that actually sets the component in error state (caught by `:invalid` selectors, with a proper `validity` prop).

This PR is an attempt at the latter (the former should be quite simple to implement).

Code notes:

- had to "manually" override `validate` in `force-error.ts` because it is added as a mixin *after* the TextField class definition.
- I'm not sure what `userValid` is supposed to represent? though it is needed to refresh the template properly.
- an error message set with `force-error` will supersede any existing error state (conversely, removing it will return the field to its original error state, if any).

2023-04-13 12:19 UTC, YonatanKra requested changes
This PR indeed exposes a missing API for setting a custom error message.

It already exists in the HTML spec: [setCustomValidity](https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/setCustomValidity)

We should adhere to it IMO.

Since there's no attribute in the spec, it begs the question should we implement one? Diverting from the spec - especially in form elements - might interfere with our components being compatible with the ElementInternals spec which is the future of form association for custom elements.

2023-04-18 12:50 UTC, YonatanKra requested changes

2023-04-18 12:50 UTC, YonatanKra commented on libs/components/src/lib/text-field/text-field.spec.ts
> +		it('should replace/restore the current error state, if any, when set/removed', async function () {
Can you split this into two `its`, please? One for `set` and one for `remove`?

2023-04-18 14:22 UTC, acelletti requested changes
@olaf-k Can we change `force-error` to `error-message` as it describes what it is that we are passing here.

2023-04-18 14:50 UTC, olaf-k commented on libs/components/src/shared/patterns/force-error.ts
> +			};
see the PR notes https://github.com/Vonage/vivid-3/pull/1103#issue-1654086388

2023-04-20 10:09 UTC, acelletti approved these changes

2023-04-20 10:24 UTC, merged