VIV-989 Add Spezia font CSS to library
Vonage/vivid-3 pull request #1107
Opened 2023-04-12 08:44 UTC by acelletti

2023-04-12 10:04 UTC, olaf-k commented on libs/styles/project.json
> +						"cp -r libs/styles/src/lib/fonts dist/libs/styles"
would probably be more consistent to rename the CSS file with an `.scss` extension and add
```
"sass libs/styles/src/lib/fonts:dist/libs/styles/fonts"
```
to the scss/commands part of the project file.

(not related to this PR but `lintFilePatterns` in this very file should probably target scss files and not css ones)

2023-04-12 12:51 UTC, olaf-k approved these changes
maybe @rachelbt can clarify why we have rules for `SpeziaMonoCompleteVariable` and `SpeziaCompleteVariableItalic` which don't seem to be used at first glance?

2023-04-13 06:22 UTC, rachelbt requested changes
why is it better this way?
Its better for performance that the font will be inside the project and not from an outer URL. 
not that important but - if project is using Volta - this causes them to import the font twice.

Also - the mono font face is missing.

2023-04-13 06:22 UTC, rachelbt commented on libs/styles/src/lib/fonts/spezia-variable.scss
> +
```suggestion
@font-face {
 font-family: SpeziaMonoCompleteVariable;
 font-stretch: 50% 200%;
 font-weight: 1 1000;
 src: '');
}
```

2023-04-13 08:32 UTC, acelletti commented on libs/styles/src/lib/fonts/spezia-variable.scss
> +
> why is it better this way?

Because it provides the boilerplate CSS for import instead of asking people to copy/paste the CSS into their own projects.

2023-04-13 08:33 UTC, acelletti commented
> Its better for performance that the font will be inside the project and not from an outer URL.
> not that important but - if project is using Volta - this causes them to import the font twice.

If they already have the font, they can use their own CSS instead of importing the default file.

2023-04-13 08:36 UTC, acelletti commented on libs/styles/src/lib/fonts/spezia-variable.scss
> +
Added the mono font, nice catch!

2023-04-13 08:57 UTC, acelletti commented
> why is it better this way?

Because it provides the boilerplate CSS for import instead of asking people to copy/paste the CSS into their own projects.

2023-04-18 13:02 UTC, rachelbt commented on docs/getting-started/fonts-and-tokens.md
> +'node_modules/@vonage/styles/fonts/spezia-variable.css';
```suggestion
Add in the project head:
```html
<link rel="stylesheet" href="node_modules/@vonage/styles/fonts/spezia-variable.css" media="all">
```
```

2023-04-18 14:54 UTC, YonatanKra approved these changes

2023-04-18 15:24 UTC, merged