fix(components): slider change event (VIV-985)
Vonage/vivid-3 pull request #1121
Opened 2023-04-18 13:23 UTC by olaf-k

2023-04-24 07:01 UTC, YonatanKra requested changes

2023-04-24 07:01 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.ts
> +			// min/max constraints backported from v3
I don't understand this comment. 
Can you elaborate please?

2023-04-24 08:14 UTC, olaf-k commented on libs/components/src/lib/slider/slider.ts
> +			// min/max constraints backported from v3
the PR fix (mix/max constraints) is backported from Foundation v3 (alpha).

2023-04-24 09:29 UTC, YonatanKra reviewed
Mind removing the comments?
They mean nothing to most people.
We have tests that will fail if we upgrade to v3, right?

2023-04-24 12:00 UTC, olaf-k commented
> Mind removing the comments? They mean nothing to most people.

I actually do? they are useful to explain why the code is here and why it looks like that. that is a strange request.

> We have tests that will fail if we upgrade to v3, right?

we don't have tests designed to fail when you upgrade Fast's version, no, why would we?

2023-04-24 14:47 UTC, YonatanKra commented
> > Mind removing the comments? They mean nothing to most people.
> 
> I actually do? they are useful to explain why the code is here and why it looks like that. that is a strange request.
> 
> > We have tests that will fail if we upgrade to v3, right?
> 
> we don't have tests designed to fail when you upgrade Fast's version, no, why would we?

According to your comments, if we upgrade FAST to v3, the tests are supposed to fail.
Am I correct?

2023-04-24 15:34 UTC, olaf-k commented
> According to your comments, if we upgrade FAST to v3, the tests are supposed to fail. Am I correct?

the comments are to remind me/whoever will maintain that:
1) the min/max computation—lacking in the v2 Fast component which we inherit from—is pretty much a copy/paste of the v3. it will not fail upon upgrade but can then be removed as duplicate.
2) the rest of the logic (setThumbPositionForOrientation + change event) is—by opposition to 1—correctly done in the v2 parent class.

2023-04-25 06:41 UTC, YonatanKra commented
> > According to your comments, if we upgrade FAST to v3, the tests are supposed to fail. Am I correct?
> 
> the comments are to remind me/whoever will maintain that:
> 
> 1. the min/max computation—lacking in the v2 Fast component which we inherit from—is pretty much a copy/paste of the v3. it will not fail upon upgrade but can then be removed as duplicate.
> 2. the rest of the logic (setThumbPositionForOrientation + change event) is—by opposition to 1—correctly done in the v2 parent class.

@olaf-k 
Anyway - if there's a test covering the `valueChanged` method, I think we can remove these comments. The fact that I (a possible future maintainer) asked what they mean makes the comments rather useless.

2023-04-25 07:30 UTC, olaf-k commented
> @olaf-k Anyway - if there's a test covering the `valueChanged` method, I think we can remove these comments. The fact that I (a possible future maintainer) asked what they mean makes the comments rather useless.

you not understanding something doesn't make it useless Yonatan.

2023-04-25 08:06 UTC, YonatanKra commented
> > @olaf-k Anyway - if there's a test covering the `valueChanged` method, I think we can remove these comments. The fact that I (a possible future maintainer) asked what they mean makes the comments rather useless.
> 
> you not understanding something doesn't make it useless Yonatan.

I agree. It doesn't make it that way, it hints on it. Need to make some more experiments :)
Can we ditch the comments and merge this?

2023-04-25 08:54 UTC, merged