feat(text-area): add a way to manually set text-area in error state (VIV-990)
Vonage/vivid-3 pull request #1126
Opened 2023-04-20 13:22 UTC by olaf-k

pretty much a copy/paste of #1103

2023-04-24 07:03 UTC, YonatanKra commented on libs/components/src/lib/text-area/text-area.spec.ts
> +		it('should be initialized as a vwc-text-area', async () => {
:)

2023-04-24 07:04 UTC, YonatanKra requested changes

2023-04-24 07:04 UTC, YonatanKra commented on libs/components/src/lib/text-area/text-area.spec.ts
> +		it('should replace/restore the current error state, if any, when set/removed', async function () {
Please split this to two different `it`s.

2023-04-24 08:20 UTC, olaf-k commented on libs/components/src/lib/text-area/text-area.spec.ts
> +		it('should replace/restore the current error state, if any, when set/removed', async function () {
we had the same exchange in https://github.com/Vonage/vivid-3/pull/1103#discussion_r1170161786
how would you split the test?

2023-04-24 09:37 UTC, YonatanKra commented on libs/components/src/lib/text-area/text-area.spec.ts
> +	});
Something in the spirit of:
```suggestion
		it('should replace the current error state when set', function () {
		element.required = true;
		setToBlurred();
		element.errorText = forcedErrorMessage;
		await elementUpdated(element);

		expect(element.validationMessage).toBe(forcedErrorMessage);
	});
	
	it('should restore the current error state when removed', async function () {
		element.required = true;
		setToBlurred();
		await elementUpdated(element);
		const initialErrorMessage = element.validationMessage;
		element.errorText = forcedErrorMessage;
		await elementUpdated(element);

		element.errorText = '';
		expect(element.validationMessage).toBe(initialErrorMessage);
	});
```

2023-04-25 08:07 UTC, YonatanKra approved these changes
LGTM.
![image](https://user-images.githubusercontent.com/6459899/234214391-57688944-b362-4e87-ae75-55b6bd7989e3.png)

2023-04-25 09:08 UTC, merged