fix(tooltip): allow setting anchor to an HTMLElement (VIV-1032)
Vonage/vivid-3 pull request #1130
Opened 2023-04-21 17:39 UTC by RichardHelm

2023-04-21 17:40 UTC, RichardHelm commented on libs/components/src/lib/tooltip/tooltip.template.ts
> +	:anchor=${(x) => x.anchor}
This is the actual fix, passing anchor as prop

2023-04-21 17:41 UTC, RichardHelm commented on libs/components/src/lib/tooltip/tooltip.ts
> +export class Tooltip extends FoundationElement {
It doesn't make any sense for tooltip to inherit form Popup so I changed it and instead copied over the relevant attributes.
Similar to how menu works

2023-04-23 09:14 UTC, rinaok requested changes
Hi @RichardHelm, I reviewed your changes. Unlike the menu component, which uses the popup inside it, the tooltip component is a private case of the popup. This is why it extends the popup. The popup manages anchor changes and open changes. There is no need to perform the same checks twice in two different components (You can see the UI tests fail now because the open state is not handled). Due to the fact that we didn't know if this was needed by users, we kept it undocumented only for our own use. If you wish, you can use the anchor with an HTMLElement in the tooltip, just add an example to the readme file. :)

2023-04-24 09:33 UTC, rinaok approved these changes

2023-04-24 09:45 UTC, merged