feat(components): toggletip (VIV-865)
Vonage/vivid-3 pull request #1137
Opened 2023-04-25 12:31 UTC by olaf-k

2023-05-03 17:08 UTC, rachelbt submitted a review, later dismissed
Nice!!!
But I have some comments :)

I don't know what are the needs for the toggle tip but I think that maybe we should set a different structure:

- Like card, dialog alert - that we provide main slot - so consumers can use vivid comps for the functionality but have their own inside structure.

- Regarding our pre-defined template, maybe we can keep the convention of other components:
header that has our headline, body - slot, footer - slot.
- What about dismiss button? 
-- If we are adding it - is it optional?
Are there any a11y issues that we need to point out in our doc?

2023-05-03 17:08 UTC, rachelbt commented on libs/components/src/lib/toggletip/toggletip.template.ts
> +			<span class="content-wrapper">
```suggestion
			<div class="content-wrapper">
```
span is an inline-element it shouldn't contain block elements

2023-05-04 08:18 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.template.ts
> +			<span class="content-wrapper">
thanks for the comments Rach.

1. sorry I don't think I understand this one though. the toggletip uses the default slot for authors to put whatever structure they want in.
2. I can sure use `header` and `footer`, good point.
3. this was discussed in the [old PR](https://github.com/Vonage/vivid-3/pull/843#issuecomment-1322199844). tl;dr: toggletips don't have a close button, nor does [our design](https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?type=design&node-id=20630-129571&t=H3XXGTfacvmHIejX-0).

2023-05-04 08:57 UTC, olaf-k commented
> Nice!!! But I have some comments :)

thanks for the comments Rach.

1. sorry I don't think I understand this one though. the toggletip uses the default slot for authors to put whatever structure they want in.
2. I can sure use `header` and `footer`, good point.
3. this was discussed in the [old PR](https://github.com/Vonage/vivid-3/pull/843#issuecomment-1322199844). tl;dr: toggletips don't have a close button, nor does [our design](https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?type=design&node-id=20630-129571&t=H3XXGTfacvmHIejX-0).

2023-05-04 15:09 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.scss
> +}
my initial goal was to only allow buttons in the action-items slot.
I didn't implement the filter, but maybe I should have. the idea is that you really should **not** put anything other than buttons (or maybe links? tbd) there ([see the Figma file](https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?type=design&node-id=20630-129571&t=dyyOU4coOjCEH6ku-0)). this is why it's called `action-items` and not just `footer`.

note that, if you *really* want to put your own design, you can just leave the `action-items` slot empty and put whatever crazy design you want in the default one.

2023-05-10 06:35 UTC, YonatanKra requested changes
Great job. Mostly test related comments.

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +	describe('open/close', () => {
Describe the API. There's no `close` property or method.
```suggestion
	describe('open', () => {
```

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +		it('should close when clicked outside', async () => {
```suggestion
		it('should set open to false when clicked outside', async () => {
```

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +			expect(element.open).toEqual(true);
How does this verify it accepts an HTMLelement as an anchor?

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +		});
There are two functionalities tested. Splitting is advised.

```suggestion
		it('should set listener to new anchor when anchor is changed', async () => {
			const anchor2 = fixture(
				'<vwc-button id="anchorButton2"></vwc-button>', ADD_TEMPLATE_TO_FIXTURE
			) as Button;
	
			element.anchor = 'anchorButton';
			await elementUpdated(element);

			element.anchor = 'anchorButton2';
			await elementUpdated(element);
			element.open = false;

			anchor2.dispatchEvent(new MouseEvent('click', {bubbles: true}));
			await elementUpdated(element);
			expect(element.open).toEqual(true);
		});
		
		it('should remove listener on old anchor when anchor is changed', async () => {
			const anchor2 = fixture(
				'<vwc-button id="anchorButton2"></vwc-button>', ADD_TEMPLATE_TO_FIXTURE
			) as Button;
	
			element.anchor = 'anchorButton';
			await elementUpdated(element);

			element.anchor = 'anchorButton2';
			await elementUpdated(element);
			element.open = false;

			anchor.dispatchEvent(new MouseEvent('click', {bubbles: true}));
			await elementUpdated(element);
			expect(element.open).toEqual(false);
		});
```

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +		});
Standard is expectations in the end. Usually, a test like this means there are two tests in one. Like this:

```suggestion
		it('should remove the aria-label from old anchor when changed', async () => {
			element.anchor = anchor;
			await elementUpdated(element);

			expect(anchor.ariaLabel).toEqual(' ; Show more information');

			element.anchor = 'anchor2';
			await elementUpdated(element);

			expect(anchor.ariaLabel).toEqual('');
		});
		
		it('should set the aria-label on anchor', async () => {
			element.anchor = anchor;
			await elementUpdated(element);

			expect(anchor.ariaLabel).toEqual(' ; Show more information');
		});
```

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +		});
Again, there are two `its` in this case:
1. Concatenate " ; Show more information" to existing aria-label
2. Revert to original aria-label when anchor is not longer an anchor.

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +	});
Defer expectations to the end and make it clear without understanding the code what is actually being tested.
 
```suggestion
		it('should have an headline element only when set', async () => {
		  const headlineExistsWithoutHeadlineSet = element.shadowRoot?.querySelectorAll('header.headline').length > 0;

			element.headline = 'A title!';
			await elementUpdated(element);
			const headlineExistsWithHeadlineSet = element.shadowRoot?.querySelectorAll('header.headline').length === 1;

      expect(headlineExistsWithoutHeadlineSet).toEqual(false);
			expect(headlineExistsWithHeadlineSet).toEqual(true);
		});
	});
```

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.ts
> +	anchorEl: HTMLElement | null = null;
This is an exposed API. Should be tested or be private (private as in `#anchorEl`).

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.ts
> +	@attr({ mode: 'boolean'	}) alternate = false;
Exposed API,  please add a describe with a test (at least that it's reflected).

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.ts
> +	@attr({ mode: 'fromView' }) placement?: Placement = 'right';
Exposed untested API.

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.ts
> +	@attr({ mode: 'fromView' }) anchor: anchorType = '';
Exposed untested API. Is it even used?

2023-05-10 06:35 UTC, YonatanKra commented on libs/components/src/lib/toggletip/README.md
> +### Action Items
I cannot see it in the ui tests.
It seems like there's only one toggle-tip open in the UI tests.
Can you add something like this (I might have gotten the query selector wrong):
```
for (const toggleTip of await page.locator('[listitem](vwc-toggle-tip:not([open])').all())
  await toggleTip.evaluate(node => node.open = true);
```
To open the toggle tips in the test?
Another case might be to add a closed example to show that without open you can't view anything.

2023-05-10 06:35 UTC, YonatanKra requested changes
Great job. Mostly test related comments.

2023-05-15 12:02 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +			expect(element.open).toEqual(true);
by ensuring that clicking the anchor has the expected behavior on the toggletip.

2023-05-15 12:19 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +		});
having multiple `expect`s in a test is reasonable as long as multiple is understood as "small number" and the test is not long.
the suggestion is longer and less readable.

2023-05-15 12:21 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.ts
> +	anchorEl: HTMLElement | null = null;
indeed, good point.

2023-05-15 12:23 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.ts
> +	@attr({ mode: 'boolean'	}) alternate = false;
it is "tested" in `basic`. that's all there is to do as it is purely forwarded.

2023-05-15 12:24 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.ts
> +	@attr({ mode: 'fromView' }) placement?: Placement = 'right';
same as previous comment.

2023-05-15 12:25 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.ts
> +	@attr({ mode: 'fromView' }) anchor: anchorType = '';
you just did review `anchor` related tests Yonata...

2023-05-15 12:27 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +		});
see previous comment.

2023-05-15 12:28 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +	});
this is not an improvement.

2023-05-15 14:37 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +		});
See previous answer :)

2023-05-15 14:38 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +	});
To me it is :)

2023-05-15 14:39 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.ts
> +	@attr({ mode: 'boolean'	}) alternate = false;
And if I remove `@attr`? Tests still pass, right?

2023-05-15 14:41 UTC, YonatanKra commented on libs/components/src/lib/toggletip/toggletip.ts
> +	@attr({ mode: 'fromView' }) anchor: anchorType = '';
Sorry, you are right. For some reason I thought the prop was `anchorType`. Maybe should consider set the type in capitals to make it clearer it is a type and not a prop name :)

2023-05-16 07:48 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.spec.ts
> +		});
"for me"

2023-05-16 07:49 UTC, olaf-k commented on libs/components/src/lib/toggletip/toggletip.ts
> +	@attr({ mode: 'boolean'	}) alternate = false;
`@attr` is a Fast construct, I'm not testing Fast.

2023-05-16 09:31 UTC, YonatanKra requested changes
Can you address this commit (only changed the tests):
https://github.com/Vonage/vivid-3/commit/fcae1768bf9d8ea9a0b0f50116abd53cce36ebee
Thanks :)

2023-05-16 10:36 UTC, YonatanKra approved these changes
LGTM

2023-05-16 10:44 UTC, merged