feat(docs): add components filter (VIV-000)
Vonage/vivid-3 pull request #1156
Opened 2023-05-11 12:23 UTC by YonatanKra

2023-05-11 14:06 UTC, rachelbt commented on apps/docs/_includes/navigation.njk
> +  	<vwc-text-field placeholder="Search Components" oninput="filterComponentsInput(event)"></vwc-text-field>
```suggestion
  	<vwc-text-field placeholder="Search Components" oninput="filterComponentsInput(event)" icon="search-line"></vwc-text-field>
```
adding a search icon

2023-05-11 14:18 UTC, YonatanKra commented on apps/docs/_includes/navigation.njk
> +  	<vwc-text-field placeholder="Search Components" oninput="filterComponentsInput(event)"></vwc-text-field>
It can be at the top of the list, but the filter only filters the components.  Putting it at the top of the list seems unrelated to me.
Waiting for @AyalaBu final input here.

2023-05-14 05:52 UTC, AyalaBu commented
@rachelbt 
I think on the top of the list it looks better

2023-05-15 08:58 UTC, olaf-k requested changes
traditionally, JS and CSS used by the doc are stored in `apps/docs/assets` (under `scripts/` and `styles/` respectively), not directly in the template files.

2023-05-15 10:00 UTC, olaf-k commented on apps/docs/_includes/navigation.njk
> +				const components = Array.from(e.target.parentNode.children);
this doesn't need to be done on every keystroke. get the components list on window.onload for instance and keep it in a var.

2023-05-15 11:55 UTC, olaf-k commented on apps/docs/assets/scripts/components.filter.js
> +		document.querySelectorAll('vwc-nav-disclosure:not([label="Components"])').forEach(disclosure => {
what about also caching this in a var instead of running the query at every keystroke?

2023-05-15 13:19 UTC, olaf-k approved these changes

2023-05-15 13:28 UTC, merged