fix(alert): complete component (VIV-1038)
Vonage/vivid-3 pull request #1164
Opened 2023-05-17 08:56 UTC by olaf-k

2023-05-23 14:02 UTC, YonatanKra requested changes
Good job. Mostly docs/test related stuff.

2023-05-23 14:02 UTC, YonatanKra commented on libs/components/src/lib/alert/alert.ts
> +	get conditionedIcon() {
This should be tested too (exposed API).
It has 4 cases:
1. Default
2. When connotation is set
3. When icon is set
4. When connotation and icon are set together.

2023-05-24 10:34 UTC, olaf-k commented on libs/components/src/lib/alert/README.md
> +Use the `icon` attribute to add an icon to your alert.
clarified in README and tests

2023-05-24 10:35 UTC, olaf-k commented on libs/components/src/lib/alert/alert.ts
> +	get conditionedIcon() {
I rearranged the icon tests and added checks for that one

2023-05-25 08:19 UTC, rachelbt reviewed
looks so much better!
Didn't check the test :) - leaving this to @YonatanKra

2023-05-25 08:19 UTC, rachelbt commented on libs/components/src/lib/alert/alert.scss
> +	min-inline-size: var(#{variables.$alert-inline-size}, 420px);
```suggestion
	min-inline-size: var(#{variables.$alert-min-inline-size}, 420px);
	max-inline-size: var(#{variables.$alert-max-inline-size}, fit-content);
```
if no max-width is set if there's lots of text the alert can be beryyyy wide :)

I'm being lazy adding this to all the places that are needed - variable + readme

2023-05-25 08:19 UTC, rachelbt commented on libs/components/src/lib/alert/alert.scss
> +		.maintext {
when we are using 2 words we usually have "-". 
maybe `alert-message` is better?

2023-05-25 08:19 UTC, rachelbt commented on libs/components/src/lib/alert/README.md
you are correct that this is the default - bus since we also have template we usually give a name to the slot.
In toggle tip theres no option adding members of text on the host - but only in the default slot. Appose to Card that has text members on the host (with pre-defined template) and other slots like body-footer.
if so, maybe the maintext is a subtitle :)
OR - the "default" behaves like main slot and removes the headling and text.
WDYS?

Also - we need to set the gaps for this scenario:
![image](https://github.com/Vonage/vivid-3/assets/7512792/33e28dd9-7b6e-4ede-bc2e-c229e8f45489)

2023-05-25 08:30 UTC, YonatanKra approved these changes
Only thing on my end is to separate the icon and connotation icon describe, but aside from that I'm good. @rachelbt has some comments of her own.

2023-05-25 08:57 UTC, olaf-k commented on libs/components/src/lib/alert/README.md
>  ### Headline
I disagree. `text` without `headline` makes sense, not the other way around.

2023-05-25 08:58 UTC, olaf-k commented on libs/components/src/lib/alert/README.md
> +<vwc-button appearance='outlined' label="Show accent connotation" onclick="openAlert('accent')"></vwc-button>
probably not, I just did not want to change literally *everything* 😅
will give it a try

2023-05-25 09:01 UTC, olaf-k commented on libs/components/src/lib/alert/alert.scss
> +	min-inline-size: var(#{variables.$alert-inline-size}, 420px);
good point. I'll add that.

2023-05-25 09:50 UTC, olaf-k commented on libs/components/src/lib/alert/README.md
I added the default slot on top of `headline` & `text` without giving it too much thought. I took for granted that it was an "either/or" situation, but I did not make it explicit in the code indeed. will change the template.

2023-05-30 05:25 UTC, rachelbt reviewed
Looks great.
Left you one last comment and lets merge :)

2023-05-30 05:25 UTC, rachelbt commented on apps/docs/_data/components.json
> -		"status": "underlying",
I think we need to make this alpha :)

2023-05-30 07:12 UTC, YonatanKra approved these changes
LGTM

2023-05-30 07:42 UTC, merged