feat(components): add icon slot to affix icons (VIV-1054)
Vonage/vivid-3 pull request #1166
Opened 2023-05-18 12:22 UTC by RichardHelm

2023-05-22 07:48 UTC, rachelbt reviewed
unit tests are not passing...

2023-05-22 07:48 UTC, rachelbt commented on libs/components/src/lib/select/README.md
> +		<svg viewBox="0 0 24 24"><path d="M12 0C5.4 0 0 5.4 0 12C0 18.6 5.4 24 12 24C18.6 24 24 18.6 24 12C24 5.4 18.6 0 12 0ZM18" fill="currentColor"></path></svg>
```suggestion
		<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="12">fill="currentColor"></circle> </svg>
```

2023-05-22 07:48 UTC, rachelbt commented on libs/components/src/lib/select/README.md
> +			<svg viewBox="0 0 24 24"><path d="M12 0C5.4 0 0 5.4 0 12C0 18.6 5.4 24 12 24C18.6 24 24 18.6 24 12C24 5.4 18.6 0 12 0ZM18" fill="currentColor"></path></svg>
```suggestion
<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="12">fill="currentColor"></circle> </svg>
```

2023-05-22 07:48 UTC, rachelbt commented on libs/components/src/lib/select/README.md
> +			<svg viewBox="0 0 24 24"><path d="M12 0C5.4 0 0 5.4 0 12C0 18.6 5.4 24 12 24C18.6 24 24 18.6 24 12C24 5.4 18.6 0 12 0ZM18" fill="currentColor"></path></svg>
```suggestion
<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="12">fill="currentColor"></circle> </svg>
```

2023-05-22 07:48 UTC, rachelbt commented on libs/components/src/lib/select/README.md
> +			<svg viewBox="0 0 24 24"><path d="M12 0C5.4 0 0 5.4 0 12C0 18.6 5.4 24 12 24C18.6 24 24 18.6 24 12C24 5.4 18.6 0 12 0ZM18" fill="currentColor"></path></svg>
```suggestion
<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="12">fill="currentColor"></circle> </svg>
```

2023-05-24 10:28 UTC, RichardHelm commented on libs/components/src/lib/select/README.md
> +		<svg viewBox="0 0 24 24"><path d="M12 0C5.4 0 0 5.4 0 12C0 18.6 5.4 24 12 24C18.6 24 24 18.6 24 12C24 5.4 18.6 0 12 0ZM18" fill="currentColor"></path></svg>
We now have a circle icon so I removed the svg

2023-05-24 14:15 UTC, olaf-k submitted a review, later dismissed

2023-05-24 14:15 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +					: null}
I'm confused. you updated `affixIconTemplateFactory` to make the wrapper optional, but present by default, so this looks unnecessary?

(also, not related to your PR at all and probably my bad, the three ternary icon choices would be more idiomatic written using `with`)

2023-05-24 14:15 UTC, olaf-k commented on libs/components/src/lib/select/select.template.ts
> +					<span class="icon"><${iconTag} :name="${() => 'chevron-down-line'}"></${iconTag}></span>
you ultimately end having to write `<${iconTag} :name="${() => icon}"></${iconTag}>` anyway, so why bother changing `affixIconTemplateFactory`? couldn't you have left line 50 alone and just patch line 46?

2023-05-24 16:51 UTC, RichardHelm commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +					: null}
You're right, I made those changes earlier because I tried a different approach, but now it makes no difference in terms of html.
However, I think this is just a regular icon and not related to the affix icon, so we shouldn't be using the affix template anyway

For the ternaries, sure I've now replaced them with `when()`

2023-05-24 16:52 UTC, RichardHelm commented on libs/components/src/lib/select/select.template.ts
> +					<span class="icon"><${iconTag} :name="${() => 'chevron-down-line'}"></${iconTag}></span>
Please see the other comment

2023-05-24 17:31 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +					: null}
I agree that, at this point, `affixIconTemplateFactory` should probably not have this name anymore (nor be a factory tbh).
but having extra code that duplicates what it does somehow feels worse than a bad name.

(thanks for the `when`!)

2023-05-25 08:35 UTC, rachelbt reviewed
Because this PR is actually 2 major changes - one is the iconAffix change and the other is the select - do you mind separating it into 2 PRs?

2023-05-25 11:14 UTC, RichardHelm commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +					: null}
Ok, I've now removed it from this PR and will raise another one for it later

2023-05-25 11:15 UTC, RichardHelm commented
@rachelbt Ok, done

2023-05-28 06:09 UTC, YonatanKra requested changes
Please see @olaf-k 's comments.
I accidentally staled his review thinking it is a different PR

2023-06-02 08:10 UTC, olaf-k submitted a review, later dismissed

2023-06-05 10:23 UTC, YonatanKra submitted a review, later dismissed

2023-06-15 08:47 UTC, YonatanKra requested changes

2023-06-15 08:47 UTC, YonatanKra commented on libs/components/src/lib/select/select.spec.ts
> +		it('should not have the has-icon class by default', async () => {
Try to be positive in your tests descriptions:
```suggestion
		it('should initialize without the "has-icon" class', async () => {
```

2023-06-15 08:47 UTC, YonatanKra commented on libs/components/src/lib/menu-item/menu-item.template.ts
> +	return affixIconTemplate(icon);
Why is this removed?

2023-06-15 08:47 UTC, YonatanKra commented on libs/components/src/lib/select/select.scss
> +		display: none;
Why not use a conditional in the template and prevent adding the component to the DOM instead?

2023-06-16 17:16 UTC, RichardHelm commented on libs/components/src/lib/select/select.spec.ts
> +		it('should not have the has-icon class by default', async () => {
Sure, updated it 👍

2023-06-20 11:50 UTC, YonatanKra commented on libs/components/src/lib/menu-item/menu-item.template.ts
> +	return affixIconTemplate(icon);
Strange it was removed earlier. Stranger still `TS` didn't catch it.

2023-06-20 16:40 UTC, YonatanKra approved these changes

2023-06-21 09:12 UTC, merged