feat(empty-state): add empty-state (VIV-1060)
Vonage/vivid-3 pull request #1169
Opened 2023-05-22 11:50 UTC by RichardHelm

2023-05-22 13:50 UTC, rachelbt requested changes

2023-05-22 13:50 UTC, rachelbt commented on libs/components/src/lib/empty-state/README.md
> +  No results match your search criteria.
```suggestion

```
when we are presenting members we usually add in the code samples the member itself without other additions if posibile

2023-05-22 13:50 UTC, rachelbt commented on libs/components/src/lib/empty-state/README.md
> +  No results match your search criteria.
```suggestion

```
same.
You can alternatively add headline since it was presented previously.

2023-05-22 13:50 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	display: block;
why is this needed?

2023-05-22 13:50 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	height: 100%;
```suggestion
	block-size: 100%;
```
I actually not sure if we need block-size.
What about inline-size? should it be auto (100%) or fit content?

2023-05-22 13:50 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	padding: 48px;
why is the padding needed?

2023-05-22 13:50 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.template.ts
> +		html<EmptyState>`<h3 class="headline">${(x) => x.headline}</h3>`
```suggestion
		html`<h3 class="headline">${(x) => x.headline}</h3>`
```
also - I know that in vivid-2 is `<h3>` but is it correct? Should it be a headline at all, and if so - do we need to allow the consumers to change it if its not the right headline?

2023-05-22 13:50 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.template.ts
> +				</div>
not sure this is needed, anyway it is not documented...

2023-05-22 13:50 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	}
```suggestion

```
I don't think that we need this.
if there's no slotted items then the slot is not rendered.
If there was padding or margin - then this was needed

2023-05-22 13:50 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.template.ts
> +	['no-actions', x.slottedActionItems?.length === 0]
not sure this is need - see my comment in the scss file

2023-05-23 12:39 UTC, olaf-k commented on libs/components/src/lib/empty-state/empty-state.template.ts
> +		html<EmptyState>`<h3 class="headline">${(x) => x.headline}</h3>`
+1. maybe `<header>` as in some other components would just do?

2023-05-23 12:55 UTC, olaf-k requested changes
looks good!

2023-05-23 15:54 UTC, RichardHelm commented on libs/components/src/lib/empty-state/empty-state.scss
> +	display: block;
This is so that height and margin can be set on the empty state

2023-05-23 15:57 UTC, RichardHelm commented on libs/components/src/lib/empty-state/empty-state.scss
> +	height: 100%;
I've added this so that the content will be vertically centered if the host element is larger
I think for inline-size the default (auto) is fine, so that it gets horizontally centered

2023-05-23 15:58 UTC, RichardHelm commented on libs/components/src/lib/empty-state/empty-state.scss
> +	padding: 48px;
It's part of the Figma design and I suppose this is so that it will be appropriately padded by default

2023-05-23 15:59 UTC, RichardHelm commented on libs/components/src/lib/empty-state/empty-state.template.ts
> +		html<EmptyState>`<h3 class="headline">${(x) => x.headline}</h3>`
Sure, I've changed to a `<header>`
If I remove `<EmptyState>` though it doesn't typecheck  anymore so I've kept that

2023-05-23 16:01 UTC, RichardHelm commented on libs/components/src/lib/empty-state/empty-state.template.ts
> +				</div>
I've added a default because the component looks weird without body text
Changed it to `Nothing to show` now, if that's fine?

2023-05-23 16:04 UTC, RichardHelm commented on libs/components/src/lib/empty-state/empty-state.scss
> +	}
I've added this because otherwise it creates a gap to the empty container for the actions:
![image](https://github.com/Vonage/vivid-3/assets/86777660/07f2b318-3454-4bb5-946b-bfd04f8056ae)

2023-05-23 16:05 UTC, RichardHelm commented on libs/components/src/lib/empty-state/empty-state.ts
> +	@attr({mode: 'fromView'}) icon: string = 'inbox-line';
I've added this because I got a linter error:
```
ESLint: 'attr' decorator assigned with a default value (unless mode is set to 'fromView', or, to 'boolean' assigned to false) will mutate the custom element in the DOM light tree.(@nrwl/nx/workspace/no-attribute-default-value)
```
Don't know if there's a better way to go about it

2023-05-24 07:32 UTC, olaf-k commented on libs/components/src/lib/empty-state/empty-state.ts
> +	@attr({mode: 'fromView'}) icon: string = 'inbox-line';
got it. in that case it can make sense to leave the attribute optional and set a fallback in the template (something along the lines of `${(x) => x.icon || 'inbox-line'}`

2023-05-24 17:29 UTC, RichardHelm commented on libs/components/src/lib/empty-state/empty-state.ts
> +	@attr({mode: 'fromView'}) icon: string = 'inbox-line';
Sure 👍 , updated it now

2023-05-25 08:42 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	height: 100%;
but why do we need this to be full width and full height?

2023-05-25 08:44 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	}
oh, I see.

2023-05-25 09:41 UTC, RichardHelm commented on libs/components/src/lib/empty-state/empty-state.scss
> +	height: 100%;
So, the full width is so that it centers horizontally on the page by default
And the full height doesn't do anything unless the `:host` has become larger, in which case we want it to vertically center in there as well.

Here is how I image it to be used:
![image](https://github.com/Vonage/vivid-3/assets/86777660/eb275907-dcab-4e48-8fb1-058214a1c2ff)
![image](https://github.com/Vonage/vivid-3/assets/86777660/672087dd-4a40-4247-9e99-fe9107785ab4)

2023-05-26 13:54 UTC, olaf-k submitted a review, later dismissed

2023-05-29 07:33 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	padding: 48px;
I'm not that sure about the inline-padding but I'll leave it

2023-05-29 07:33 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	height: 120px;
```suggestion
	inline-size: 120px;
	block-size: 120px;
```

2023-05-29 07:33 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	border-radius: 60px;
```suggestion
	border-radius: 50%;
```

2023-05-29 07:33 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.template.ts
> +						<${iconTag} class="icon" name="${(x) => x.icon ?? 'inbox-line'}" size="5"></${iconTag}>
I don't think we need a default icon.
What if there's no need for an icon or no place for it?
If this is removed - then I guess we can wrap the `.icon-container` with when there's an icon

2023-05-29 07:33 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	text-align: center;
this is redundant.
you can set `text-align: center` on `.content` and it will effect both of them

2023-05-29 07:33 UTC, rachelbt commented on libs/components/src/lib/empty-state/ui.test.ts
> +			`${htmlString} <div style="margin: 5px;">${block}</div>`,
try adding height of 380px, to the div so our PNG will be smaller

2023-05-29 07:33 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	gap: 24px;
```suggestion
	gap: 24px;
	box-sizing: border-box;
```

2023-05-31 12:23 UTC, olaf-k submitted a review, later dismissed

2023-06-01 17:13 UTC, RichardHelm commented
Hey @rachelbt, please let me know if you're happy with the PR now

2023-06-05 13:44 UTC, rachelbt approved these changes

2023-06-05 14:30 UTC, merged