feat(nav-item): add meta slot (VIV-1097)
Vonage/vivid-3 pull request #1173
Opened 2023-05-25 11:10 UTC by RichardHelm

2023-05-31 14:36 UTC, olaf-k requested changes

2023-05-31 14:36 UTC, olaf-k commented on libs/components/src/lib/text-anchor/text-anchor.ts
> +	}
I'm not super comfortable with this way of patching TextAnchor.
either we code a slot directly in `text-anchor` which `nav-item` can then use

or

`nav-item` has its own template (which admittedly will be 99% like `text-anchor` but with a slot.
@YonatanKra thoughts?

2023-06-01 17:27 UTC, RichardHelm commented on apps/docs/_includes/navigation.njk
> +				{% if (item.status) == "alpha" %}<vwc-badge slot="meta" text="alpha" appearance="subtle" shape="pill" connotation="success"></vwc-badge>{% endif %}
Sure, I've changed it 👍

2023-06-01 17:27 UTC, RichardHelm commented on libs/components/src/lib/nav-item/README.md
> +</script>
Thanks, updated the examples

2023-06-18 08:43 UTC, YonatanKra commented on libs/components/src/lib/text-anchor/text-anchor.ts
> +	}
I agree with @olaf-k here.
I'm not too much into slots, but if this is the policy then why not add the slot to the `text-anchor`? Because adding an API to `text-anchor` for `getBodyTemplate` is just a complicated way of adding a slot :)

2023-06-19 10:36 UTC, RichardHelm commented on libs/components/src/lib/text-anchor/text-anchor.ts
> +	}
Sure I can could add a slot to text-anchor, but's it not used as a component here, instead the template is reused.
`breadcrumb-item` reuses the template as well, so that means it would also get `meta` slot which is unintended
What do you suggest to do then?

2023-06-22 10:50 UTC, acelletti approved these changes

2023-06-22 10:50 UTC, acelletti commented on libs/components/src/lib/text-anchor/text-anchor.ts
> +	}
@YonatanKra I agree with @RichardHelm that adding a slot to the text anchor would have unintended consequences and I think the implementation here makes sense. I am approving this and unless you have any actionable changes I would be inclined to merge this.

2023-06-27 11:59 UTC, merged