fix(icon): fix icon color
Vonage/vivid-3 pull request #1175
Opened 2023-05-25 12:17 UTC by RichardHelm

2023-05-25 14:12 UTC, olaf-k requested changes

2023-05-25 14:12 UTC, olaf-k commented on libs/components/src/lib/nav-item/README.md
> +</vwc-nav>
```suggestion
<vwc-nav>
	<vwc-nav-item href="#" icon="profile" text="Account"></vwc-nav-item>
	<vwc-nav-item href="#" icon="profile" aria-label="Account"></vwc-nav-item>
</vwc-nav>
```
I understand the rationale to merge the two examples as they refer to the same attribute but we should keep them as short and to the point as possible. (the usage of aria-current is explained right before, there's no need to duplicate it here.)

2023-05-25 16:24 UTC, olaf-k approved these changes

2023-05-28 06:10 UTC, rachelbt requested changes
this is not a fix - the icon need to be in that color - @AyalaBu please

2023-05-28 07:58 UTC, AyalaBu commented
In the nav-item the icons is supposed to have the same color as text,
since it's also clickable.

2023-05-30 11:42 UTC, RichardHelm commented
@rachelbt I've followed the Figma design where the icon has the same color as the text

2023-05-30 11:45 UTC, rachelbt approved these changes

2023-05-31 15:17 UTC, merged