docs(icons): migrate icons gallery(VIV-1120)
Vonage/vivid-3 pull request #1194
Opened 2023-06-05 08:15 UTC by rinaok

2023-06-05 09:27 UTC, YonatanKra requested changes
Looks amazing! Good job!

2023-06-05 09:39 UTC, rinaok commented on docs/design/icons-gallery.md
> +</script>
@YonatanKra Done :)

2023-06-05 10:20 UTC, rinaok commented
![Screenshot 2023-06-05 at 13 18 52](https://github.com/Vonage/vivid-3/assets/10883919/e0bbf460-bf15-4239-9641-98134c8fdfe9)


@RichardHelm The empty states are not aligned inside the layout. Maybe it should not be set to default of height=100% ?

2023-06-05 10:29 UTC, rinaok commented
> @olaf-k Is this more clear now?

![Screenshot 2023-06-05 at 13 29 34](https://github.com/Vonage/vivid-3/assets/10883919/22cd6df6-fc46-4401-acbd-ae81ff3349a8)

2023-06-05 10:36 UTC, olaf-k commented
> > @olaf-k Is this more clear now?

it was clear already, my point is that these filters are mutually exclusive, i.e., selecting `solid` and `linear` at the same time is allowed although it doesn't make sense. I'm not sure if there are overlaps between the others, too lazy to check, but radios might be more suitable here.

2023-06-05 10:48 UTC, RichardHelm commented
> ![Screenshot 2023-06-05 at 13 18 52](https://user-images.githubusercontent.com/10883919/243324693-e0bbf460-bf15-4239-9641-98134c8fdfe9.png)
> 
> @RichardHelm The empty states are not aligned inside the layout. Maybe it should not be set to default of height=100% ?

Hi @rinaok, firstly, it looks great!
I think you can get them to align with `align-self: start;` on them.
But I feel like it's a bit of the an abuse of the empty-state to begin with to use it for data display, so maybe you're better served with some custom CSS?
Please note as well that I've updated the empty-state PR to remove the default 48px padding now.

2023-06-05 11:47 UTC, rachelbt commented
> I think you can get them to align with `align-self: start;` on them.

this will not work.
The align-center is inside the shadow-dom

2023-06-05 11:53 UTC, rinaok commented
> > > @olaf-k Is this more clear now?
> 
> it was clear already, my point is that these filters are mutually exclusive, i.e., selecting `solid` and `linear` at the same time is allowed although it doesn't make sense. I'm not sure if there are overlaps between the others, too lazy to check, but radios might be more suitable here.

@olaf-k Changed it to radio-group

2023-06-05 12:17 UTC, rinaok commented
> > I think you can get them to align with `align-self: start;` on them.
> 
> this will not work. The align-center is inside the shadow-dom

@rachelbt It worked, it looks good now :)

2023-06-06 04:57 UTC, YonatanKra commented on apps/docs/assets/scripts/icons-gallery.js
> +const VERSION = "4.1.2";
We should set the icons version in a central place and import it from there both here and in the icon component.
Can be a constants file in the `shared` folder or something like that.

2023-06-06 07:18 UTC, YonatanKra submitted a review, later dismissed
@rinaok 
I approve this one, but decide on your own if you want to take care of [this](https://github.com/Vonage/vivid-3/pull/1194#discussion_r1218899115) now or open an issue for it in JIRA.

2023-06-06 07:38 UTC, olaf-k requested changes

2023-06-06 07:41 UTC, olaf-k requested changes

2023-06-06 12:08 UTC, rinaok commented on apps/docs/assets/scripts/icons-gallery.js
> +  jsonData = await response.json();
added try catch

2023-06-06 12:26 UTC, olaf-k commented
> @olaf-k Changed it to radio-group

did you?
![image](https://github.com/Vonage/vivid-3/assets/1153034/44ebe1f0-ae86-4a6c-8a11-5ed03bf79033)
DID YOU?

2023-06-06 12:49 UTC, rinaok commented
> > @olaf-k Changed it to radio-group
> 
> did you? ![image](https://user-images.githubusercontent.com/1153034/243693580-44ebe1f0-ae86-4a6c-8a11-5ed03bf79033.png) DID YOU?

Wasn't my decision 💁🏻‍♀️ But I also think that it looks better with tags

2023-06-06 12:50 UTC, rinaok commented on apps/docs/assets/scripts/icons-gallery.js
> +const VERSION = "4.1.2";
This is the only place that uses icon's version, maybe later if it will be used in more places we can move it

2023-06-06 14:08 UTC, rachelbt reviewed
Iove the initiative and the fact that the icon will be inside our docs!!

I added some css changes - I hope I didn't forgot anything in my copy-paste from the dev-tools.
If you can - it is better to use classes rather than IDs.
Not that important - but we usually call classes with dash and not with camel case (tag-wrapper over tagWrapper)

2023-06-06 14:08 UTC, rachelbt commented on docs/design/icons-gallery.md
> +<vwc-button id="showMoreButton" label="Show More" appearance='filled' onclick="showMore()"></vwc-button>
```suggestion
<div>
<vwc-button id="showMoreButton" label="Show More" appearance='filled' onclick="showMore()"></vwc-button>
</div>
```
insert it inside the layout and dive it this class:
```
    grid-column: 1/-1;
    text-align: center;
```

2023-06-06 14:08 UTC, rachelbt commented on apps/docs/assets/styles/icons-gallery.css
> +}
```suggestion

```

2023-06-06 14:08 UTC, rachelbt commented on apps/docs/assets/styles/icons-gallery.css
> +}
no need - see my comment regarding the button position in the HTML

2023-06-06 14:08 UTC, rachelbt commented on apps/docs/assets/styles/icons-gallery.css
> +    position: relative;
I'm not sure this is needed...

2023-06-06 14:08 UTC, rachelbt commented on docs/design/icons-gallery.md
> +</span>
```suggestion
</div>
```

2023-06-07 05:53 UTC, rachelbt reviewed
added some css additions :)

2023-06-07 05:53 UTC, rachelbt commented on apps/docs/assets/styles/icons-gallery.css
> +    display: flex;
```suggestion
    display: flex;
    margin-block: 32px;
    row-gap: 16px;
```

2023-06-07 05:53 UTC, rachelbt commented on apps/docs/assets/styles/icons-gallery.css
> +    margin-block: 32px;
```suggestion

```

2023-06-07 05:53 UTC, rachelbt commented on docs/design/icons-gallery.md
> +    </div>
```suggestion
    <vwc-layout id="iconsLayout" gutters="small">
    <div class="button-wrapper">
      <vwc-button id="showMoreButton" label="Show More" appearance='filled' onclick="showMore()"></vwc-button>
    </div>
    </vwc-layout>
```

2023-06-07 05:53 UTC, rachelbt commented on apps/docs/assets/styles/icons-gallery.css
> +    --layout-grid-template-columns: repeat(auto-fill, minmax(150px, 150px));
```suggestion
    --layout-grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
```it looks better in mobile

2023-06-07 07:06 UTC, YonatanKra submitted a review, later dismissed

2023-06-07 08:52 UTC, rachelbt commented on apps/docs/assets/styles/icons-gallery.css
> +    display: flex;
```suggestion
    display: flex;
    flex-wrap: wrap;
```

2023-06-07 09:31 UTC, rachelbt approved these changes

2023-06-07 09:39 UTC, merged