fix(combobox): add properties documentation (VIV-1142)
Vonage/vivid-3 pull request #1219
Opened 2023-06-20 13:54 UTC by rinaok

2023-06-21 09:30 UTC, RichardHelm commented on libs/components/src/lib/combobox/README.md
> +- Default: `[]`
I'm assuming these are read-only? If so we should probably mention it

```suggestion
### options

A read-only list of options.

- Type: `Option[]`
- Default: `[]`

### selectedOptions

A read-only collection of the selected options.

- Type: `Option[]`
- Default: `[]`
```

2023-06-21 09:30 UTC, RichardHelm commented on libs/components/src/lib/combobox/README.md
> +- Default: `undefined`
It's -1 when nothing is selected? So I think we should document that as well
```suggestion
### selectedIndex

The index of the selected option or -1 if no option is selected.

- Type: `number`
- Default: `undefined`
```

2023-06-21 09:30 UTC, RichardHelm commented on libs/components/src/lib/combobox/combobox.spec.ts
> +	describe('selectedIndex', () => {
Maybe we should add a test for `options` as well
We should test all the things we describe in our documentation

2023-06-21 10:24 UTC, rinaok commented on libs/components/src/lib/combobox/combobox.spec.ts
> +	describe('selectedIndex', () => {
added

2023-06-21 14:23 UTC, YonatanKra requested changes
Small tests :)

2023-06-21 14:23 UTC, YonatanKra commented on libs/components/src/lib/combobox/combobox.spec.ts
> +
Missing API in tests:
`selectedOptions`

2023-06-21 14:23 UTC, YonatanKra commented on libs/components/src/lib/select/README.md
> +### selectedOptions
Not tested :)

2023-06-21 14:28 UTC, rinaok commented on libs/components/src/lib/select/README.md
> +### selectedOptions
it is tested 

![image](https://github.com/Vonage/vivid-3/assets/10883919/e27b4ace-0c8a-4d93-8ea6-3958c723d358)

2023-06-21 14:29 UTC, rinaok commented on libs/components/src/lib/combobox/combobox.spec.ts
> +
![image](https://github.com/Vonage/vivid-3/assets/10883919/0bd140b4-6f3d-4ed1-a93f-c5805637561e)

2023-06-21 14:32 UTC, YonatanKra commented on libs/components/src/lib/listbox/listbox.spec.ts
> +
Does it have its own `describe`?

2023-06-23 14:06 UTC, RichardHelm requested changes

2023-06-23 14:06 UTC, RichardHelm commented on libs/components/src/lib/select/ui.test.ts-snapshots/snapshots-select-Desktop-Firefox-linux.png
In the new screenshot one of the menu is not open anymore. This is a problem with this test where it sometimes is not open making it flaky.
We really need to fix the test, but in the meantime could you please regenerate the screenshot with the menu open?

2023-06-23 14:08 UTC, RichardHelm commented
@rinaok Looks great, I've copied the wording form combobox to the other READMEs as well
Just the screenshot needs updating

2023-06-25 15:00 UTC, YonatanKra approved these changes

2023-06-25 16:21 UTC, merged