feat(file-uploader): new component (VIV-962)
Vonage/vivid-3 pull request #1233
Opened 2023-06-28 15:10 UTC by rinaok

2023-06-30 19:29 UTC, RichardHelm requested changes

2023-06-30 19:29 UTC, RichardHelm commented on libs/components/src/lib/file-uploader/README.md
> +```
In this example we're not making use of the form at all. Let's give an example of uploading the file together with some other data:
```suggestion
### In a form

<style>
	form {
		width: 250px;
	}
	vwc-button {
		justify-self: flex-start;
	}
</style>
<form id='form'>
	<vwc-layout column-basis="block">
		<vwc-text-field name='username' label='Username'></vwc-text-field>
		<vwc-file-uploader id='fileUploader' label='Pick files' helper-text="multiple files of any type" max-files="50" upload-multiple>Drag & Drop or click to upload</vwc-file-uploader>
		<vwc-divider></vwc-divider>
		<vwc-button label='Submit' appearance='filled' shape='pill' type="submit"></vwc-button>
	</vwc-layout>
</form>
<script>
	form.addEventListener("submit", (event) => {
		event.preventDefault();
    
		const formData = new FormData(form);
		
		for (const [index, file] of fileUploader.files.entries()) {
			formData.append(`file[${index}]`, file);
		}

		const request = new XMLHttpRequest();
		request.open("POST", "/upload");
		request.send(formData);
	});
</script>
```
```

2023-07-02 08:34 UTC, rinaok commented on libs/components/src/lib/file-uploader/README.md
> +- Default: `false`
If we want it to be true by default, we should change the name of the attribute, for example `manual-upload`

2023-07-02 08:43 UTC, rinaok commented on libs/components/src/lib/file-uploader/README.md
> +```
I copied these CSS variables from vivid's 2 `custom size` example: https://vivid.vonage.com/?path=/story/components-file-picker-presentation--custom-size&args=self:!undefined

@AyalaBu In the figma file, we only have the `normal` and `extended` sizes. Is the custom size no longer needed?

What do you think, @rachelbt?

2023-07-02 09:06 UTC, AyalaBu commented on libs/components/src/lib/file-uploader/README.md
> +```
We didn't have a custom size in UI Kit 2.0
I think that we should allow the width to change, like in the text-field component,
but not the height.

2023-07-02 09:28 UTC, rachelbt commented on libs/components/src/lib/file-uploader/README.md
> +```
I agree about the width.
The hight need to have a css-variable and a default height because its there are other elements inside base.

2023-07-03 14:31 UTC, rinaok commented on package.json
> +    "dropzone": "^6.0.0-beta.2",
@YonatanKra Good question, Dropzone has dropped support for IE in the beta release. Should we support it? https://github.com/dropzone/dropzone/blob/main/CHANGELOG.md

2023-07-03 14:35 UTC, rinaok commented on libs/components/src/lib/file-uploader/file-uploader.ts
> +	}
@YonatanKra I am testing all of them.

2023-07-03 14:41 UTC, rinaok commented on libs/components/src/lib/file-uploader/file-uploader.spec.ts
> +			expect(element.getQueuedFiles().length).toEqual(0);
added `expect(element.getAcceptedFiles().length).toEqual(1);`

2023-07-03 14:54 UTC, rinaok commented on libs/components/src/lib/file-uploader/file-uploader.spec.ts
> +	describe('dictionary', function () {
We don't have a `dictionary` property but I combined all the `dict` tests together :

```
dictFileTooBig
dictResponseError
dictFileSizeUnits
dictInvalidFileType
dictMaxFilesExceeded
```

2023-07-03 14:56 UTC, rinaok commented on libs/components/src/lib/file-uploader/file-uploader.spec.ts
> +		it('should change text to dictFileSizeUnits', async function () {
The `dictFileSizeUnits` allows you to translate the different units. Starting with `tb` for terabytes and going down to `b` for bytes. So in the test, I'm changing the `MB` unit to a new text.

2023-07-03 15:03 UTC, rinaok commented on libs/components/src/lib/file-uploader/file-uploader.spec.ts
> +	describe('get files with error status', function () {
checks `getFilesWithErrorStatus`

2023-07-03 15:07 UTC, rinaok commented on libs/components/src/lib/file-uploader/file-uploader.spec.ts
> +			element.addFile(file);
@YonatanKra When it’s finished uploading

2023-07-03 15:14 UTC, rinaok commented on libs/components/src/lib/file-uploader/file-uploader.spec.ts
> +		it('should get queued files if not autoProcessQueue', async function () {
No, queuedFiles is only if 'autoProcessQueue' is not set

2023-07-03 15:18 UTC, rinaok commented on libs/components/src/lib/file-uploader/file-uploader.spec.ts
> +			expect(element.getQueuedFiles().length).toEqual(1);
no, but this test checks the QueuedFiles not the acceptedFiles

2023-07-03 15:22 UTC, rinaok commented on libs/components/src/lib/file-uploader/file-uploader.spec.ts
> +	describe('files', function () {
added :)

2023-07-03 15:24 UTC, rinaok commented on package.json
> +    "dropzone": "^6.0.0-beta.2",
@gfrileux @YonatanKra This beta version was released 2 years ago. 
https://www.npmjs.com/package/dropzone?activeTab=versions

2023-07-20 14:21 UTC, closed without merging