chore(ci): extract coverage upload into separate job (VIV-1136)
Vonage/vivid-3 pull request #1250
Opened 2023-07-06 14:22 UTC by RichardHelm

2023-07-09 05:51 UTC, YonatanKra requested changes
Great job!
Thanks!
Just a small change :)

2023-07-09 05:51 UTC, YonatanKra commented on .github/workflows/pull-request.yml
> +
We can move to relative paths so we wouldn't need to state the branch/commit hash.
See here:
https://github.com/Vonage/vivid-3/blob/main/.github/workflows/release-please.yml#L90

2023-07-10 08:55 UTC, RichardHelm commented on .github/workflows/pull-request.yml
> +
Ah, that's much better
Updated 👍

2023-07-11 05:03 UTC, YonatanKra approved these changes
Great stuff! Thanks!

2023-07-12 08:54 UTC, merged