fix(docs): prevent caching when there's a bad fetch (VIV-1195)
Vonage/vivid-3 pull request #1254
Opened 2023-07-09 14:58 UTC by YonatanKra

2023-07-09 16:07 UTC, rinaok requested changes
<img width="1752" alt="Screenshot 2023-07-09 at 19 06 52" src="https://github.com/Vonage/vivid-3/assets/10883919/7b8bb4ac-c86b-4d0a-96a6-b203e07ac2aa">


There is a problem loading fonts and pictures

2023-07-09 18:15 UTC, YonatanKra commented
> <img alt="Screenshot 2023-07-09 at 19 06 52" width="1752" src="https://user-images.githubusercontent.com/10883919/252155916-7b8bb4ac-c86b-4d0a-96a6-b203e07ac2aa.png">
> There is a problem loading fonts and pictures

Thanks. Strangely it works locally. Looking into it. Thanks again :)

2023-07-09 18:39 UTC, YonatanKra commented
@rinaok - can you recheck? Looks good on my end. Then again, it looked good before so... ;)

2023-07-10 07:31 UTC, rinaok commented
> icon.resources.vonage.com

@YonatanKra Yes, now it is loading :)

2023-07-10 07:32 UTC, rinaok commented on apps/docs/assets/bundled-scripts/sw.js
> +const iconsUrl = 'icon.resources.vonage.com';
Is it possible to make this a global url? It appears in multiple places in the code.

2023-07-12 06:59 UTC, YonatanKra commented on apps/docs/assets/bundled-scripts/sw.js
> +const iconsUrl = 'icon.resources.vonage.com';
It seems like a bigger issue due to how we our build works. I'll sort it out in a different [issue](https://jira.vonage.com/browse/VIV-1198).

2023-07-12 07:45 UTC, rinaok commented on apps/docs/assets/bundled-scripts/sw.js
> +const iconsUrl = 'icon.resources.vonage.com';
You can add it to this PR: https://jira.vonage.com/browse/VIV-1128

2023-07-12 07:45 UTC, rinaok approved these changes

2023-07-12 08:40 UTC, merged