chore(docs): update design tokens docs,fix color and add link (VIV-1201)
Vonage/vivid-3 pull request #1260
Opened 2023-07-12 07:54 UTC by rinaok

2023-07-12 13:52 UTC, YonatanKra requested changes
A small clarification and suggestion.

2023-07-12 13:52 UTC, YonatanKra commented on docs/design/foundations.md
> +</vwc-note></p>
I don't understand this part. What are the `Core Variables`? How do I use them? Do I need to use them? If not, do I need to know about them? Is it meant for a consumer? A Vivid developer/contributor?

2023-07-12 13:52 UTC, YonatanKra commented on docs/design/foundations.md
> +Using design tokens allows us to manage and maintain our design system as Vonage’s design Single source of truth.
These are 3 paragraphs that repeat the same idea: "What are design tokens?"

``` suggest
Design tokens are a set of values that maintain a design system. They represent anything defined by design: font size in pixel, a color as a RGB value, an opacity as a number, etc. They’re used instead of hard-coded values to ensure flexibility and unity across all product experiences.

Design tokens are directly integrated into our component libraries and UI kits and are the design's Single Source of Truth.
```

2023-07-12 13:55 UTC, rinaok commented on docs/design/foundations.md
> +</vwc-note></p>
@YonatanKra I think that we should remove all of this paragraph, but was afraid to erase everything lol. If you agree I can remove it, cause in my opinion nobody will read it.

2023-07-12 13:58 UTC, rinaok commented on docs/design/foundations.md
> +Using design tokens allows us to manage and maintain our design system as Vonage’s design Single source of truth.
@YonatanKra I think we can stay with this one and remove everything else:

`Design tokens are all the values needed to construct and maintain a design system — color, typography, spacing, object styles, sizing, etc.

Using design tokens allows us to manage and maintain our design system as Vonage’s design Single source of truth.`

WDYT?

2023-07-12 15:54 UTC, YonatanKra commented on docs/design/foundations.md
> +</vwc-note></p>
Let's remove it. It means nothing to both of us :)

2023-07-12 15:59 UTC, YonatanKra commented on docs/design/foundations.md
> +Using design tokens allows us to manage and maintain our design system as Vonage’s design Single source of truth.
I don't like this phrasing: `Design tokens are all the values needed to construct and maintain a design system`
This one is a bit more straightforward: `Design tokens are a set of values that maintain a design system.`
(I even asked Grammarly ;) )
IMO, breaking two ideas into two sentences is better than combining them into one less understandable one.
The 2nd sentence in your version repeats on `maintain` again, which IMO is less preferable. I tried to reduce repeatition and add some more info - or go over the same one in a different way at least.
So I'll go with:
```
Design tokens are a set of values that maintain a design system. 
They represent anything defined by design: font size in pixel, a color as a RGB value, an opacity as a number, etc. 

The Design Tokens are the design system's Single Source of Truth.
```
WDYT?

2023-07-12 16:47 UTC, YonatanKra commented on docs/design/foundations.md
> +Using design tokens allows us to manage and maintain our design system as Vonage’s design Single source of truth.
Definitely.
Maybe gradients belong to Colors and design tokens need to be on its own page?

2023-07-13 08:45 UTC, rinaok commented on docs/design/foundations.md
> +Using design tokens allows us to manage and maintain our design system as Vonage’s design Single source of truth.
I changed it to Guidelines instead of Foundations cause it's guidelines about design-tokens.

2023-07-13 10:24 UTC, YonatanKra approved these changes
LGTM. Thanks!

2023-07-13 10:25 UTC, merged