feat(menu-item): allow default action when role is presentation (VIV-1183)
Vonage/vivid-3 pull request #1272
Opened 2023-07-17 12:54 UTC by YonatanKra

2023-07-17 13:16 UTC, rinaok requested changes

2023-07-17 13:16 UTC, rinaok commented on libs/components/src/lib/menu-item/README.md
> +```
1. The example should be inside a menu like all the other examples.
2. How the user can navigate and click on the menu-item if the menu is not focusable?

2023-07-17 13:20 UTC, rinaok requested changes

2023-07-17 13:20 UTC, rinaok commented on libs/components/src/lib/menu-item/README.md
> +	</a>
![Screenshot 2023-07-17 at 16 19 36](https://github.com/Vonage/vivid-3/assets/10883919/b5869934-f38e-4958-b5c6-1d28f319edf9)

Can't see the example

2023-07-17 13:31 UTC, YonatanKra commented on libs/components/src/lib/menu-item/README.md
> +```
1. Sure
2. You are right. It works, but the focus needs to be corrected visually.
Thanks!

2023-07-17 14:08 UTC, rachelbt reviewed
we have some issues with this:
1. we can't force style on the a - and we are counting on devs to add text-decoration: none to the a.
2. We have as you said - focus from the A and not from the menu item.
:(

2023-07-18 11:08 UTC, rinaok approved these changes

2023-07-18 11:50 UTC, merged