fix(text-filed): nicer visual focus with slotted action items (VIV-1224)
Vonage/vivid-3 pull request #1280
Opened 2023-07-20 07:46 UTC by rachelbt

2023-07-20 08:39 UTC, rachelbt commented
> There's something wrong with the Firefox snapshots

yeh I know - didn't want to regenerate all.
Waiting for @AyalaBu and then I'll open this to code-review and I'll fix the png :)
Thanks!

2023-07-24 11:29 UTC, YonatanKra commented on libs/components/src/lib/text-field/text-field.spec.ts
> +			const baseElementHasNoHeader = element.shadowRoot?.
`baseElementHasNoHeader` - why is that named like this? What's it supposed to be?

2023-07-24 15:49 UTC, YonatanKra requested changes

2023-07-25 03:39 UTC, YonatanKra approved these changes

2023-07-25 06:38 UTC, merged