feat(file-picker): add file-picker component (VIV-962)
Vonage/vivid-3 pull request #1284
Opened 2023-07-20 13:00 UTC by RichardHelm

2023-07-24 10:45 UTC, rinaok requested changes
The validation message (https://vivid.deno.dev/components/text-field#validation) is missing.
If the file picker is empty when you click submit, but you must choose a file, what happens?

2023-07-24 10:45 UTC, rinaok commented on libs/components/src/lib/file-picker/file-picker.template.ts
> +		<div class="base" aria-label="${x => x.label}">
What happens if the user adds only an `aria-label`? 

<img width="1238" alt="Screenshot 2023-07-24 at 13 10 59" src="https://github.com/Vonage/vivid-3/assets/10883919/1f8e0ae3-69d6-4c4d-ad41-5f304faac43b">

2023-07-24 10:45 UTC, rinaok commented on libs/components/src/lib/file-picker/file-picker.template.ts
> +				<slot class="main"></slot>
Maybe we should have a Placeholder instead of a slot like in other components?  https://vivid.deno.dev/components/text-field#placeholder

2023-07-24 10:45 UTC, rinaok commented on libs/components/src/lib/file-picker/file-picker.spec.ts
> +		});
What should it expect at the end?

2023-07-24 10:45 UTC, rinaok commented on libs/components/src/lib/file-picker/file-picker.scss
> +	min-inline-size : 400px;
```suggestion
	inline-size: 400px;
```

2023-07-24 10:45 UTC, rinaok commented on libs/components/src/lib/file-picker/file-picker.ts
> +	}
Can it be private if it is only used internally?

2023-07-24 10:45 UTC, rinaok commented on libs/components/src/lib/file-picker/ui.test.ts
> +const components = ['file-picker', 'button', 'layout', 'divider'];
```suggestion
const components = ['file-picker', 'button', 'layout', 'text-field'];
```

2023-07-24 10:45 UTC, rinaok commented on apps/docs/_data/components.json
> +			"/assets/modules/components/divider/index.js",
```suggestion
			"/assets/modules/components/text-field/index.js",
```

2023-07-24 11:00 UTC, rinaok commented on libs/components/src/lib/file-picker/file-picker.template.ts
> + * @param context
![Screenshot 2023-07-24 at 14 00 34](https://github.com/Vonage/vivid-3/assets/10883919/a7abf870-5dc7-4e09-823c-c9a821d79218)

2023-07-24 13:26 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.template.ts
> +		<div class="base" aria-label="${x => x.label}">
When putting `aria-label` on vwc-file-picker element:
![image](https://github.com/Vonage/vivid-3/assets/86777660/b18d62c5-ad11-4ae1-9a68-e9176bb4b659)

I removed adding it to base as well, as we would then have 2 `aria-label`

2023-07-24 13:31 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.template.ts
> +				<slot class="main"></slot>
So when I did the `empty-state` we decided to not put any default text inside as it's not in line with other components, and I think the same reasoning would apply here

2023-07-24 13:31 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.spec.ts
> +		});
Expecting no error, I updated the test to make it explicit

2023-07-24 13:32 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.scss
> +	min-inline-size : 400px;
Oh I meant to put `max-inline-size`. I don't think it should have a fixed size

2023-07-24 13:33 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.ts
> +	}
Unfortunately not as it's used by the template

2023-07-24 16:40 UTC, RichardHelm commented
@rinaok I made some changes, please have another look
I looked into the validation issue but because the file-picker is not a form element, it's difficult to add validation support

2023-07-25 09:26 UTC, rinaok commented
> @rinaok I made some changes, please have another look I looked into the validation issue but because the file-picker is not a form element, it's difficult to add validation support

Approved :) Can you just open a Jira issue to add a validation error to the file picker?

2023-07-25 09:26 UTC, rinaok submitted a review, later dismissed

2023-07-26 09:38 UTC, RichardHelm commented
> > @rinaok I made some changes, please have another look I looked into the validation issue but because the file-picker is not a form element, it's difficult to add validation support
> 
> @RichardHelm Approved :) Can you just open a Jira issue to add a validation error to the file picker?

Sure, let's use the old ticket we already have: https://jira.vonage.com/browse/VIV-802

2023-07-26 09:50 UTC, rinaok approved these changes

2023-07-26 13:07 UTC, merged