feat(menu): add header footer and action items slots (VIV-947)
Vonage/vivid-3 pull request #1285
Opened 2023-07-20 15:53 UTC by rinaok

2023-07-24 10:34 UTC, rachelbt reviewed
went over the template and the css - left some comments :)

2023-07-24 10:34 UTC, rachelbt commented on libs/components/src/lib/menu/README.md
> +### Action Items
why do we nned both action-items and footer?

2023-07-24 10:34 UTC, rachelbt commented on libs/components/src/lib/menu/menu.scss
> +	flex-direction: column;
```suggestion
	flex-direction: column;
	gap: 8px;
```

2023-07-24 10:34 UTC, rachelbt commented on libs/components/src/lib/menu/menu.scss
> +	padding: 24px 24px 0;
```suggestion
	padding-inline: 16px;
	padding-block-start: 8px;
```

2023-07-24 10:34 UTC, rachelbt commented on libs/components/src/lib/menu/menu.scss
>  	min-inline-size: var(#{variables.$menu-min-inline-size});
I'm not sure this need to be here - this needs to be on the base

2023-07-24 10:34 UTC, rachelbt commented on libs/components/src/lib/menu/menu.scss
>  	min-inline-size: var(#{variables.$menu-min-inline-size});
also the overflow

2023-07-24 10:34 UTC, rachelbt commented on libs/components/src/lib/menu/menu.scss
>  	min-inline-size: var(#{variables.$menu-min-inline-size});
and remove the `padding-block: 8px;`

2023-07-24 10:34 UTC, rachelbt commented on libs/components/src/lib/menu/menu.scss
> +	padding: 0 24px 24px;
```suggestion
	padding-inline: 16px;
	padding-block-end: 8px;
```

2023-07-24 10:34 UTC, rachelbt commented on libs/components/src/lib/menu/menu.template.ts
> +			</div>
I don't think this is needed - we only need a footer slot.
maybe a validation components for cancel submit is needed...\

2023-07-24 10:34 UTC, rachelbt commented on libs/components/src/lib/menu/README.md
> +  <vwc-checkbox slot="footer" label="I agree"></vwc-checkbox>
```suggestion
```
Not sure this has to do with the menu-items :)

2023-07-24 10:49 UTC, rinaok commented on libs/components/src/lib/menu/README.md
> +### Action Items
Similar to dialog. The examples all had action items at the bottom. Do you think we don't need it?

2023-07-24 10:56 UTC, rinaok commented on libs/components/src/lib/menu/menu.template.ts
> +			</div>
@rachelbt But the same as in dialog all the examples have two action-buttons at the bottom :( 
https://docs.google.com/document/d/1Ag5Nmu53-v6YgqWpN_Uz_K4-KSOYWzRGLhWqrvT6GXU/edit#heading=h.36st4rl33pcx

2023-07-24 10:58 UTC, rinaok commented on libs/components/src/lib/menu/README.md
> +  <vwc-checkbox slot="footer" label="I agree"></vwc-checkbox>
@rachelbt Just wanted to show an example for the footer combined with the action buttons, do you have another idea?

2023-07-24 11:37 UTC, RichardHelm requested changes

2023-07-24 11:37 UTC, RichardHelm commented on libs/components/src/lib/menu/menu.scss
> -	padding-block: 8px;
The menu without header/footer is now missing the padding: 
![image](https://github.com/Vonage/vivid-3/assets/86777660/4c952bed-738e-426e-9af6-e019b9dcbaa0)

2023-07-24 11:45 UTC, RichardHelm commented on libs/components/src/lib/menu/README.md
> +## Use Cases
Can I put arbitrary content in default slot? Like data-grid?
![image](https://github.com/Vonage/vivid-3/assets/86777660/2d77f9fa-b254-4182-91b2-3c47f206118d)

Can we add a use case for that please?

2023-07-24 14:02 UTC, rinaok commented on libs/components/src/lib/menu/README.md
> +## Use Cases
@RichardHelm This is an example from vivid-2. We don't have checkboxes inside a data-grid in vivid-3. And also, I'm not sure if it is correct to do it. We have menu-items for checkboxes.

2023-07-24 16:22 UTC, rinaok commented on libs/components/src/lib/menu/README.md
> +### Action Items
Updated to only action-items, removed the footer

2023-07-24 17:24 UTC, RichardHelm commented on libs/components/src/lib/menu/README.md
> +## Use Cases
It's just an example. What I mean is you are supposed to be able to put anything inside menu, right?
And if you do that, will it break accessibility?

So we should have an example for that.

E.g. in dashboard we have this (nav-items):
![image](https://github.com/Vonage/vivid-3/assets/86777660/e4ee3199-6e61-48d8-9e41-b0f3c9ceb111)

2023-07-25 13:55 UTC, rachelbt reviewed
css + HTML looks good!
The only thing that worth considering in a different ticket is the scroll - if there's a need for sticky header or footer or both.

2023-07-26 08:47 UTC, RichardHelm approved these changes

2023-07-26 08:58 UTC, merged