feat(split-button): add new component (VIV-786)
Vonage/vivid-3 pull request #1297
Opened 2023-08-03 14:32 UTC by rinaok

2023-08-08 06:54 UTC, YonatanKra requested changes
Great job! I like how it was done!

I've written 12 comments. Many of them are testing style suggestions I think make the code clearer and easier to read.

I've written a few that require a bit more thinking. Please let me know when you're on it, and we can discuss it online.

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/README.md
> +### Icon with Label
This is not an API. It better fits into the `Use Cases` section IMO.

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.spec.ts
> +			expect(control).toBeInstanceOf(Element);
I think this is more explicit:
```suggestion
			const controlHasDisabledClass = getControlElement(element).classList.contains(`appearance-${appearance}.disabled`);
			expect(controlHasDisabledClass).toBeTruthy();
```

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.spec.ts
> +			expect(control?.classList.contains(`size-${size}`)).toBeTruthy();
```suggestion
			const control = getControlElement(element);
			expect(control?.classList.contains(`size-${size}`)).toBeTruthy();
```

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.spec.ts
> +			expect(control).toBeInstanceOf(Element);
```suggestion
			const control = getControlElement(control); 
			expect(control.classList.contains(`appearance-${appearance}`).toBeTruthy();
```

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.spec.ts
> +			expect(control).toBeInstanceOf(Element);
```suggestion
			const control = getControlElement(element); 
			expect(control.classList.contains(`shape-${shape}`).toBeTruthy();
```

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.spec.ts
> +			expect(control).toBeInstanceOf(Element);
```suggestion
			const control = getControlElement(element); 
			expect(control.classList.contains(`connotation-${connotation}`).toBeTruthy();
```

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.spec.ts
> +			const control = element.shadowRoot?.querySelector('.control');
```suggestion
			const control = getControlElement(element);
```

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.template.ts
> +		?autofocus="${(x) => x.autofocus}"
Can you please add a test for this?

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.template.ts
> +		aria-haspopup="true"
This is tricky.
We assume it has a popup because that's our use case. Might it actually not have a popup (user didn't set it)?

Two points here:
1. Note that `menu` controls the `aria-haspopup` of its anchor. Maybe it should be delegated to the `popup` itself? What do you think?
2.  If we choose to leave this `true`, as this is the use case, I think we should mention this in the a11y section of the docs => `if you are using a split button, you must set the menu to its indicator`

What do you think?

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.template.ts
> +		?autofocus="${(x) => x.autofocus}"
I already mentioned this above for testing, but now I see that we have two elements with `autofocus`. It's kind of meaningless, because only the first one is taken into account according to the spec. Is there a reason why this `autofocus` is here?

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.template.ts
> +		aria-pressed="${(x) => x.ariaPressed}"
A few questions here:
1. What's the meaning of `aria-invalid` in the case of `split-button`?
2. I think we should add an a11y section in the docs according to [this](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live). This is important as the value might change according to the value in the menu(?).
3. These values are not tested and are not even mentioned in the `basic` section. Can you add a test for them as well?
4. Do we have a `pressed` state on this button?

2023-08-08 06:54 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.template.ts
> +		aria-labelledby="${(x) => x.ariaLabelledBy}">
Can you make sure these are tested, please?

2023-08-08 06:59 UTC, rachelbt reviewed
I didn't see that @YonatanKra was also reviewing the PR. I checked only the template + css.
the split button looks good, left some comments to make it better :)
some general comments:
1. the aria-label that is added - is implemented on both buttons - but it should be only on the more option. Having said that- we need to think tow to set an aria-label if there's only icon in the control button.
2. the outline divider is on top of the outer border
3. this one is for @AyalaBu - the half disable state is strange - especially the outline one.
4. is it possible to place the menu to the bottom-start of the indicator button? I think a use case for split-button and menu will be nice (and remove it from the first preview - so users will not expect a menu in the template)
5. really sorry - have some more css comments - but I want to wait with them after you finish what I left for now :)

2023-08-08 06:59 UTC, rachelbt commented on libs/components/src/lib/split-button/split-button.scss
> +	@include appearance.appearance;
isn't it better to set this on the base?

2023-08-08 06:59 UTC, rachelbt commented on libs/components/src/lib/split-button/split-button.scss
> +	&:not(.icon-only) {
icon-only class is never set

2023-08-08 06:59 UTC, rachelbt commented on libs/components/src/lib/split-button/split-button.template.ts
> +		<div class="base">
I wonder if we need to add this: `role="group"`

2023-08-08 06:59 UTC, rachelbt commented on libs/components/src/lib/split-button/split-button.scss
> +	&.icon-only {
this is not working - no class like this is added in the template

2023-08-08 06:59 UTC, rachelbt commented on libs/components/src/lib/split-button/split-button.scss
> +		border-left: 0;
why is this needed?

2023-08-08 06:59 UTC, rachelbt commented on libs/components/src/lib/split-button/split-button.scss
> +		@include mixins.get-size-properties(
control need all this, but indicator does not.

2023-08-08 06:59 UTC, rachelbt commented on libs/components/src/lib/split-button/split-button.scss
> +			width: 22px;
try using the size property and not fixed px.

2023-08-08 06:59 UTC, rachelbt commented on libs/components/src/lib/split-button/split-button.template.ts
> +		class="control ${getClasses}"
it feels like its more clean to move this to base - then you have the class only once.

2023-08-08 06:59 UTC, rachelbt commented on libs/components/src/lib/split-button/split-button.ts
> +	@attr({ mode: 'boolean' }) open = false;
is this needed?

2023-08-08 07:29 UTC, AyalaBu commented on libs/components/src/lib/split-button/split-button.scss
> +	$connotations: accent cta success alert,
There was no half disabled design for a split button.
I don't think it should be allowed.
Also, I didn't see it even once.
If it's disabled, then it's wholly disabled.

2023-08-08 07:31 UTC, AyalaBu commented on libs/components/src/lib/split-button/split-button.scss
> +	$default: ghost
I believe it is filled, but it really can depend on the designer's decision.

2023-08-08 11:20 UTC, rinaok commented on libs/components/src/lib/split-button/split-button.scss
> +		@include mixins.get-size-properties(
why not?

2023-08-08 11:20 UTC, rinaok commented on libs/components/src/lib/split-button/split-button.template.ts
> +		class="control ${getClasses}"
are you talking about control?

2023-08-08 14:29 UTC, rinaok commented on libs/components/src/lib/split-button/split-button.template.ts
> +		aria-haspopup="true"
@YonatanKra Basically the split button's structure should be like this:

`<div role="group" aria-label="Split Button Example">
  <button id="main-button">Main Action</button>
  <button aria-haspopup="true" aria-expanded="false" aria-controls="dropdown-menu">▼</button>
  <ul id="dropdown-menu" role="menu" aria-labelledby="main-button">
    <li role="menuitem"><a href="#">Option 1</a></li>
    <li role="menuitem"><a href="#">Option 2</a></li>
    <li role="menuitem"><a href="#">Option 3</a></li>
  </ul>
</div>`

That's why I wanted to add the menu with a slot inside to the template. If that was the case we could handle the expanded, I mentioned this issue in the doc.

1. aria-haspopup should be on menu not on the popup.
2. I can add it to the a11y section.

2023-08-08 14:51 UTC, rinaok commented on libs/components/src/lib/split-button/split-button.template.ts
> +		<div class="base">
added

2023-08-08 14:51 UTC, rinaok commented on libs/components/src/lib/split-button/split-button.scss
> +	@include appearance.appearance;
the two buttons will not get the appearance

2023-08-09 08:21 UTC, YonatanKra commented on libs/components/src/lib/split-button/split-button.template.ts
> +		aria-haspopup="true"
1. `has-popup` let's split the question:

- The attribute should be on the anchor, or should it not? 
- What I meant by delegating the `has-popup` to the popup was that currently menu is doing that. Other components that are using the `popup` don't. Is there a use case of using the popup where we don't want the anchor to have `has-popup`?

2. The `menu` auto adds the `has-popup` attribute to the anchor, so there's no need to hard-code it to `true` (IMO). This way, if someone adds a menu, the menu will add `has-popup`. If no menu was added, there's no popup... do you think this covers our use cases?

2023-08-10 09:26 UTC, rachelbt reviewed
@rinaok @AyalaBu 
I changed the css, I think now it fits the design better.
@AyalaBu the indicator width of the condensed and expanded are not as in Figma since there's no values of size of 38px or 26px in our sizes.
Also - there was difference in the separator opacity. I gave all 0.35.

2023-08-10 10:36 UTC, rinaok commented
> 

The outlined hover doesn't look good now:

![image](https://github.com/Vonage/vivid-3/assets/10883919/6420cb85-97e1-47e6-8abe-a9507c5e5a80)

2023-08-10 10:45 UTC, AyalaBu commented
Looks great!

Aside of one issue:
Outline button hover state looks kind of off,
but only when you hover the more actions part.
![Screenshot 2023-08-10 at 13 44 28](https://github.com/Vonage/vivid-3/assets/106529909/87c4d3e3-1781-4fab-a4c3-9b7b51c81732)

2023-08-10 11:46 UTC, rachelbt commented
> Looks great!
> 
> Aside of one issue: Outline button hover state looks kind of off, but only when you hover the more actions part. ![Screenshot 2023-08-10 at 13 44 28](https://user-images.githubusercontent.com/106529909/259715443-87c4d3e3-1781-4fab-a4c3-9b7b51c81732.png)

@AyalaBu @rinaok 
I fixed the hover issue :)

2023-08-10 11:47 UTC, rachelbt commented on libs/components/src/lib/split-button/README.md
> +      alert("clicked on action");
this is kind of nagging, and seems a bit unrelated to the documentation

2023-08-10 12:03 UTC, rinaok commented on libs/components/src/lib/split-button/README.md
> +      alert("clicked on action");
But it shows the users how to use it, maybe I can move it to use cases

2023-08-10 12:13 UTC, rinaok commented on libs/components/src/lib/split-button/README.md
> +      alert("clicked on action");
@rachelbt Updated

2023-08-10 12:43 UTC, rachelbt approved these changes

2023-08-10 12:43 UTC, merged