chore(build): replace esbuild with rollup
Vonage/vivid-3 pull request #13
Opened 2021-11-09 14:53 UTC by YonatanKra

2021-11-09 15:12 UTC, yinonov requested changes
should rollup.config.js be .git ignored?

2021-11-09 15:12 UTC, yinonov commented on rollup.config.ts
> +
should we?
```suggestion

/**
 * @type {import('rollup').RollupOptions}
 */
```

2021-11-10 05:08 UTC, YonatanKra commented on rollup.config.js
> +// };
Removed :)

2021-11-10 05:10 UTC, YonatanKra commented on rollup.config.ts
> +
What for?

2021-11-10 07:38 UTC, yinonov commented on package.json
> +    "build": "rollup -c",
I kind of like the separation of scripts to files

2021-11-10 07:39 UTC, yinonov commented on rollup.config.ts
> +
https://rollupjs.org/guide/en/#config-intellisense
maybe not needed in the ts case?

2021-11-10 08:49 UTC, YonatanKra commented on rollup.config.ts
> +
Not needed. That's why I'm using TS anywhere possible.

2021-11-10 08:50 UTC, YonatanKra commented on package.json
> +    "build": "rollup -c",
In the future, when we will have a good reason to do so, and the capacity to maintain scripts, I am all for it. This is why I postponed with Nx cause building the `generators` and `executors` is a big task.

2021-11-10 08:51 UTC, YonatanKra commented on rollup.config.ts
> +
This file is no longer in the repo BTW.

2021-11-10 09:11 UTC, yinonov approved these changes

2021-11-10 09:26 UTC, yinonov approved these changes

2021-11-10 09:26 UTC, merged