feat(date-picker): add date-picker component (VIV-1244)
Vonage/vivid-3 pull request #1324
Opened 2023-08-10 18:33 UTC by RichardHelm

2023-08-13 11:29 UTC, rachelbt reviewed
WOW - this is one of a big component!! 👏 👏 
Went over css - a little on the HTML structure in the template.
In general - it looks very good - left some comments regarding colors, appearance and using grid over flex.

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +	display: flex;
why not use `display: grid `- and then you can also remove the `months-row` wrapper div.

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +		position: relative;
why is this needed?

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +		font: var(#{constants.$vvd-typography-base-extended});
please add color - in all the buttons - otherwise it gets button default of browser or user agent (in my safari  iphone it get s blue)

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +		}
why not use appearance ghost + connotation?

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +		block-size: 48px;
the buttons sets the block-side - why is this needed?

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +	display: flex;
you can use `display: grid` and remove all un-needed row wrappers and padding or margin on the calendar children

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +	margin-top: 7px;
we try to avoid odd numbers - 8px is better :)

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +	.calendar-separator {
again - cant this be done with `::before`?

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +	}
this will be un-needed if you use `grid`

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +		position: relative;
```suggestion

```
what is this needed for?

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +
why not use appearance states?

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +		font: var(#{constants.$vvd-typography-base});
also - add color :)

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +		inline-size: 48px;
you can use `aspect-ratio`
https://caniuse.com/mdn-css_properties_aspect-ratio

2023-08-13 11:29 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +		}
again - cant we use appearance?

2023-08-14 17:57 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.template.ts
> +						${renderMonthPickerGrid(context)}
I tried this but it didn't work well with the layout, so changed it to `vwc-divider` with `role="presentation"` now

2023-08-14 17:58 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +	display: flex;
It seems the aria `grid` requires the use of a row element with `role="row"`
Therefore leaving this

2023-08-14 17:59 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +		font: var(#{constants.$vvd-typography-base-extended});
Sure, added 👍

2023-08-14 18:00 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +		}
Good point, I added it now

2023-08-14 18:00 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +		block-size: 48px;
I changed it to a padding now 👍

2023-08-14 18:01 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +	margin-top: 7px;
Sure 👍

2023-08-14 18:02 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +	.calendar-separator {
Same here

2023-08-14 18:02 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +	display: flex;
Same here

2023-08-14 18:02 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +		position: relative;
Same as the other buttons

2023-08-14 18:02 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +
Done

2023-08-14 18:02 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +		font: var(#{constants.$vvd-typography-base});
Done

2023-08-14 18:02 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +		inline-size: 48px;
Sure, done 👍

2023-08-14 18:03 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.scss
> +		}
Yes, done

2023-08-15 12:05 UTC, YonatanKra commented
When I select a date, I'm focused inside the input. Clicking the input again does not open the calendar to pick another date. I need to blur and refocus in order to get the date picker again.

2023-08-15 14:02 UTC, YonatanKra requested changes
Wow! That's a big one!
Nice work! A few comments and discussions. Less than I'd expect for such a big PR :)

2023-08-18 12:49 UTC, RichardHelm commented on libs/components/src/lib/components.ts
> +export * from './date-picker';
Yes, fixed 👍

2023-08-18 12:49 UTC, RichardHelm commented on libs/components/src/lib/date-picker/calendar/calendarGrid.spec.ts
> +		expect(grid.grid[0][2].isOutsideMonth).toBe(false);
Sure, done

2023-08-18 12:52 UTC, RichardHelm commented on libs/components/src/lib/date-picker/calendar/calendarGrid.spec.ts
> +	describe('for August 2023 with en-US locale', () => {
It's just an example, changed it to `for the example month August 2023`

2023-08-18 12:53 UTC, RichardHelm commented on libs/components/src/lib/date-picker/calendar/calendarGrid.ts
> +export const buildCalendarGrid = (
Done 👍

2023-08-18 12:56 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.spec.ts
> +		// Unfortunately it causes jest to throw "TypeError: Converting circular structure to JSON" when a test fails
Yes, when a test fails jest will throw that error if the workaround is in place. I don't know why

In our case we're focussing an element is inside the shadow dom, so `shadowRoot.activeElement` should be set to the element. But JSDOM does not do that, which breaks the code and we cannot test it

2023-08-18 12:56 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.spec.ts
> +		it('should not prevent default when pressing any other key', async () => {
Sure done 👍

2023-08-18 12:57 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.spec.ts
> +			expect(getDialogTitle()).toBe('August 2023');
Ok, updated with `expect(element.shadowRoot!.querySelector('.month-grid')).toBeNull();`

2023-08-18 12:59 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.ts
> +		this.$emit('change');
No, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) it should be fired here:
> Depending on the kind of element being changed and the way the user interacts with the element, the change event fires at a different moment:
...
> When the user commits the change explicitly (e.g., by selecting a value from a <select>'s dropdown with a mouse click, by selecting a date from a date picker for <input type="date">

2023-08-18 13:04 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.ts
> +	@observable selectedMonth = getCurrentMonth();
I have considered this, but I think it would be overkill and make testing etc. harder

Instead I've now prefixed all the internal members with `_`, WDYT?

2023-08-18 13:06 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.ts
> +	onBaseKeyDown(event: KeyboardEvent) {
See other comment

2023-08-18 13:06 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.ts
> +	onPrevYearClick() {
See other comment

2023-08-18 13:07 UTC, RichardHelm commented on libs/components/src/lib/date-picker/ui.test.ts
> +test('should show the component', async ({ page }: { page: Page }) => {
Sure, I've added an e2e test now for basic select functionality

2023-08-18 13:08 UTC, RichardHelm commented
@YonatanKra , please have another look.

I've changed the functionality to open the popup again when clicking on the text field, or, for keyboard users, when pressing enter

2023-08-20 11:47 UTC, rachelbt reviewed
CSS - LGTM
I wonder if we need to consider adding a button to open the date-picker (like in t[his example](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/)) because in mobile its a bit annoying that pressing the text-field open both the keyboard and the the popup.
@AyalaBu WDYT? maybe only in mobile we need to do this change.
This can be in a separate PT I think :)

2023-08-20 11:47 UTC, rachelbt commented on libs/components/src/lib/date-picker/date-picker.scss
> +		color: var(#{constants.$vvd-color-canvas-text});
```suggestion
		color: var(#{constants.$vvd-color-canvas-text});
		#{focus-variables.$focus-stroke-gap-color}: transparent;
```
this is to make the focus outline lighter.
You may also need to add:
`@use "../focus/partials/variables" as focus-variables;
`

2023-08-21 07:30 UTC, YonatanKra commented on libs/components/src/lib/date-picker/date-picker.ts
> +	@observable selectedMonth = getCurrentMonth();
Still unsure if this is the right way to go exposing all that stuff. 
I also think it's a bigger discussion and shouldn't hold this PR :)

2023-08-21 09:54 UTC, YonatanKra approved these changes
Nice work! Thanks!
Can you just connect the form association ticket from JIRA to this PR for later reference please?

2023-08-21 09:58 UTC, RichardHelm commented
Sure, it's [VIV-1272](https://jira.vonage.com/browse/VIV-1272)

2023-08-21 10:24 UTC, merged

2023-09-04 06:46 UTC, AyalaBu commented on libs/components/src/lib/date-picker/date-picker.scss
> +		}
MUI updated their datepicker and actually changed it a bit and added a button to open a datepicker only.
I really like it and I think that we should consider this behavior.
I think it is a better UX.

https://mui.com/x/react-date-pickers/date-picker/#basic-usage

WDYT?