fix(typography): fix font-setting typography css (VIV-1262)
Vonage/vivid-3 pull request #1332
Opened 2023-08-16 14:10 UTC by rachelbt

the fix was initially only adding documentation however it let to:
- fixing wrong setting of font for sub sup text
- adding class .base for use to text (equivalent to p element)
- adding option for removing margin-block with tight class

2023-08-17 09:33 UTC, RichardHelm requested changes

2023-08-17 09:33 UTC, RichardHelm commented on docs/getting-started/advanced.md
> +[see all usage examples in the Typography](/designs/typography/#Using-Vivid-Typography).
```suggestion
[See typography usage examples](/designs/typography/#Using-Vivid-Typography).
```

2023-08-17 09:33 UTC, RichardHelm commented on libs/components/package-lock.json
Why was this file added? Can we remove it?

2023-08-17 09:33 UTC, RichardHelm commented on docs/design/typography.md
> +Use the class `tight` to remove `margin-block`.
I think we should add here that the css needs to be included for this
```suggestion
## Using Vivid Typography

The Vivid typography css is optional. To use it, you will need to [include the typography styles](/getting-started/advanced).

The typography style target both HTML tags and css classes.  
All `headlines` and `p` elements also get `margin-block`.  
Use the class `tight` to remove `margin-block`.  
```

2023-08-17 09:48 UTC, rachelbt commented on libs/components/package-lock.json
by mistake - I'll revert it

2023-08-21 09:45 UTC, RichardHelm approved these changes

2023-08-22 12:18 UTC, merged