fix(select): add placeholder (VIV-1242)
Vonage/vivid-3 pull request #1333
Opened 2023-08-16 14:40 UTC by rinaok

2023-08-21 10:40 UTC, RichardHelm requested changes

2023-08-21 10:40 UTC, RichardHelm commented on libs/components/src/lib/select/select.spec.ts
> +			await elementUpdated(element);
Why does this test not have the placeholder here?

It doesn't seem to work when setting both the placeholder and `selected` / `value`

```suggestion
		it('should change selectedindex -1 when option selected', async () => {
			element = (await fixture(
				`<${COMPONENT_TAG} placeholder="placeholder">
					<option value="1">1</option>
					<option value="2" selected>2</option>
					<option value="3">3</option>
				</${COMPONENT_TAG}>`
			)) as Select;

			await elementUpdated(element);
```

2023-08-21 10:40 UTC, RichardHelm commented on libs/components/src/lib/select/select.spec.ts
> +	describe('placeholder', function () {
Can we add some more tests here please?
Maybe that the placeholder is displayed and that, like selectedIndex, value will be as expected

2023-08-21 10:40 UTC, RichardHelm commented on libs/components/src/lib/select/select.spec.ts
> +		it('should set selectedindex -1 when placeholder', async () => {
```suggestion
		it('should set selectedindex -1 when placeholder is set', async () => {
```

2023-08-21 10:40 UTC, RichardHelm commented on libs/components/src/lib/select/select.ts
> +	 * The ref to the internal `.control` element.
```suggestion
	 * The ref to the internal placeholder option.
```

2023-08-21 19:23 UTC, RichardHelm reviewed
Looks good now!
Just the screenshots seem to be failing now

2023-08-22 08:36 UTC, rinaok commented
> Looks good now! Just the screenshots seem to be failing now

@RichardHelm They didn't pass because of the date-picker.

2023-08-22 09:05 UTC, RichardHelm approved these changes

2023-08-22 09:11 UTC, merged