feat(docs): add locale switcher (VIV-1274)
Vonage/vivid-3 pull request #1342
Opened 2023-08-21 17:56 UTC by RichardHelm

When adding `locale-switcher` to preview:
```diff
```html preview locale-switcher
```

It will add a locale switcher with the example:
![image](https://github.com/Vonage/vivid-3/assets/86777660/158fe8a3-fa42-4a92-94bb-c123676d0579)

2023-08-22 04:16 UTC, YonatanKra requested changes
A small change for future generations :)

2023-08-22 04:16 UTC, YonatanKra commented on apps/docs/rollup.config.js
> +
The global scope is getting crowded :)
Please create functions by concern (inputs, locales, importsFile) for better readability.

2023-08-22 15:22 UTC, RichardHelm commented on apps/docs/rollup.config.js
> +
Sure, I refactored the file

2023-08-23 07:59 UTC, YonatanKra approved these changes
Great stuff. Thanks!

2023-08-23 08:37 UTC, merged