feat(listbox): publish listbox and add shape and orientation (VIV-863)
Vonage/vivid-3 pull request #1345
Opened 2023-08-22 13:25 UTC by rinaok

2023-08-27 09:35 UTC, rinaok commented
> I realise this is some work started by Yinon, and while the code is fine, the component raises a lot of questions:
> 
> * The component does not exist in Figma. Should it be added then?
> * When used horizontally, isn't the multiple mode just the same as a select with multiple?
> * Maybe this whole component should just be a variant of select?
> * When used vertically, isn't it the same as [radio group example](https://vivid-5hxj38p4qb70.deno.dev/components/action-group#radio-group) of action-group?
> * If we add this input component, shouldn't it also have `label`, `value`, `helper-text` etc. and events, like other input elements?
> 
> Basically this PR adds a new component that hasn't actually be designed by anyone and has a lot of overlap with other components. So I'm not sure if this is really the right way to go.

@RichardHelm  I can remove the export and alpha tag from the PR and add only the horizontal changes until we decide what to do. Alternatively, we could just use it internally, like the popup, for example inside select - instead of a div class="listbox">

2023-08-29 09:22 UTC, RichardHelm commented
@rinaok Sure that sound good! Let's keep it internal for now

2023-08-29 09:22 UTC, RichardHelm commented on libs/components/src/lib/listbox/listbox.spec.ts
> +			expect(element.hasAttribute('keydown')).toBeFalsy();
I don't think this works

2023-08-29 10:51 UTC, rinaok commented on libs/components/src/lib/listbox/listbox.spec.ts
> +			expect(element.hasAttribute('keydown')).toBeFalsy();
You are right, copied it from the original PR and haven’t noticed this test.

2023-08-30 13:03 UTC, RichardHelm requested changes

2023-08-30 13:03 UTC, RichardHelm commented on libs/components/src/lib/listbox/listbox.spec.ts
> +		it('should not remove keydown event listener when orientation is vertical', async function () {
```suggestion
		it('should not remove keydown event listener when orientation is horizontal', async function () {
```

2023-08-30 13:32 UTC, RichardHelm approved these changes

2023-08-30 13:41 UTC, merged