feat(text-field): leading action-items slot (VIV-1239)
Vonage/vivid-3 pull request #1351
Opened 2023-08-24 10:05 UTC by rachelbt

2023-08-25 13:27 UTC, RichardHelm commented on libs/components/src/lib/text-field/text-field.scss
>  	position: absolute;
I see no reason why leading and trailing action items need to be position absolute? Only the icon
These slots are really awkward to use otherwise, because you need to provide the exact width.

I tried laying them out normally and I see no problem:

https://github.com/Vonage/vivid-3/assets/86777660/e04bc8ef-b3d5-42ce-9f3a-aac82a758816

2023-08-30 10:12 UTC, rachelbt commented on libs/components/src/lib/text-field/text-field.scss
>  	position: absolute;
thank for this!
fixed it - not slots position: absolute!

2023-08-30 12:47 UTC, RichardHelm commented on libs/components/src/lib/text-field/text-field.spec.ts
> +			expect(baseElementHasIcon).toEqual(false);
Just updating the wording
```suggestion
		it('should remove .no-leading class from .base if icon is set', async function () {
			element.icon = 'home';
			await elementUpdated(element);
			const baseElementHasNoLeadingClass = element.shadowRoot?.
				querySelector('.base')?.classList.contains('no-leading');
			expect(baseElementHasNoLeadingClass).toEqual(false);
```

2023-08-30 18:55 UTC, rachelbt commented on libs/components/src/lib/text-field/README.md
> +Use `--text-field-inline-end-padding` variable to set the text-field inline-end padding when using the `action-items` slot.
```suggestion
~~Use `--text-field-inline-end-padding` variable to set the text-field inline-end padding when using the `action-items` slot.~~
```

2023-08-30 19:02 UTC, rachelbt commented on libs/components/src/lib/text-field/README.md
> +Use `--text-field-inline-end-padding` variable to set the text-field inline-end padding when using the `action-items` slot.
went for the strike-through.

2023-08-30 19:03 UTC, rachelbt commented on libs/components/src/lib/text-field/README.md
> +~~Use `--text-field-inline-end-padding` variable to set the text-field inline-end padding when using the `action-items` slot.~~
```suggestion
This css variable is not in use anymore. Don't worry if it is set - the design still be the same :). 
~~Use `--text-field-inline-end-padding` variable to set the text-field inline-end padding when using the `action-items` slot.~~
```

2023-08-31 11:34 UTC, RichardHelm approved these changes

2023-08-31 11:35 UTC, RichardHelm approved these changes

2023-08-31 11:50 UTC, RichardHelm requested changes
I just realised we're missing the `@slot` annotations for both leading and normal action items.
Could you please add them as well?

2023-09-04 08:26 UTC, RichardHelm approved these changes

2023-09-04 08:42 UTC, merged