feat(date-picker): add min and max attributes (VIV-1273)
Vonage/vivid-3 pull request #1353
Opened 2023-08-25 16:46 UTC by RichardHelm

2023-08-29 19:09 UTC, YonatanKra requested changes
Some small remarks. Mostly about the tests.

2023-08-29 19:09 UTC, YonatanKra commented on libs/components/src/lib/date-picker/date-picker.spec.ts
> +				getDateButton('2023-08-10')
Would that be more understandable?
```suggestion
                        const firstTabbableElement = getDateButton('2023-08-10');
			expect(element.shadowRoot!.activeElement).toBe(firstTabbableElement);
```

2023-08-29 19:09 UTC, YonatanKra commented on libs/components/src/lib/date-picker/date-picker.spec.ts
> +			await elementUpdated(element);
Can this be extracted to `openMonthView()`?

2023-08-29 19:09 UTC, YonatanKra commented on libs/components/src/lib/date-picker/date-picker.spec.ts
> +				getDateButton('2023-08-01')
### 
```suggestion
			const focusedButton = getDateButton('2023-08-01');
			focusedButton.focus();

			pressKey('ArrowRight');

			expect(element.shadowRoot!.activeElement).toBe(focusedButton);
```

2023-08-31 11:13 UTC, RichardHelm commented on libs/components/src/lib/date-picker/calendar/dateStr.ts
> +	return dateA.getTime() - dateB.getTime();
Sure, done 👍

2023-08-31 11:15 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.spec.ts
> +				expect(getDateButton('2023-08-01').disabled).toBe(true);
Sure, updated the tests to check all buttons now 👍

2023-08-31 11:15 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.spec.ts
> +			it('should disable previous month button if the previous month is earlier than min', async () => {
Added tests for that now

2023-08-31 11:16 UTC, RichardHelm commented on libs/components/src/lib/date-picker/date-picker.spec.ts
> +				getDateButton('2023-08-10')
Yes, done

2023-08-31 17:09 UTC, YonatanKra approved these changes
LGTM! 
Nice job :)

2023-09-01 09:49 UTC, merged