feat(menu-item): add submenu (VIV-1230)
Vonage/vivid-3 pull request #1359
Opened 2023-09-03 12:08 UTC by rinaok

2023-09-06 14:45 UTC, RichardHelm commented
Very cool! I didn't review the code but noticed some things when trying it out:

- When using keyboard you can open multiple submenus at once:
![image](https://github.com/Vonage/vivid-3/assets/86777660/c368160c-c50a-443f-8645-eea1df72b609)
- When moving the mouse to click on an item in the submenu further down, the item loses hover so it closes / changes the submenu

https://github.com/Vonage/vivid-3/assets/86777660/9dfcf72d-52a9-46c6-8bae-0a33754d4e74

Maybe we need to look into something like https://smashingmagazine.com/2023/08/better-context-menus-safe-triangles

2023-09-12 07:50 UTC, rinaok commented
> Very cool! I didn't review the code but noticed some things when trying it out:
> 
> * When using keyboard you can open multiple submenus at once:
>   ![image](https://user-images.githubusercontent.com/86777660/266031444-c368160c-c50a-443f-8645-eea1df72b609.png)
> * When moving the mouse to click on an item in the submenu further down, the item loses hover so it closes / changes the submenu
> 
>  Screen.Recording.2023-09-06.at.15.39.47.mov 
> Maybe we need to look into something like https://smashingmagazine.com/2023/08/better-context-menus-safe-triangles

@RichardHelm Fixed everything but the Safe Triangles. Can you check again? :) I know there are some teams waiting for this, maybe for the Safe Triangles we can open another issue.

2023-09-12 09:22 UTC, RichardHelm requested changes
@rinaok Thanks, it works great now! I just left some minor comments

2023-09-12 09:22 UTC, RichardHelm commented on libs/components/src/lib/menu-item/menu-item.spec.ts
> -
Can we bring these tests back please? I think this should work again now that we're using fast's logic

2023-09-12 09:22 UTC, RichardHelm commented on libs/components/src/lib/menu-item/menu-item.spec.ts
> +		});
As this is basically testing the same thing with different keys, maybe we can write it like this instead?

```suggestion
		it.each(['Enter', ' '])('should expand first menuitem when "%s" is pressed', async (key) => {
			const menuitem = menuElement.querySelector('#menuitem') as MenuItem;

			menuitem.focus();
			menuitem.dispatchEvent(new KeyboardEvent('keydown', { key }));

			await elementUpdated(menuElement);
			expect(menuitem.expanded).toEqual(true);
		});
```

2023-09-12 09:22 UTC, RichardHelm commented on libs/components/src/lib/menu-item/menu-item.template.ts
>  		aria-checked="${x => (x.role !== MenuItemRole.menuitem ? x.checked : void 0)}"
Not sure who wrote `void 0` to begin with, but let's use undefined instead

```suggestion
		aria-haspopup="${x => (x.hasSubmenu ? 'menu' : undefined)}"
		aria-checked="${x => (x.role !== MenuItemRole.menuitem ? x.checked : undefined)}"
```

2023-09-12 09:33 UTC, rinaok commented on libs/components/src/lib/menu-item/menu-item.template.ts
>  		aria-checked="${x => (x.role !== MenuItemRole.menuitem ? x.checked : void 0)}"
@RichardHelm The void 0 is copied from FAST code

2023-09-12 09:34 UTC, rinaok commented on libs/components/src/lib/menu-item/menu-item.spec.ts
> -
Yes, I forgot to revert it

2023-09-12 09:56 UTC, RichardHelm approved these changes

2023-09-12 09:59 UTC, merged