feat(file-picker): add support for form association (VIV-802)
Vonage/vivid-3 pull request #1381
Opened 2023-09-14 15:45 UTC by RichardHelm

2023-09-28 17:48 UTC, YonatanKra requested changes
Great stuff. A huge one with a few comments :)

2023-09-28 17:48 UTC, YonatanKra commented on libs/shared/src/lib/test-utils/index.ts
> +export const nextTick = async () => {
As I mentioned above, you implemented `elementUpdated` which is our standard. Can you please revert to it?

2023-09-29 14:32 UTC, RichardHelm commented on apps/docs/assets/bundled-scripts/live-sample.js
> +	iframe.contentWindow.document.documentElement.lang = select.value;
Updates the html lang attribute to the new language
It's needed for CJK characters to be rendered correctly

2023-09-29 14:32 UTC, RichardHelm commented on libs/components/src/lib/avatar/ui.test.ts-snapshots/snapshots-avatar-Desktop-Chromium-linux.png
I don't know, probably some tiny changes in rendering due to the update

2023-09-29 14:33 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.form-associated.ts
> +class _FilePicker extends FoundationElement {}
I have taken this pattern from FAST: https://github.com/microsoft/fast/blob/%40microsoft/fast-foundation_v2.49.0/packages/web-components/fast-foundation/src/text-field/text-field.form-associated.ts

2023-09-29 14:33 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.spec.ts
> +			await nextTick();
It was needed because of the setTimeout, but removed now

2023-09-29 14:34 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.spec.ts
> +		expect(valueBeforeReset).not.toBe('');
Sure

2023-09-29 14:37 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.ts
> +	};
This was the same as super.valueChanged but without setting the form value
I've now changed this to override `setFormValue` instead so we don't have to copy as much code

2023-09-29 14:38 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.ts
>  			// Replace "upload" with "select" in dict messages
Removed

2023-09-29 14:40 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.ts
> +		}, 0);
`queuecomplete` is triggered after upload. But I've found that `addedfiles` is emitted after status change so I'm using it now which simplifies the code somewhat

2023-09-29 14:42 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.ts
> +		// For historical reasons, the value IDL attribute prefixes the filename with the string "C:\fakepath\".
This comment was straight from the html spec: https://html.spec.whatwg.org/multipage/input.html#fakepath-srsly

But I've changed it to be clearer now

2023-09-29 14:42 UTC, RichardHelm commented on libs/components/src/lib/file-picker/ui.test.ts
> +import * as path from 'path';
Sure, done

2023-09-29 14:42 UTC, RichardHelm commented on libs/components/src/locales/en-GB.ts
> +				'October',
🤦

2023-09-29 14:42 UTC, RichardHelm commented on libs/shared/src/lib/test-utils/index.ts
> +export const nextTick = async () => {
Yes, done, it's no longer needed

2023-10-01 15:10 UTC, YonatanKra requested changes
Just two more steps :)

2023-10-01 15:10 UTC, YonatanKra commented on libs/components/src/lib/file-picker/file-picker.ts
> +		super.setFormValue(value, state);
Extract logic to global module function (or a private one on the class). 
Self-descriptive and no need to read it unless one really needs to.

```suggestion
		if (formAssociationInjnectsFakePath(value)) {
			return;
		}

		super.setFormValue(value, state);
```

2023-10-01 15:10 UTC, YonatanKra commented on libs/components/src/lib/file-picker/file-picker.ts
>  		this.value = files.length > 0 ? `C:\\fakepath\\${files[0].name}` : '';
Extract the logic to a global module function and use it instead of the comment.
More durable, more self-explanatory code IMO.

```suggestion
		this.value = setFakePathLikeNativeInput(files);
```

2023-10-02 10:45 UTC, YonatanKra approved these changes
Good to go 🥳

2023-10-02 10:56 UTC, merged