chore(number-field): add missing docs for number field (VIV-1328)
Vonage/vivid-3 pull request #1388
Opened 2023-09-20 08:13 UTC by YonatanKra

* Added relevant tests for `valueAsNumber()`, `stepUp` and `stepDown`
* Added methods to Readme

2023-09-20 08:45 UTC, rinaok submitted a review, later dismissed

2023-09-20 10:52 UTC, RichardHelm requested changes

2023-09-20 10:52 UTC, RichardHelm commented on libs/components/src/lib/number-field/README.md
> +| `valueAsNumber` | `number` | Returns the value as a number                 |
`valueAsNumber` should be under properties

2023-09-21 08:58 UTC, YonatanKra commented on libs/components/src/lib/number-field/README.md
> +| `valueAsNumber` | `number` | Returns the value as a number                 |
Should it be at all?
It's part of the HTML spec...

2023-09-21 10:21 UTC, RichardHelm approved these changes

2023-09-21 10:28 UTC, RichardHelm commented on libs/components/src/lib/number-field/README.md
> +| `valueAsNumber` | `number` | Returns the value as a number                 |
Ah I didn't know that, alright then.

However, and this is a different discussion, maybe yes we should actually include things like this in our docs as it will make it easier and clearer for users.

2023-09-21 11:21 UTC, merged