fix(docs): customization tabs
Vonage/vivid-3 pull request #1392
Opened 2023-09-27 08:24 UTC by rinaok

2023-09-28 11:53 UTC, RichardHelm requested changes

2023-09-28 11:53 UTC, RichardHelm commented on apps/docs/variables-preview/index.js
> +    vwc-tab[aria-selected="true"] {
What does this do?

From my understanding, the issue is only with the customization example for tabs

2023-09-28 15:08 UTC, RichardHelm commented on apps/docs/variables-preview/index.js
> +    vwc-tab[aria-selected="true"] {
No it does work, it overrides the connotations colors with accouncement so they are all pink

But with your change the selector doesn't match any more and has no effect

I think the purpose of this ticket is just to fix the tabs example to color the tab components as well

2023-10-01 09:11 UTC, rinaok commented on apps/docs/variables-preview/index.js
> +    vwc-tab[aria-selected="true"] {
I didn't understand the ticket right, fixed :)

2023-10-02 08:38 UTC, RichardHelm approved these changes

2023-10-02 11:10 UTC, merged