Viv 1354 component a11y tests
Vonage/vivid-3 pull request #1409
Opened 2023-10-10 15:47 UTC by TaylorJ76

Adds an axe test to each component unit test.
I have put fixes in where they are quick and easy, others I have skips the test with a comment on why it is failing.

2023-10-10 16:46 UTC, RichardHelm commented
Very cool 👍 

I've noticed that some of tests do an additional `expect(await axe(element)).toHaveNoViolations();` at the end while others don't. Is there some kind of logic behind this?

Have you considered adding the check to `elementUpdated()` instead so that they run whenever some UI changes?

2023-10-11 11:03 UTC, RichardHelm requested changes

2023-10-11 11:03 UTC, RichardHelm commented on libs/components/src/lib/tag-group/tag-group.spec.ts
> +			element.ariaLabel = 'Tag group';
I think this can be a bit simpler
```suggestion
				`<${COMPONENT_TAG} aria-label="Tag group">
					<vwc-tag label="Label 1"></vwc-tag>
					<vwc-tag label="Label 2"></vwc-tag>
					<vwc-tag label="Label 3"></vwc-tag>
				</${COMPONENT_TAG}>`
			)) as TagGroup;
```

2023-10-11 11:03 UTC, RichardHelm commented on libs/components/src/lib/tag/tag.spec.ts
> +			expect(await axe(exposedHTMLString)).toHaveNoViolations();
Again this should be a separate test

2023-10-11 11:05 UTC, RichardHelm commented
> Yes, I have been using the `elementUpdated` to wait for UI changes. In some tests I do more than one axe test to test the component in different states (ini the Avatar component for example)

I get that, I was thinking to run the test as part of `elementUpdated`. But that would probably flag a lot of issues when the component does not have all the required attributes etc....

2023-10-11 12:11 UTC, TaylorJ76 commented on package.json
> +    "test:pa11y": "pa11y-ci"
Not needed. Removed

2023-10-11 13:36 UTC, RichardHelm approved these changes

2023-10-11 14:52 UTC, merged