docs(button): example toggle button practice
Vonage/vivid-3 pull request #141
Opened 2022-01-30 17:03 UTC by yinonov

2022-02-01 15:32 UTC, rinaok reviewed
Why is the toggle button under usage examples and not components?

2022-02-03 14:47 UTC, rinaok requested changes
.

2022-02-06 12:53 UTC, rinaok approved these changes

2022-02-10 10:36 UTC, rachelbt commented
What about the "on" state? 
![image](https://user-images.githubusercontent.com/7512792/153389588-f59cd20f-9e07-40fd-a076-d4f7342eeb5e.png)
![image](https://user-images.githubusercontent.com/7512792/153389638-805135ad-39ac-49e2-b4d5-7b61704ed12d.png)
![image](https://user-images.githubusercontent.com/7512792/153389527-44c06808-d4be-4b73-bc3d-6853af7a0596.png)

In only text button - if the text doesn't change - how can a user know that the button is toggled? Are we leaving it to our consumers to decide and switch between appearances?

2022-02-10 11:03 UTC, yinonov commented
> What about the "on" state? ![image](https://user-images.githubusercontent.com/7512792/153389588-f59cd20f-9e07-40fd-a076-d4f7342eeb5e.png) ![image](https://user-images.githubusercontent.com/7512792/153389638-805135ad-39ac-49e2-b4d5-7b61704ed12d.png) ![image](https://user-images.githubusercontent.com/7512792/153389527-44c06808-d4be-4b73-bc3d-6853af7a0596.png)
> 
> In only text button - if the text doesn't change - how can a user know that the button is toggled? Are we leaving it to our consumers to decide and switch between appearances?

yes, it's for consumers to decide. the point here is to reflect how easy it is to tweak a button to be toggle-able.

1 of the issues I experience here is that the _toggled-to_ icon isn't preloaded. thus, firstly shows the preloading spinner

2022-02-27 14:51 UTC, YonatanKra commented
> > What about the "on" state? ![image](https://user-images.githubusercontent.com/7512792/153389588-f59cd20f-9e07-40fd-a076-d4f7342eeb5e.png) ![image](https://user-images.githubusercontent.com/7512792/153389638-805135ad-39ac-49e2-b4d5-7b61704ed12d.png) ![image](https://user-images.githubusercontent.com/7512792/153389527-44c06808-d4be-4b73-bc3d-6853af7a0596.png)
> > In only text button - if the text doesn't change - how can a user know that the button is toggled? Are we leaving it to our consumers to decide and switch between appearances?
> 
> yes, it's for consumers to decide. the point here is to reflect how easy it is to tweak a button to be toggle-able.
> 
> 1 of the issues I experience here is that the _toggled-to_ icon isn't preloaded. thus, firstly shows the preloading spinner

Won't it always be a problem? I mean, we can't control how fast a user downloads an icon...

2022-02-27 14:52 UTC, YonatanKra commented on docs/usage-examples/toggle-button.md
> +    target.ariaPressed = !target.ariaPressed;
This is actually one of the values of `vivid` - a developer would hardly think of changing the aria pressed value...

2022-02-27 15:49 UTC, yinonov commented on docs/usage-examples/toggle-button.md
> +    target.ariaPressed = !target.ariaPressed;
ure right, but does this tiny "program" justify a dedicated component?

2022-02-27 15:51 UTC, yinonov commented
> > > What about the "on" state? ![image](https://user-images.githubusercontent.com/7512792/153389588-f59cd20f-9e07-40fd-a076-d4f7342eeb5e.png) ![image](https://user-images.githubusercontent.com/7512792/153389638-805135ad-39ac-49e2-b4d5-7b61704ed12d.png) ![image](https://user-images.githubusercontent.com/7512792/153389527-44c06808-d4be-4b73-bc3d-6853af7a0596.png)
> > > In only text button - if the text doesn't change - how can a user know that the button is toggled? Are we leaving it to our consumers to decide and switch between appearances?
> > 
> > 
> > yes, it's for consumers to decide. the point here is to reflect how easy it is to tweak a button to be toggle-able.
> > 1 of the issues I experience here is that the _toggled-to_ icon isn't preloaded. thus, firstly shows the preloading spinner
> 
> Won't it always be a problem? I mean, we can't control how fast a user downloads an icon...

I think this might introduce a lazy/eager loading mechanism for icon component. maybe a task of its own?

2022-07-18 06:12 UTC, YonatanKra approved these changes

2022-07-18 10:52 UTC, merged