feat(audio-player): new component (VIV-942)
Vonage/vivid-3 pull request #1411
Opened 2023-10-11 15:41 UTC by rinaok

2023-10-23 08:58 UTC, rachelbt reviewed
didn't went over the `audio-player.ts` or the tests...
added some css comments :)
adding links to issues that was fixed in the audio in vivid-2 that was raised by users - can you go over them and see if the v-3 is OK with them?
https://jira.vonage.com/browse/VIV-872
https://github.com/Vonage/vivid/pull/1386
https://github.com/Vonage/vivid/pull/1392
https://github.com/Vonage/vivid/pull/1394

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +		background-color: var(--vvd-color-neutral-50);
```suggestion
		background-color: var(#{constants.$vvd-color-neutral-50});
```

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +			background-color: var(--vvd-color-neutral-300);
```suggestion
			background-color: var(#{constants.$vvd-color-neutral-300});
```

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +				border-radius: 6px;
```suggestion
				border-radius: 50%;
```

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +				pointer-events: all;
```suggestion
				pointer-events: all;
				
				&::before {
					position: absolute;
					z-index: -1;
					display: block;
					background-color: var(#{appearance.get-appearance-token(fill)});
					block-size: 0;
					border-radius: inherit;
					content: "";
					inline-size: 0;
					inset-block-start: 50%;
					inset-inline-start: 50%;
					opacity: 0;
					transform: translate(-50%, -50%);
					transition: opacity 0.2s ease-in-out, inline-size 0.2s ease-in-out, block-size 0.2s ease-in-out;
				}
```

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +					}
```suggestion
&::before {
						block-size: 30px;
						inline-size: 30px;
						opacity: 0.1;
					}
```

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +					background-color: var(--vvd-color-neutral-300);
why is this needed? isn't this suppose to be effected by the appearance?

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +	.slider {
nesting the slider and all its other elements creates long classes that effect the browser reading of the style.
`.pin {...}`
is better then:
`.base .controls .slider .progress .pin {...}`

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +		min-width: 200px;
```suggestion
		min-inline-size: 200px;
```

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +				height: 12px;
```suggestion
				inline-size: 12px;
				block-size: 12px;
```

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +			margin-left: 8px;
```suggestion
			block-size: 4px;
			margin-inline-end: 16px;
			margin-inline-start: 8px;
```

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +				height: 100%;
```suggestion
				inline-size: 0;
				block-size: 100%;
```

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +					right: -8px;
```suggestion
					inset-block-start: -4px;
					inset-inline-end: -8px;
```

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +			min-width: 32px;
```suggestion
			min-inline-size: 32px;
```

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.template.ts
> +      <${buttonTag} class="pause" icon="${x => x.paused ? 'play-solid' : 'pause-solid'}"
we are using only icon - we need to add `aria-lable`. but it needs to change according to the play/pause

2023-10-23 08:58 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.template.ts
> +            <div class="pin ${getClasses}" role='button' id="progress-pin"
same here with label, is this need to be accessed with keyboard?

2023-10-24 11:45 UTC, rinaok commented on libs/components/src/lib/audio-player/audio-player.template.ts
> +            <div class="pin ${getClasses}" role='button' id="progress-pin"
@rachelbt Vivid-2 allows you to access it, but it does nothing, while native HTML audio allows you to move it.

2023-10-24 13:34 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.template.ts
> +            <div class="pin ${getClasses}" role='button' id="progress-pin"
not sure I understand. How does keyboard navigation can change the progress button.
Another thing is - we need here aria-label on the button if its focusable and interactive

2023-10-24 16:04 UTC, RichardHelm requested changes
Looks great! I added some comments

2023-10-24 16:04 UTC, RichardHelm commented on libs/components/src/lib/audio-player/README.md
> +Represents a audio player custom element.
Can we add some more meaningful description here please?

2023-10-25 12:25 UTC, rinaok commented on libs/components/src/lib/audio-player/audio-player.template.ts
> +		html`<div class="slider" ${ref('_sliderEl')} @click="${(x, c) => x._rewind(c.event as MouseEvent)}">
@RichardHelm Our slider doesn't look like audio's slider and we also don't have a slider with cta connotation

2023-10-25 12:27 UTC, rinaok commented on libs/components/src/lib/audio-player/ui.test.ts-snapshots/snapshots-audio-player-Desktop-Chromium-linux.png
I didn't see this design, I was told to copy vivid-2 design. @AyalaBu Should I use the new design?

2023-10-29 14:34 UTC, rachelbt reviewed
nice to see that the css is so small :)
the disable state looks a bit strange that the button + slider pin are not the same shade:
![image](https://github.com/Vonage/vivid-3/assets/7512792/c8defcba-63da-48fc-979b-b6f31d903ff8)

Also - I tried pressing on the slider to move the audio back or forth but it's not working properly :(

2023-10-29 18:00 UTC, rinaok commented
> nice to see that the css is so small :) the disable state looks a bit strange that the button + slider pin are not the same shade: ![image](https://user-images.githubusercontent.com/7512792/278877367-c8defcba-63da-48fc-979b-b6f31d903ff8.png)
> 
> Also - I tried pressing on the slider to move the audio back or forth but it's not working properly :(

fixed it, the disable state button's and slider's default. @AyalaBu What do you think?

2023-10-29 18:01 UTC, rinaok commented on libs/components/src/lib/audio-player/audio-player.spec.ts
> +			audioConstructor.mockImplementation(() => mockAudioElement.duration);
because `duration` is readonly

2023-10-30 11:29 UTC, TaylorJ76 requested changes

2023-10-30 11:29 UTC, TaylorJ76 commented on libs/components/src/lib/audio-player/audio-player.template.ts
> +    <div class="base ${getClasses}" aria-disabled="${x => x.disabled}" aria-label="${x => x.ariaLabel}">
`aria` attributes are not needed here as the div is not an interactive element.

2023-10-30 11:29 UTC, TaylorJ76 commented on libs/components/src/lib/audio-player/audio-player.ts
> +			this._sliderEl.value = percent.toString();
It would be nice to update the slider's `aria-valuetext` attribute with the current time. (I have updated slider to allow this in my [a11y PR](https://github.com/Vonage/vivid-3/pull/1426/files))
Currently the screenreader is reading out the percentage value when the slider is interacted with.

2023-10-30 11:29 UTC, TaylorJ76 commented on libs/components/src/lib/slider/slider.template.ts
> +		aria-label="${x => x.ariaLabel ? x.ariaLabel : 'slider'}"
This should only add the `aria-label` if it is provided (`${x => x.ariaLabel`). 
Screen readers know it is a slider from the `role` attribute.

2023-10-30 12:26 UTC, rinaok commented on libs/components/src/lib/slider/slider.template.ts
> +		aria-label="${x => x.ariaLabel ? x.ariaLabel : 'slider'}"
@TaylorJ76 If I remove it I'm, getting this error:

 `vwc-audio-player > a11y > should pass html a11y test
-----
Error: expect(received).toHaveNoViolations(expected)

Expected the HTML found at $('vwc-audio-player,vwc-slider,.horizontal') to have no violations:

<div role="slider" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" aria-disabled="true" aria-orientation="horizontal" class="control disabled horizontal">

Received:

"ARIA input fields must have an accessible name (aria-input-field-name)"

Fix any of the following:
  aria-label attribute does not exist or is empty
  aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
  Element has no title attribute

You can find more information on this issue here: 
https://dequeuniversity.com/rules/axe/4.4/aria-input-field-name?application=axeAPIJest`

2023-10-31 18:55 UTC, RichardHelm requested changes

2023-10-31 18:55 UTC, RichardHelm commented on libs/components/src/lib/audio-player/README.md
> +### Time Stamp
I feel like this should be the default, maybe we should have something like `notime` instead to hide it.

2023-10-31 18:55 UTC, RichardHelm commented on libs/components/src/lib/audio-player/README.md
> +### No Seek
This variant is not present in Figma. Not sure if we should have it

2023-10-31 18:55 UTC, RichardHelm commented on libs/components/src/lib/audio-player/audio-player.scss
> +		min-inline-size: 200px;
Currently you can't change the width of the audio-player
It would to be able to do that and the slider takes the available space

2023-10-31 18:55 UTC, RichardHelm commented on libs/components/src/lib/audio-player/audio-player.scss
> +	.controls {
In Figma there is a 16px gap between the button / text / slider but we don't have it

2023-10-31 18:55 UTC, RichardHelm commented on libs/components/src/lib/audio-player/audio-player.template.ts
> +	@keyup="${x => x._rewind()}"
When you mouseup outside of the slider it doesn't rewind.
Maybe we should use `@change` instead?

2023-10-31 18:55 UTC, RichardHelm commented on libs/components/src/lib/audio-player/audio-player.ts
> +	@attr({ converter: nullableNumberConverter }) duration?: number;
Why is this an attribute?

2023-11-01 08:06 UTC, TaylorJ76 requested changes

2023-11-01 08:06 UTC, TaylorJ76 commented on libs/components/src/lib/audio-player/audio-player.ts
> +			this._sliderEl.value = percent.toString();
If you add `this._sliderEl.ariaValuetext = this._formatTime(current);` then the current time will be read out by a screenreader instead of the percentage number which will much more useful.

2023-11-01 15:45 UTC, rinaok commented on libs/components/src/lib/audio-player/audio-player.ts
> +	@attr({ converter: nullableNumberConverter }) duration?: number;
If the duration is not set yet, I need this attribute to add the disable class to the template.

2023-11-01 16:35 UTC, TaylorJ76 commented on libs/components/src/lib/audio-player/audio-player.ts
> +			this._sliderEl.value = percent.toString();
Did you forget to push this change? Or do you not agree?

2023-11-01 17:01 UTC, rinaok commented on libs/components/src/lib/audio-player/audio-player.ts
> +			this._sliderEl.ariaValuetext = this._formatTime(current);
@TaylorJ76 The change is inside.

2023-11-01 17:02 UTC, rinaok commented on libs/components/src/lib/audio-player/audio-player.ts
> +			this._sliderEl.value = percent.toString();
https://github.com/Vonage/vivid-3/pull/1411#discussion_r1379067252

2023-11-02 10:00 UTC, RichardHelm commented on libs/components/src/lib/audio-player/audio-player.ts
> +	@attr({ converter: nullableNumberConverter }) duration?: number;
But why is it an attribute?

2023-11-02 13:26 UTC, rinaok commented on libs/components/src/lib/audio-player/audio-player.ts
> +	@attr({ converter: nullableNumberConverter }) duration?: number;
Changed it to observal

2023-11-05 12:51 UTC, rinaok commented
@TaylorJ76 The PR is ready but the selectable-box's ui tests are failing, IDKW.

2023-11-06 09:51 UTC, TaylorJ76 approved these changes

2023-11-06 09:58 UTC, merged