feat(selectable-box): add component (VIV-1173)
Vonage/vivid-3 pull request #1417
Opened 2023-10-18 08:14 UTC by TaylorJ76

2023-10-18 13:04 UTC, rachelbt reviewed
went over the doc, html + css.
look really nice :)
I think it will be nice if we will add some use case for it in a group of items.
This can also be good for a good accessibility use.

2023-10-18 13:04 UTC, rachelbt commented on libs/shared/src/lib/sass/mixins/connotation/_mixins.scss
> +  	@include utils.spread-list-selectors('.connotation', config.$connotations, config.$default) using ($type) {
there was no change here - mind reverting it?

2023-10-18 13:04 UTC, rachelbt commented on libs/components/src/lib/selectable-box/README.md
> +Setting the `clickable` attribute makes the whole card clickable, just make sure the card does not contain other clickable elements.
this is really important, maybe we need to add an alert icon at the beginning of the line?

2023-10-18 14:15 UTC, TaylorJ76 commented on libs/components/src/lib/selectable-box/selectable-box.scss
> +}
Yeah, I tried it inside and it caused issues.

2023-10-18 14:16 UTC, TaylorJ76 commented on libs/components/src/lib/selectable-box/selectable-box.scss
> +	min-height: calc(var(--spacing-unit) * 2 + 22px);
The min-height is the minimum needed to display the control (radio / checkbox) with the correct spacing.

2023-10-18 15:59 UTC, RichardHelm requested changes
Looks great! I added some comments, most of which should be minor

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/README.md
> +Represents a selectable-box custom element.
This should be a more meaningful sentence

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/README.md
> +    <div>Box content</div>
Minor, but I guess we don't need to wrap the content in a div
```suggestion
    Box content
```

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/README.md
> +### Control
While control is a very good name, in other components `control` is the control element and that is assumed to be the case by some code like FormAssociated.
So to avoid a possible name conflicts in the future I would change it to `control-type`

```suggestion
### Control type
```

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/README.md
> +When `control` is set to `radio`, it is the consuming app's responsibility to ensure only 1 selectable box in a group is checked at a time.
```suggestion
When `control` is set to `radio`, it is the consuming app's responsibility to ensure only one selectable box in a group is checked at a time.
```

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/README.md
> +    <vwc-selectable-box control="radio" style="max-inline-size: 450px">
There's a problem with the radio, it cannot be unchecked

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/README.md
> +    <vwc-selectable-box clickable connotation="cta" style="max-inline-size: 450px">
There's a problem with the focus ring here:
<img width="171" alt="image" src="https://github.com/Vonage/vivid-3/assets/86777660/75d777b5-03f5-489b-9a0b-337f09aa7a17">

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/definition.ts
> +export const selectableBoxRegistries = [selectableBoxDefinition()];
If your template uses other components you need to add them here (check other components)
That would be: focus, checkbox, radio

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.scss
> +);
More of a design problem, but when the card is `clickable`, IMO it should have a hover, active (pressed), and checked state but these have not been defined in Figma.
Also the current appearance does not match up with what's in Figma color wise

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.template.ts
> +			${x.clickable ? 'tabindex="-1" aria-hidden="true"' : ''}
Something is getting messed up here:
<img width="708" alt="image" src="https://github.com/Vonage/vivid-3/assets/86777660/9c2fb038-798d-4d86-9c96-a4091eb2343c">

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.template.ts
> +		${x => renderControl(x, context)}
This will recreate the control every time something changes. It's better to have the functions on individual attributes so that only those will update when they change
```suggestion
		${renderControl(context)}
```

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.ts
> +		this.$emit('change', { checked: this.checked });
This is reasonable but in other components we're not emitting the checked value, so for consistency I would remove it
```suggestion
		this.$emit('change');
```

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.ts
> +		if (event.code === 'Space' && this.clickable) this.handleCheckedChange();
Should this accept Enter as well?

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.spec.ts
> +	describe('changed event', () => {
```suggestion
	describe('change event', () => {
```

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.spec.ts
> +	describe('checked', () => {
I think it's never getting tested that checked is updated when clicking on the card / control

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.template.ts
> +		role="${x => x.clickable ? x.control || 'checkbox' : null}"
Mhm, maybe we should use a different role. Not sure if making the whole thing a checkbox/radio is really accurate.
E.g. Google Meet backgrounds use role=button with aria-pressed:
<img width="313" alt="image" src="https://github.com/Vonage/vivid-3/assets/86777660/c5ce4b1b-2c7d-46b5-9942-fdcb45d45e30">

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.ts
> +	handleCheckedChange() {
This (and keydown handler) needs internal annotation or it will be exported as part of the custom element manifest.
Additionally, it is preferable to prefix it with an underscore to discourage users from calling it anyway.
```suggestion
/**
 * @internal
 */
	_handleCheckedChange() {
```

2023-10-18 15:59 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.ts
> + */
This needs annotation for the default slot and change event (see other components). It will cause these things to be added to the custom element manifest, which is then used to generate the vue wrappers.

2023-10-19 06:33 UTC, rachelbt commented on libs/components/src/lib/selectable-box/selectable-box.scss
> +);
I agree. 
Something is not fully aligned here with our appearances, design-wise - hence, you also needed to add the transparent background instead of using the automated colors of fill , outline, text. @AyalaBu ?

2023-10-19 08:29 UTC, TaylorJ76 commented on libs/components/src/lib/selectable-box/selectable-box.scss
> +);
The reason for adding the transparent background bit was to override the hover styles when only the checkbox/radio is clickable.

2023-10-19 08:31 UTC, TaylorJ76 commented on libs/components/src/lib/selectable-box/selectable-box.scss
> +);
I will reach out to @AyalaBu to get confirmation on the appearance because it hover state was accounted for in the design.

2023-10-25 12:46 UTC, RichardHelm requested changes

2023-10-26 07:57 UTC, rachelbt reviewed
O love the use examples!!
left some comments about the api naming :)

2023-10-26 07:57 UTC, rachelbt commented on libs/components/src/lib/selectable-box/README.md
> +### Size
I'm sorry - but this is not size, size effect the sizes of the component.
I'm sorry if I was not clear at the first time.
I would stay with `spacing` but maybe use the small - medium like in column spacing of layout.
Again raising the issue of discarding the tight and adding `none` to spacing.
@RichardHelm @rinaok WDYT?

2023-10-26 07:57 UTC, rachelbt commented on libs/components/src/lib/selectable-box/selectable-box.scss
> +	display: flex;
why is this needed?

2023-10-26 07:57 UTC, rachelbt commented on libs/components/src/lib/selectable-box/selectable-box.scss
> +}
this does nothing :) 
It needs to be extracted to be outside of `.base `
I'm not sure that we need to add this at all - this should be the consumers concern.

2023-10-26 07:57 UTC, rachelbt commented on libs/components/src/lib/selectable-box/selectable-box.scss
> +}
```suggestion
}

	::slotted(*) {
		border-radius: 6px;
	}
```

2023-10-26 09:48 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.scss
> +}
Not sure if this is good, as it will add the radius to all slotted children.

But the issue needs to be fixed somehow:
![image](https://github.com/Vonage/vivid-3/assets/86777660/ccb84929-995b-48a2-b9a4-2f4689a51c1e)

2023-10-26 10:08 UTC, RichardHelm approved these changes

2023-10-27 10:41 UTC, RichardHelm approved these changes

2023-10-27 13:06 UTC, merged