chore: add a11y attributes to make axe tests pass
Vonage/vivid-3 pull request #1426
Opened 2023-10-27 13:29 UTC by TaylorJ76

2023-10-30 09:59 UTC, TaylorJ76 commented on libs/components/jestGlobalSetup.cjs
> +	process.env.TZ = 'UTC';
This is to stop date based tests failing because of daylight savings time in the UK

2023-10-30 16:47 UTC, RichardHelm requested changes

2023-10-30 16:47 UTC, RichardHelm commented on libs/components/src/lib/checkbox/checkbox.template.ts
> +			aria-describedby="${x => x.ariaDescribedby}"
This does not work, you cannot refer to to an element outside the shadow DOM by ID

I would remove it as it's not currently possible
```suggestion
```

2023-10-30 16:47 UTC, RichardHelm commented on libs/components/src/lib/checkbox/checkbox.ts
> +	@attr({attribute: 'aria-label'}) override ariaLabel: string | null = null;
Not necessary to override this

```suggestion
```

2023-10-30 16:47 UTC, RichardHelm commented on libs/components/src/lib/checkbox/checkbox.template.ts
> +			aria-label="${x => x.ariaLabel}"
We use this pattern of passing ariaLabel to a child in several places.

However, this has the problem that the aria-label attribute also takes effect on the component itself and labels it.
![image](https://github.com/Vonage/vivid-3/assets/86777660/923480ee-5a37-4ee6-81a6-cc53604ffbfb)

I tested it in Voiceover and it will announce "A default checkbox, group" and only when going inside the group "A default checkbox, unticked tickbox..."

In Material Design 3 it's solved by adding `role=presentation` on the component itself.

2023-10-30 16:47 UTC, RichardHelm commented on libs/components/src/lib/number-field/number-field.ts
> +	@attr({attribute: 'subtract-button-aria-label'}) subtractButtonAriaLabel: string | null = null;
I think, like their label, increment / decrement is a more fitting name
```suggestion
	@attr({attribute: 'increment-button-aria-label'}) addButtonAriaLabel: string | null = null;
	@attr({attribute: 'decrement-button-aria-label'}) subtractButtonAriaLabel: string | null = null;
```

2023-10-30 16:47 UTC, RichardHelm commented on libs/components/src/lib/progress-ring/progress-ring.template.ts
> +        aria-describedby="${x => x.ariaDescribedby}"
Same concerns here

2023-10-30 16:47 UTC, RichardHelm commented on libs/components/src/lib/radio/README.md
> +- If a label is not provided either through the `label` attribute, then the checkbox will needs accessible label.
```suggestion
- If a label is not provided either through the `label` attribute, then the checkbox needs an accessible label.
```

2023-10-30 16:47 UTC, RichardHelm commented on libs/components/src/lib/radio/radio.template.ts
> +		aria-describedby="${x => x.ariaDescribedby}"
And here

2023-10-30 16:47 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.template.ts
> +		aria-valuetext="${x => x.ariaValuetext || x.valueTextFormatter(x.value)}"
And here

2023-10-30 16:47 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +			expect(control.getAttribute('aria-disabled')).toBe('true');
Maybe this should be it's own test

2023-10-31 08:18 UTC, TaylorJ76 commented on libs/components/src/lib/checkbox/checkbox.ts
> +	@attr({attribute: 'aria-label'}) override ariaLabel: string | null = null;
When I remove this the a11y tests are failing.

2023-10-31 09:56 UTC, RichardHelm approved these changes

2023-10-31 11:09 UTC, RichardHelm approved these changes

2023-10-31 13:09 UTC, merged