feat(slider): add cta connotation (VIV-1373)
Vonage/vivid-3 pull request #1429
Opened 2023-10-30 13:51 UTC by rinaok

2023-10-30 16:00 UTC, RichardHelm requested changes
Nice 👍  Got some minor comments

2023-10-30 16:00 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +		];
```suggestion
		] as const;
```

2023-10-30 16:00 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +		});
Not sure if this test is really needed
```suggestion
		it('should not set any connotation classes when no connotation is set', async function () {
			possibleConnotations.forEach(connotation => {
				expect(getControlElement(element)
					?.classList
					.contains(`connotation-${connotation}`))
					.toEqual(false);
			});
		});
```

2023-10-30 16:00 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +	});
I think we can write it like this for all connotations
```suggestion
		it.each(possibleConnotations)('should set the connotation class for "%s"', async function (connotation) {
			element.connotation = connotation;
			await elementUpdated(element);
			expect(getControlElement(element)
				?.classList
				.contains(`connotation-${connotation}`))
				.toEqual(true);
		});
	});
```

2023-10-31 06:35 UTC, rachelbt reviewed
LGTM,
the only thing is that is missing is the export of the connotation in the definition.ts:
export type { SliderConnotation } from './slider';

2023-10-31 10:08 UTC, RichardHelm approved these changes

2023-10-31 10:10 UTC, merged