fix(selectable-box): a11y issues when clickable (VIV-1392)
Vonage/vivid-3 pull request #1446
Opened 2023-11-14 08:30 UTC by TaylorJ76

When the selectable-box is clickable it creates an a11y issue using the checkbox / radio components inside. (Nesting interactive elements).

This PR creates internal components for check-mark and radio-mark. Which are then used in the checkbox and radio components respectively, as well as the clickable selectable box.

It also renames `clickable` to `container-clickable` to be more clear of its intention.

2023-11-20 16:35 UTC, RichardHelm commented
Wouldn't it be possible to just use the `inert` attribute with checkbox/radio instead? It will remove the element from the accessibility tree so it should have the same effect

> It also renames clickable to container-clickable to be more clear of its intention.
2 things about this:
- I'm not sure if `container-clickable` is much clearer than `clickable`. In AWS cloudscape they call it `entireCardClickable`, so maybe we could call it `entire-box-clickable`?
- It's a breaking change, maybe we should keep `clickable` as a deprecated attribute for backwards compatibility

2023-11-23 08:03 UTC, rachelbt commented
> Wouldn't it be possible to just use the `inert` attribute with checkbox/radio instead? It will remove the element from the accessibility tree so it should have the same effect
> 
> > It also renames clickable to container-clickable to be more clear of its intention.
> > 2 things about this:
> 
> * I'm not sure if `container-clickable` is much clearer than `clickable`. In AWS cloudscape they call it `entireCardClickable`, so maybe we could call it `entire-box-clickable`?
> * It's a breaking change, maybe we should keep `clickable` as a deprecated attribute for backwards compatibility

Since its under alpha there's no issue with breaking change :)
I think clickable is so much better then long properties. `entire-box-clickable` is sooooooo long :( 
How about `clickable-box`?

2023-11-23 08:13 UTC, rachelbt reviewed
👍

2023-11-23 08:13 UTC, rachelbt commented on libs/shared/src/lib/sass/mixins/appearance/_mixins.scss
> -  selected: '&:where(#{$selected}):where(:not(#{$disabled}, #{$hover}))',
since we currently do not have hover state UI test - this may effect places where there's no definition for selected+hover (like subtle).

2023-11-23 08:13 UTC, rachelbt commented on libs/components/src/lib/selectable-box/selectable-box.scss
> +	$appearances: duotone,
please also remove the selectablebox from the mapping in` _vriables.scss`

2023-11-23 11:19 UTC, TaylorJ76 commented on libs/shared/src/lib/sass/mixins/appearance/_mixins.scss
> -  selected: '&:where(#{$selected}):where(:not(#{$disabled}, #{$hover}))',
I have gone through the components where this could have been an issue and I'm pretty sure they all behave as they should.
The alternative to this is to override the hover styles on a selected card, but I don't really want to do that anything that hacky.

2023-11-27 10:18 UTC, RichardHelm requested changes
Nice! Just one small thing

2023-11-27 10:18 UTC, RichardHelm commented on libs/components/src/lib/selectable-box/selectable-box.spec.ts
>  					expect(spy).not.toHaveBeenCalled();
This doesn't test the right thing, spy is still registered on the original element not the new one

2023-11-28 10:30 UTC, RichardHelm approved these changes

2023-11-28 10:55 UTC, merged