fix(typography): bold style using b or strong tag (VIV-1317)
Vonage/vivid-3 pull request #1447
Opened 2023-11-16 11:09 UTC by rachelbt

2023-11-20 15:20 UTC, RichardHelm requested changes

2023-11-20 15:20 UTC, RichardHelm commented on libs/styles/src/lib/core/typography.scss
> +		}
Why add this? Headings have weight 500, so then the bold tags are not going to do anything inside headings

2023-11-20 15:20 UTC, RichardHelm commented on libs/styles/src/lib/core/typography.scss
> +		font-weight: 600;
Let's leave this for now, but this should probably be a token

2023-11-20 15:57 UTC, rachelbt commented on libs/styles/src/lib/core/typography.scss
> +		}
but they do!
If this is bot here - it gets 600 - and its extra bold in the headers

2023-11-21 17:40 UTC, RichardHelm commented on libs/styles/src/lib/core/typography.scss
> +		font-weight: 600;
Yes I understand. I mean the value 600 should be from a token as it should be configurable.

So if someone wants their bold text to be 700 they can change `typography-base-bold` but here it remains 600

2023-11-21 17:42 UTC, RichardHelm commented on libs/styles/src/lib/core/typography.scss
> +		}
Yes it becomes extra bold as expected when using bold tags.

But I can see the argument headings are already considered bold, so bold tags shouldn't do anything so I will approve this

2023-11-21 17:42 UTC, RichardHelm approved these changes

2023-11-23 07:03 UTC, rachelbt commented on libs/styles/src/lib/core/typography.scss
> +		font-weight: 600;
bold is 600, 700 is extra-bold.
Either way - if someone is using <b> and want it to be 700, then he or she can run this over with css.
I'm not sure how common is the use of <b> or <strong> anyway.

2023-11-27 11:18 UTC, merged