fix: accessible name for menu (aria-label)
Vonage/vivid-3 pull request #1477
Opened 2023-12-04 10:26 UTC by TaylorJ76

2023-12-11 12:47 UTC, rachelbt reviewed
all of the examples in menu-item are inside of menu - we should add the aria-label there too

2023-12-11 12:47 UTC, rachelbt commented on libs/components/src/lib/menu/menu.template.ts
> +function handleEscapeKey(menu: Menu, event: Event) {
if the menu is open esc should close it?
If yes - it doesn't work :(
we also have auto dismiss, maybe it suppose to be only there?

2023-12-13 07:25 UTC, TaylorJ76 commented on libs/components/src/lib/menu/menu.template.ts
> +function handleEscapeKey(menu: Menu, event: Event) {
You need to be focussed on the menu in order to close the menu with esc.
I will open a story to look at the general keyboard accessibility of menu as there are other issues which as out of the scope of this PR.

2023-12-13 10:14 UTC, RichardHelm requested changes

2023-12-13 10:14 UTC, RichardHelm commented on apps/docs/assets/scripts/theme-handler.js
> +
Should not be necessary to do this
```suggestion
menu.addEventListener('change', event => {
  if (event.target.checked)
    setTheme(event.target.text?.toLowerCase()));
});
```

2023-12-13 17:05 UTC, RichardHelm commented on apps/docs/assets/scripts/theme-handler.js
> +});
```suggestion
menu.addEventListener('change', event => {
  if (event.target.checked)
    setTheme(event.target.text?.toLowerCase());
});
```

2023-12-14 10:30 UTC, RichardHelm approved these changes

2023-12-19 09:47 UTC, merged