feat(split-button, vue-wrappers): add split-button to vivid-vue (VIV-1497)
Vonage/vivid-3 pull request #1530
Opened 2024-01-11 12:38 UTC by RichardHelm

2024-01-11 12:56 UTC, egor-limenko approved these changes

2024-01-11 14:08 UTC, rinaok commented on libs/components/src/lib/split-button/split-button.template.ts
> -		aria-haspopup="true"
Why?

2024-01-11 14:20 UTC, rinaok requested changes

2024-01-11 14:20 UTC, rinaok commented on libs/components/src/lib/split-button/README.md
> -
Why? I think it's needed.

2024-01-11 15:00 UTC, RichardHelm commented on libs/components/src/lib/split-button/split-button.template.ts
> -		aria-haspopup="true"
Menu adds aria-expanded and aria-haspopup automatically

2024-01-12 08:17 UTC, TaylorJ76 approved these changes

2024-01-14 09:37 UTC, rinaok approved these changes

2024-01-15 12:09 UTC, merged