fix(select, checkbox): error & success style (VIV-1458)
Vonage/vivid-3 pull request #1541
Opened 2024-01-17 15:49 UTC by rachelbt

2024-01-19 11:47 UTC, RichardHelm commented on libs/components/src/lib/select/select.scss
Can we add a screenshot for this?

2024-02-05 13:17 UTC, RichardHelm requested changes
Please see comment

2024-02-06 11:12 UTC, rachelbt commented on libs/components/src/lib/select/select.scss
you mean for the ghost select states?
I guess we need to.

2024-02-06 15:11 UTC, RichardHelm approved these changes

2024-02-13 07:05 UTC, rachelbt commented
@RichardHelm  - changed  the code for checkbox according to Ayala's request of design

2024-02-19 13:52 UTC, RichardHelm approved these changes

2024-02-19 13:53 UTC, merged