chore(select, menu-item, nav-disclosure): refactor focus (VIV-1519)
Vonage/vivid-3 pull request #1553
Opened 2024-01-25 13:38 UTC by rachelbt

2024-01-25 17:42 UTC, RichardHelm commented on libs/components/src/lib/menu-item/ui.test.ts-snapshots/snapshots-menu-item-Desktop-Firefox-linux.png
What happened to this?

2024-01-28 07:43 UTC, rachelbt commented on libs/components/src/lib/menu-item/ui.test.ts-snapshots/snapshots-menu-item-Desktop-Firefox-linux.png
I added transparent to the box-shadow so the focus now is like it should be and not 3px

2024-01-29 08:36 UTC, RichardHelm commented on libs/components/src/lib/menu-item/ui.test.ts-snapshots/snapshots-menu-item-Desktop-Firefox-linux.png
But why does it look like this in Firefox?
![image](https://github.com/Vonage/vivid-3/assets/86777660/697016f3-ec8b-4c1a-a5c5-c4317cea71fd)

2024-01-29 08:38 UTC, RichardHelm requested changes

2024-01-29 08:38 UTC, RichardHelm commented on libs/components/src/lib/menu-item/menu-item.scss
>  }
I think this is not right, outline: none turned into focus style

2024-01-30 13:46 UTC, RichardHelm approved these changes

2024-01-31 09:40 UTC, merged