feat(tabs): add tab scroll panel as property (VIV-1528)
Vonage/vivid-3 pull request #1555
Opened 2024-01-29 16:19 UTC by rachelbt

2024-01-29 18:42 UTC, RichardHelm requested changes
I think this is the right way to go, even though it should be the default

2024-01-29 18:42 UTC, RichardHelm commented on libs/components/src/lib/tabs/tabs.scss
> +		overflow-x: hidden;
Shouldn't this be auto as well? 🤔

2024-01-29 18:42 UTC, RichardHelm commented on libs/components/src/lib/tabs/tabs.spec.ts
> +		it('should set class "scroll" is panel-scroll is set', async () => {
```suggestion
		it('should set class "scroll" if panel-scroll is set', async () => {
```

2024-01-29 18:42 UTC, RichardHelm commented on libs/components/src/lib/tabs/README.md
> +For scroll only in the panel - set a value for the `--tabs-vertical-max-height` variable.
I don't understand the purpose of this variable.
In the example there is no difference between using height and the variable.


When I make it smaller than the natural height of the tabs, I get this? Why would anyone want this?
![image](https://github.com/Vonage/vivid-3/assets/86777660/2945d1ca-9a15-4d4a-a9b4-659a3b28b92d)

2024-01-29 18:42 UTC, RichardHelm commented on libs/components/src/lib/tabs/tabs.ts
> +	@attr ({mode: 'boolean',attribute: 'panel-scroll', }) panelScroll = false;
Mhm, maybe there can be a better name for this:
* Because it controls overflow, it could be called `panel-overflow="auto"`?
* Or panel-scrollable

2024-01-30 06:24 UTC, rachelbt commented on libs/components/src/lib/tabs/tabs.ts
> +	@attr ({mode: 'boolean',attribute: 'panel-scroll', }) panelScroll = false;
whar do you think about: `scrollable-panel`

2024-01-30 06:28 UTC, rachelbt commented on libs/components/src/lib/tabs/README.md
> +For scroll only in the panel - set a value for the `--tabs-vertical-max-height` variable.
I started writing an example for a use case for it - and as I write it - I come to understand that it is useless. I'll remove it. Thanks

2024-01-30 06:31 UTC, rachelbt commented on libs/components/src/lib/tabs/tabs.scss
> +		overflow-x: hidden;
not sure that horizontal & vertical scroll are good us, on the other side - hiding content is not a good UX too....

2024-01-30 13:44 UTC, RichardHelm commented on libs/components/src/lib/tabs/tabs.ts
> +	@attr ({mode: 'boolean',attribute: 'panel-scroll', }) panelScroll = false;
@rachelbt Sure, sounds good!

2024-01-31 11:25 UTC, merged