feat(range-slider): add component (VIV-1488)
Vonage/vivid-3 pull request #1584
Opened 2024-02-16 18:46 UTC by RichardHelm

2024-02-20 12:10 UTC, rinaok submitted a review, later dismissed
The navigation does not contain the component.

2024-02-20 12:34 UTC, rachelbt commented
> The navigation does not contain the component.

this is because we decided to have one or 2 teams checking the component before we add it to the "public" :)

2024-02-20 12:40 UTC, rachelbt requested changes
looks good!
left 2 comments

2024-02-20 12:40 UTC, rachelbt commented on libs/components/src/lib/range-slider/README.md
> +
when using keyboard navigation the up-down arrows are acting strange.
top arrow is down and down is up :stuck_out_tongue_winking_eye:

2024-02-20 16:54 UTC, RichardHelm commented on libs/components/src/lib/range-slider/range-slider.scss
> +	left: unset !important;
Sure, done 👍

2024-02-20 16:54 UTC, RichardHelm commented on libs/components/src/lib/range-slider/README.md
> +
🙃

2024-02-21 10:46 UTC, rachelbt commented
> > The navigation does not contain the component.
> 
> this is because we decided to have one or 2 teams checking the component before we add it to the "public" :)

but you can see it with adding the component name:
https://vivid-fd8y50sq3b1b.deno.dev/components/range-slider

2024-02-21 10:49 UTC, rachelbt commented on libs/components/src/lib/slider/slider.scss
> +	#{variables.$track-start-top}: 0;
sorry for nagging - but maybe if we are allready adding variables lets change it to logical properties of inset-start & end 🙏🏻

2024-02-22 09:49 UTC, TaylorJ76 requested changes
Looking good!
Only thing I noticed was that the screen reader (voiceover on mac) was not reading out the minus values correctly.
Eg: "-4" is being read as "4". I can see that the code is correct, but I wonder if we need to investigate why.

2024-02-22 18:03 UTC, RichardHelm commented
@TaylorJ76 Well spotted, this seems to be an issue with VoiceOver: https://discussions.apple.com/thread/254773710?sortBy=best

It also affects other components like slider, number-field etc. so I think a possible fix / workaround is out of scope for this PR

2024-02-26 09:27 UTC, TaylorJ76 approved these changes

2024-02-28 15:26 UTC, merged