feat(video-player): add component (VIV1486)
Vonage/vivid-3 pull request #1594
Opened 2024-02-21 09:10 UTC by TaylorJ76

2024-02-22 07:53 UTC, rachelbt reviewed
nice :)
Went over the docs and the css.
The doc page is not aligned to other pages, I commented in some places but not all (laziness :) )

I think that the looks of the video player is not fully "vivid" especially the big play button.

the controls of the video in mobile are not responsive and causing horizontal scroll:
![image](https://github.com/Vonage/vivid-3/assets/7512792/eec5bc17-39d0-4db3-93f3-2833ab0e12cd)

I left css comments and this is one in general - we are not using em in vivid, I see the need here to keep it responsive but it is a bit strange here, not sure what we need to do about it :)

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +@import url("../../../../../node_modules/video.js/dist/video-js.css");
```suggestion
@import url("../../../../../node_modules/video.js/dist/video-js.css");
@use "../../../../../dist/libs/tokens/scss/tokens.constants" as constants;

```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +	font: var(--vvd-typography-base);
```suggestion
	font: var(#{constants.$vvd-typography-base});
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +		margin-left: -1.25em;
```suggestion
                 $big-button-size: 2.5em;
		inline-size: $big-button-size;
		block-size: $big-button-size;
		margin-block-start: -$big-button-size;
		margin-inline-start -$big-button-size;
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +		min-width: auto;
```suggestion
		inline-size: auto;
		min-inline-size: auto; 
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +		line-height: 4em;
```suggestion
		line-height: 4;
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +		height: 4em;
```suggestion
		inline-size: calc(100% - 8px);
		block-size: 4em;
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +				#{border-radius-variables.$border-radius-normal}
same as before :)

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +			#{border-radius-variables.$border-radius-none}
not code related - but why are not we keeping the border-radius to the top as well - we don't have this kind of style in vivivd even when a menu is opened

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +		width: 12em;
```suggestion
		inset-inline-start: -4em;
		inline-size: 12em;
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +			width: 4em;
```suggestion
		inset-inline-start: 0;
		inline-size: 4em;
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +			background: #000;
```suggestion
			background: var(#{constants.$vvd-color-canvas-text});
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +		margin-bottom: 2.5em;
```suggestion
		margin-block-end: 2.5em;
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +		background: #000;
```suggestion
		background: var(#{constants.$vvd-color-canvas-text});
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/video-player.scss
> +		top: -5em;
```suggestion
		inset-block-start: -5em;
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/README.md
> +## Usage
```suggestion
## Members
```

2024-02-22 07:53 UTC, rachelbt commented on libs/components/src/lib/video-player/README.md
> +#### src attribute
```suggestion
#### src attribute

Type: string
Default: undefined
```
not sure this is the correct values - but this is missing for all the members

2024-02-22 10:54 UTC, YonatanKra requested changes
One big component. Nice work!
A few changes to cope with Vivid standards.
![image](https://github.com/Vonage/vivid-3/assets/6459899/08f0ff0f-a951-4ff8-ac4f-59327342d20b)

2024-02-22 11:09 UTC, TaylorJ76 commented on libs/components/src/lib/enums.ts
> +}
The reason I didn't is that we have a request for audio player to have the same functionality.

2024-02-22 18:08 UTC, RichardHelm commented on libs/components/src/locales/en-GB.ts
> +		'Audio Player': 'Audio Player',
I think we can just import the locale from video.js to avoid copying it:
```suggestion
	videoPlayer: {
		videoJsLocale: <...imported from video.js...>,
```

2024-02-23 10:39 UTC, TaylorJ76 commented on libs/components/src/lib/video-player/README.md
> +</style>
```html preview 800px - Makes this preview panel 800px height, which doesn't look great.

2024-02-23 10:41 UTC, TaylorJ76 commented
> nice :) Went over the docs and the css. The doc page is not aligned to other pages, I commented in some places but not all (laziness :) )
> 
> I think that the looks of the video player is not fully "vivid" especially the big play button.
> 
> the controls of the video in mobile are not responsive and causing horizontal scroll: ![image](https://private-user-images.githubusercontent.com/7512792/306909855-eec5bc17-39d0-4db3-93f3-2833ab0e12cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODUwOTksIm5iZiI6MTcwODY4NDc5OSwicGF0aCI6Ii83NTEyNzkyLzMwNjkwOTg1NS1lZWM1YmMxNy0zOWQwLTRkYjMtOTNmMy0yODMzYWIwZTEyY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMTAzOTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTY2YWE5MWUyYWUyYjFmODc3NTEzZTMzZjM5MzlhZGY5Y2VlODRkMDBkYmMyOTk3MDFjY2FkNTNkNDQyZTczYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dItCaiBQpGYlE-qb-UGgf1ILwP_90eAOdIv8fh2m0tk)
> 
> I left css comments and this is one in general - we are not using em in vivid, I see the need here to keep it responsive but it is a bit strange here, not sure what we need to do about it :)

I have sorted the responsiveness using container queries and converted `em`s to `px`s
And I have changed the big button to be smaller and hopefully more Vivid-like.

2024-02-23 14:38 UTC, TaylorJ76 commented on libs/components/src/lib/video-player/IconFontStyles.ts
> +export const iconFontStyles = `@font-face {
I found a way to delete the icon font stuff all together. Now using the built in svgs

2024-02-27 15:42 UTC, TaylorJ76 commented on libs/components/src/lib/video-player/IconFontStyles.ts
> +    font-family: VideoJS;
I have found a way to remove this completely.

2024-02-28 15:44 UTC, YonatanKra requested changes
A few testing comments.

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +	describe('src', () => {
Are the below `it`s all the possible use cases for changing `src`? For instance 
- What happens when you remove `src`?
- What are valid values for `src`?
- How do you handle invalid `src`?

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +		it('should set the muted attribute on the video element', async () => {
This description doesn't seem to be the case anymore. Can you set a more accurate description please?

```suggestion
		it('should set reflect autoplay on the video element', async () => {
```

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +	describe('autoplay', () => {
Again, it seems like `autoplay` should have more tests. For instance 
- Does removal works the same?
- Can this be used as a programatic API? (e.g. element.autoplay = true;)

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +		it('should disable playback rates when passed an empty string', async () => {
According to the test, it should hide the playback rates, right?
```suggestion
		it('should hide playback rates when passed an empty string', async () => {
```

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +		it('displays the captions button and menu', async () => {
```suggestion
		it('should display the captions button and menu when caption tracks are set', async () => {
```

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +						default>
I suggest not to use external content. This can actually be replaced with any other string (even an empty one) because what matters is the number of tracks of `kind="captions"`.
```suggestion
						src=""
```

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +						label="French">
```suggestion
						src=""
```

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +			expect(element.shadowRoot!.querySelectorAll('[kind="captions"]').length).toBe(2);
This expectation means nothing. All it is saying: "if I add two tracks of kind captions, there should be two elements of kind captions". Where's the captions button test? And probably the captions selection options test?

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +			expect(element.shadowRoot!.querySelectorAll('[kind="descriptions"]').length).toBe(2);
As above with captions - I cannot see how this expects a button. And as above, is the button all that's added? Or is there a menu to select from?

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +			expect(element.shadowRoot!.querySelector('[kind="chapters"]')).not.toBe(null);
As above - what should really happen. In this case, you are using `not`. This should be avoided most of the times, as negative assertions are a code smell

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +		});
This test is more "correct" IMO:
```suggestion
		it('should modify skip button amount', async () => {
			element = (await fixture(
				`<${COMPONENT_TAG} skip-by="30">
					<source src="${VIDEO_SRC}" type="video/mp4">
				</${COMPONENT_TAG}>`
			)) as VideoPlayer;
			const [skipBackwardButtonWhenValueIs30, skipForwardButtonWhenValueIs30] = getSkipButtons(30);
			
			element.skipBy = 15;
			const [skipBackwardButtonWhenValueIs15, skipForwardButtonWhenValueIs15] = getSkipButtons(15);
			
			expect(skipBackwardButtonWhenValueIs30).toBeTruthy();
			expect(skipForwardButtonWhenValueIs30).toBeTruthy();
			expect(skipBackwardButtonWhenValueIs15).toBeTruthy();
			expect(skipForwardButtonWhenValueIs15).toBeTruthy();
			expect(getSkipButtons(30)[0]).toBeNull();
			expect(getSkipButtons(30)[1]).toBeNull();
		});
```
Notice I've used some helper function to make the code easier to read (it needs to be implemented - and of course reused in the rest of the tests using skip buttons :) ).

Due to its length, I'd even split it to 3 tests:
1. Initial state when no skip-by is given
2. Initial state when skip-by is given
3. Initial state when skip-by is given and value is changed dynamically (via JS API)
This will create 3 short tests that explain the API

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +		it('should disable skip by buttons when passed 0', async () => {
That's a great `edge case` test!

2024-02-28 15:44 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +		xit('should pass html a11y test', async () => {
This is a skipped test. Either remove it or make it pass :)

2024-02-28 15:56 UTC, YonatanKra requested changes
None tests related comments

2024-02-28 15:56 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.template.ts
> +	// context: ElementDefinitionContext
This can be removed

2024-02-28 15:56 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.ts
> +	initialiseVideo() {
Two things:
1. This is funny, actually. Now I understand why `init` functions are `init` functions - to keep the peace between UK and US devs ;) My laptop screams at `initialise` and wants to turn it into `initialize` ;)
2. Can this be a private function as well? (`#initVideo`)

2024-02-28 15:56 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.ts
> +	getSettings() {
Can this method be private (`#getSettings`)? 

Or even better, a private getter? 
```
#settings() {
...
}
```
Right now it is exposed and part of our API.

2024-02-28 15:56 UTC, YonatanKra commented on libs/components/tsconfig.json
> +    "resolveJsonModule": true
Where do we import a `.json`?

2024-02-28 15:56 UTC, YonatanKra commented on libs/wrapper-gen/src/generator/polyfill/dom.ts
> +
What does this solve?

2024-02-28 15:56 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.ts
> +	player: any;
This can probably be a private property (`#player`)

2024-02-28 15:56 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.ts
> +	videoEle: any;
Again, this should probably be private.

2024-02-29 11:43 UTC, TaylorJ76 commented on libs/wrapper-gen/src/generator/polyfill/dom.ts
> +
I think @RichardHelm added this as a fix to allow the docs site to deploy.

2024-02-29 11:45 UTC, TaylorJ76 commented on libs/components/tsconfig.json
> +    "resolveJsonModule": true
In the locales files. We import the locales provided by video.js.

2024-02-29 14:49 UTC, TaylorJ76 commented on libs/components/src/lib/video-player/video-player.ts
> +	player: any;
We are using it in the tests to mock the events.

2024-02-29 15:41 UTC, TaylorJ76 commented on libs/components/src/lib/video-player/video-player.spec.ts
> +						label="French">
Not sure why we need to remove the label

2024-03-06 11:49 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +			it('should show the internal invalid src error message', async() => {
```suggestion
			it('should show the invalid src error when no src provided', async() => {
```

2024-03-06 11:49 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +		describe('no src provided', () => {
can remove this describe as it holds only one usecase (see my suggestion for the `it`)

2024-03-06 11:51 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +				expect(dialogContentEl!.textContent?.trim()).toBe('No compatible source was found for this media.');
This is a bit confusing for me.
Creating the component with no `src` means two elements change? What's the connection between these two elements?

2024-03-06 11:52 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +		it('should show the big play button by removing the vjs-hidden class', async () => {
```suggestion
		it('should remove the vjs-hidden class when src is set', async () => {
```

2024-03-06 11:55 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.spec.ts
> +		it('should show the big play button by removing the vjs-hidden class', async () => {
This is part of the `src` tests. You have the exact same test there.
This part is supposed to be the `clean init test` - so maybe test here that hidden class is set on first init with no params.

2024-03-06 13:00 UTC, TaylorJ76 commented on libs/components/src/lib/video-player/video-player.spec.ts
> +				expect(dialogContentEl!.textContent?.trim()).toBe('No compatible source was found for this media.');
When there is no src. Video.js appears as if it has loaded properly and displays the big play button.
I thought it would be more informative to the consumer if a message was displayed.

2024-03-06 15:07 UTC, YonatanKra commented on libs/components/src/lib/video-player/video-player.ts
> +		}
IMO most of it should go to the component's template. WDYT?

2024-03-12 06:37 UTC, rachelbt reviewed
Docs look great! 
So much more informative and tidy! 👍

2024-03-12 06:39 UTC, rachelbt reviewed
2 last ui test are nor rendering :(

2024-03-14 12:40 UTC, YonatanKra commented on libs/components/src/lib/video-player/ui.test.ts
> +	videoEle?.evaluate(element => element.style.visibility = 'hidden');
Don't we want to test user behavior? You can emulate user clicks and actual interaction with the video...
Can we use the above instead of using `evaluate`?

2024-03-20 12:23 UTC, RichardHelm requested changes

2024-03-20 12:23 UTC, RichardHelm commented on libs/components/src/lib/video-player/locale.ts
> +}
We don't care about these so I think it should just be opaque:
```suggestion
export type VideoPlayerLocale = unknown;
```

2024-03-20 12:23 UTC, RichardHelm commented on libs/components/src/lib/video-player/video-player.ts
> + * @public
```suggestion
 * @public
 * @component video-player
```

2024-03-20 12:23 UTC, RichardHelm commented on libs/components/src/lib/video-player/video-player.ts
> +	player: any;
We can prefix it at least:
```suggestion
	_player: any;
```

2024-03-20 12:23 UTC, RichardHelm commented on libs/components/src/lib/video-player/video-player.spec.ts
> +		}, true);
```suggestion
		return playbackRates.reverse().every((rate, index) =>
			playbackRatesMenuItems[index].querySelector('.vjs-menu-item-text')!.textContent === `${rate}x`;
		);
```

2024-03-20 12:23 UTC, RichardHelm commented on libs/components/src/lib/video-player/README.md
> +	html { max-inline-size: 800px }
How can consumers change the size of the video-player? Without changing <html>?
Also, the video player should not be display `inline`

2024-03-20 14:38 UTC, TaylorJ76 commented on libs/components/src/lib/video-player/README.md
> +	html { max-inline-size: 800px }
The Video is fluid and expands to fill the size of it's container, so consumers have control based on where it is placed in the page.

2024-03-20 14:39 UTC, TaylorJ76 commented on libs/components/src/lib/video-player/video-player.ts
> +	player: any;
We seem to have conflicting views on code conventions as Yonatan requested the prefix should be removed.

2024-03-21 10:16 UTC, RichardHelm approved these changes

2024-03-21 10:56 UTC, merged