chore(text-field, combobox, number-field): refactor focus (VIV-1572)
Vonage/vivid-3 pull request #1620
Opened 2024-03-03 13:58 UTC by rachelbt

2024-03-04 11:33 UTC, RichardHelm requested changes

2024-03-04 11:33 UTC, RichardHelm commented on libs/components/src/lib/text-field/text-field.scss
> +	.wrapper:focus-within::after {
If this code works fine, why add the one with `:has` as well? It isn't even any simpler

2024-03-04 11:33 UTC, RichardHelm commented on libs/components/src/lib/combobox/combobox.scss
> +.fieldset:focus-within::after {
We could consider adding wrapper element to combobox as well to simplify the CSS

2024-03-04 11:33 UTC, RichardHelm commented on libs/components/src/shared/patterns/focus.ts
🎉

2024-03-04 15:28 UTC, rachelbt commented on libs/components/src/lib/text-field/text-field.scss
> +	.wrapper:focus-within::after {
bacause I do not like the face that we add an addition pseudo element. Its the right way to use has. I guess in 1/2 a year or so we can remove the fallback

2024-03-04 15:30 UTC, rachelbt commented on libs/components/src/lib/combobox/combobox.scss
> +.fieldset:focus-within::after {
Its a good question wether we should add it.
We don't need an addition HTML wrapper, but on the other hand it helps consistency and cleaner css.
Either way - I wouldn't want to do thin in this PR.

2024-03-04 16:20 UTC, RichardHelm commented on libs/components/src/lib/text-field/text-field.scss
> +	.wrapper:focus-within::after {
But the `:has` code is also using a pseudo element 🤔

2024-03-05 07:30 UTC, rachelbt commented on libs/components/src/lib/text-field/text-field.scss
> +	.wrapper:focus-within::after {
that we already have :) Not creating a new one for the focus

2024-03-05 09:43 UTC, RichardHelm approved these changes

2024-03-05 13:30 UTC, merged