feat(dial pad): new composed component (VIV-1512)
Vonage/vivid-3 pull request #1629
Opened 2024-03-07 15:52 UTC by rinaok

2024-03-12 09:53 UTC, rachelbt reviewed
Nice!
Didn't went over the unit-tests :)

2024-03-12 09:53 UTC, rachelbt commented on apps/docs/_data/components.json
> +	{
I wonder if this needs to be under: composed components or ant other title.

2024-03-12 09:53 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +.base {
```suggestion
@use "../../../../../dist/libs/tokens/scss/tokens.constants" as constants;

.base {
```

2024-03-12 09:53 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +    border-bottom: 1px solid var(--vvd-color-neutral-300);
```suggestion
    border-bottom: 1px solid var(#{constants.$vvd-color-neutral-300});
```

2024-03-12 09:53 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +    border: 1px solid var(--vvd-color-neutral-300);
```suggestion
    border: 1px solid var(#{constants.$vvd-color-neutral-300});;
```

2024-03-12 09:53 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +    border-radius: 16px;
```suggestion
     border-radius: #{border-radius-variables.$border-radius-normal};
```
also regarding the border-radius - nested vwc-buttons have 8px border and with here 16px ic causes design break in hover:
![image](https://github.com/Vonage/vivid-3/assets/7512792/f443742a-f3dc-47fb-846b-6b585057ae41)
maybe vwc-buttons need to be rounded?

2024-03-12 09:53 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +    inline-size: 230px;
since this is repeating it will be nice to move it to a sass variable.
Also this is OK for desktop but it can look strange on mobile 230px when there's 460px screen width...

2024-03-12 09:53 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +    inline-size: 230px;
same - regarding width

2024-03-12 09:53 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +    grid-template-rows: 1fr 1fr 1fr 1fr;
```suggestion
    grid-template-columns: repeat(3, 1fr);
    grid-template-rows: repeat(4, 1fr);
```

2024-03-13 09:47 UTC, rinaok commented on apps/docs/_data/components.json
> +	{
@rachelbt I know it's written in the documents that it should, but I left it for the end to decide if it's best.

2024-03-13 10:20 UTC, rinaok commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +    border-radius: 16px;
@rachelbt I think it's a question for @AyalaBu

2024-03-13 10:33 UTC, rinaok commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +    inline-size: 230px;
@rachelbt So should we make the inline-size public?

2024-03-13 11:44 UTC, AyalaBu commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +    inline-size: 230px;
The designers' request was for a centered text and also it was bigger.
Can we make it happen?
Also I know that it's pretty common for a dialpad in a cell to appear without text,
but with underline it just looks weird.
Can add some text like "enter a number"? (it was also in the designers' original design)

2024-03-13 14:45 UTC, AyalaBu commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +    border-radius: 16px;
16px radius is border-radius in stacked button in pill shape
This was done a long time ago and I don't think we can make this shape disappear
Also this was an option chosen by designers in this component

2024-03-19 16:10 UTC, RichardHelm requested changes
Looks great! I left some comments

2024-03-19 16:10 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.ts
> + * @event change - Emitted when the text field value changes
We now annotate component like this for the wrappers:
```suggestion
 * @public
 * @component dial-pad
 * @event change - Emitted when the text field value changes
```

2024-03-19 16:10 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.ts
> + *
Can we add a v-model for value as well?

2024-03-20 14:42 UTC, rinaok commented on libs/components/src/lib/dial-pad/dial-pad.spec.ts
> +	describe.each(['input', 'change', 'blur', 'focus'])('%s event', (eventName) => {
added

2024-03-20 15:26 UTC, rinaok commented on libs/components/src/lib/dial-pad/dial-pad.ts
> +	@attr({ attribute: 'digit-hashtag-aria-label' }) digitHashtagAriaLabel: string | null = null;
@RichardHelm WDYM? They exists in the locale:


```
dialPad: {
		inputLabel: 'Phone number',
		deleteButtonLabel: 'Delete',
		callButtonLabel: 'Call',
		endCallButtonLabel: 'End call',
		digitOneLabel: '1',
		digitTwoLabel: '2 ABC',
		digitThreeLabel: '3 DEF',
		digitFourLabel: '4 GHI',
		digitFiveLabel: '5 JKL',
		digitSixLabel: '6 MNO',
		digitSevenLabel: '7 PQRS',
		digitEightLabel: '8 TUV',
		digitNineLabel: '9 WXYZ',
		digitAsteriskLabel: '*',
		digitZeroLabel: '0',
		digitHashtagLabel: '#',
	},
```

2024-03-21 07:36 UTC, rachelbt reviewed
left some css comments to make the dial-pad more accurate to design.
will need to go over again after changes are made :)

2024-03-21 07:36 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +	border-radius: #{border-radius-variables.$border-radius-extra-expanded};
```suggestion
	border-radius: #{border-radius-variables.$border-radius-expanded};
 overflow: hidden;
 inline-size: 100%;
```
I would go with this one, and remove the shape-pill from the the digits buttons.

2024-03-21 07:36 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +	margin: 16px;
I wonder if it will be better on the host and if someone wants to remove it or change it it will be easier

2024-03-21 07:36 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +	gap: $gap;
```suggestion
 grid-template-rows: 80px 1fr auto;
```
this way - there will be no layout change when the error text or helper text is added (as long as it is max 2 lines there)

2024-03-21 07:36 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +	margin-top: 12px;
```suggestion
	margin-top: 24px;
```
I removed the gap in base so this need to be bigger

2024-03-21 07:36 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +	inline-size: $inline-size;
```suggestion
	inline-size: 100%;
```

2024-03-21 07:36 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +	inline-size: $inline-size;
```suggestion
	inline-size: 100%;
	box-sizing: border-box;
```
I think that the inline-size needs also to be set on host.
I also think that 230px is maybe nice on desktop but maybe will be needed to be smaller or a bit wider. 
Moving the width to host will make the devs life easier

2024-03-21 07:36 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +	border: 1px solid var(#{constants.$vvd-color-neutral-300});
```suggestion
	box-shadow: inset 0 0 0 1px  var(#{constants.$vvd-color-neutral-300});
```

2024-03-21 07:36 UTC, rachelbt commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +	display: flex;
```suggestion
--vvd-button-accent-primary: var(#{constants.$vvd-color-neutral-600});

	display: flex;
```
this is for the text of the digits.
but this will also effect the digits - so you'll need to add class for the slotted icon and set it with color:
color: var(#{constants.$vvd-color-canvas-text});

2024-03-21 09:42 UTC, rinaok commented on libs/components/src/lib/dial-pad/dial-pad.scss
> +	border-radius: #{border-radius-variables.$border-radius-extra-expanded};
@AyalaBu approved this shape, I don't think we can change it

2024-03-21 10:26 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.ts
> +	@attr({ attribute: 'digit-hashtag-aria-label' }) digitHashtagAriaLabel: string | null = null;
Yes, but the values from the locale are not being used
The proposal states that the aria-labels will come from the locale and it doesn't have any attributes to customise them, so that is what I would expect here

2024-03-21 10:31 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.ts
> + *
There is some documentation in wrapper-gen README.
It probably needs to look like this: `` * @vueModel modelValue value input `(event.target as any).value` ``

2024-03-25 16:28 UTC, RichardHelm requested changes

2024-03-25 16:28 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.ts
> +			!(e.target instanceof Button)
Click doesn't register when clicking on icon

2024-03-26 14:39 UTC, RichardHelm approved these changes

2024-03-27 09:49 UTC, merged