feat(figma): icons builder poc (VIV-000)
Vonage/vivid-3 pull request #1652
Opened 2024-03-28 14:30 UTC by rinaok

2024-04-17 10:54 UTC, RichardHelm requested changes

2024-04-17 14:33 UTC, rinaok commented on libs/icons-builder/README.md
> +   You can find the plugin here: https://www.figma.com/community/plugin/1354446799950687095
Added

2024-04-17 15:46 UTC, rinaok commented on libs/icons-builder/dist/index.js
removed

2024-04-18 11:33 UTC, rinaok commented on libs/icons-builder/package.json
> +	},
Done :)

2024-05-05 13:11 UTC, closed without merging