fix(icon): connotation and docs
Vonage/vivid-3 pull request #168
Opened 2022-02-02 09:26 UTC by rinaok

2022-02-02 15:00 UTC, rinaok commented
@yinonov Isn't it missing the `inline` attribute?

2022-02-02 22:40 UTC, yinonov commented
> @yinonov Isn't it missing the `inline` attribute? 

It's "inline" by default if not setting size

2022-02-03 17:22 UTC, yinonov requested changes

2022-02-06 09:13 UTC, rinaok commented on libs/components/src/lib/icon/icon.scss
> +	$default: primary,
@yinonov It didn't resolve the issue. Default color for icons is still primary.
<img width="105" alt="Screen Shot 2022-02-06 at 11 12 18" src="https://user-images.githubusercontent.com/10883919/152674424-beb61242-9457-4123-a1c9-aa0a0b8e3b94.png">

2022-02-07 15:03 UTC, yinonov approved these changes

2022-02-07 15:09 UTC, merged