fix(audio-player): css for responsive extended audio (VIV-1745)
Vonage/vivid-3 pull request #1681
Opened 2024-04-30 10:54 UTC by rachelbt

2024-05-13 08:59 UTC, TaylorJ76 requested changes

2024-05-13 08:59 UTC, TaylorJ76 commented on libs/components/src/lib/audio-player/audio-player.scss
> +	inline-size: 350px;
This could create a horizontal scroll in small viewports and will fail [this rule](https://www.w3.org/WAI/WCAG22/Understanding/reflow.html) in a11y testing.
Could we change it to `max-inline-size`?

2024-05-13 12:33 UTC, rachelbt commented on libs/components/src/lib/audio-player/audio-player.scss
> +	inline-size: 350px;
```suggestion
	max-inline-size: 350px;
```

2024-05-14 07:59 UTC, TaylorJ76 approved these changes

2024-05-15 07:11 UTC, rachelbt commented on libs/components/src/lib/audio-player/definition.ts
> +import { menuRegistries } from '../menu/definition';
```suggestion

```

2024-05-15 07:11 UTC, rachelbt commented on libs/components/src/lib/audio-player/definition.ts
> +	...menuRegistries,
```suggestion

```

2024-05-15 08:30 UTC, TaylorJ76 requested changes

2024-05-15 08:30 UTC, TaylorJ76 commented on libs/components/src/lib/audio-player/README.md
> +### Minimum inline Size **Deprecated**
Can we follow the same format as selectable-box for the deprecated variable?

2024-05-20 08:10 UTC, TaylorJ76 approved these changes

2024-05-20 09:42 UTC, merged