fix(menu): make auto-dismiss dismiss on focusout (VIV-1747)
Vonage/vivid-3 pull request #1690
Opened 2024-05-02 14:39 UTC by RichardHelm

Aligns auto-dismiss behaviour with select, which uses focus to dismiss

2024-05-08 17:14 UTC, YonatanKra requested changes
Nice job! Simplifies the whole mechanism!
One little request and it's done.
Thanks!

2024-05-08 17:14 UTC, YonatanKra commented on libs/components/src/lib/menu/menu.spec.ts
>  		});
Should set these tests in the (badly named :) ) `when anchor is removed` describe to make sure we remove the listener - so as to prevent memory leak.

2024-05-09 09:25 UTC, RichardHelm commented on libs/components/src/lib/menu/menu.spec.ts
>  		});
Sure, added a test for it

2024-05-09 09:47 UTC, YonatanKra approved these changes

2024-05-09 09:59 UTC, merged