fix(appearance): change ghost text-color from 500 to 600 (VIV-1774)
Vonage/vivid-3 pull request #1716
Opened 2024-05-19 14:37 UTC by rachelbt

2024-06-03 10:21 UTC, RichardHelm commented on libs/components/src/lib/accordion-item/accordion-item.scss
Maybe the ugliness can be better contained with something like this:

```suggestion
:host {
	display: flex;
	box-sizing: border-box;
	flex-direction: column;
}

@include variables-backwards-compatibility();
```

with 

```
@mixin variables-backwards-compatibility() {
  :host {
    // build vars for the connotations configured in connotation/config
  }

  .control {
    // do the mapping
  }
}
```

Will make it easier to delete once the time comes

2024-06-05 13:02 UTC, RichardHelm requested changes
Looks good, minor comments

2024-06-05 13:02 UTC, RichardHelm commented on libs/shared/src/lib/sass/mixins/connotation/_mixins.scss
> +@mixin variables-backwards-compatibility($component, $element-class) {
Let's add some comment to our crazy code

```suggestion
/**
 * Ghost text color has changed from primary to firm in VIV-1774. For backwards compatibility with code
 * setting primary we need to default firm to primary value if it is provided.
 */
@mixin variables-backwards-compatibility($component, $element-class) {
```

2024-06-06 06:10 UTC, rachelbt commented on libs/components/src/lib/split-button/split-button.scss
> +		faint firm,
```suggestion
		faint,
```

2024-06-06 10:38 UTC, RichardHelm approved these changes

2024-06-06 11:48 UTC, merged