feat(slider, range-slider): add pin feature (VIV-1611)
Vonage/vivid-3 pull request #1724
Opened 2024-05-22 16:56 UTC by RichardHelm

2024-05-28 05:30 UTC, YonatanKra requested changes
Nice job all in all.
Quite a lot of comments, but quite a lot of changes ;)
 It'll probably take a few rounds to complete this CR.

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/range-slider/range-slider.template.ts
> +						])}"
Can we set this as a function at the top? `getRangeSliderClasses` should be fitting.

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/range-slider/range-slider.template.ts
> +					:open=${(x) => x._isThumbPopupOpen('start')}
I truly discourage `_` properties and methods.
We can either use internal events, private methods and props etc.
If the property/method is public, then it should be documented. If it is private - it should be private and not accessible outside the class.
You can look at #1726 for an example of how I privatize public functions. We can set a pair-coding session on this one as well.

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/range-slider/range-slider.template.ts
> +						])}"
`getThumbContainerClasses` function?

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/range-slider/range-slider.ts
> +	 */
Adding comments like these hurt my eyes while reading the code (I'm not kidding - it physically hurts). Better to make the property/method truly private than giving some obscure indication it is "internal" in a comment. 
I know FAST is doing it. I know a lot of people are doing it. Right now these comments are not part of JS and hence will not help in runtime (they might be, according to a person I know, but it'll take years from now).
So IMO it is better to make functions private.

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/slider/README.md
> +You can set the `valueTextFormatter` member to customize how values will be formatted for the sliders' `aria-valuetext` attribute. The formatting will also be used for the tooltip when `pin` is enabl
See my comment in the popup regarding this.
Part of my suggestion was to split the a11y part to sub parts using `###` titles.
Here it should be:
`### Role`
`### aria-label`
`### aria-valuetext`
WDYT?

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
> +			element.ariaValuetext = 'value text';
What happens if I use `valueTextFormatter`? Will it override the `aria-valuetext`?

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
> +		it('should not show popup when thumb focus is not visible', async () => {
Try to use positive terms when describing a test. What it should do and not what it shouldn't do. I guess it should `hide` or `remove` the elements from the DOM.
In addition, how do you emulate `thumb focus is not visible`?

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
> +			element.focus = () => getControlElement(element).focus();
Maybe this can enter our test-utils? I think we do that a lot, no?

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
> +		it('should have visible focus when control is focused', async () => {
```suggestion
		it('should have visible-focus class when control is focused', async () => {
```

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
> +	describe('thumb', () => {
Is `thumb` a property?
Because if not, the test is wrong. You should test the property the consumer is using the manipulate the `thumb` and test it and not the `thumb` itself.

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
> +				mouseUp();
This can be simplified with functions like: "dragVertically", "dragHorizontally" maybe?

2024-05-28 05:30 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.template.ts
> +		@focusin="${(x) => x._onFocusIn()}"
`_` methods are discouraged :)

2024-05-28 17:58 UTC, RichardHelm commented on libs/components/src/lib/popup/README.md
> +
Popup is an internal component that cannot be used by consumers, so this is just internal documentation

2024-05-28 17:59 UTC, RichardHelm commented on libs/components/src/lib/popup/popup.ts
> +	@attr({ mode: 'boolean', attribute: 'animation-frame' }) animationFrame =
Same as above, popup is internal

2024-05-28 18:01 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +			element.ariaValuetext = 'value text';
`valueTextFormatter` has a default value. So no, it will not

2024-05-28 18:03 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +	describe('thumb', () => {
No thumb refers to the actual thumb of the slider

2024-05-28 18:05 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +		it('should have visible focus when control is focused', async () => {
I don't really care what class it has, only that focus is not visible

2024-05-28 18:07 UTC, RichardHelm commented on libs/components/src/lib/range-slider/README.md
> +You can set the `valueTextFormatter` member to customize how values will be formatted for the thumbs' `aria-valuetext` attribute. The formatting will also be used for the tooltip when `pin` is enable
Sure but I don't want to start adding sections in this PR. It is not how we do it elsewhere so changing it is out of scope of the PR

2024-05-28 18:08 UTC, RichardHelm commented on libs/components/src/lib/range-slider/range-slider.spec.ts
> +			it('should move non-visible focus to the corresponding thumb', async () => {
Updated it

2024-05-28 18:08 UTC, RichardHelm commented on libs/components/src/lib/slider/README.md
> +You can set the `valueTextFormatter` member to customize how values will be formatted for the sliders' `aria-valuetext` attribute. The formatting will also be used for the tooltip when `pin` is enabl
As above, I don't want to make these changes in this PR

2024-06-03 03:29 UTC, YonatanKra commented on libs/components/src/lib/range-slider/README.md
> +Toggles display the start and end values with a tooltip. Use the `valueTextFormatter` member to customize the format of the values.
Looking at it now it makes even less sense. Why `start` and `end` values? It just shows the current value, doesn't it?

2024-06-03 03:31 UTC, YonatanKra commented on libs/components/src/lib/range-slider/README.md
> +You can set the `valueTextFormatter` member to customize how values will be formatted for the thumbs' `aria-valuetext` attribute. The formatting will also be used for the tooltip when `pin` is enable
So we don't do something right because we did it wrong until now? ;)
Let's start a change - this section is supposed to inform people regarding a11y features and IMO my suggestion sets a11y considerations at the forefront.

2024-06-03 09:13 UTC, RichardHelm commented
Splitting this PR into smaller ones

2024-06-03 09:13 UTC, closed without merging