chore(audio-player): refactor the audio player (VIV-1785)
Vonage/vivid-3 pull request #1726
Opened 2024-05-27 12:24 UTC by YonatanKra

- [ ] add play/pause methods
- [ ] hide the player element property
- [ ] make duration readonly
- [ ] make paused readonly
- [ ] Hide private methods that are not part of the HTML spec
- [ ] Remove formatTime from the class to a static function
- [ ] Refactor tests + cover all use cases
- [ ] Update documentation

2024-05-28 12:47 UTC, RichardHelm requested changes
This is much better! I left some comments and also we will need to come to a conclusion for the `_` members

2024-06-03 03:53 UTC, YonatanKra commented on libs/components/src/lib/audio-player/audio-player.ts
> +	}
1. It prevents an error when the user tries to set the paused value, while preventing the value from going out of sync (as per the HTML spec)
2. The `value;` is there because we have a rule of `non empty functions` :)
If we deleted this, tests will fail.

2024-06-03 03:55 UTC, YonatanKra commented on libs/components/src/lib/audio-player/audio-player.ts
> +	}
Same answer :)

2024-06-03 03:56 UTC, YonatanKra commented on libs/components/src/lib/audio-player/audio-player.ts
> +	}
As much as possible :)

2024-06-03 04:15 UTC, YonatanKra commented on libs/components/src/lib/audio-player/audio-player.ts
> +	#updateProgress = () => {
Good point. Actually, `currentTime` is part of the spec as a readonly member. 
Will change. Thanks!

2024-06-03 14:47 UTC, RichardHelm approved these changes
Thanks, component is much better now!
Minor suggestion left, take it or leave it...

2024-06-03 14:47 UTC, RichardHelm commented on libs/components/src/lib/audio-player/audio-player.ts
> +	}
I see. I think the rule allows comments so it could be made clearer like this:
```suggestion
	set paused(_) {
		// ignore
	}
```

2024-06-03 15:00 UTC, RichardHelm approved these changes

2024-06-04 03:29 UTC, merged