feat(popup): support placement strategy and animation frame options (VIV-1611)
Vonage/vivid-3 pull request #1736
Opened 2024-06-03 09:18 UTC by RichardHelm

2024-06-04 04:10 UTC, YonatanKra requested changes
Nice!
Thanks for this split and work well done.
Because now I understand that `popup` is our "facade" for `floatingUI` it makes much more sense.
3 comments and we're done here :)

2024-06-04 04:10 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.ts
> +		DOM.queueUpdate(() => this.#updateAutoUpdate());
Now I see that the reason we have 1 `rAF` in the case `animationFrame` is false. 
I gather a few things from this:
1. If we delete the `DOM.queueupdate` and leave just the `autoUpdate` all tests are passing. It is either irrelevant or it should be tested in the `open` tests. `should update position in the next animation frame` or something like that. 
2. This explains why when we set `animationFrame` to false, we get one `rAF` call. So I'd might change the `animationFrame` property's name to something more meaningful like `softPositionAnimation` or `smoothPositionAnimation` or `gradualPositionAnimation`. WDYT?

2024-06-04 04:10 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.ts
> +		this.#updateAutoUpdate();
`updateAutoUpdate` is not a descriptive name ;)
Wouldn't `updatePopupParmeters` be more descriptive?
I'm open for other names as well :)

2024-06-04 08:14 UTC, rachelbt reviewed
I haven't assigned myself and saw that @YonatanKra reviewed. Adding only one comment

2024-06-04 08:14 UTC, rachelbt commented on libs/components/src/lib/popup/README.md
> +- Type: `PlacementStrategy.Flip` | `PlacementStrategy.AutoPlacementHorizontal` | `PlacementStrategy.AutoPlacementVertical`
why no use the same convention like placement with value?
`placement-strategy = "flip" | "auto-placement-horizontal" | "auto-placement-vertical"`

2024-06-04 10:20 UTC, RichardHelm commented on libs/components/src/lib/popup/popup.ts
> +		DOM.queueUpdate(() => this.#updateAutoUpdate());
No, this change has nothing to do with animationFrame or its tests
If you delete it, the ui tests will fail. The reason is that it is wrong to call autoUpdate before open has changed in the the DOM, because floatingUI requires the floating element to be measurable. Which it isn't if open is false (`display: none`)

2024-06-04 10:32 UTC, RichardHelm commented on libs/components/src/lib/popup/popup.ts
> +		this.#updateAutoUpdate();
Mhm, I don't think the name is that bad. Anyway, I would say that is out of scope of this PR

2024-06-04 10:41 UTC, RichardHelm commented on libs/components/src/lib/popup/README.md
> +- Type: `PlacementStrategy.Flip` | `PlacementStrategy.AutoPlacementHorizontal` | `PlacementStrategy.AutoPlacementVertical`
Well, the actual reason why it is that way is that originally `PlacementStrategy.Flip` would be the actual middleware and not a string. But I had to change it to support the UI tests.

I don't think anything is improved by changing it now

2024-06-04 11:15 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.spec.ts
> +		});
I do not believe so. 
We do care about the amount of times rAF is called.
Floating UI is an implementation detail. You can implement this on your own or switch library - the tests should still pass :)

2024-06-04 11:18 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.ts
> +		DOM.queueUpdate(() => this.#updateAutoUpdate());
Then why not add a small unit test for it?
It should autoUpdate after `open` changed (e.g. after `elementUpdated`)

2024-06-04 11:19 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.ts
> +		this.#updateAutoUpdate();
Well... it made me read the function in order to just understand what it does, which makes it a bad name (always take the weak link as your test case - and I'm the weak link here ;) ).

2024-06-04 15:29 UTC, RichardHelm commented on libs/components/src/lib/popup/popup.ts
> +		this.#updateAutoUpdate();
Sure, maybe there is a better name but this review is already getting very big so I want to focus only the things actually in the PR

2024-06-05 05:50 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.spec.ts
> +		});
We are not testing dependencies for correctness. The fact you are using Floating UI is irrelevant. It is an implementation detail. We are testing the outcome of this - so if we removed floating UI or the corresponding code that implements this API, the test should fail.

2024-06-05 05:52 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.ts
> +		this.#updateAutoUpdate();
This review has only 4 comments ;)

2024-06-05 10:14 UTC, RichardHelm commented on libs/components/src/lib/popup/popup.spec.ts
> +		});
I've updated the test now to test that it continuously calls rAF. However the test is still bad and doesn't really test anything at all

If I change the test further to test that it actually updates position I end up testing floatingUI through popup...

Testing the outcome is not always what you want to do. E.g. when you have some code that sends an email, you don't want to test that it sends an actual email. Just that it calls some other code that is responsible for sending emails.

I'd argue that it's the same here. It's not popups job to calculate positions and keep them up to date, so we just verify that calls the code that is responsible for that

2024-06-17 17:47 UTC, YonatanKra requested changes

2024-06-17 17:47 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.spec.ts
> +		});
These can be combined to a single test:
```suggestion
		it('should begin to auto update after DOM is updated', async function () {
			element.anchor = anchor;
			element.open = true;
			const updateCallsBeforeDOMUpdate = floatingUI.autoUpdate.mock.calls.length;
			await elementUpdated(element);
      expect(updateCallsBeforeDOMUpdate).toBe(0);
			expect(floatingUI.autoUpdate).toHaveBeenCalledTimes(1);
		});
```

2024-06-17 17:47 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.spec.ts
> +				})
If we are going for this testing strategy, we should at least make sure the function is called with the correct parameters (anchor, popup element etc.)

2024-06-18 11:08 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.spec.ts
> +				})
Ok.
I deleted `this.anchor` from the call to `autoUpdate` and tests still passed.
Can you share where this is tested?

2024-06-18 16:15 UTC, RichardHelm commented on libs/components/src/lib/popup/popup.spec.ts
> +				})
Apparently nowhere then ;) But that is unrelated to my change

2024-06-19 08:06 UTC, YonatanKra approved these changes

2024-07-24 11:57 UTC, TaylorJ76 approved these changes

2024-07-24 11:57 UTC, merged