feat(slider): add pin feature (VIV-1611)
Vonage/vivid-3 pull request #1737
Opened 2024-06-03 09:21 UTC by RichardHelm

2024-06-04 11:12 UTC, YonatanKra requested changes
10x!
9 comments but I think most of them we discussed on slack or are mostly a prompt for possible change. All in all very few actually stop us from merging.

2024-06-04 11:12 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
> +		it('should have no visible focus when control is focused through mousedown', async () => {
```suggestion
		it('should prevent "focus-visible" class when focused after mousedown', async () => {
```

2024-06-04 14:03 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +		it('should display ariaValuetext in the popup if provided', async () => {
The `ariaValuetext` member is a mistake and should not exist.
`aria-valuetext` on the actual slider is automatically set based on `valueFormatter`, unless `ariaValuetext` is provided to override it.

2024-06-04 14:05 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +		it('should show popup when element has visible focus', async () => {
Visible focus means that the focus is visible (focus ring is displayed)

2024-06-04 14:09 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +	describe('dragging', () => {
No, it tests dragging the thumb

Can be made clearer:
```suggestion
	describe('dragging the thumb', () => {
```

2024-06-04 14:09 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +	describe('thumb', () => {
While there is coincidentally a member called `thumb`, this test is testing the drag handle on the slider, which is called thumb

The `thumb` member is defined by Fast and internal, in accordance with their way of marking internal members (`@internal`)

2024-06-04 14:11 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.ts
> +	}
When using private by convention (`_`) these are not considered exposed

2024-06-04 14:20 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.ts
> +			this.#isNonVisibleFocus = false;
Yes agreed, I think we should over time get rid of Fast foundation and pull all the code into our components

2024-06-04 14:24 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +		it('should have no visible focus when control is focused through mousedown', async () => {
No, what I wrote is exactly what I want to test. I don't care what the class is called

2024-06-04 14:28 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.ts
> +		const internals = this as any;
Sure, renamed to `fastSliderInternals`

I can't pull it out of the class because it uses private members.

I want to run my code before / after the overridden ones so event listener doesn't give that control

2024-06-05 11:10 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.ts
> +			this.#isNonVisibleFocus = true;
Yes, it's the same as the others
I added a test for this event as well now 👍

2024-06-19 08:14 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
> +	describe('dragging', () => {
Can it just be under the `thumb` tests?

2024-06-19 08:16 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.ts
> +		const internals = this as any;
Ok - so I take it as a Fast foundation tech debt.

2024-06-19 08:18 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.ts
> +	}
That's the problem - we have multiple conventions for the same purpose... ok, will give it more thought. Thanks.

2024-06-24 08:14 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
>  	});
After seeing this pattern in various tests, I believe we should refrain from using `it.each` and `describe.each`.
Does this test look clear and concise to you?

2024-06-24 08:17 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
> +		});
Please revert to the clearer format of simple describe and it.
This is very hard to understand and maintain.
Tests should be very simple.

2024-06-24 08:18 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
> +	describe('thumb', () => {
Fast are wrong. Thumb is public.
I mean, one can pretend it is not, but it is...

2024-06-24 08:20 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.ts
> +	}
As I've shown in a sample branch - the whole operation can be achieved without exposing multiple properties and adhere to the `ideal` state in our manifesto to use more `#` and less `_`.
Now that we understand what was not covered with tests, it is easy to do the refactor and prevent properties leaks like these.

2024-06-24 09:55 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.ts
> +	}
I don't see anything wrong with this code, it is very clear
Your refactor didn't work correctly when multiple conditions are met and then one stops being met. I think internal state is required to keep track of hover etc.

2024-06-24 09:56 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
>  	});
What's the alternative? Repeating the test several times doesn't seem clearer or more concise to me

2024-06-24 09:59 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
> +		});
As mentioned before, this test is needed to catch the issue in your refactor
Sure, I can revert it and I would be prefer it that way, but then we lose the thoroughness

2024-06-24 10:51 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.ts
> +	}
The word `internal` is key :)
Currently, the state isn't internal and the same result can be achieved without exposing the internal state.
The fact my refactor didn't work is - that the tests were incomplete. It was actually intentional, following my "tip" to delete lines and see if tests fail.

2024-06-24 11:03 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
>  	});
This test practically uses a loop for 2 use cases... it saves almost nothing while compromising clarity.
In addition, the test is quite misleading because I could just do:
`element.orientation = 'Sabathical';` and `expect(getPopup()!.placementStrategy).toBe('Sabathical');` will pass.
So it doesn't do anything except "bind" the value to the slider which does not require more than one test.
IMO it is preferred to write a test that shows that only valid values are accepted with a default value if an invalid value is supplied.

2024-06-24 11:04 UTC, YonatanKra commented on libs/components/src/lib/slider/slider.spec.ts
> +		});
Sorry for not being clear. I meant to rewrite it without the cumbersome `describe.each` :)

2024-06-24 17:28 UTC, RichardHelm commented on libs/components/src/lib/slider/slider.spec.ts
>  	});
It's not a straight forwarding. There is a mapping from orientation to placementStrategy that I'm testing both cases of:
```
	:placementStrategy=${(x) =>
            x.orientation === Orientation.horizontal
	            ? PlacementStrategy.AutoPlacementHorizontal
	            : PlacementStrategy.AutoPlacementVertical}
```

2024-06-25 13:12 UTC, YonatanKra approved these changes
As we agreed:
1. Create the ticket to remove the FAST hacks
2. We will set a meeting to discuss the code standard regarding private properties

2024-07-23 17:01 UTC, merged