chore: moves angular eslint to dev deps
Vonage/vivid-3 pull request #1775
Opened 2024-06-14 08:00 UTC by TaylorJ76

2024-06-17 07:53 UTC, YonatanKra requested changes

2024-06-17 07:53 UTC, YonatanKra commented on libs/eslint-plugin/.eslintrc.json
> +		"@typescript-eslint/no-attribute-default-value": "off"
What's that for?

2024-06-17 09:40 UTC, TaylorJ76 commented on libs/eslint-plugin/.eslintrc.json
> +		"@typescript-eslint/no-attribute-default-value": "off"
Not needed. Removed.

2024-06-19 13:25 UTC, YonatanKra approved these changes

2024-06-20 09:24 UTC, merged