chore(docs): v4 migration page (VIV-1801)
Vonage/vivid-3 pull request #1776
Opened 2024-06-14 12:17 UTC by rachelbt

2024-06-17 10:42 UTC, TaylorJ76 requested changes

2024-06-17 10:42 UTC, TaylorJ76 commented on docs/resources/v4-release-migration.md
> +This is a migration guide to make the upgrade easy :)
```suggestion
# Vivid v4.0.0 Migration Guide

Release date: 1st July 2024.  
This document provides descriptions of the breaking changes in this release and instructions on how to prepare for them.
```

2024-06-17 10:42 UTC, TaylorJ76 commented on docs/resources/v4-release-migration.md
> +### The change
Could we provide a short description of the change for each? 
For example: 

The audio-player will now stretch to fill it's container's width by default. Previously it was restricted to 350px.

2024-06-17 10:42 UTC, TaylorJ76 commented on docs/resources/v4-release-migration.md
> +TBA: Look into how we help with an upgrade script?
Maybe mention something about the eslint-plugin? Ask Richard for some help with the text.

2024-06-18 06:59 UTC, rachelbt commented on docs/resources/v4-release-migration.md
> +TBA: Look into how we help with an upgrade script?
I did, he said that he will send me a line or two for this section :)

2024-06-19 13:44 UTC, TaylorJ76 requested changes

2024-06-19 13:44 UTC, TaylorJ76 commented on docs/resources/v4-release-migration.md
> +- First, make sure you're on the latest version of Vivid 2.x.
Should this say Vivid 2.x?

2024-06-19 13:53 UTC, rachelbt commented on docs/resources/v4-release-migration.md
> +- First, make sure you're on the latest version of Vivid 2.x.
suppose to be 3.x :)

2024-06-19 14:56 UTC, TaylorJ76 submitted a review, later dismissed

2024-06-21 14:51 UTC, RichardHelm requested changes

2024-06-21 14:51 UTC, RichardHelm commented on docs/resources/v4-release-migration.md
> +	@update:model-value="$event => (value = $event)"
Actually needs to be this:
```suggestion
	@update:modelValue="$event => (value = $event)"
```

2024-06-21 14:51 UTC, RichardHelm commented on docs/resources/v4-release-migration.md
> +  The `no-current-value-attribute` rule of our ESLint plugin can perform this migration automatically.
Importantly, the rule applies to both points:
```suggestion
- Replace all usage of `currentValue` / `currentChecked` with `modelValue` and all usages `currentStart` / `currentEnd` with `start` / `end`.  
  The `no-current-value-attribute` rule of our ESLint plugin can perform this migration automatically.
```

2024-06-21 14:51 UTC, RichardHelm commented on docs/resources/v4-release-migration.md
> +</vwc-note>
Not true, it will go in 3.x
```suggestion
```

2024-06-21 14:51 UTC, RichardHelm commented on docs/resources/v4-release-migration.md
> +Data-grid-cell will no longer have a fixed block-size but will adjust to its content and its text will not be trimmed by default ad before.
This is only for non-header cells:
```suggestion
Data-grid-cells outside of the table header will no longer have a fixed block-size but will adjust to its content and its text will not be trimmed by default as before.
```

2024-06-24 10:58 UTC, RichardHelm approved these changes

2024-06-26 03:39 UTC, closed without merging