feat(buttons): add outline-light appearance (VIV-1775)
Vonage/vivid-3 pull request #1791
Opened 2024-06-23 08:56 UTC by rachelbt

2024-06-24 08:31 UTC, YonatanKra requested changes

2024-06-24 08:31 UTC, YonatanKra commented on docs/design/appearance.md
> +### Important to know
What is important to know? Just the example?

2024-06-24 13:15 UTC, rachelbt commented on docs/design/appearance.md
> +`button`, `split-button`
```suggestion
`button`
```

2024-06-24 13:15 UTC, rachelbt commented on docs/design/appearance.md
> +### Important to know
```suggestion

```

2024-06-24 13:15 UTC, rachelbt commented on docs/design/appearance.md
> +### Important to know
bad copy paste :)

2024-06-25 08:56 UTC, YonatanKra approved these changes
Can you create a ticket to move the appearance-ui to the docs?

2024-06-25 12:17 UTC, merged

2024-06-25 12:32 UTC, rachelbt commented
> Can you create a ticket to move the appearance-ui to the docs?

done: https://jira.vonage.com/browse/VIV-1839