fix(audio-player): keep paused state while dragging (VIV-1787)
Vonage/vivid-3 pull request #1792
Opened 2024-06-24 08:13 UTC by YonatanKra

2024-06-24 15:23 UTC, RichardHelm requested changes
I found two issues when testing this:

1. The slider doesn't drag smoothly anymore

https://github.com/Vonage/vivid-3/assets/86777660/eead0399-3274-4c0e-b1e0-1032ea1fe9e3



2. Audio player should pause while dragging

2024-06-25 15:17 UTC, YonatanKra commented
> I found two issues when testing this:
> 
> 1. The slider doesn't drag smoothly anymore
> 
>  Screen.Recording.2024-06-24.at.16.18.10.mov 
> 2. Audio player should pause while dragging

Thanks.
1. This is also happening in the slider with no relation to the audio player (I did send an update that prevents changing the slider from two different locations).
2. This is the main reason for the fix. The native HTML audio keeps playing while dragging.

2024-06-25 15:51 UTC, RichardHelm commented
@YonatanKra Thanks, first issue is solved.

For the second, it depends on the implementation but most audio players (e.g. native `<audio>` in Chrome) pause the audio while being dragged and resume it afterwards. Otherwise you get choppy sound as it is dragged around

2024-06-26 09:52 UTC, RichardHelm approved these changes

2024-06-27 05:46 UTC, merged