add Main Pull Request
Vonage/vivid-3 pull request #18
Opened 2021-11-10 11:13 UTC by rinaok

2021-11-10 11:45 UTC, yinonov requested changes

2021-11-10 11:45 UTC, yinonov commented on .github/workflows/pull-request-main.yml
> +      - run: printf "registry=https://npm.pkg.github.com/Vonage\n_authToken=\${{ secrets.NPM_VVD_VNG_AUTOMATION_TOKEN }}\n//npm.pkg.github.com/:_authToken=\${{ secrets.NPM_VVD_VNG_AUTOMATION_TOKEN }}
can we dry-run this? we dont want to deploy anything not meaningful at this point of exploration

2021-11-10 11:56 UTC, rinaok commented on .github/workflows/pull-request-main.yml
> +      - run: printf "registry=https://npm.pkg.github.com/Vonage\n_authToken=\${{ secrets.NPM_VVD_VNG_AUTOMATION_TOKEN }}\n//npm.pkg.github.com/:_authToken=\${{ secrets.NPM_VVD_VNG_AUTOMATION_TOKEN }}
It's not for deployment

2021-11-10 12:12 UTC, yinonov commented on .github/workflows/pull-request-main.yml
> +      - run: printf "registry=https://npm.pkg.github.com/Vonage\n_authToken=\${{ secrets.NPM_VVD_VNG_AUTOMATION_TOKEN }}\n//npm.pkg.github.com/:_authToken=\${{ secrets.NPM_VVD_VNG_AUTOMATION_TOKEN }}
ok. just makes sure later this publishes a tagged version and not the semver

2021-11-13 08:39 UTC, yinonov commented on .github/workflows/pull-request.yml
> +      - run: printf "registry=https://npm.pkg.github.com/Vonage\n_authToken=\${{ secrets.NPM_VVD_VNG_AUTOMATION_TOKEN }}\n//npm.pkg.github.com/:_authToken=\${{ secrets.NPM_VVD_VNG_AUTOMATION_TOKEN }}
still required?

2021-11-14 11:36 UTC, rinaok commented on .github/workflows/pull-request.yml
> +      - run: printf "registry=https://npm.pkg.github.com/Vonage\n_authToken=\${{ secrets.NPM_VVD_VNG_AUTOMATION_TOKEN }}\n//npm.pkg.github.com/:_authToken=\${{ secrets.NPM_VVD_VNG_AUTOMATION_TOKEN }}
no

2021-11-14 14:38 UTC, closed without merging