fix(tabs): change gutters default to small (VIV-1796)
Vonage/vivid-3 pull request #1804
Opened 2024-06-26 14:30 UTC by rachelbt

2024-06-26 15:48 UTC, RichardHelm requested changes

2024-06-26 15:48 UTC, RichardHelm commented on libs/components/src/lib/tabs/tabs.template.ts
> +		['gutters-small', !gutters],
Nit, but it will set the class twice.
```suggestion
		`gutters-${gutters ?? 'small'}`,
```

2024-06-26 15:48 UTC, RichardHelm commented on libs/components/src/lib/tabs/README.md
> +- Default: `small`
Why does this not require updating any tests? Shouldn't it break screenshots

2024-06-27 06:01 UTC, rachelbt commented on libs/components/src/lib/tabs/tabs.template.ts
> +		['gutters-small', !gutters],
thanks!!!
Was wondering how to do that and didn't want to bother anyone :)

2024-06-27 06:07 UTC, rachelbt commented on libs/components/src/lib/tabs/README.md
> +- Default: `small`
you are right - the first code should failed the ui tests. (in all the other we added in the code `gutters="small"`).
Updating

2024-06-27 17:48 UTC, RichardHelm approved these changes

2024-06-30 07:17 UTC, merged