test( layout): add test coverage
Vonage/vivid-3 pull request #182
Opened 2022-02-08 13:18 UTC by rinaok

2022-02-08 13:20 UTC, yinonov reviewed
.

2022-02-08 13:25 UTC, yinonov requested changes

2022-02-08 13:25 UTC, yinonov commented on libs/components/src/lib/layout/layout.spec.ts
> +		it('sets correct internal gutters style', async () => {
Can u reword using 'should'?

2022-02-13 09:28 UTC, YonatanKra commented on libs/components/src/lib/layout/layout.spec.ts
> +			expect(control)
Should I expect this to fail if I do not define `gutters`?

2022-02-13 09:29 UTC, YonatanKra commented on libs/components/src/lib/layout/layout.spec.ts
> +			expect(control)
Same question regarding failure here

2022-02-13 09:30 UTC, YonatanKra commented on libs/components/src/lib/layout/layout.spec.ts
> +		it('should set correct internal gutters style', async () => {
Maybe class instead of style?
```suggestion
		it('should set correct internal gutters class', async () => {
```

2022-02-13 09:34 UTC, YonatanKra commented on libs/components/src/lib/layout/layout.spec.ts
> +		});
Should I expect this to fail if I do not define `gutters`?
We'd might want to check "before and after".
```suggestion
			const gutters = Size.BaseLarge;
			const control = getControlElement();
			const classExistsWithoutGutters = control.classes.hasClass(`control.gutters-${gutters}`);
			(element as any).gutters = gutters;
			await elementUpdated(element);

			expect(classExistsWithoutGutters).toEqual(false);
			expect(control.classes.hasClass(`control.gutters-${gutters}`)).toEqual(true);
		});
```
You can even refactor for better readability by extracting to meaningfully named functions.

2022-02-13 09:36 UTC, YonatanKra commented on libs/components/src/lib/layout/layout.spec.ts
> +		it('should set correct internal column-basis style', async () => {
Same as above both for `style => class` as well as the test itself.

2022-02-13 09:36 UTC, YonatanKra commented on libs/components/src/lib/layout/layout.spec.ts
> +		it('should set correct internal column-spacing style', async () => {
Same as above

2022-02-13 09:36 UTC, YonatanKra commented on libs/components/src/lib/layout/layout.spec.ts
> +		it('should set correct internal auto-sizing style', async () => {
Same as above

2022-02-13 09:37 UTC, YonatanKra requested changes
See remarks in the tests files

2022-02-13 20:46 UTC, yinonov reviewed
it seems like the width cross browsers' viewport is different

2022-02-14 11:13 UTC, rinaok commented
> is the width cross browsers' viewport different? 🤔

@yinonov @YonatanKra The UI test in Firefox looks different.

2022-02-14 11:19 UTC, YonatanKra commented
> > is the width cross browsers' viewport different? 🤔
> 
> @yinonov @YonatanKra The UI test in Firefox looks different. 

Yes it is different in each browser

2022-02-14 12:17 UTC, yinonov approved these changes

2022-02-15 15:21 UTC, merged