feat(dialog): improve api with modal attribute (VIV-1657)
Vonage/vivid-3 pull request #1853
Opened 2024-07-17 14:09 UTC by RichardHelm

2024-07-23 07:12 UTC, TaylorJ76 requested changes

2024-07-23 07:12 UTC, TaylorJ76 commented on libs/components/src/lib/dialog/dialog.template.ts
>  		dialog.open = false;
Should we stop the propagation of the event here to stop it affecting other components that are listening for an escape key event?
For example, if the modal markup was inside a side drawer component for some reason, escape would also close the side drawer as well as the modal.

2024-07-24 11:28 UTC, RichardHelm commented on libs/components/src/lib/dialog/dialog.template.ts
>  		dialog.open = false;
@TaylorJ76 Yes, but that would not really be related to the `modal` feature.
Also, we need to do it for all other components.
I created a new ticket for it: https://jira.vonage.com/browse/VIV-1950

2024-07-24 11:59 UTC, TaylorJ76 approved these changes

2024-07-24 13:36 UTC, merged