feat(empty-state): adding connotation and design variation (VIV-1378)
Vonage/vivid-3 pull request #1863
Opened 2024-07-24 15:09 UTC by rachelbt

2024-07-29 06:08 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +		var(#{constants.$vvd-color-canvas}) 80%
```suggestion
		var(#{constants.$vvd-color-canvas}) 70%
```

2024-07-29 06:08 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	color: var(#{constants.$vvd-color-canvas});
```suggestion
	color: var(#{constants.$vvd-color-canvas-text});
```

2024-07-29 15:20 UTC, RichardHelm requested changes

2024-07-29 15:20 UTC, RichardHelm commented on libs/components/src/lib/empty-state/empty-state.scss
> +	@include appearance.appearance;
IMO, it is not right to use appearance mixin here. Design didn't use appearance so why should the code? The mixed colors end up different from the design 

```suggestion
	@include connotation.connotation(empty-state);
```

2024-07-29 15:20 UTC, RichardHelm commented on libs/components/src/lib/empty-state/README.md
> +- Default: `undefined`
It seems weird to have a boolean `icon-design`.
Maybe it should be an enum instead, like `graphic-appearance/design=outlined/filled`
Or rename to something like `outlined-icon`. However, I think enum is better to leave room for more options in the future

2024-07-30 06:55 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	@include appearance.appearance;
the badge is a huge mistake of mine and I'll fix it.

But we are always using connotation and appearance together - see alert & progress.
On the other hand we have icons that do not use it.
I wonder what is the right way to do that.
Do we want all components that has one appearance, no states to use connotation directly or use it via appearances...
If I'm not using connotation directly - I can use whatever shades I want, is it good for the design-system or should we align to appearances?
@AyalaBu @TaylorJ76 
WDYT?

2024-07-31 08:46 UTC, rachelbt commented on libs/components/src/lib/empty-state/empty-state.scss
> +	@include appearance.appearance;
I removed the appearance and created a ticket to align other component to the same convention: https://jira.vonage.com/browse/VIV-1960

2024-07-31 09:31 UTC, RichardHelm requested changes
Looks good! Just these outdated names

2024-07-31 09:31 UTC, RichardHelm commented on libs/components/src/lib/empty-state/README.md
> +Use graphic-design to change the design of the icon circle
```suggestion
Use icon-decoration to change the design of the icon circle.
```

2024-07-31 09:31 UTC, RichardHelm commented on libs/components/src/lib/empty-state/empty-state.ts
> +	 * HTML Attribute: icon-design
```suggestion
	 * HTML Attribute: icon-decoration
```

2024-07-31 10:37 UTC, RichardHelm approved these changes

2024-07-31 11:49 UTC, merged