feat(dialog, side-drawer): add cancel event (VIV-1899)
Vonage/vivid-3 pull request #1869
Opened 2024-08-01 16:20 UTC by RichardHelm

2024-08-12 09:41 UTC, TaylorJ76 submitted a review, later dismissed

2024-08-12 16:41 UTC, YonatanKra requested changes
Thanks for that. 
Some minor changes

2024-08-12 16:41 UTC, YonatanKra commented on libs/components/src/lib/dialog/README.md
> +| `cancel` | `CustomEvent<undefined>` | No      | Yes      | The `cancel` event fires when the user requests to close the dialog. You can prevent the dialog from closing by calling `.preventDefault()
```suggestion
| `cancel` | `CustomEvent<undefined>` | No      | Yes      | The `cancel` event fires when the user requests to close the dialog, before the dialog closes. You can prevent the dialog from closing by calling `.preventDefault()` on the event.     |
```

2024-08-12 16:41 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.template.ts
> +		@click="${(x) => x._handleCloseRequest()}"
`_handleCloseRequest` does not belong on the class.
Create a local function in the template file and use it instead of polluting the class itself.

2024-08-12 16:41 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.template.ts
>  				?aria-modal="${(x) => x._openedAsModal}"
Why do we need `_openAsModal` if we already have an exposed API `modal`?

2024-08-12 16:41 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.template.ts
> +				@keydown="${(x, c) => x._onKeyDown(c.event as KeyboardEvent)}"
Please remove `_onKeyDown` from the class and create a local template function.

2024-08-12 16:41 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.ts
> +			// See: https://html.spec.whatwg.org/multipage/interaction.html#close-watcher-infrastructure
Can this be tested?

2024-08-12 16:41 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.ts
> +	_handleCloseRequest() {
See my comment regarding the removal of this method.

2024-08-12 16:41 UTC, YonatanKra commented on libs/components/src/lib/side-drawer/README.md
> +| `cancel` | `CustomEvent<undefined>` | No      | Yes      | Fired when the user requests to close the side-drawer. You can prevent the side drawer from closing by calling `.preventDefault()` on the
```suggestion
| `cancel` | `CustomEvent<undefined>` | No      | Yes      | Fired when the user requests to close the side-drawer, before it is closed. You can prevent the side drawer from closing by calling `.preventDefault()` on the event. |
```

2024-08-12 16:41 UTC, YonatanKra commented on libs/components/src/lib/side-drawer/side-drawer.template.ts
> +		@keydown="${(x, c) => x._onKeydown(c.event as KeyboardEvent)}"
See my remarks in the dialog

2024-08-12 16:41 UTC, YonatanKra commented on libs/components/src/lib/side-drawer/side-drawer.template.ts
> +			@click="${(x) => x._handleCloseRequest()}"
See my remarks in the dialog

2024-08-12 17:27 UTC, RichardHelm commented on libs/components/src/lib/dialog/README.md
> +| `cancel` | `CustomEvent<undefined>` | No      | Yes      | The `cancel` event fires when the user requests to close the dialog. You can prevent the dialog from closing by calling `.preventDefault()
I don't think this is relevant or adds anything

2024-08-12 17:31 UTC, RichardHelm commented on libs/components/src/lib/dialog/dialog.ts
> +			// See: https://html.spec.whatwg.org/multipage/interaction.html#close-watcher-infrastructure
I have added a UI test for correct behaviour now
However, it passes anyway because this behaviour is a recent addition to the spec. It is not yet implemented in the browser versions that we test with

2024-08-27 10:45 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.ts
> +			// See: https://html.spec.whatwg.org/multipage/interaction.html#close-watcher-infrastructure
I'm unable to reproduce this behavior even when I remove this line. Here are the steps I've taken:
1. Create a modal dialog
2. Add event listener to the `cancel` event and prevent default
3. Open the modal
4. Hit escape multiple times
5. Dialog remains open
Is this the flow that's supposed to reproduce this use case?

2024-08-27 10:47 UTC, YonatanKra requested changes

2024-08-27 10:47 UTC, YonatanKra commented on libs/components/src/lib/side-drawer/side-drawer.ts
> +			// we need to return true from our handler to opt - out of this behavior.
How is this helping? What scenario does this intend to fix?

2024-09-02 10:56 UTC, RichardHelm commented on libs/components/src/lib/dialog/dialog.ts
> +			// See: https://html.spec.whatwg.org/multipage/interaction.html#close-watcher-infrastructure
Yes, that's right. It will close the dialog in step 5 if you use a browser that implements the spec, e.g. Chrome

2024-09-02 11:04 UTC, RichardHelm commented on libs/components/src/lib/side-drawer/side-drawer.ts
> +			// we need to return true from our handler to opt - out of this behavior.
I have only moved this code, but it will not call preventDefault on all keydown events in side drawer

2024-09-04 07:40 UTC, YonatanKra submitted a review, later dismissed
Mostly the tests comments.

2024-09-04 07:40 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.template.ts
>  				?aria-modal="${(x) => x._openedAsModal}"
How would it break backwards compatibility?
When was the `modal` added?

2024-09-16 15:41 UTC, RichardHelm commented on libs/components/src/lib/dialog/dialog.template.ts
>  				?aria-modal="${(x) => x._openedAsModal}"
If `showModal()` would set `modal` attribute, behaviour of code like this would change:
```
x.showModal()
x.close()
x.open = true; // will be modal now but wasn't before
```

2024-09-16 15:44 UTC, RichardHelm commented on libs/components/src/lib/dialog/dialog.template.ts
> +				@keydown="${(x, c) => x._onKeyDown(c.event as KeyboardEvent)}"
As with the others, I think all logic should go into the class

2024-09-18 08:05 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.template.ts
>  				?aria-modal="${(x) => x._openedAsModal}"
We talked about this privately. Let's move to `#` instead of `_` to prevent such cases from slipping to production.

2024-09-18 08:06 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.template.ts
> +				@keydown="${(x, c) => x._onKeyDown(c.event as KeyboardEvent)}"
After we saw how things can go wrong in the Dialog, I think we can safely revert to our own coding standards and remove the `_`. WDYT?

2024-10-10 08:46 UTC, TaylorJ76 approved these changes

2024-10-10 09:55 UTC, merged