feat(searchable-select): add component (VIV-1793)
Vonage/vivid-3 pull request #1882
Opened 2024-08-14 17:10 UTC by RichardHelm

2024-09-23 07:16 UTC, TaylorJ76 reviewed
Margin between label and control is smaller than other form elements.

2024-09-23 16:31 UTC, RichardHelm commented
@TaylorJ76 You're right, fixed

2024-09-24 07:08 UTC, TaylorJ76 requested changes
When using a keyboard to navigate the listbox options, when I key down to an item that is outside of the visible scrollable area, it doesn't scroll into view.
As a result you loose track of which item you are focussed on.

2024-09-25 07:23 UTC, rachelbt commented on libs/components/src/lib/searchable-select/option-tag.scss
> +	$appearances: subtle-light,
I think this is not the right place to create a new appearance.
This needs to be added properly - with all the states and not only the ones that are needed here.
I suggest we use suble and once we have the one with opacity we will use it.

2024-09-25 07:32 UTC, rachelbt commented on libs/components/src/lib/searchable-select/option-tag.template.ts
> +import { html, when } from '@microsoft/fast-element';
why can't we use vwc-tag?

2024-09-25 08:29 UTC, TaylorJ76 reviewed
It would also be good if the popup with menu didn't ever exceed the available visible viewport.
So, it would adapt it's height if, when populated, it exceed the viewport.

2024-09-25 17:12 UTC, RichardHelm commented on libs/components/src/lib/searchable-select/option-tag.template.ts
> +import { html, when } from '@microsoft/fast-element';
It has different semantics. Tag is an option while the option-tag is text + remove button. Also, the whole tag appears interactive unlike option-tag where only remove button is clickable. It also does not have `light` appearance.

2024-09-25 17:24 UTC, RichardHelm commented on libs/components/src/lib/searchable-select/option-tag.scss
> +	$appearances: subtle-light,
Sure, I've removed the appearance and created a ticket for it: https://jira.vonage.com/browse/VIV-2161

2024-09-25 17:36 UTC, RichardHelm commented
@TaylorJ76 
> When using a keyboard to navigate the listbox options, when I key down to an item that is outside of the visible scrollable area, it doesn't scroll into view.

Makes sense. I have created a new ticket for this as well to keep the PR focussed: https://jira.vonage.com/browse/VIV-2162

> It would also be good if the popup with menu didn't ever exceed the available visible viewport.
It makes sense but the current behaviour is the same as `vwc-select` etc. So it should be fixed for all of them. I have created a ticket for it: https://jira.vonage.com/browse/VIV-2163

2024-09-26 08:20 UTC, TaylorJ76 requested changes

2024-09-26 08:20 UTC, TaylorJ76 commented on libs/components/src/lib/searchable-select/searchable-select.template.ts
> +							html<SearchableSelect>`<div class="empty-message">
Is there a way this can be optimised by removing the duplication with the *no matches* code block above?

2024-09-26 08:20 UTC, TaylorJ76 commented
Great stuff @RichardHelm!

2024-09-26 14:00 UTC, merged