feat(dialog): stop escape press propagation (VIV-1950)
Vonage/vivid-3 pull request #1883
Opened 2024-08-19 15:20 UTC by YonatanKra

2024-08-22 09:56 UTC, TaylorJ76 commented on apps/docs/assets/scripts/icons-gallery/icons-gallery.js
> -
Wasn't this added recently?

2024-08-27 07:53 UTC, YonatanKra commented on apps/docs/assets/scripts/icons-gallery/icons-gallery.js
> -
I have no idea how this got there... only shows not having tests on the docs has become a problem :)

2024-08-28 07:43 UTC, TaylorJ76 requested changes

2024-08-28 07:43 UTC, TaylorJ76 commented on libs/components/src/shared/date-picker/date-picker-base.ts
> +		if (handleEscapeKeyAndStopPropogation(event)) {
This needs to only stop propogation when the popup is open.

2024-08-28 14:27 UTC, TaylorJ76 approved these changes

2024-08-29 06:41 UTC, merged