fix(dial-pad): fix input, blur, change and focus events leak (VIV-2065)
Vonage/vivid-3 pull request #1911
Opened 2024-09-18 16:06 UTC by YonatanKra

Events now fire only once

2024-09-18 16:40 UTC, RichardHelm requested changes

2024-09-18 16:40 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.ts
> -		this.value = this._textFieldEl.value;
This is no longer happening

2024-09-18 16:40 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.template.ts
> +			@focus="${eventHandlerFactory('focus')}">
Blur and focus events are still emitted twice
I think `.stopImmediatePropagation()` has no effect as the events do not bubble in first the place. There is actually no need to do anything as the component emits `focus` and `blur` automatically if a child receives focus.
This is however incorrectly documented as `Emitted when the text field receives focus`

2024-09-18 16:40 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.template.ts
> +			@change="${eventHandlerFactory('change')}"
The events are not emitted when the delete button is clicked
The change event is still emitted twice for some reason

2024-09-18 17:51 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.ts
> -		this.value = this._textFieldEl.value;
Nice catch. It was not tested :(
It is now :)

2024-09-18 17:55 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.template.ts
> +			@focus="${eventHandlerFactory('focus')}">
I can see the problem now.
It stems from the fact we have a hidden knowledge in a `_onDigit` that fires the `change` event also on click...
I saw a lot of opporunities for a refactor here and missing tests.

2024-09-18 17:57 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.template.ts
> +			@change="${eventHandlerFactory('change')}"
Regardig change:
It stems from the fact we have a hidden knowledge in a `_onDigit` that fires the `change` event also on click in certain areas.
Not tested (hence not documented and not in the template file so far away from the actual event listene)... now it will be. Thanks.

2024-09-18 18:54 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.template.ts
> +			@change="${eventHandlerFactory('change')}"
The delete button now works as expected

2024-09-18 19:14 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.template.ts
> +			@focus="${eventHandlerFactory('focus')}">
Yes, you are correct. Every click anywhere in the dialog emits a focus.
The problem is that our `text-field` emits an event that bubbles despit it being set as `bubbles: false`
Will research further in the morning

2024-09-18 19:23 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.template.ts
> +			@focus="${eventHandlerFactory('focus')}">
I actually think the author of the component meant for the focus and blur to be fired only on the `text-field`. Hence this is a bug. We need to stop all other focus events and send an event only from `text-field`. WDYT?

2024-09-19 08:40 UTC, RichardHelm requested changes

2024-09-19 08:40 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.ts
>  		this.$emit('change');
It should emit 'input' as well right?

2024-09-19 08:40 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.template.ts
> +	_.$emit('Blah');
```suggestion
```

2024-09-19 08:40 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.template.ts
> +			@focus="${eventHandlerFactory('focus')}">
Well, it may be intended that way but the dial-pad becomes the focused element in the main document when any child receives focus. When it becomes focused it should emit a `focus` event like all elements
Maybe the text-field events should be forwarded as `text-field-focus/blur`?

2024-09-19 12:37 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.ts
>  		this.$emit('change');
Handled in a different PR.

2024-09-20 02:51 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.template.ts
> +			@focus="${eventHandlerFactory('focus')}">
I don't know if there's a difference. We need to decide if we want to the text-field to be the focus here. The buttons serve as a different kind of text-field, and eventually, affect it much like typing does.
Moreover, tabbing works just as expected - originating from the focused dial pad button and moving to the next/previous one.
Do we want a dedicated event for text-field? It's doable. Just need to decide. Anyway, it's not part of this PR.

2024-09-20 14:16 UTC, RichardHelm approved these changes

2024-09-24 17:32 UTC, merged