fix(dial-pad): prevent focus loss after removal of delete button (VIV-2126)
Vonage/vivid-3 pull request #1912
Opened 2024-09-19 10:05 UTC by YonatanKra

1. Add blur listener to the dial pad
2. Type 1 number
3. Delete number using the backspace button in the text-field
4. See that focus remains inside the dial pad

2024-09-20 14:23 UTC, RichardHelm requested changes

2024-09-20 14:23 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.ts
> +			);
Why would this be needed?
If there is actually a reason for it needs to be explained in a comment

```suggestion
			this._textFieldEl.focus();
```

2024-09-24 17:42 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.ts
> +			);
1. We need to prevent the focus event from firing
2. This is tested
3. I've wrapped the logic in a function with a descriptive name.

2024-09-26 13:17 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.ts
> +			);
I don't understand. The component will not emit focus (or blur) when focus moves within, so this should not be necessary.

2024-10-21 05:33 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.ts
> +			);
See the related issue.
When pressing the delete button (in the UI) to delete the last character in the input, it fires a blur event and the dial pad loses focus. This makes sure it remains that way. 
See the descriptions:
<img width="679" alt="image" src="https://github.com/user-attachments/assets/e0530dcc-af70-4b32-9a45-8a249f30fc16">

2024-10-21 14:06 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.ts
> +			);
This solves the problem of focus leaving the component after deleting the last character. Focus does not remain inside the component hence the event being fired.

2024-10-21 14:53 UTC, RichardHelm commented on libs/components/src/lib/dial-pad/dial-pad.ts
> +			);
Yes I understand that. But how does the suggested change not resolve the issue? Focus moves to text-field, therefore no blur (or focus) will be emitted on the dial-pad

2024-10-22 04:01 UTC, YonatanKra commented on libs/components/src/lib/dial-pad/dial-pad.ts
> +			);
Oh, I see what you mean. 
The focus will happen before the event dispatches.
Nice one, thanks!

2024-10-22 09:11 UTC, RichardHelm approved these changes

2024-10-22 09:43 UTC, merged