feat(menu): add strategy-absolute to allow positioning menu absolute rather then fixed (VIV-2135)
Vonage/vivid-3 pull request #1918
Opened 2024-09-24 17:30 UTC by rachelbt

2024-09-24 17:31 UTC, rachelbt commented on libs/components/src/lib/menu/README.md
> +</div>
```suggestion
<vwc-menu open aria-label="Menu example" placement="bottom-end">
	<vwc-button
		slot="anchor"
		icon="more-vertical-line"
		aria-label="Open menu"
		appearance="outlined"
	></vwc-button>
	<vwc-menu-item text="Menu item 1"></vwc-menu-item>
	<vwc-menu-item text="Menu item 2"></vwc-menu-item>
</vwc-menu>
```

2024-09-26 07:32 UTC, TaylorJ76 requested changes

2024-09-26 07:32 UTC, TaylorJ76 commented on libs/components/src/lib/menu/menu.ts
> +	@attr({ mode: 'boolean', attribute: 'strategy-absolute' }) strategyAbsolute =
Suggestion:

```
import type { Strategy as Position } from '@floating-ui/dom';

...

@attr position?: Position = 'fixed';
 ```

The reason I'm suggestion `position` is that consumers don't know strategy is because we are using it under the hood in popup.
Position feels a bit more obvious what its function is.

2024-09-26 08:20 UTC, rachelbt commented on libs/components/src/lib/menu/menu.ts
> +	@attr({ mode: 'boolean', attribute: 'strategy-absolute' }) strategyAbsolute =
I agree that strategy is not ideal, the thing is that we also have `placement` - that can be confusing with `position`.

2024-09-26 14:17 UTC, TaylorJ76 commented on libs/components/src/lib/menu/menu.ts
> +	@attr({ mode: 'boolean', attribute: 'strategy-absolute' }) strategyAbsolute =
How about `placement-strategy`? 
It gives a bit more context to what it does and shows it is related to `placement`.

2024-09-30 08:52 UTC, TaylorJ76 submitted a review, later dismissed

2024-09-30 13:01 UTC, rachelbt reviewed
@TaylorJ76 , I changed the property to position-strategy, since placement-strategy is something else that we have in popup...

2024-09-30 14:36 UTC, TaylorJ76 submitted a review, later dismissed

2024-10-02 06:36 UTC, TaylorJ76 approved these changes

2024-10-02 07:41 UTC, merged