chore(docs): update icon docs to new format (VIV-2099)
Vonage/vivid-3 pull request #1952
Opened 2024-10-17 09:05 UTC by RichardHelm

2024-10-18 09:45 UTC, TaylorJ76 requested changes
This UI tests are also failing.

2024-10-20 19:14 UTC, rachelbt commented on libs/components/src/lib/icon/VARIATIONS.md
> +### Custom Icon
I think that sizes should come bebore this

2024-10-21 07:38 UTC, RichardHelm commented on libs/components/src/lib/icon/README.md
> +### Events
I've copied them from the Vue wrappers but I suppose we can remove the non-relevant ones

2024-10-21 07:41 UTC, RichardHelm commented on libs/components/src/lib/icon/VARIATIONS.md
> +### Custom Icon
Well, it's part of the Icon section which should go first I think

2024-10-22 06:57 UTC, TaylorJ76 approved these changes

2024-10-22 09:14 UTC, merged