feat(button): stacked button
Vonage/vivid-3 pull request #196
Opened 2022-02-14 11:02 UTC by rachelbt

2022-02-14 12:21 UTC, yinonov requested changes

2022-02-14 12:21 UTC, yinonov commented on libs/components/src/lib/button/partials/variables.scss
> +$stacked-icon-gap: --stacked-button-icon-gap;
Can we adopt the private access convention of variable prefixed with underline?

2022-02-14 12:23 UTC, yinonov requested changes

2022-02-14 12:23 UTC, yinonov commented on libs/components/src/lib/button/README.md
> +<vwc-button label='Stached' appearance='filled' icon='message-sent-line' stacked size='base-small'></vwc-button>
Notice the typo steched

2022-02-14 13:12 UTC, rachelbt commented on libs/components/src/lib/button/README.md
> +<vwc-button label='Stached' appearance='filled' icon='message-sent-line' stacked size='base-small'></vwc-button>
I'm the worse with typos :(

2022-02-14 16:04 UTC, yinonov commented on libs/components/src/lib/button/README.md
> +<vwc-button label='stacked' appearance='filled' icon='message-sent-line' icon-trailing stacked size='base'></vwc-button>
this is another case where _base_ value isn't true.
_base_ stands for a row height of most common components (textfield, button, etc'.)

2022-02-14 16:05 UTC, yinonov commented on libs/components/src/lib/button/README.md
> +<vwc-button label='stacked' appearance='filled' icon='message-sent-line' icon-trailing stacked size='base'></vwc-button>
needs to be discussed as I'm yet sure how this should be resolved

2022-02-22 11:22 UTC, rachelbt commented on libs/components/src/lib/button/partials/variables.scss
> +$stacked-icon-gap: --stacked-button-icon-gap;
added an underscore

2022-02-22 11:22 UTC, rachelbt commented on libs/components/src/lib/button/README.md
> +<vwc-button label='stacked' appearance='filled' icon='message-sent-line' icon-trailing stacked size='base'></vwc-button>
Not sure I got it....

2022-02-22 11:58 UTC, yinonov commented on libs/components/src/lib/button/README.md
> +<vwc-button label='stacked' appearance='filled' icon='message-sent-line' icon-trailing stacked size='base'></vwc-button>
the `base` keyword mean a certain row height of common controls. stack button is not the same height.
This is a problem in this new `base` convention

2022-02-22 11:59 UTC, yinonov commented on libs/components/src/lib/button/README.md
> +<vwc-button label='stacked' appearance='filled' icon='message-sent-line' icon-trailing stacked size='base'></vwc-button>
> back to the planning table

2022-02-22 14:33 UTC, rachelbt commented on libs/components/src/lib/button/README.md
> +<vwc-button label='stacked' appearance='filled' icon='message-sent-line' icon-trailing stacked size='base'></vwc-button>
oh! Now I get it.

2022-03-31 13:06 UTC, yinonov commented on libs/components/src/lib/button/README.md
> +<vwc-button label='stacked' appearance='filled' icon='message-sent-line' icon-trailing stacked size='base'></vwc-button>
what do we think of 1 of the former suggestions?

**density**

possible values: `-1` | `0` | `1`
default: `0`

2022-05-03 06:38 UTC, rachelbt reviewed
in the popup readme - under dismissible, the button need to get `size="condensed"`.

2022-05-03 06:38 UTC, rachelbt commented on libs/components/src/lib/button/button.scss
> +        font-size: 90px;
that's a bit too big 🤣 :
![image](https://user-images.githubusercontent.com/7512792/166411955-58c43bc2-e277-47c6-b48b-26280bdbe6ae.png)

2022-05-04 08:24 UTC, yinonov commented on libs/components/src/lib/button/button.scss
> +        font-size: 90px;
of course 😅 it's on purpose to notice that this should be attended.

@jshenkman

- what should be the size of icon with no label within a stack button. I imagine it should be bigger?
- is shape pill applicable on a stacked button? don't feel it is designed well

2022-05-11 10:14 UTC, yinonov approved these changes

2022-05-11 10:15 UTC, merged