chore(docs): card page new format (VIV-2086)
Vonage/vivid-3 pull request #1972
Opened 2024-10-28 14:49 UTC by rachelbt

2024-10-31 10:33 UTC, TaylorJ76 reviewed
Make sure the headings are in [title case](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case)

[Online tool](https://capitalizemytitle.com/style/APA/)

2024-10-31 10:49 UTC, TaylorJ76 requested changes

2024-10-31 10:49 UTC, TaylorJ76 commented on libs/components/src/lib/card/README.md
> +| **elevation**  | `2`, `4` (default), `8`, `12`, `16`, `24` | Sets the element's elevation  |
What about `headline`, `subtitle` and `text`?

2024-10-31 10:49 UTC, TaylorJ76 commented on libs/components/src/lib/card/README.md
>  <vwc-card
Maybe take this example a bit further and add a menu to the slotted button?

2024-10-31 10:49 UTC, TaylorJ76 commented on libs/components/src/lib/card/USE-CASES.md
> +You can slot a card with `appearance="ghost""` inside selectable box
```suggestion
You can slot a card with `appearance="ghost"` inside selectable box
```

2024-10-31 10:49 UTC, TaylorJ76 commented on libs/components/src/lib/card/VARIATIONS.md
> +## Card Texts
```suggestion
## Card Text Content
```

2024-10-31 10:49 UTC, TaylorJ76 commented on libs/components/src/lib/card/VARIATIONS.md
> +The `icon` attribute displays an icon from the [icon library](/icons/icons-gallery), which prefixes the Text Field's input element.
The text references the Text Field... easy mistake to make :)

2024-10-31 10:49 UTC, TaylorJ76 commented on libs/components/src/lib/card/README.md
>  	style="max-inline-size: 300px"
Can we use a class here?

2024-10-31 10:49 UTC, TaylorJ76 commented on libs/components/src/lib/card/USE-CASES.md
> +## Card UI
I don't think we need this heading, just make both the heading H2s

2024-10-31 14:00 UTC, rachelbt commented on libs/components/src/lib/card/README.md
> +| **elevation**  | `2`, `4` (default), `8`, `12`, `16`, `24` | Sets the element's elevation  |
I did the same as button and text-field - where the label and other text prop not in the list 
https://vivid.deno.dev/components/button/code/#properties
https://vivid.deno.dev/components/text-field/code/#properties

2024-10-31 16:28 UTC, TaylorJ76 commented on libs/components/src/lib/card/README.md
> +| **elevation**  | `2`, `4` (default), `8`, `12`, `16`, `24` | Sets the element's elevation  |
I'll go back over those then. Thanks for pointing that out.

2024-11-01 07:17 UTC, rachelbt commented on libs/components/src/lib/card/GUIDELINES.md
> +## Advantages of card UI design
```suggestion
## Advantages of Card UI Design
```

2024-11-01 07:17 UTC, rachelbt commented on libs/components/src/lib/card/GUIDELINES.md
> +### Highly responsive
```suggestion
### Highly Responsive
```

2024-11-01 07:17 UTC, rachelbt commented on libs/components/src/lib/card/GUIDELINES.md
> +### Easy-to-understand
```suggestion
### Easy-To-Understand
```

2024-11-01 07:17 UTC, rachelbt commented on libs/components/src/lib/card/GUIDELINES.md
> +### Intuitive and UX friendly
```suggestion
### Intuitive and UX Friendly
```

2024-11-01 07:17 UTC, rachelbt commented on libs/components/src/lib/card/GUIDELINES.md
> +### Attractive and modern-looking
```suggestion
### Attractive and Modern-Looking
```

2024-11-01 07:17 UTC, rachelbt commented on libs/components/src/lib/card/USE-CASES.md
> +## Cards inside a layout
```suggestion
## Cards Inside a Layout
```

2024-11-01 07:17 UTC, rachelbt commented on libs/components/src/lib/card/USE-CASES.md
> +## Selectable cards
```suggestion
## Selectable Cards
```

2024-11-01 07:32 UTC, rachelbt commented on libs/components/src/lib/card/README.md
> +| **elevation**  | `2`, `4` (default), `8`, `12`, `16`, `24` | Sets the element's elevation  |
added

2024-11-01 09:46 UTC, TaylorJ76 approved these changes

2024-11-04 09:37 UTC, merged