feat(file-picker): add single file mode (VIV-1988)
Vonage/vivid-3 pull request #1974
Opened 2024-10-30 18:22 UTC by YonatanKra

2024-10-31 11:12 UTC, TaylorJ76 requested changes
None of these examples work unless they are wrapped in a form (like in the Form use case). Can we wrap all then examples in a form so that users can see how it functions?

Also, can we change the Max Files example to be more than 1, and put a note to say to use the `single-file` attribute if you only want to upload one file?

2024-10-31 11:12 UTC, TaylorJ76 commented on libs/components/src/lib/file-picker/README.md
> +### Single File
Can we move this example up the page a bit to be above the Max File Size example?

2024-10-31 18:39 UTC, YonatanKra commented on libs/components/src/lib/file-picker/README.md
> +### Single File
I moved it just below `label`.
Regarding the form change - can you please elaborate what doesn't work outside a form?
We never put form elements inside a form in the examples, because we'd like people to be able to just copy and paste the code (K.I.S.).

2024-11-01 06:25 UTC, TaylorJ76 commented on libs/components/src/lib/file-picker/README.md
> +### Single File
Sorry, my bad. It does work. It's just that the file list gets cut off in the examples.
Can we give the examples more height so that at least one select file will appear inside the viewing area?

2024-11-02 04:16 UTC, YonatanKra commented on libs/components/src/lib/file-picker/README.md
> +### Single File
Done

2024-11-04 07:41 UTC, TaylorJ76 approved these changes

2024-11-05 08:13 UTC, merged