feat(file-picker): support clearing files (VIV-1995)
Vonage/vivid-3 pull request #1983
Opened 2024-11-06 18:26 UTC by RichardHelm

2024-11-07 08:22 UTC, YonatanKra requested changes
Nice and very well needed feature. Thanks :)

2024-11-07 08:22 UTC, YonatanKra commented on libs/components/src/lib/file-picker/file-picker.ts
> +	_dropzone?: Dropzone;
Why do we need to expose dropzone?

2024-11-07 08:22 UTC, YonatanKra commented on libs/components/src/lib/file-picker/file-picker.spec.ts
> +			unmountedElement.removeAllFiles();
Isn't `removeAllFiles` tested in its own `it`?

2024-11-07 08:22 UTC, YonatanKra commented on libs/components/src/lib/file-picker/file-picker.spec.ts
> +		it('should remove all files when setting value to an empty string', async function () {
Nice addition :)

2024-11-07 10:12 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.spec.ts
> +			unmountedElement.removeAllFiles();
Yes, this is just to cover the optional chain.
To ensure it doesn't throw when component is unmounted

2024-11-07 10:13 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.ts
> +	_dropzone?: Dropzone;
Otherwise there is an error when accessing `#dropzone` from `valueChanged`
I believe this is because FAST will call `valueChanged` before the constructor is completed and the private member is not ready

2024-11-07 10:50 UTC, YonatanKra commented on libs/components/src/lib/file-picker/file-picker.ts
> +	_dropzone?: Dropzone;
I pushed a change that reverts it. Seems to work.
The problem is that `valuechanged` is sent to an event listener, which fires outside the context of the element.
By changing the `valueChanged` to be an arrow function, it retains the context wherever it is called.

2024-11-07 10:54 UTC, YonatanKra commented on libs/components/src/lib/file-picker/file-picker.spec.ts
> +			unmountedElement.removeAllFiles();
Looking at the full test (for some reason it was hidden in the diff), it's a very general test and an unclear spec.
1. Would `removeAllFiles` cause an error in unmounted state at any point?
2. Did removing and appending the component to the DOM (connecting/disconnecting in WC terms?) cause an error before?
In other words, `what piece of code do I delete for the expectation to fail?`

2024-11-08 19:03 UTC, RichardHelm commented on libs/components/src/lib/file-picker/file-picker.ts
> +	_dropzone?: Dropzone;
That's not what's happening though. With your fix `valueChange` will be initialised at a later point and miss the initial call that causes the error. But I'm happy to accept it like this

2024-11-08 19:51 UTC, YonatanKra approved these changes

2024-11-11 10:22 UTC, merged