chore(docs): dialog page restructure (VIV-2093)
Vonage/vivid-3 pull request #2010
Opened 2024-11-17 10:14 UTC by rachelbt

2024-11-17 10:14 UTC, rachelbt commented on apps/vue-docs/docs/.vitepress/config.ts
> +
```suggestion
```

2024-11-17 10:14 UTC, rachelbt commented on libs/consts/vite.config.ts
> +
```suggestion
```

2024-11-17 10:14 UTC, rachelbt commented on libs/consts/vite.config.ts
> +
```suggestion
```

2024-11-19 16:00 UTC, TaylorJ76 commented on libs/components/src/lib/dialog/USE-CASES.md
> +Dialogs can be modal or non-modal. Modal dialogs prevent users from interacting with the rest of the application until the dialog is closed and render a backdrop behind the dialog. Non-modal dialogs
This would be more useful next to the `modal` example. Maybe in an "info" note?

2024-11-19 16:01 UTC, TaylorJ76 commented on libs/components/src/lib/dialog/USE-CASES.md
> +## Use Cases
Don't need this heading.

2024-11-19 16:02 UTC, TaylorJ76 commented on libs/components/src/lib/dialog/USE-CASES.md
> +			<vwc-button type="submit" label="Submit"></vwc-button>
I think the button should have an appearance other than ghost.

2024-11-19 16:09 UTC, TaylorJ76 commented on libs/components/src/lib/dialog/ACCESSIBILITY.md
> +- It is the consumer's concern to add `aria-label` to the dialog element.
Maybe mention that a dialog should have a heading, but if for some reason it doesn't then the consumer should add `aria-label`.

2024-11-19 16:10 UTC, TaylorJ76 commented on libs/components/src/lib/dialog/ACCESSIBILITY.md
> +- The dismiss button is automatically given a localized version of the word "Close". This can be overridden using `dismiss-button-aria-label`.
I don't see this property on the properties list on the code page.

2024-11-19 16:10 UTC, TaylorJ76 commented on libs/components/src/lib/dialog/ACCESSIBILITY.md
> +## Dialog Dismiss
Should probably be a H3, it still comes under Implementation.

2024-11-19 16:13 UTC, rachelbt commented on libs/components/src/lib/dialog/README.md
> +## Properties
had a issue with a commit that I didn't pushed...
It is fixed now

2024-11-19 16:13 UTC, rachelbt commented on libs/components/src/lib/dialog/README.md
> +## Slots
same...

2024-11-20 09:19 UTC, TaylorJ76 requested changes

2024-11-20 09:19 UTC, TaylorJ76 commented on libs/components/src/lib/dialog/USE-CASES.md
> +## Dialogs can be modal or non-modal
I feel this would be better placed in the code section where the modal dialog is demonstrated. Maybe in an "info note"?

2024-11-20 10:25 UTC, rachelbt commented on libs/components/src/lib/dialog/USE-CASES.md
> +## Dialogs can be modal or non-modal
I wondered about this as well. 
But wouldn't it be strange with the 2 bullets coming after it?

2024-11-20 10:50 UTC, rachelbt commented on libs/components/src/lib/dialog/USE-CASES.md
> +## Dialogs can be modal or non-modal
added

2024-11-21 09:42 UTC, TaylorJ76 commented
<img width="791" alt="Screenshot 2024-11-21 at 09 42 07" src="https://github.com/user-attachments/assets/bf18b6b9-6832-4e95-82db-001d64cf5fb2">

Something has gone a bit wrong with the properties table.

2024-11-25 14:57 UTC, merged