fix(documentation): basic style
Vonage/vivid-3 pull request #202
Opened 2022-02-16 11:01 UTC by rachelbt

basic side nav style until we will have side nav
`<code>` tag styling
`table` styling

2022-02-16 11:34 UTC, yinonov requested changes
add indentation to nested links?

2022-02-16 11:34 UTC, yinonov commented on apps/docs/_includes/navigation.njk
> +    </nav>
```suggestion
</nav>
```

2022-02-16 11:34 UTC, yinonov commented on apps/docs/assets/styles/main.css
> +}
can u region that part with a _temp_ comment?
```css
// #region something...
```

2022-02-16 15:45 UTC, rachelbt commented
> add indentation to nested links?

I'll add a little indentation for the list like in the design:
![image](https://user-images.githubusercontent.com/7512792/154301173-41abb13b-d92b-401a-8dff-52853ce544fd.png)
Not styling the inner list though cuz currently we dont have nested. I do hope that the UL CSS will be temporary and be replaced with the Side nav :)

2022-02-17 19:07 UTC, yinonov approved these changes

2022-02-17 19:07 UTC, merged