feat(file-picker): add styled scrollbar & fix files-list height (VIV-2236) - BLOCKED BY VIV-2214
Vonage/vivid-3 pull request #2029
Opened 2024-11-24 12:21 UTC by rachelbt

2024-11-28 11:17 UTC, RichardHelm requested changes

2024-11-28 11:17 UTC, RichardHelm commented on libs/components/src/lib/file-picker/README.md
> +Use `--file-picker-list-block-size` the set the max-block-size of list of the added files, other than `408px`.
Why do we need a default value?

And wouldn't it make more sense to build the layout in a way where the list of files becomes scrollable if there isn't enough space for the component.
So when setting `max-height: 600px` on the host and the list of files becomes too big it will automatically scroll without any CSS variables.

2024-12-01 14:07 UTC, rachelbt commented on libs/components/src/lib/file-picker/file-picker.scss
> -		border-style: solid;
was removed as requested here: https://jira.vonage.com/browse/VIV-2227 (in the comments)

2024-12-02 11:58 UTC, RichardHelm approved these changes

2024-12-04 10:40 UTC, merged