chore(components): decoupling loose ends (VIV-000)
Vonage/vivid-3 pull request #2058
Opened 2024-12-12 15:17 UTC by TaylorJ76

Adds missing types and a helper functions.
Changes many components to use the new local classes / functions.

2025-01-22 11:12 UTC, YonatanKra requested changes
Two comments. Not bad for such a big PR :)

2025-01-22 11:12 UTC, YonatanKra commented on libs/components/src/lib/menu-item/menu-item.ts
> +import { AnchoredRegion } from '@microsoft/fast-foundation';
That's still reliant on `@microsoft/fast-foundation`. Shouldn't this be removed as well?

2025-01-22 11:12 UTC, YonatanKra commented on libs/components/src/lib/number-field/number-field.ts
> +import { DelegatesARIATextbox } from '../text-field/text-field';
Maybe this should be part of our shared foundation for form elements instead of in the `text-field`?

2025-01-29 09:44 UTC, TaylorJ76 commented on libs/components/src/lib/menu-item/menu-item.ts
> +import { AnchoredRegion } from '@microsoft/fast-foundation';
I have created a new task to deal with this.

2025-01-29 12:23 UTC, YonatanKra commented on libs/components/src/lib/number-field/number-field.ts
> +import { DelegatesARIATextbox } from '../text-field/text-field';
I've added this to our dev tasks list.

2025-01-29 12:24 UTC, YonatanKra approved these changes

2025-01-30 09:46 UTC, merged