refactor(popup): migrate to fast element
Vonage/vivid-3 pull request #206
Opened 2022-02-17 16:06 UTC by rinaok

`vwc-elevation` and `vwc-icon-button` need to be migrated to accomplish this PR.

2022-03-02 16:29 UTC, rinaok commented
@yinonov @YonatanKra  I receive the following error when calling `computePosition`: 
`Uncaught (in promise) ReferenceError: process is not defined`.

<img width="500" alt="Screen Shot 2022-03-02 at 18 25 44" src="https://user-images.githubusercontent.com/10883919/156403938-717151d2-675a-4ca0-a9a1-6b8e8b3ed964.png">
<img width="692" alt="Screen Shot 2022-03-02 at 18 26 06" src="https://user-images.githubusercontent.com/10883919/156403994-64669d3b-a869-4013-942d-b0ed6dcc2a22.png">

Found this issue: https://github.com/floating-ui/floating-ui/issues/1506

2022-03-03 09:17 UTC, YonatanKra commented
@rinaok - I don't mean the version in `package.json`.
You should use `@floating-ui/dom` and not `core` IMO.

2022-03-03 16:30 UTC, yinonov requested changes

2022-03-03 16:30 UTC, yinonov commented on libs/components/src/lib/popup/popup.ts
> +		if (!this.popupEl || this.popupEl === undefined) {
same here

2022-03-10 15:26 UTC, yinonov reviewed
if popup strategy is set to _fixed_, it should probably close the popup upon scroll. similar to the browsers strategy. WDYT?

2022-03-10 15:39 UTC, rinaok commented on libs/components/src/lib/popup/popup.spec.ts
> +}));
@YonatanKra  @yinonov 
Jest fails with an error message stating that ResizeObserver inside floating-ui classes is undefined.
That fixed the problem.

2022-03-10 15:56 UTC, rinaok commented
> if popup strategy is set to _fixed_, it should probably close the popup upon scroll. similar to the browsers strategy. WDYT?

yes, I agree. It does look strange. I've added `hide()` Middleware and removed the `shift() `Middleware. I think it's better now. Tell me what you think.

2022-03-13 10:10 UTC, YonatanKra requested changes
A really small change :)

2022-03-13 10:13 UTC, rachelbt commented on libs/components/src/lib/popup/popup.scss
> +@use '../../../../shared/src/lib/sass/mixins/typography' as typography;
not sure what we need this for

2022-03-13 10:13 UTC, rachelbt commented on libs/components/src/lib/popup/popup.scss
> +	background-color: var(#{--vvd-color-surface-4dp});
there's non need for `#{} `if you are not using a scss variable here.
But we should use them :)
you can set a variable in the start of the file (if we would have more than one its better to open.a new file for it) and set:
`$popup-bg: --vvd-color-surface-4dp;
`and use it in the CSS here and in the arrow bg like this:
`background-color: var(#{$popup-bg});`

2022-03-13 10:52 UTC, yinonov commented on change/@vonage-vivid-fff24903-c6b1-40dd-9364-7f55a550515e.json
> +  "type": "major",
Popup is alpha. And is probably underlying component for now. I vote 'none'

2022-03-13 11:30 UTC, YonatanKra commented
Note that the coverage is very small (reduces our whole repo's coverage by 5%).
![image](https://user-images.githubusercontent.com/6459899/158057288-b471a26f-89d7-4fa6-a2fc-bff61553c75c.png)
Seems like some features are not tested:
1. `aria-hidden` is never set to false in the tests.
2. `part=vvid-theme-alternate` is a not-tested branch.
3. `renderArrow` is not called during the tests.
4. `renderDismissButton` is not called during the tests.

2022-03-13 15:21 UTC, rinaok commented on libs/components/src/lib/popup/README.md
> +- Default: `'fixed'`
https://floating-ui.com/docs/computePosition#strategy

2022-03-13 15:32 UTC, rinaok commented on libs/components/src/lib/popup/popup.scss
> +@use '../../../../shared/src/lib/sass/mixins/typography' as typography;
removed

2022-03-13 15:33 UTC, rinaok commented on libs/components/src/lib/popup/popup.scss
> +	background-color: var(#{--vvd-color-surface-4dp});
done :)

2022-03-13 16:41 UTC, yinonov commented
> > if popup strategy is set to _fixed_, it should probably close the popup upon scroll. similar to the browsers strategy. WDYT?
> 
> @yinonov yes, I agree. It does look strange. I've added `hide()` Middleware and removed the `shift() `Middleware. I think it's better now. Tell me what you think.

Maybe we should add html snippet for fixed and express this exact dialog to users?

2022-03-13 16:42 UTC, yinonov requested changes

2022-03-13 16:42 UTC, yinonov commented on libs/components/src/lib/popup/README.md
> +## Z-index
```suggestion
## Top-layer
```

2022-03-14 11:28 UTC, rachelbt commented on libs/components/src/lib/popup/README.md
> +- Default: `'fixed'`
according to floating UI our default is absolute...

2022-03-14 13:45 UTC, rinaok commented on libs/components/src/lib/popup/README.md
> +- Default: `'fixed'`
@rachelbt It is absolute by their default, yes. But our default is fixed.
@yinonov Why we changed the default to fixed?

2022-03-14 13:47 UTC, rinaok commented
> > > if popup strategy is set to _fixed_, it should probably close the popup upon scroll. similar to the browsers strategy. WDYT?
> > 
> > 
> > @yinonov yes, I agree. It does look strange. I've added `hide()` Middleware and removed the `shift() `Middleware. I think it's better now. Tell me what you think.
> 
> Maybe we should add html snippet for fixed and express this exact dialog to users?

@yinonov We already have a snippet for strategy, what do you want to show there?

2022-03-15 11:39 UTC, YonatanKra requested changes

2022-03-15 11:39 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.spec.ts
> +	});
These are two different API's.
```suggestion
	describe('render arrow', () => {
		it('should render an arrow icon if arrow is true', async () => {
			// TODO
		});
		
		it('should not render an arrow icon if arrow is false', async () => {
			// TODO
		});
		
		it('should remove the arrow class on the container if arrow is false', () => {
		        const controlElement = element.shadowRoot?.querySelector('.control');
			expect(controlElement.classList.contains('.arrow')).toEqual(false);
		});
		
		it('should set the arrow class on the container if arrow is true', () => {
		        element.arrow = true;
			await elementUpdated(element);
			const controlElement = element.shadowRoot?.querySelector('.control');
			expect(controlElement.classList.contains('.arrow')).toEqual(true);
		});
	});
```
This suggestion only covers the idea for `arrow`. Do the same for dismissible.

2022-03-15 11:39 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.spec.ts
> +		it('should set aroa-hidden', async () => {
```suggestion
		it('should set aria-hidden', async () => {
```

2022-03-15 16:15 UTC, rinaok commented on libs/components/src/lib/popup/popup.spec.ts
> +	});
@YonatanKra It won't work, the arrow and dismiss classes are not inside the control.
Also the "should remove the arrow class on the container if arrow is false" check is not necessary cause "initializes as a vwc-popup" test already checks it.

2022-03-16 09:18 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.spec.ts
> +	});
That's exactly why we should add the correct test to document where we should expect the class.
BTW - is this class exposed as API? I think what's more important is that we have an icon/button, no?

2022-03-16 12:10 UTC, YonatanKra approved these changes

2022-03-16 12:33 UTC, yinonov commented
https://github.dev/Vonage/vivid-3/blob/374ff2f9087b8ff73e0a60b3d54067c1cf1f4225/libs/components/rollup.config.prod.ts#L41-L44

2022-03-16 12:34 UTC, yinonov requested changes

2022-03-16 12:34 UTC, yinonov commented on libs/components/rollup.config.prod.ts
> +		})];
This should be checked thoroughly

2022-03-16 12:49 UTC, YonatanKra commented on libs/components/rollup.config.prod.ts
> +		})];
That's the official solution

2022-03-21 12:41 UTC, yinonov requested changes

2022-03-21 12:41 UTC, yinonov commented on libs/components/src/lib/popup/popup.ts
> +	@attr private anchorEl: Element | null | undefined;
why is this an interface? wasn't it a getter? have we decided to expose it as well?
we already have `anchor` member. it can, alone, accept _string_ or _HTMLElement_

2022-03-21 12:46 UTC, rinaok commented on libs/components/src/lib/popup/popup.ts
> +	@attr private anchorEl: Element | null | undefined;
it's private, it's not an interface

2022-03-23 20:42 UTC, yinonov requested changes

2022-03-23 20:42 UTC, yinonov commented on libs/components/src/lib/popup/popup.spec.ts
>  			expect(element.shadowRoot?.querySelector('.dismissible')).not.toBeNull();
I know we talked about this today but I missed the part where `getControlElement(element)` is actually responsible for querying the `.control`. so we better use it

2022-03-27 19:35 UTC, yinonov requested changes

2022-03-27 19:35 UTC, yinonov commented on change/@vonage-vivid-fff24903-c6b1-40dd-9364-7f55a550515e.json
> +  "type": "minor",
exist in 2
```suggestion
  "type": "none",
```

2022-03-27 19:35 UTC, yinonov commented on libs/components/src/lib/enums.ts
> -}
where will this move to? we might wanna have a single source of truth for these types. components using popup under the hood might need to proxy it

2022-03-27 19:35 UTC, yinonov commented on libs/components/src/lib/popup/README.md
> +## Top-layer
```suggestion
## Caveat
```

2022-03-27 19:35 UTC, yinonov commented on libs/components/src/lib/popup/popup.template.ts
> +	return html`<vwc-button @click="${x => x.handleDismissClick()}"
small maybe?

```suggestion
	return html`<vwc-button size="base-small" @click="${x => x.handleDismissClick()}"
```

2022-03-27 19:35 UTC, yinonov commented on libs/components/src/lib/popup/ui.test.ts
> +import * as path from 'path';
snapshots are messed up. like, not anchored properly

2022-03-27 19:35 UTC, yinonov commented on libs/components/src/lib/popup/ui.test.ts
> +		componentName,
how did you import more components to the page? I'm seeing _icon_ which isn't imported by _popup_

2022-03-28 12:58 UTC, rinaok commented on libs/components/src/lib/enums.ts
> -}
I didn't move it. I'm using floating-ui's enums.

2022-03-28 17:14 UTC, yinonov commented on libs/components/src/lib/popup/ui.test.ts
> +		componentName,
nice! 🥇

2022-04-03 07:57 UTC, yinonov approved these changes

2022-04-03 10:48 UTC, YonatanKra requested changes

2022-04-03 10:48 UTC, YonatanKra commented on libs/components/src/lib/popup/README.md
> +Since the popup is positioned absolutely to its anchor, it is best to wrap it with a div element and set its position `relative`.
```suggestion
The popup is positioned absolutely to its anchor.  It is recommended to wrap it with a div element and set its position `relative`.
```
Would also appreciate a short description like: "how things can go wrong" or "what adding the wrapper solves" sentence.

2022-04-03 10:48 UTC, YonatanKra commented on libs/components/src/lib/popup/README.md
> +Use the `arrow` attribute to add small triangle to indicate the trigger element.
```suggestion
Adds a small triangle to indicate the trigger element.
```

2022-04-03 10:48 UTC, YonatanKra commented on libs/components/src/lib/popup/README.md
> +Use the `dismissible` attribute to add close button to the popup.
```suggestion
Adds a close button to the popup.
```

2022-04-03 10:48 UTC, YonatanKra commented on libs/components/src/lib/popup/README.md
> +Use the `alternate` attribute to set the color-scheme to dark.
```suggestion
Sets the color-scheme to dark or light (depending on current user's system settings).
```

2022-04-03 10:48 UTC, YonatanKra commented on libs/components/src/lib/popup/README.md
> +Use the `corner` attribute to set the placement of the popup.
```suggestion
Sets the placement of the popup around the anchor.
```
Is this correct? Around the anchor?

2022-04-03 10:48 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.ts
> +	}
What's that for?

2022-04-03 10:48 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.ts
> +		if (this.cleanup) { this.cleanup(); }
Is `cleanup` an api? It is not documented and not tested. Why would cleanup no exist?

2022-04-03 10:48 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.ts
> +			visibility: referenceHidden ? 'hidden' : 'visible',
One of these cases is not tested. Don't know which without running locally.

2022-04-03 10:48 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.ts
> +		const staticSide: any = { top: 'bottom', right: 'left', bottom: 'top', left: 'right' };
Why not set as constant at the top of the file?
And about the content - it is a WTF moment :)
Can you explain the usecase plz? There's no test for it. The function `updatePosition` is an open API (public) but not tested, so hard to tell what this function is supposed to do.

2022-04-03 10:48 UTC, YonatanKra commented on libs/components/src/lib/components.ts
> -export * from './side-drawer';
What happened to side-drawer?

2022-04-03 10:48 UTC, YonatanKra commented on libs/components/src/lib/popup/ui.test.ts
> +	const template = extractHTMLBlocksFromReadme(path.join(__dirname, 'README.md'))
Are these use cases include all of the `top`/`bottom`/`left`/`right` use cases possible?

2022-04-03 10:57 UTC, rinaok commented on libs/components/src/lib/popup/README.md
> +Use the `corner` attribute to set the placement of the popup.
yes

2022-04-03 11:02 UTC, rinaok commented on libs/components/src/lib/popup/popup.ts
> +		if (this.cleanup) { this.cleanup(); }
You can read about cleanup here: https://floating-ui.com/docs/autoUpdate.

2022-04-03 14:08 UTC, YonatanKra commented on change/@vonage-vivid-fff24903-c6b1-40dd-9364-7f55a550515e.json
> +  "type": "none",
Why is the type `none`? Why not `minor`? Isn't it a new feature?

2022-04-03 15:01 UTC, rinaok commented on change/@vonage-vivid-fff24903-c6b1-40dd-9364-7f55a550515e.json
> +  "type": "none",
@yinonov changed it to none

2022-04-05 08:02 UTC, YonatanKra commented on libs/shared/src/lib/test-utils/index.spec.ts
> +    it(`should return a dom element under div under body with add`, function () {
![image](https://user-images.githubusercontent.com/6459899/161707341-b8853ea3-7ae6-4c17-9bf7-5df047873623.png)

2022-04-05 12:23 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.spec.ts
> +			expect(true).toBeTruthy();
This is not the test that should be here.
You should `spyOn` the `element.updatePosition` method and see that it stops running after the element disconnects if you change a position.

2022-04-05 12:25 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.spec.ts
> +	global.ResizeObserver = jest.fn()
I think this should be defined in a `beforeEach` - otherwise `element.updatePosition` might differ in every test. Also, for testing the cleanup, you should set `observe` to run a spy.
`observeSpy = jest.fn(element.updatePosition)`
and then:
`observe: observeSpy,`

2022-04-05 12:29 UTC, YonatanKra commented on libs/components/src/lib/popup/ui.test.ts
> +	const template = extractHTMLBlocksFromReadme(path.join(__dirname, 'README.md'))
I think in this case, because we have so many use cases for positioning, it is worthwhile to hard code them here instead of taking out of docs an incomplete list of them.

2022-04-05 12:30 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.ts
> +	handleDismissClick(): void {
Is this tested? Do we actually test the `click` event?

2022-04-06 05:42 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.spec.ts
> +			element.anchor = '';
This is unclear. We need to change something that triggers the observer.

2022-04-06 05:43 UTC, YonatanKra commented on libs/components/src/lib/popup/popup.ts
> +			this.cleanup = autoUpdate(this.anchorEl, this.popupEl, () => this.updatePosition());
now I see something else that's troubling - shouldn't we run `clean` if `anchor` is undefined?
I mean - if we remove the `anchor` from the DOM, the observer is still there which is a possible memory leak.

2022-04-06 05:45 UTC, YonatanKra commented on libs/components/src/lib/popup/ui.test.ts
> +test('should show the component', async ({ page }: { page: Page }) => {
Do we still need this if we have the new test? Does this test anything not tested below?

2022-04-06 05:46 UTC, YonatanKra commented on libs/components/src/lib/popup/ui.test.ts
> +test('should show all positionings', async ({ page }: { page: Page }) => {
![image](https://user-images.githubusercontent.com/6459899/161904099-b45c5fe0-653e-4f03-bbbe-a3c73568e95e.png)

2022-04-06 08:05 UTC, rinaok commented on libs/components/src/lib/popup/popup.ts
> +			this.cleanup = autoUpdate(this.anchorEl, this.popupEl, () => this.updatePosition());
yes, you are right

2022-04-06 08:37 UTC, rinaok commented on libs/components/src/lib/popup/ui.test.ts
> +test('should show the component', async ({ page }: { page: Page }) => {
this test only tests the corners.

2022-04-06 12:41 UTC, YonatanKra approved these changes

2022-04-06 12:43 UTC, merged