chore(docs): Text Area docs update (VIV-2210)
Vonage/vivid-3 pull request #2060
Opened 2024-12-15 16:02 UTC by rachelbt

2024-12-17 09:22 UTC, TaylorJ76 requested changes

2024-12-17 09:22 UTC, TaylorJ76 commented on libs/components/src/lib/text-area/README.md
> +	label="First name"
```suggestion
	label="Description"
```

2024-12-17 09:22 UTC, TaylorJ76 commented on libs/components/src/lib/text-area/README.md
> +### Helper-Text
```suggestion
### Helper Text Slot
```

2024-12-17 09:22 UTC, TaylorJ76 commented on libs/components/src/lib/text-area/README.md
> +| **helper-text** | Sets the input element's appearance |
```suggestion
| `helper-text` | Sets the input element's appearance |
```

2024-12-17 09:22 UTC, TaylorJ76 commented on libs/components/src/lib/text-area/README.md
> +The `helper-text` slot allows you to use rich content as the text area's helper text.
```suggestion
The `helper-text` slot allows you to use rich content as the Text Area's helper text.
```

2024-12-17 09:22 UTC, TaylorJ76 commented on libs/components/src/lib/text-area/VARIATIONS.md
> +Use the `rows` attribute to set the number of visible rows of text in the text area.
```suggestion
Use the `rows` attribute to set the number of visible rows of text in the Text Area.
```

2024-12-17 13:54 UTC, rachelbt commented on libs/components/src/lib/text-area/README.md
> +| **helper-text** | Sets the input element's appearance |
but this is the way alert, card, checkbox, buttons and more are.
https://vivid.deno.dev/components/alert/code/#slots-1
https://vivid.deno.dev/components/button/code/#slots-1

2024-12-17 13:57 UTC, TaylorJ76 commented on libs/components/src/lib/text-area/README.md
> +| **helper-text** | Sets the input element's appearance |
Fair enough. Can we change the ones in the Properties and Event tables to match then please?

2024-12-18 14:38 UTC, TaylorJ76 approved these changes

2024-12-19 09:17 UTC, merged