refactor(elevation): migrate to fast element
Vonage/vivid-3 pull request #211
Opened 2022-02-20 14:37 UTC by rinaok

2022-02-21 21:45 UTC, yinonov requested changes

2022-02-21 21:45 UTC, yinonov commented on libs/components/src/lib/elevation/README.md
> +***Note: This component is responsible for the perceived elevation alone and not to DOM elements z-indexing.***
```suggestion
**Note: This component is responsible for the perceived visual elevation alone and not to the HTML elements stacking context.**
```

2022-02-21 21:50 UTC, yinonov requested changes

2022-02-21 21:50 UTC, yinonov commented on libs/components/src/lib/elevation/elevation.scss
> +	width: fit-content;
why even setting this? it default to a block flow. can be controlled with the `host` simply by setting `display: block` and a `width`
```suggestion
```

2022-02-22 06:52 UTC, rachelbt commented on libs/components/src/lib/elevation/elevation.scss
> +	width: fit-content;
On one hand you're right. On the other - the elevation need to wrap its content in a way. Why does it bothers you that we contain it to fit its containing child?

2022-02-22 08:14 UTC, rachelbt commented
@rinaok the dp=0 is wrong - it suppose to give an outline "border".
like in the [StoryBook of vivid](https://vivid.vonage.com/?path=/story/alpha-components-elevation--all-elevations)

2022-02-22 09:08 UTC, rinaok commented on libs/components/src/lib/elevation/elevation.scss
> +	width: fit-content;
@yinonov I haven't added this. I copied the CSS file from Vivid. If you want to change it, perhaps you should also change it in Vivid.

2022-02-22 10:00 UTC, rachelbt commented on libs/components/src/lib/elevation/elevation.scss
> +	width: fit-content;
because of the bug that @rinaok found in the example of the elevation hover effect - theres no need for it as it doesn't work with nested components :)
You can remove it.

2022-02-25 15:54 UTC, yinonov requested changes

2022-02-25 15:54 UTC, yinonov commented on libs/components/src/lib/elevation/README.md
> +**Note: This component is responsible for the perceived visual elevation alone and not to the HTML elements stacking context.**
```suggestion
**Note: This component is responsible for the perceived visual elevation alone and not for the HTML elements stacking context.**
```

2022-02-28 19:44 UTC, yinonov requested changes
let #229 in first and validate elevation tokens

2022-03-01 12:30 UTC, yinonov requested changes

2022-03-01 12:30 UTC, yinonov commented on change/@vivid-nx-styles-a3612f30-0b1f-4c32-94c7-60e77193d012.json
> +{
not relevant anymore?

2022-03-01 12:38 UTC, yinonov approved these changes

2022-03-01 13:01 UTC, merged