chore(docs): convert demo to iframe
Vonage/vivid-3 pull request #227
Opened 2022-02-27 16:52 UTC by rinaok

2022-02-28 16:02 UTC, YonatanKra reviewed
Looks nice. Can merge like it IMO, but the suggestions will make the code more readable IMO.

2022-02-28 18:42 UTC, yinonov commented on apps/docs/transformers/code-block-demo.js
> +const generateCodeBlockDemo = function (pre, index, header, outputPath) {
2nd that

2022-02-28 18:45 UTC, yinonov requested changes

2022-02-28 19:12 UTC, yinonov requested changes

2022-02-28 19:12 UTC, yinonov commented on apps/docs/transformers/code-block-demo.js
> +const generateCodeBlockDemo = function (pre, index, header, outputPath) {
```suggestion
const generateCodeBlockDemo = function (pre, index, headEl, outputPath) {
```

2022-02-28 19:16 UTC, yinonov requested changes

2022-02-28 19:16 UTC, yinonov commented on apps/docs/transformers/code-block-demo.js
> +        <iframe class="${CBD_DEMO}" src="${iframeSrc}" onload=onloadIframe(this)></iframe>
```suggestion
        <iframe class="${CBD_DEMO}" src="${iframeSrc}" onload=onloadIframe(this) loading="lazy"></iframe>
```

2022-02-28 19:23 UTC, yinonov reviewed
did you notice the network tasking? it has grown significantly

2022-03-17 09:40 UTC, yinonov approved these changes

2022-03-17 09:47 UTC, merged