refactor(docs): add components roadmap
Vonage/vivid-3 pull request #234
Opened 2022-03-02 17:11 UTC by rinaok

2022-03-03 06:59 UTC, rachelbt commented on README.md
> +| button               | migrate    | done        |
I personally wouldn't call the button done because the "stacked button" is still not in main

2022-03-03 13:38 UTC, yinonov commented on docs/components.md
> +<!-- Statuses can be GA | Alpha | WIP | backlog | deprecated -->
```suggestion
<!-- Statuses can be GA | alpha | WIP | backlog | deprecated | obsolete -->
```

2022-03-03 13:59 UTC, rinaok commented on docs/components.md
> +| Name   | vivid | vivid@next |
why the button is duplicated?

2022-03-08 10:53 UTC, yinonov requested changes

2022-03-08 10:53 UTC, yinonov commented on docs/components.md
> +| surface              |    obsolete     | deprecated |
other way around no?

2022-03-08 10:57 UTC, yinonov requested changes

2022-03-08 10:57 UTC, yinonov commented on docs/components.md
> +| surface              |    obsolete     | deprecated |
```suggestion
```

2022-03-08 10:59 UTC, yinonov requested changes

2022-03-08 10:59 UTC, yinonov commented on docs/components.md
> +| button               |       GA        |     GA     |
```suggestion
| button               |       GA        |     alpha     |
```

2022-03-08 11:00 UTC, yinonov requested changes

2022-03-08 11:00 UTC, yinonov commented on docs/components.md
> +| anchor               |      alpha      |     GA     |
```suggestion
| anchor               |      -      |     WIP     |
```

2022-03-08 11:07 UTC, yinonov requested changes

2022-03-08 11:07 UTC, yinonov commented on docs/components.md
> +| chip                 |      alpha      | -          |
```suggestion
| chip                 |      obsolete      | -          |
```

2022-03-08 13:03 UTC, yinonov commented on docs/components.md
> +| chip                 | obsolete |deprecated  |
```suggestion
| chip                 | obsolete | -          |
```

2022-03-08 13:04 UTC, yinonov commented on docs/components.md
> +| chipset              | obsolete |deprecated  |
```suggestion
| chipset              | obsolete | -          |
```

2022-03-08 13:04 UTC, yinonov commented on docs/components.md
> +| carousel             | obsolete | deprecated |
```suggestion
| carousel             | obsolete | -          |
```

2022-03-08 13:04 UTC, yinonov commented on docs/components.md
> +| datepicker           | alpha    | deprecated |
```suggestion
| datepicker           | alpha    | -          |
```

2022-03-08 13:05 UTC, yinonov approved these changes

2022-03-08 15:05 UTC, merged