feat(button): add states style
Vonage/vivid-3 pull request #235
Opened 2022-03-03 08:41 UTC by rachelbt

still missing design tokens of colors to match the design

2022-03-03 13:40 UTC, yinonov requested changes

2022-03-03 13:40 UTC, yinonov commented on libs/shared/src/lib/sass/mixins/_states.scss
> +        background-color: var(--vvd-color-neutral-20);
all variables should refer to scss consts

2022-03-03 13:47 UTC, yinonov requested changes

2022-03-03 13:47 UTC, yinonov commented on libs/shared/src/lib/sass/mixins/_states.scss
> +  $connotation: (
we wont always have connotation, so maybe just have a default style if no connotation

2022-03-03 13:47 UTC, yinonov commented on libs/shared/src/lib/sass/mixins/_states.scss
> +        }
we need to map this our in the mixin
like in
https://github.com/Vonage/vivid-3/blob/6e76ede9b7208b95eb20eb4b3d9677ba094cdc65/libs/shared/src/lib/sass/mixins/connotation/_variables.scss#L9-L46

2022-03-09 15:00 UTC, rachelbt commented on libs/shared/src/lib/sass/mixins/_states.scss
> +  $connotation: (
I added a default state

2022-03-09 15:01 UTC, rachelbt commented on libs/shared/src/lib/sass/mixins/_states.scss
> +        }
added colors to the map and used them in the state mixin

2022-03-10 05:23 UTC, yinonov requested changes
Should we disable indication on a disabled/idle control?

2022-03-10 08:11 UTC, rachelbt commented
> 

Right!! I've restricted the style when not idle. I don't think we need to target when disabled (as attribute) because it added the class (*-idle) anyway, right?

2022-03-10 09:27 UTC, yinonov commented on libs/components/src/lib/button/button.scss
> +	$shades: diverse contrast soft softer,
Softer? Softest? Final.final.design?

2022-03-10 09:33 UTC, rachelbt commented on libs/components/src/lib/button/button.scss
> +	$shades: diverse contrast soft softer,
is _light_ better?

2022-03-10 10:44 UTC, yinonov commented on libs/components/src/lib/button/button.scss
> +	$shades: diverse contrast soft softer,
yeap

2022-03-10 10:50 UTC, yinonov commented on libs/components/src/lib/button/button.scss
> +	$shades: diverse contrast soft softer,
muted, pale, dull, dim etc'...

2022-03-10 12:02 UTC, rachelbt commented on libs/components/src/lib/button/button.scss
> +	$shades: diverse contrast soft softer,
ohhhh - pale I like!

2022-03-16 08:33 UTC, yinonov commented
@rachelbt run `npx beachball change` to create the change file. it's a `none` type

2022-03-29 16:07 UTC, yinonov submitted a review, later dismissed

2022-04-11 11:00 UTC, closed without merging

2022-04-11 11:48 UTC, yinonov commented
> decided to control the states via appearance and not as a separated mixin

do we still need `libs/shared/src/lib/sass/mixins/_states.scss`?