feat(breadcrumb-item): breadcrumb item component
Vonage/vivid-3 pull request #246
Opened 2022-03-10 19:56 UTC by YonatanKra

2022-03-14 15:48 UTC, rachelbt commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.scss
> +.control a {
there's no parent with class "control" so this make no sense... You can target the a within the breadcrumb-item class

2022-03-14 15:48 UTC, rachelbt commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.scss
> +	color: var(#{theme-consts.$vvd-color-neutral-70});
add here:
a { style }
to target only A inside the item

2022-03-14 16:25 UTC, yinonov requested changes

2022-03-14 16:25 UTC, yinonov commented on apps/docs/_data/components.json
> +      "/assets/modules/components/anchor/index.js",
why anchor?

2022-03-14 16:26 UTC, yinonov requested changes

2022-03-14 16:36 UTC, yinonov commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.template.ts
> +		'control', 'breadcrumb-item'
name of the component is out. _control_ is the new convention

2022-03-14 17:00 UTC, yinonov requested changes

2022-03-14 17:00 UTC, yinonov commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.template.ts
> +  ${when(x => x.text && x.href && x.href.length > 0,
you tweaked the conditions.
I think the original conditions were to decide if the breadcrum-item is a linkable text or just the commonly last item. which is the current page.

2022-03-14 17:00 UTC, yinonov commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.ts
> +export class BreadcrumbItem extends FastBreadcrumbItem {
oh, I see the problem with extending our `text-anchor` here. it's still repeating same members. the aspiration is to not repeat our code.

notice how the `text-anchor`'s _text_ member will soon be modified with it's reflection strategy. but this class's _text_ member won't
https://github.com/Vonage/vivid-3/blob/91ac6640621faebd4c1670f3e30802a091954eb8/libs/components/src/lib/text-anchor/text-anchor.ts#L18-L19

2022-03-15 02:57 UTC, YonatanKra commented on apps/docs/_data/components.json
> +      "/assets/modules/components/icon/index.js"
Actually - that's a good point!
Anchor is no longer there, right?
And another thing to note is this:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/6459899/158296855-c23b7fb5-e274-4633-851d-85cc010633fb.png">
Seems like it is bundled.
Another confirmation we get for the bundling is the UI test that sets the `breadcrumb-item` in isolation - and still calls for `vwc-icon`.
So I guess this is working.
See the docs still work when I remove these two lines.

2022-03-15 03:00 UTC, YonatanKra commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.template.ts
> +  ${when(x => x.text && x.href && x.href.length > 0,
I have, because in the figma design we also have this case:
`link > ... > text`
Where the `...` is simple text indicating a lot of links?
Our need is a bit different than `fast`.
@yinonov 
Do we want the `breadcrumb-item` to decide if it is the last one? Or is it the concern of `breadcrumb` or even the user?

2022-03-15 03:07 UTC, YonatanKra commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.ts
> +export class BreadcrumbItem extends FastBreadcrumbItem {
Good point. I extended `text-anchor` instead of `fastBreadcrumbItem`. Now we get all the goodies of `text-anchor`.
Thing is - now we need to test everything `text-anchor` does as well...

2022-03-15 03:20 UTC, YonatanKra commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.scss
> +	color: var(#{theme-consts.$vvd-color-neutral-70});
Also added `vwc-icon { style }`

2022-03-15 05:39 UTC, yinonov commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.ts
> +	@attr({ mode: 'boolean' }) separator = false;
TS don't yell on missing override annotation here?

2022-03-15 06:03 UTC, YonatanKra commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.ts
> +	@attr({ mode: 'boolean' }) separator = false;
It is not an override. It is an extesion. Tect anchor doesn't have a separator

2022-03-15 07:31 UTC, rachelbt commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.template.ts
> +		'control', 'breadcrumb-item'
I know. But here its a problem because the a also has this class name...

2022-03-15 07:36 UTC, rachelbt commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.scss
> +		color: var(--vvd-color-cta-70);
this is not working?
color: var(#{theme-consts.$vvd-color-cta-70});

2022-03-15 09:27 UTC, yinonov approved these changes

2022-03-15 09:28 UTC, merged