Refactor-affix-patterns
Vonage/vivid-3 pull request #250
Opened 2022-03-11 14:55 UTC by yinonov

2022-03-15 10:33 UTC, YonatanKra requested changes
The `Affix` classes are not tested.
Tests are there to spare us regressions as well as document.
If there were tests, I guess I'd have had less questions :)

2022-03-15 10:33 UTC, YonatanKra commented on libs/components/src/shared/patterns/affix.ts
> +// import { classNames } from '@microsoft/fast-web-utilities';
If this is commented, it can be removed...
```suggestion

```

2022-03-15 10:33 UTC, YonatanKra commented on libs/components/src/shared/patterns/affix.ts
> +// 		const iconTag = context.tagFor(Icon);
Can this be removed?
```suggestion

```

2022-03-15 10:33 UTC, YonatanKra commented on libs/components/src/shared/patterns/affix.ts
> +// 	};
Can these be removed as well?

2022-03-15 10:33 UTC, YonatanKra commented on libs/components/src/shared/patterns/affix.ts
> +export class AffixIconWithTrailing extends AffixIcon {
What does that do? What's the meaning of `trailing`? Can you plz add a test that documents this?

2022-03-16 08:14 UTC, yinonov commented on libs/components/src/shared/patterns/affix.ts
> +export class AffixIconWithTrailing extends AffixIcon {
not sure how to test patterns, they are used in templates or classes and tested in the consuming component

2022-03-30 06:19 UTC, YonatanKra approved these changes

2022-03-30 07:22 UTC, merged