fix(docs): a bit of style
Vonage/vivid-3 pull request #258
Opened 2022-03-16 09:30 UTC by rachelbt

2022-03-17 11:52 UTC, yinonov requested changes

2022-03-17 11:52 UTC, yinonov commented on apps/docs/assets/styles/main.css
> +}
not too fond of this one. it collides with the dynamic shadow's flow

2022-03-20 09:10 UTC, rachelbt commented on apps/docs/assets/styles/main.css
> +}
but theres no other way to add the shadow to the top app

2022-03-20 13:27 UTC, yinonov commented on apps/docs/assets/styles/main.css
> +}
why add shadow?

2022-03-24 10:15 UTC, rachelbt commented on apps/docs/assets/styles/main.css
> +}
I removed the shadow

2022-03-24 12:46 UTC, yinonov approved these changes

2022-03-24 13:24 UTC, yinonov commented on apps/docs/assets/styles/main.css
> -  color: var(--vvd-color-on-canvas);
this breaks the style

2022-03-24 17:13 UTC, yinonov commented on apps/docs/assets/styles/main.css
> -  color: var(--vvd-color-on-canvas);
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/15140652/159972657-07f8e062-50be-41fe-8354-0c42f1a8506f.png">

2022-03-24 19:20 UTC, yinonov commented on apps/docs/assets/styles/main.css
> -  color: var(--vvd-color-on-canvas);
typography and color are different concerns. text component should not control text color.
This must not merge as is

2022-03-27 06:52 UTC, rachelbt commented on apps/docs/assets/styles/main.css
> -  color: var(--vvd-color-on-canvas);
removed it after updating from main the change of the color-scheme

2022-03-27 06:54 UTC, yinonov commented on apps/docs/assets/styles/main.css
> -  color: var(--vvd-color-on-canvas);
the background and foreground will align to dark theme but wont be set as our tokens now

2022-03-27 08:34 UTC, rachelbt commented on apps/docs/assets/styles/main.css
> -  color: var(--vvd-color-on-canvas);
I added back the `bg color` and the `color` properties on `body`

2022-03-27 09:12 UTC, yinonov approved these changes

2022-03-27 09:13 UTC, merged