chore(icon): add icon tests
Vonage/vivid-3 pull request #277
Opened 2022-03-30 21:28 UTC by YonatanKra

2022-03-31 07:00 UTC, yinonov requested changes

2022-03-31 07:00 UTC, yinonov commented on libs/components/src/lib/icon/__snapshots__/icon.spec.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
what is that file? 1st of its kind in the repo

2022-03-31 07:00 UTC, yinonov commented on libs/components/src/lib/icon/icon.spec.ts
> +		element.placeholder = 'hhh';
this is not a public interface. should be referred to as state. maybe shouldn't be decorated by _**observable**_

2022-03-31 07:00 UTC, yinonov commented on libs/components/src/lib/icon/icon.spec.ts
> +		element.state = 'loading';
same as its previous sibling

2022-03-31 07:00 UTC, yinonov commented on libs/shared/src/lib/test-utils/index.spec.ts
> +    it(`should return the element after rAF`, function (done) {
what?

2022-03-31 07:00 UTC, yinonov commented on libs/shared/src/lib/test-utils/index.spec.ts
> +    it(`should return the control element inside shadowDOM`, function () {
I don't think using _control_ as ref will last long as convention
see https://github.com/microsoft/fast/issues/5757

when setting a relevant ref in a template we can plainly query it as property
`el.control // or any other ref name`

2022-03-31 08:05 UTC, YonatanKra commented on libs/shared/src/lib/test-utils/index.spec.ts
> +    it(`should return the control element inside shadowDOM`, function () {
I didn't invent it - took it off from existing code as convention.
If convention is obsolete - we can change it. Not relevant to this PR methinks.

2022-03-31 08:06 UTC, YonatanKra commented on libs/shared/src/lib/test-utils/index.spec.ts
> +    it(`should return the element after rAF`, function (done) {
Actually - this is wrong :)

2022-03-31 12:56 UTC, yinonov commented on libs/components/src/lib/icon/__snapshots__/icon.spec.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
why is it back? and only with icon?

2022-04-01 14:04 UTC, yinonov approved these changes

2022-04-02 08:51 UTC, yinonov approved these changes

2022-04-02 14:08 UTC, merged

2022-10-11 07:24 UTC, YonatanKra commented
On purpose. I dont want the fetch to complete before the timers run out.

On Fri, Apr 1, 2022, 17:05 yinon ***@***.***> wrote:

> ***@***.**** approved this pull request.
> ------------------------------
>
> In libs/components/src/lib/icon/icon.spec.ts
> <https://github.com/Vonage/vivid-3/pull/277#discussion_r840580757>:
>
> > +	 */
> +	function setIconTypeAndAdvanceTime(timeInMs: number) {
> +		element.type = 'none';
> +		jest.advanceTimersByTime(timeInMs);
> +	}
> +
> +	/**
> +	 * @param iconType
> +	 */
> +	function setIconTypeAndRunAllTimers(iconType: string | undefined) {
> +		element.type = iconType;
> +		jest.runAllTimers();
> +	}
> +
> +	it('should show nothing when first changing the icon', async function () {
> +		fakeFetch(4000);
>
> isn't this too long?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Vonage/vivid-3/pull/277#pullrequestreview-928920555>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABRJD63IBSQUNQXOAKN4STTVC37BNANCNFSM5SDHHWOQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>