chore(components): migrate in calendar component
Vonage/vivid-3 pull request #287
Opened 2022-04-03 07:49 UTC by yinonov

Closes #283

2022-04-18 07:13 UTC, YonatanKra requested changes

2022-04-18 07:13 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.ts
> +	// }
Remove

2022-04-18 07:13 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.ts
> +	getDaysAsDatetime = (dateArr: Date[]): Date[] => {
It looks like a public API (even though you write `internal`). Why not use a private function? Or is it used in the template?
In any event, it is not documented. How does one use it? It should be documented in the tests, since by looking at it I find it hard to understand what it's supposed to do.
I also think the name of the method is not accurate.  It seems to be adding more and more items to the array until it has enough (`this._day`?). But what for?

2022-04-18 07:13 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.ts
> +	_days = 7;
If this is private, why not use `#`?

2022-04-18 07:13 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.ts
> +	_hours = 24;
`#hours`?

2022-04-18 07:13 UTC, YonatanKra commented on libs/components/src/lib/calendar/helpers/calendar.event-context.ts
> +export const getEventContextFactorial = (shadowRoot: ShadowRoot, hours: number) => {
What do you need the `factorial` for if it already gets `this: calendar` which holds both `shadowRoot` and `hours`?

2022-04-18 07:13 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.ts
> +	getEventContext = getEventContextFactorial(this.shadowRoot as ShadowRoot, this._hours);
Can it just be:
`getEventContext = (e) => {// do whatever with "this" and "e" }`

2022-04-18 07:13 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.ts
> +	// }
Remove?

2022-04-18 07:13 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.ts
> +		}*/
Remove?

2022-04-18 07:13 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.ts
> +			// default selectable element (first header)
Do we really need this comment? I know this from the tests and it doesn't add much...

2022-04-18 07:13 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.ts
> +		// we need to return true from our handler to opt - out of this behavior.
This should probably be tested and not written as a comment.

2022-04-18 07:21 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should set hebrew locales', async () => {
I actually don't know. I proxy that to the INTL

2022-04-18 08:51 UTC, yinonov commented on libs/components/src/lib/calendar/README.md
> +(only applicable for views of more than a single day. which is the only supported view at this time)
```suggestion
```

2022-04-18 08:52 UTC, yinonov commented on libs/components/src/lib/calendar/README.md
> +Use the `datetime` attribute to set date date within a week of choice.
```suggestion
Use the `datetime` attribute to set date within a week of choice.
```

2022-04-18 08:55 UTC, yinonov commented on libs/components/src/lib/calendar/helpers/calendar.event-context.ts
> +export const getEventContextFactorial = (shadowRoot: ShadowRoot, hours: number) => {
currying and principal of no more than 2 args. plus, hours maybe dynamic in the future and should be scaffolded to scale. I'd look into the shadowRoot

2022-04-18 08:57 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.ts
> +		// we need to return true from our handler to opt - out of this behavior.
that's fast's hidden knowledge. that's how they handle events fired from templates

2022-04-18 08:57 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.ts
> +		// we need to return true from our handler to opt - out of this behavior.
took me a while to reveal. maybe should link to the doc?

2022-04-18 08:58 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.ts
> +			// default selectable element (first header)
```suggestion
```

2022-04-18 09:18 UTC, yinonov commented on libs/components/src/lib/calendar/README.md
> +TODO - describe focus management and keyboard navigation.
```suggestion
```

2022-04-18 09:19 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +			const calendarFirstDate = getCalendarFirstDate(element);
date refers to column while time refers to rows. not clear enough?

2022-04-18 09:28 UTC, yinonov commented on libs/components/src/lib/calendar/README.md
> +
I actually don't know. I proxy that to the INTL as that what it accepts

2022-04-18 09:59 UTC, rinaok commented on libs/components/src/lib/calendar/README.md
> +# calendar
```suggestion
# vwc-calendar
```

2022-04-18 23:17 UTC, yinonov commented on libs/components/src/lib/calendar/README.md
> +# calendar
I know most our pages headers are prefixing the _vwc-_. but what do you think is nicer?

2022-04-18 23:20 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should return correct day and hour from mouse click event', async () => {
you mean I should 
```suggestion
		it('should return correct day and hour from mouse clicking inside one of the columns cells', async () => {
```

2022-04-18 23:22 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +			rowHeader.getBoundingClientRect = jest.fn().mockReturnValue({ height: 49, y: 85 });
not here. see if the definition clears it

2022-04-18 23:22 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should return hour from mouse click event', async () => {
```suggestion
		it('should return hour from mouse clicking on a row header', async () => {
```

2022-04-18 23:27 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should return null from mouse click event', async () => {
```suggestion
		it('should return null if mouse clicking outside the mapped region', async () => {
```

2022-04-18 23:29 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should circle back focus on keyboard arrow interactions', async () => {
there are conditions in code which must be covered by a flow

2022-04-18 23:30 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		// });
I need them to test calendar event. they are part of commented code I will uncomment once PRing the _calendar event_

2022-04-18 23:31 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.ts
> +	_days = 7;
cause template needs it 😫

2022-04-18 23:34 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.ts
> +	// }
see the TODO comment. i'll be uncommenting it right after this is merged. dont want to overload with the calendar-event in this PR. it is already quite packed

2022-04-19 10:38 UTC, rinaok commented on libs/components/src/lib/calendar/README.md
> +# calendar
I think it's nicer without it

2022-04-19 10:56 UTC, yinonov commented on libs/components/src/lib/calendar/README.md
> +# calendar
I do too. will capitalize at least
```suggestion
# Calendar
```

2022-04-19 11:00 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should throw on wrong event type', async () => {
```suggestion
		it('should throw on invalid event', async () => {
```

2022-04-19 11:03 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should throw on invalid event', async () => {
```suggestion
		it('should throw if unsupported event passed', async () => {
```

2022-04-19 11:06 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +			const e = new FocusEvent('click', { composed: true });
focus event is just arbitrary unsupported event. the code will throw immediately as it checks for event type
```suggestion
			const e = new FocusEvent('focus');
```

2022-04-19 11:13 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should throw if no target object', async () => {
I copied it from a spec somewhere. it's actually the composed path object target. but that how it was defined originally

2022-04-19 11:15 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +			expect(context?.hour).toEqual(undefined);
```suggestion
			expect(context?.hour).toBeUndefined();
```

2022-04-19 11:20 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should return day and hour from keydown \'space\' event', async () => {
```suggestion
		it('should return day from keydown \'space\' in grid cell', async () => {
```

2022-04-19 12:22 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.spec.ts
> +			const calendarFirstDate = getCalendarFirstDate(element);
I guess not if I asked :)
You could select any cell, and it will have the column's date.
Maybe `startOfWeekDate`? Or `firstColumnDate`?

2022-04-19 12:37 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should set hebrew locales', async () => {
Then it should be removed in the documentation if it is not supported, or covered here (and also dis`covered` - OMG I just love PR puns, don't you? ;) ).

2022-04-19 12:41 UTC, YonatanKra commented on libs/components/src/lib/calendar/README.md
> +
Then we should cover that in a test and know what the user should expect...
Or just remove it and say we do not support it.
What's the meaning of multiple locales anyway? You can be in only one place...

Ohhhhhh... maybe for quantum computers? Superposition? ;)

2022-04-19 12:44 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should throw if no target object', async () => {
Where? Because it is unclear. My suggestion is a more accurate description of the scenario, wouldn't you agree?

2022-04-19 12:46 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		// });
I don't understand...
If they are not related to this PR, then they should not be here.

2022-04-19 13:39 UTC, yinonov commented on libs/components/src/lib/calendar/README.md
> +
this member acts as a mediator to the `Intl.DateTimeFormat` method. same as passing the `datetime` member. we're not testing datetime.
it's also documented with link to original standard...
it sounds like an investigation and is same as vivid-2. I think this sublimes the scope of this PR

2022-04-19 13:48 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should set hebrew locales', async () => {
dad puns

2022-04-19 18:41 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should set hebrew locales', async () => {
`Intl.DateTimeFormat` expects a parameter of certain type. it's not for us to decide.
whatever it accepts, that's what we should pass. we can't decide it's not supported

2022-04-19 21:16 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should return day and hour from keydown \'enter\' event', async () => {
what do you mean?

2022-04-19 21:19 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		});
removing

2022-04-19 21:27 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +
```suggestion
```

2022-04-19 21:47 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should circle back focus on keyboard arrow interactions', async () => {
coverage require testing this condition where you keyboard navigate all the way to the last column and then it routes back to the first column from the end

2022-04-24 06:20 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should circle back focus on keyboard arrow interactions', async () => {
would this be clearer?
```suggestion
		it('should circle back focus from last column to first', async () => {
```

2022-04-24 06:21 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.ts
> +	_hours = 24;
should be reachable from a helper function

2022-04-24 06:27 UTC, YonatanKra commented on libs/components/src/lib/calendar/README.md
> +
Thing is - we don't know what it is doing.
I ask "what happens if I send and array" and the response is "I don't know" - doesn't sound like mediation to me ;)
In addition, we're not testing `Intl.DateTimeFormat`. We are testing our API and our API is supposed to mediate this to `Intl.DateTimeFormat`, but it might not...

2022-04-24 06:28 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should set hebrew locales', async () => {
We can decide we do not support it, or document what happens when one uses `locales`, which is doing something behind the scenes (the user should not care it is using `Intl.DateTimeFormat` IMO).

2022-04-24 06:29 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should return day and hour from keydown \'enter\' event', async () => {
`should return day and hour from keydown \'enter\' event` - for any event? At any time?
If I'm focused on a button in a form outside the calendar?

2022-04-24 06:30 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should circle back focus on keyboard arrow interactions', async () => {
Great! The change is good to go.

2022-04-24 06:52 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should return day and hour from keydown \'enter\' event', async () => {
how is this possible? u can't be trigger a keyboard click on an element while focused elsewhere

2022-04-24 06:56 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.ts
> +		// we need to return true from our handler to opt - out of this behavior.
Tests are the real documentation. This is part of the API. A consumer would expect `preventDefault` to be called. If this changes, it changes the API. Test :)

2022-04-24 07:14 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should return day and hour from keydown \'enter\' event', async () => {
and actually even if consumers programmatically trigger it, it'll work. no problem

2022-04-24 07:29 UTC, YonatanKra commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should return day and hour from keydown \'enter\' event', async () => {
So write it down in the description - `should emit enter keydown event with day and hour when focused on <what element>`

2022-04-24 07:36 UTC, yinonov commented on libs/components/src/lib/calendar/calendar.spec.ts
> +		it('should return day and hour from keydown \'enter\' event', async () => {
```suggestion
		it('should emit \'enter\' keydown event with day and hour when focused on grid cell', async () => {
```

2022-04-24 08:18 UTC, YonatanKra approved these changes

2022-04-24 08:22 UTC, merged