refactor(tooltip): migrate-to-fast-element
Vonage/vivid-3 pull request #295
Opened 2022-04-05 13:36 UTC by rinaok

2022-04-07 15:09 UTC, yinonov requested changes

2022-04-07 15:09 UTC, yinonov commented on libs/components/src/lib/tooltip/tooltip.scss
> +	&-title {
does tooltip have title? or only text content?

2022-04-07 17:26 UTC, YonatanKra commented on libs/components/src/lib/tooltip/tooltip.template.ts
> +      <div class="tooltip-title">${(x) => x.text}</div>
If I delete this row, tests still pass... need to add a test case for this.

2022-04-10 09:06 UTC, rachelbt commented on libs/components/src/lib/tooltip/tooltip.scss
> +		color: var(#{theme-consts.$vvd-color-primary});
tooltip doesn't need background,  it "uses" the bg of the popup.
I guess `$vvd-color-on-canvas `is more accurate here (even-though it gets the same result :) )

2022-04-10 09:14 UTC, rinaok commented on libs/components/src/lib/tooltip/tooltip.template.ts
> +      <div class="tooltip-title">${(x) => x.text}</div>
@YonatanKra Which row are you exactly talking about?

2022-04-11 12:06 UTC, yinonov requested changes

2022-04-13 13:02 UTC, YonatanKra commented on libs/components/src/lib/tooltip/tooltip.template.ts
> +      <div class="tooltip-title">${(x) => x.text}</div>
Row 27. Delete it - tests still pass.
It's not such a bad thing cause it is tested in the `ui-tests`, but just be aware of that.

2022-04-13 14:00 UTC, YonatanKra approved these changes
LGTM

2022-04-13 14:28 UTC, yinonov approved these changes

2022-04-13 14:55 UTC, merged