update layout readme
Vonage/vivid-3 pull request #298
Opened 2022-04-06 14:34 UTC by rinaok

2022-04-06 14:44 UTC, rinaok commented
@rachelbt @yinonov I'm trying to document layout in a more understandable way. How can I show the margins is gutters?

2022-04-07 06:51 UTC, rachelbt commented
> @rachelbt @yinonov I'm trying to document layout in a more understandable way. How can I show the margins is gutters?

It is so important the layout docs! 🦾 

I think that the easy way to show the margin is with image, and one code example. 
I also thing that we can give each layout a wrapper to style it and we can insert the CSS inside the iframe css to avoid code duplication, in all of our code preview.

![image](https://user-images.githubusercontent.com/7512792/162136671-356580dd-fd09-4916-86ae-1156d1e2bd23.png)

```
<div class="box-wrapper">
<vwc-layout>
  <div class="box">default</div>
  <div class="box">default</div>
</vwc-layout>
</div>
```
in `iframe.css`:
```
.box-wrapper{
  background-image: linear-gradient(to right, var(--vvd-color-info-30), var(--vvd-color-cta-30));
  padding: 1rem;
  border-radius: 6px;
}
.box-wrapper + .box-wrapper { margin-top: 2rem;}
.box {    
  border-radius: 6px;
  background-color: var(--vvd-color-canvas)
  color: var(--vvd-color-on-canvas);
  padding: 1rem;
  text-align: center;
}
```

2022-04-07 08:58 UTC, rinaok commented
> > @rachelbt @yinonov I'm trying to document layout in a more understandable way. How can I show the margins is gutters?
> 
> It is so important the layout docs! 🦾
> 
> I think that the easy way to show the margin is with image, and one code example. I also thing that we can give each layout a wrapper to style it and we can insert the CSS inside the iframe css to avoid code duplication, in all of our code preview.
> 
> ![image](https://user-images.githubusercontent.com/7512792/162136671-356580dd-fd09-4916-86ae-1156d1e2bd23.png)
> 
> ```
> <div class="box-wrapper">
> <vwc-layout>
>   <div class="box">default</div>
>   <div class="box">default</div>
> </vwc-layout>
> </div>
> ```
> 
> in `iframe.css`:
> 
> ```
> .box-wrapper{
>   background-image: linear-gradient(to right, var(--vvd-color-info-30), var(--vvd-color-cta-30));
>   padding: 1rem;
>   border-radius: 6px;
> }
> .box-wrapper + .box-wrapper { margin-top: 2rem;}
> .box {    
>   border-radius: 6px;
>   background-color: var(--vvd-color-canvas)
>   color: var(--vvd-color-on-canvas);
>   padding: 1rem;
>   text-align: center;
> }
> ```

Wow! Looks awesome 👏 😎 🤩

2022-04-08 07:33 UTC, yinonov requested changes

2022-04-08 07:33 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +Use the `auto-sizing` attribute to set the initial preferred `auto-sizing`.
shed more light?
[Auto-Sizing Columns in CSS Grid: `auto-fill` vs `auto-fit` - CSS ...https://css-tricks.com › auto-sizing-columns-css-grid-aut...](https://css-tricks.com/auto-sizing-columns-css-grid-auto-fill-vs-auto-fit/)

or 

https://stackoverflow.com/a/46227025/3027703

2022-04-08 07:41 UTC, yinonov reviewed
please see https://github.com/Vonage/vivid-3/pull/300#pullrequestreview-936037716

This is a great initiative and improves the doc a lot
but in practice it adds more code to read within the code snippets and can be avoided by applying this elsewhere in our implementation details

2022-04-25 12:47 UTC, rinaok commented
> please see [#300 (review)](https://github.com/Vonage/vivid-3/pull/300#pullrequestreview-936037716)
> 
> This is a great initiative and improves the doc a lot but in practice it adds more code to read within the code snippets and can be avoided by applying this elsewhere in our implementation details

@yinonov Is there a way to do it without adding <div class="box-wrapper"> and <div class="box">?

2022-04-25 14:47 UTC, YonatanKra requested changes
First - the first example should be explained - what is the default? How does it work?
Second - I think `auto-sizing` is too-much-info.  let's move it to the end.
Third - once the defaults are explained, I think it is easier to explain the variations.

2022-04-25 20:36 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +With `fill`, everything is the same as `fit`, except empty tracks are not collapsed.
well written! bravo

2022-04-25 20:36 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +  <vwc-layout style="--layout-grid-template-columns: repeat(auto-fit, minmax(100px, 1fr));">
why overriding the style if we only want to show fill / fit difference?

should preserve dedicated doc section for this css variable member

2022-04-25 20:39 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +  <vwc-layout style="--layout-grid-template-columns: repeat(auto-fit, minmax(100px, 1fr));">
never mind, I now see they don't relate

2022-04-26 09:03 UTC, YonatanKra approved these changes

2022-04-27 10:38 UTC, rinaok commented on libs/components/src/lib/layout/README.md
> +- Default: auto
@yinonov what should be the default?

2022-04-30 19:49 UTC, yinonov requested changes

2022-04-30 19:49 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +# layout
maybe the first example of images should also be replaced with card. the images aren't fluid and don't fully stretch

2022-05-10 06:19 UTC, rachelbt commented
Looks really good!
The only thing I would change is the preview of the column spacing - the demo div wrapper padding is too big.
Maybe you can add a variation for the demo-gradient class of tight like this:
.demo-gradient {
/*gradient style*/
&.tight {padding: 0.2rem}
}
to get this:
![image](https://user-images.githubusercontent.com/7512792/167560797-96c9cb68-d5de-49d5-a54a-6e950c28b660.png)

2022-05-10 08:14 UTC, yinonov commented on change/@vonage-vivid-fc53a33b-c30e-4be2-823f-e64619c0e655.json
> +{
is this file needed?

2022-05-10 08:14 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +- Type: `'base-small'` | `'base'` | `'base-large'` | `'block'`
this will change very soon

2022-05-10 08:16 UTC, yinonov reviewed
the ui tests seem poor and doesn't reflect enough scenarios

2022-05-11 10:45 UTC, yinonov requested changes

2022-05-11 10:45 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +## Column-basis
```suggestion
## Column Basis
```

2022-05-11 10:45 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +## Auto-sizing
```suggestion
## Auto Sizing
```

2022-05-11 10:45 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +## Column-spacing
```suggestion
## Column Spacing
```

2022-05-11 10:48 UTC, rinaok commented on change/@vonage-vivid-fc53a33b-c30e-4be2-823f-e64619c0e655.json
> +{
removed

2022-05-11 10:48 UTC, rinaok commented
> 

The ui tests are without the stying

2022-05-11 10:49 UTC, rinaok commented
> the ui tests seem poor and doesn't reflect enough scenarios

@yinonov The ui tests are without the styling but they are the same as in the docs

2022-05-11 12:48 UTC, yinonov approved these changes

2022-05-11 13:16 UTC, merged