feat(banner): add banner component
Vonage/vivid-3 pull request #304
Opened 2022-04-07 12:42 UTC by YonatanKra

Still missing:

- [ ] readme
- [ ] ui tests (from readme)

2022-04-08 06:36 UTC, yinonov requested changes

2022-04-08 06:36 UTC, yinonov commented on libs/components/src/lib/banner/README.md
> +    border: solid 1px #ccc;">
do we really need this?

2022-04-08 06:36 UTC, yinonov commented on libs/components/src/lib/banner/README.md
> +# banner
API members are missing their type & default

<img width="429" alt="image" src="https://user-images.githubusercontent.com/15140652/162376306-ff9de6ea-6654-4fe1-952e-fba6e6e3631f.png">

2022-04-08 06:36 UTC, yinonov commented on libs/components/src/lib/banner/README.md
> +<vwc-button appearance="filled" connotation="cta" label="Toggle open state" onclick="document.getElementById('toggled-banner').toggleAttribute('open')"></vwc-button>
place above the banner, prevent that layout shift

2022-04-08 06:36 UTC, yinonov commented on libs/components/src/lib/banner/README.md
> +The `message` attribute adds a message to the banner.
should we maybe align with _text_ member convention?

2022-04-08 06:36 UTC, yinonov commented on libs/components/src/lib/banner/README.md
> +Default connotation is `info`.
```suggestion
The `connotation` attribute sets the colors according to the wanted connotation.

- Type: `'info'` | `'announcement'` | `'success'` | `'warning'` | `'alert'`
- Default: `'info'`
```

2022-04-08 06:36 UTC, yinonov commented on libs/components/src/lib/banner/banner.scss
> +					--icon-size: 20px;
this has no effect. icons are sized 14px

2022-04-08 06:36 UTC, yinonov commented on libs/components/src/lib/banner/banner.template.ts
> +      @click="${x => x.open = false}">
```suggestion
    <vwc-button
      class="dismiss-button"
      size="base-small"
      icon="close-line"
      @click="${x => x.open = false}">
```

2022-04-08 06:36 UTC, yinonov commented on libs/components/src/lib/banner/banner.scss
> +					padding-inline-end: 15px;
```suggestion
					inline-inline-end: 15px;
```

2022-04-08 06:36 UTC, yinonov commented on libs/components/src/lib/banner/banner.scss
> +					--icon-size: 20px;
```suggestion
					font-size: 20px;
```

2022-04-08 06:36 UTC, yinonov commented on libs/components/src/lib/banner/banner.scss
> +				padding-inline-end: 8px;
```suggestion
				margin-inline-end: 8px;
```

2022-04-08 06:40 UTC, yinonov requested changes

2022-04-08 06:40 UTC, yinonov commented on libs/components/src/lib/banner/README.md
> +| `vwc-banner:closed`  | Fires when the closing animation is done                        |
the prefix (_vwc_) here is hardcoded. I think we can do better as in the design system module.

we should probably keep it as a const somewhere and refer to it

https://github.com/Vonage/vivid-3/blob/e0d0189fec878e630120f7e7240d1ca1947fd8c1/libs/components/src/shared/design-system/index.ts#L9

2022-04-08 06:42 UTC, yinonov commented on libs/components/src/lib/banner/README.md
> +### Accessibility
<img width="728" alt="image" src="https://user-images.githubusercontent.com/15140652/162379202-73d42d02-17da-45ec-ab7a-f6be9ed1b436.png">

> we default a banner component role to ‘status’ with a redundant aria-live attribute set to polite (To maximize compatibility when using this role). This indicates that the screen reader should wait until the user is idle before presenting updates to the user.
> However, we can modify the above attributes (role and aria-live) to fit contextually. So if the information is critical, we could still alter the banner's role to 'alert', telling assistive technologies to interrupt other processes and provide users with immediate notification.
>

2022-04-08 08:34 UTC, YonatanKra commented on libs/components/src/lib/banner/README.md
> +    border: solid 1px #ccc;">
Nope - just makes for a good showcase.
Want me to remove it?

2022-04-08 08:50 UTC, YonatanKra commented on libs/components/src/lib/banner/README.md
> +| `vwc-banner:closed`  | Fires when the closing animation is done                        |
Dunno - over engineered?
By using `vwc-*` we lock it down to us. Why would it ever change?

2022-04-08 13:18 UTC, yinonov requested changes

2022-04-08 13:18 UTC, yinonov commented on libs/components/src/lib/banner/README.md
> +We default the banner component role to ‘status’ with a redundant aria-live attribute set to polite (to maximize compatibility when using this role). This indicates that the screen reader should wait
maybe author in an objective manner?

2022-04-08 13:18 UTC, yinonov commented on libs/components/src/lib/banner/banner.scss
> +					padding-inline-end: 15px;
@jshenkman is this value correct? 15px?

2022-04-08 13:18 UTC, yinonov commented on libs/components/src/lib/banner/banner.scss
> +					padding-inline-start: 15px;
@jshenkman same here 15px

2022-04-08 13:18 UTC, yinonov commented on libs/shared/src/lib/sass/mixins/connotation/_config.scss
> +$connotations-set: $predefined-connotations !default;
use the `$subset` above instead.
This might not be the most correct naming but it's now handled in a different PR

```suggestion
```

2022-04-09 17:15 UTC, yinonov approved these changes

2022-04-09 18:38 UTC, merged

2022-04-09 19:42 UTC, YonatanKra commented on libs/components/src/lib/banner/README.md
> +| `vwc-banner:closed`  | Fires when the closing animation is done                        |
Ok - can open a new issue for this one I guess.