refactor(expansion-panel): migrate-to-fast-element
Vonage/vivid-3 pull request #311
Opened 2022-04-10 15:30 UTC by rinaok

2022-04-14 14:19 UTC, rachelbt reviewed
👍  😄

2022-04-14 14:19 UTC, rachelbt commented on libs/components/src/lib/accordion-item/README.md
> +Add the `icon-trailing` attribute to add an icon to the right of the heading text.
```suggestion
Mind that `icon-trailing` will overide the Indicator```

2022-04-14 14:19 UTC, rachelbt commented on libs/components/src/lib/accordion-item/README.md
> +Use the `heading-level` attribute to change the accordion item's size.
```suggestion
Use the `heading-level` attribute to change the accordion heading to fit the page hierarchy.```

2022-04-14 15:43 UTC, yinonov requested changes

2022-04-14 15:43 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +```js
```suggestion
```html preview
```

2022-04-14 15:43 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +## Icon
icon is a common member. sort to the end (icon-trailing too)

2022-04-14 15:43 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +## Dense
let's make sure this is still required @jshenkman

2022-04-14 19:21 UTC, yinonov requested changes

2022-04-14 19:21 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.ts
> +	@attr({ mode: 'fromView', attribute: 'heading-level' }) headingLevel: 2 | 3 | 4 | 5 | 6 = 3;
no need to assign value. just default to 3 if no assigned value
```suggestion
	@attr({ attribute: 'heading-level' }) headingLevel: 2 | 3 | 4 | 5 | 6;
```

2022-04-14 19:21 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.ts
> +	@attr({ mode: 'boolean', attribute: 'icon-trailing' }) iconTrailing = false;
use the affix pattern mixin both to applyMixin on class and render in template

2022-04-14 19:21 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.ts
> +	}
feels like another pattern right? along with the `open` member. we often run into this set. better if it comes from a single source of truth

2022-04-14 19:21 UTC, yinonov commented on libs/components/src/lib/accordion-item/index.ts
> +export const vividaccordionItem =
```suggestion
export const vividAccordionItem =
```

2022-04-14 21:01 UTC, yinonov requested changes

2022-04-14 21:01 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +		<div class="accordion-item-body">
```suggestion
		<div class="accordion-item-body" id="content" role="region" aria-labelledby="header">
```

2022-04-14 21:01 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +	<button class="accordion-item-button" @click=${x=> x.toggleOpen()}
```suggestion
	<button class="accordion-item-button" id="header" @click=${x=> x.toggleOpen()}
```

2022-04-17 09:22 UTC, rinaok commented on libs/components/src/lib/accordion-item/README.md
> +```js
It's not a code example, so it does not have a preview

2022-04-17 19:08 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +```js
doesn't have to annotate with _preview_. but it's an _html_ and not _js_

2022-04-17 19:11 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +```js
I'm not sure it's very informative for readers. they dont have interior knowledge of the template.
maybe drop in a quote from accordion aria practice that explains the heading hierarchy.
add a snippet preview with saying something like "the following will output..."

2022-04-17 19:16 UTC, yinonov requested changes
we discussed the conditional rendering of indicator in correlation with icon position.
it's now known to us but maybe confusing to consumers.

I think we should address it in the docs

edit:
found it
https://github.com/Vonage/vivid-3/pull/311/files#r851794034

2022-04-17 19:17 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +Add the `icon-trailing` attribute to add an icon to the right of the heading text.  Mind that `icon-trailing` will overide the Indicator.
```suggestion
Add the `icon-trailing` attribute to add an icon to the right of the heading text.  Mind that `icon-trailing` will override the Indicator.
```

2022-04-17 20:00 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +| `show`       | `(): void` | Opens the accordion item from the closed state. |
I started aligning methods to our members convention. there shouldn't be any difference I think. consider? or think it should be like this?

see event context
https://vivid-dy25ra84f90g.deno.dev/components/calendar

2022-04-18 09:57 UTC, rinaok commented on libs/components/src/lib/accordion-item/README.md
> +| `show`       | `(): void` | Opens the accordion item from the closed state. |
It is more clear this way. Perhaps we can discuss it further. It isn't relevant for this PR since all the components need to change.

2022-04-19 09:37 UTC, yinonov commented on docs/components.md
> +| accordion item      | GA         | WIP        |
```suggestion
| accordion item       | GA         | WIP        |
```

2022-04-19 09:37 UTC, yinonov commented on docs/components.md
> +| list accordion item | GA         | obsolete   |
```suggestion
| list accordion item  | GA         | obsolete   |
```

2022-04-19 09:40 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +| `show`       | `(): void` | Opens the accordion item from the closed state. |
right but this is a good place to start

2022-04-19 09:52 UTC, yinonov requested changes

2022-04-19 09:52 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(hasClassOpenAfterShow).toEqual(true);
```suggestion
			expect(hasClassOpenBeforeShow).toBeFalsy();
			expect(hasClassOpenAfterShow).toBeTruthy();
```

2022-04-19 09:52 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(hasClassOpenAfterHide).toEqual(false);
same as above

2022-04-19 09:52 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +		it('should set "open" to false and remove "open" class', async () => {
I think we need to keep definition as simple as possible
```suggestion
		it('should unset "open"', async () => {
```

2022-04-19 09:52 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +		it('should toggle when open attribute changes', async () => {
```suggestion
		it('should toggle "open" state', async () => {
```

2022-04-19 09:52 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +		<div class="accordion-item-body" id="content" role="region" aria-labelledby="header">
css convention of scoped portions was needed in large scale style files to namespace parts and avoid conflicts
this is redundant for web components and might even deviate from the web components templates convention. templates has their own encapsulated tree

prefixes are no longer required

```suggestion
		<div class="body" id="content" role="region" aria-labelledby="header">
```

2022-04-19 09:52 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +		<div class="accordion-item-body" id="content" role="region" aria-labelledby="header">
let's remove it from other classes?

2022-04-19 14:25 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +Use the `open` attribute to indicate whether the accordion item is open.
```suggestion
Use the `open` attribute to set the accordion-item's open state.
```

2022-04-19 14:27 UTC, yinonov requested changes

2022-04-19 14:27 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +<div class="wrapper">
this adds more reading material. remove from all?

2022-04-19 14:35 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +## Dense
still need to discuss (preferably omit). maybe comment out first?

2022-04-19 14:40 UTC, yinonov requested changes

2022-04-19 14:40 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +Opens the accordion item.
should be ordered above the type & default

2022-04-19 14:40 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +Closes the accordion item.
why do we have these methods anyway? I think it's a good opportunity to try and question these. are they redundant? do they add some capability which lacks in a property member? maybe it should accept callback and that's its purpose?

2022-04-19 14:53 UTC, rinaok commented on libs/components/src/lib/accordion-item/README.md
> +<div class="wrapper">
@yinonov but then the indicator is far on the right of the example.

2022-04-19 14:54 UTC, rinaok commented on libs/components/src/lib/accordion-item/README.md
> +Closes the accordion item.
@yinonov My opinion is that we should remove all the hide and show methods.. from the side-drawer and from other components as well.

2022-04-19 15:04 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +Closes the accordion item.
go ahead

2022-04-24 11:26 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +```js
```suggestion
```html preview
```

2022-04-24 11:26 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +```js
```suggestion
```html
```

2022-04-24 11:26 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +```html preview
```suggestion
```html
```

2022-04-24 11:27 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +The following sets the heading of the accordion-item to level 2
```suggestion
The following sets the heading of accordion-item to level 2
```

2022-04-24 11:27 UTC, yinonov approved these changes

2022-04-24 12:07 UTC, yinonov approved these changes

2022-04-24 12:07 UTC, merged