chore(card): migrate component
Vonage/vivid-3 pull request #318
Opened 2022-04-14 14:05 UTC by rachelbt

****Still in work***
Need test + UI tests

2022-04-14 15:34 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +# card
docs flow should be in alphabetical order and in groups as follows -

1. dedicated API members (component dedicated props)
2. common members (size, connotation etc')
3. slot members
4. appendix (e.g. a11y)

description of each member should come before type & default

there's no need to prefix each member with its host (e.g. card heading, card subtitle etc')

2022-04-14 15:34 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +- Default: `'''`
```suggestion
- Default: `''`
```

2022-04-14 15:35 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +- Default: `'''`
```suggestion
- Default: `''`
```

2022-04-14 15:35 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +- Default: `'''`
```suggestion
- Default: `''`
```

2022-04-14 15:35 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +- Default: `'''`
```suggestion
- Default: `''`
```

2022-04-14 15:35 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +- Default: `'''`
```suggestion
- Default: `''`
```

2022-04-17 18:52 UTC, yinonov requested changes
slots and properties can be (should be) rendered conditionally if authors sets their members

<img width="654" alt="image" src="https://user-images.githubusercontent.com/15140652/163728387-b384276e-ff49-4902-8062-aef21c7c5299.png">

2022-04-17 18:52 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +
missing plain html preview

2022-04-17 18:52 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +<div style="width: 300px; height: 200px;">
over engineering. let's keep the snippet simple. if it takes 100% of the container, that's what it should show. later in the page u can show a tiled layout of cards

2022-04-17 18:52 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +## Icon
common identity. should be ordered last. u can also copy paste this from other components

2022-04-17 18:55 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +<div style="width: 300px; height: 200px;">
alternatively u can set style to the card itself `display: inline-block`

2022-04-18 05:32 UTC, rachelbt commented
> slots and properties can be (should be) rendered conditionally if authors sets their members
> 
> <img alt="image" width="654" src="https://user-images.githubusercontent.com/15140652/163728387-b384276e-ff49-4902-8062-aef21c7c5299.png">

I know - this is in my TODO couldn't handle the JS alone :)

2022-04-18 05:43 UTC, rachelbt commented on libs/components/src/lib/card/README.md
> +<div style="width: 300px; height: 200px;">
That what I did from the beginning. But the inline style of the height of the iframe caused the card to be presented incorrectly and preview only half of it.
I know its not ideal but for now - me working still on the card here it feels OK. 
I understand that it redundant and un-needed code

2022-04-18 05:45 UTC, rachelbt commented on libs/components/src/lib/card/README.md
> +## Icon
Can't copy paste cause it can only be on the left.
Ordered it alphabetical....

2022-04-21 17:21 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +- Type: `String: 0|2|4|8|12|16|24`
```suggestion
- Type: `0` | `2` | `4` | `8` | `12` | `16` | `24`
```

2022-04-21 17:22 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +- Type: `String: 0|2|4|8|12|16|24`
we should enable a way to unset elevation. maybe even default to `none`. in vivid 2 we don't feature a `none` option?

2022-04-24 05:54 UTC, rachelbt commented on libs/components/src/lib/card/README.md
> +- Type: `String: 0|2|4|8|12|16|24`
no. the default is 4 as in Joella's design

2022-04-24 06:18 UTC, yinonov requested changes

2022-04-24 06:18 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +- Type: `0` | `2` | `4` | `8` | `12` | `16` | `24`
sorry forgot also
```suggestion
- Type: `'0'` | `'2'` | `'4'` | `'8'` | `'12'` | `'16'` | `'24'`
```

2022-04-25 06:36 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +## Icon
It's a common identity shared in other components so is ordered after all "personal" members.
U can copy its description from other components where trailing doesn't apply. Don't need to rewrite description

2022-04-25 06:37 UTC, yinonov requested changes

2022-04-25 06:37 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +- Default: `4`
What if we don't want elevation to apply on card?

2022-04-27 09:13 UTC, rinaok commented on libs/components/src/lib/card/README.md
> +Add a `heading` attribute to add card heading title
```suggestion
Add a `heading` attribute to add card heading title.
```

2022-04-27 09:14 UTC, rinaok commented on libs/components/src/lib/card/README.md
> +Add a `subtitle` attribute to add card subtitle
```suggestion
Add a `subtitle` attribute to add card subtitle.
```

2022-04-27 09:14 UTC, rinaok commented on libs/components/src/lib/card/README.md
> +```
```suggestion
## Text
Add a `text` attribute to add text to the card.

- Type: `String`
- Default: `''`


```html preview
<vwc-card heading="Vivid Card Component" subtitle="extra text to the card heading" text="the card can contain multiple lines of text"></vwc-card>
```
```

2022-04-27 09:17 UTC, rinaok commented on libs/components/src/lib/card/README.md
> +the `elevation` control the elevation depth
```suggestion
Control the elevation depth by adding the `elevation` attribute.
```

2022-04-27 09:20 UTC, rinaok commented on libs/components/src/lib/card/README.md
> +## Trim Heading & subtitle
```suggestion
## CSS Custom Properties

### Trim Heading & subtitle
```

2022-04-27 09:32 UTC, rinaok commented on libs/components/src/lib/card/README.md
> +- Type: `String: 0|2|4|8|12|16|24`
@yinonov @rachelbt Why do we call the attribute **elevation** and not **dp** as in vwc-elevation? It's confusing.

2022-04-28 13:56 UTC, rachelbt commented on libs/components/src/lib/card/README.md
> +Add a `heading` attribute to add card heading title
removed all the dots altogether :)

2022-05-02 12:35 UTC, rachelbt commented on libs/components/src/lib/card/README.md
> +- Type: `String: 0|2|4|8|12|16|24`
its more semantically correct here. 
Only 'dp' is out of context. In elevation it is clear what id does but in card - elevation make more sense. 
Maybe we need to call it - 'elevation-dp' but its a bit too long :)

2022-05-03 07:15 UTC, YonatanKra requested changes

2022-05-03 07:15 UTC, YonatanKra commented on libs/components/src/lib/card/card.template.ts
> +	<vwc-elevation dp=${(x => x.elevation ??  '4')}>
You never test the elevation API methinks. You should add tests to it if it is relevant.
This will also bring you to 100% coverage ;)
Especially when you have a TODO...

2022-05-03 07:15 UTC, YonatanKra commented on libs/components/src/lib/card/card.ts
> +	@attr elevation?: 0 | 2 | 4 | 8 | 12 | 16 | 24; // TODO: get values from design tokens
Remove TODO and add an issue for it instead.

2022-05-03 09:09 UTC, rachelbt commented on libs/components/src/lib/card/README.md
> +
most of the components doesn't have it...

2022-05-05 19:23 UTC, yinonov requested changes

2022-05-05 19:23 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +<div slot="content">If you need diferant structure - use this slot</div>
```suggestion
<div slot="content">If you need different structure - use this slot</div>
```

2022-05-08 08:31 UTC, yinonov approved these changes

2022-05-08 12:19 UTC, yinonov approved these changes

2022-05-08 12:52 UTC, YonatanKra approved these changes

2022-05-08 13:07 UTC, merged