feat(progress-ring): add progress-ring component
Vonage/vivid-3 pull request #320
Opened 2022-04-15 07:55 UTC by YonatanKra

2022-04-15 09:13 UTC, yinonov requested changes

2022-04-15 09:13 UTC, yinonov commented on libs/components/src/lib/progress-ring/progress-ring.ts
> +	@attr size?: ProgressRingSize;
this should have a larger spectrum. check vivid. might need to discuss it now

2022-04-15 09:13 UTC, yinonov commented on libs/components/src/lib/progress-ring/progress-ring.scss
> +	stroke: gray;
change to token?

2022-04-15 09:13 UTC, yinonov commented on libs/components/src/lib/progress-ring/progress-ring.scss
> +	stroke: gray;
change to token?

2022-04-15 09:13 UTC, yinonov commented on libs/components/src/lib/progress-ring/progress-ring.scss
> +	stroke: black;
change to token?

2022-04-15 15:49 UTC, YonatanKra commented on libs/components/src/lib/progress-ring/progress-ring.ts
> +	@attr size?: ProgressRingSize;
It follows what's in `Figma`. Do we deviate from `Figma`?

2022-04-15 16:16 UTC, YonatanKra commented
@jshenkman - the `paused` state is not defined.
Also, @yinonov mentioned there are more sizes than there are in [`Figma`](https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=1450%3A11822). Are there? Can they be defined if there are?

2022-04-18 10:07 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +# progress-ring
```suggestion
# vwc-progress-ring
```

2022-04-18 10:08 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +<script type="module">import '@vonage/vivid/progress-ring';</script>
```suggestion
<script type="module">
   import '@vonage/vivid/progress-ring';
 </script>
```

2022-04-18 10:11 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +<vwc-progress-ring min="0" max="100" value="ii"></vwc-progress-ring>
```suggestion
```html preview
<vwc-progress-ring></vwc-progress-ring>
```
We should keep the first example as simple as possible.

2022-04-18 10:12 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +## API
```suggestion

```

2022-04-18 10:17 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +```
```suggestion
```html preview
    <vwc-progress-ring min="0" max="50" value="12.5"></vwc-progress-ring>
    <vwc-progress-ring min="0" max="50" value="50"></vwc-progress-ring>
```

It might be helpful to add an example to Max and Min, so it's more clear.
```

2022-04-18 10:19 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +```
```suggestion
```html preview
    <vwc-progress-ring value="12.5"></vwc-progress-ring>
    <vwc-progress-ring value="45"></vwc-progress-ring>
    <vwc-progress-ring value="73"></vwc-progress-ring>
    <vwc-progress-ring value="100"></vwc-progress-ring>

```
The value examples should be before the Min/Max examples.
```

2022-04-18 10:21 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +    <br/>
Why not use vwc-layout?

2022-04-18 10:21 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +    <br/>
Why not use vwc-layout?

2022-04-18 10:25 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +    <vwc-progress-ring min="0" max="50" value="indeterminate"></vwc-progress-ring>
```suggestion
    <vwc-progress-ring min="0" max="50"></vwc-progress-ring>
```
Why do we need it if it works just as well without it?

2022-04-18 10:26 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +## Example Usage
The usage examples above are redundant because they repeat the same information.

2022-04-18 10:28 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +In the example below, we set the value to `12.5` while the range is `0` to `50`.  This means, 25% of the progress bar will be filled.
This text should appear at the Min/Max example.

2022-04-18 10:32 UTC, rinaok commented on libs/components/src/lib/progress-ring/progress-ring.ts
> +	 * Indicates the text's text.
?

2022-04-18 10:32 UTC, rinaok commented on libs/components/src/lib/progress-ring/progress-ring.ts
> +	 * HTML Attribute: text
```suggestion
	 * HTML Attribute: size
```

2022-04-18 10:33 UTC, rinaok commented on libs/components/src/lib/progress-ring/progress-ring.ts
> +	 * Indicates the text's text.
```suggestion
	 * Indicates the progress ring's size.
```

2022-04-18 10:35 UTC, rinaok commented on libs/components/src/lib/progress-ring/ui.test.ts
> +	extractHTMLBlocksFromReadme,
```suggestion
```

2022-04-18 10:35 UTC, rinaok commented on libs/components/src/lib/progress-ring/ui.test.ts
> +import * as path from 'path';
```suggestion
```

2022-04-26 09:16 UTC, YonatanKra commented on libs/components/src/lib/progress-ring/README.md
> +In the example below, we set the value to `12.5` while the range is `0` to `50`.  This means, 25% of the progress bar will be filled.
This already appears above explaining the separate API properties.
This example usage is stating determinate state - which is not an API but a behavior.

2022-04-27 13:03 UTC, rinaok commented on libs/components/src/lib/progress-ring/README.md
> +# vwc-progress-ring
```suggestion
# progress-ring
```
we decided to remove it from all the components

2022-04-27 13:05 UTC, YonatanKra commented on libs/components/src/lib/progress-ring/README.md
> +# vwc-progress-ring
Ping-Pong ;)

2022-04-27 13:06 UTC, rinaok approved these changes

2022-04-28 06:19 UTC, yinonov approved these changes

2022-04-28 06:20 UTC, merged