refactor(docs): code block demo as markdownit plugin
Vonage/vivid-3 pull request #329
Opened 2022-04-24 12:44 UTC by yinonov

2022-05-10 07:04 UTC, yinonov commented on libs/components/src/lib/accordion-item/README.md
> +```html-preview
```suggestion
```html preview
```

2022-05-23 12:28 UTC, rinaok commented on apps/docs/transformers/code-block-demo.js
> +    try {
All the try-and-catch is no longer necessary. I added them for debugging purposes.

2022-05-23 12:32 UTC, rinaok commented
@yinonov Looks very nice!

2022-05-23 12:33 UTC, rinaok requested changes

2022-05-23 12:33 UTC, rinaok commented on apps/docs/transformers/code-block-demo.js
> +    }
All the try-and-catch is no longer necessary. I added them for debugging purposes.

2022-05-23 12:33 UTC, rinaok commented on apps/docs/transformers/code-block-demo.js
> +        console.log("verifyAndCreateSaveFolder error: ", e);
Also here

2022-05-23 12:33 UTC, rinaok commented on apps/docs/transformers/code-block-demo.js
> +    }
And here

2022-05-23 12:33 UTC, rinaok commented on apps/docs/transformers/code-block-demo.js
> +    }
.

2022-05-23 12:33 UTC, rinaok commented on apps/docs/transformers/code-block-demo.js
> +    }
.

2022-05-23 12:45 UTC, rinaok commented
![Screen Shot 2022-05-23 at 15 43 38](https://user-images.githubusercontent.com/10883919/169821926-03f0e3e0-db14-4bc1-aeb4-6389ce669bf8.png)

Is this the way it should be? Without highlighting?

2022-05-23 15:40 UTC, yinonov commented on apps/docs/transformers/code-block-demo.js
> +    }
oh 🫤

2022-05-23 15:41 UTC, yinonov commented
> ![Screen Shot 2022-05-23 at 15 43 38](https://user-images.githubusercontent.com/10883919/169821926-03f0e3e0-db14-4bc1-aeb4-6389ce669bf8.png)
> 
> Is this the way it should be? Without highlighting?

no. strange that's what u get
it uses our tokens now

<img width="894" alt="image" src="https://user-images.githubusercontent.com/15140652/169856657-303efe3e-ca53-487b-a96e-2268df075a78.png">

<img width="835" alt="image" src="https://user-images.githubusercontent.com/15140652/169856742-d7c43537-82e7-4601-a373-f32022386969.png">

2022-05-24 07:49 UTC, rinaok commented
> > ![Screen Shot 2022-05-23 at 15 43 38](https://user-images.githubusercontent.com/10883919/169821926-03f0e3e0-db14-4bc1-aeb4-6389ce669bf8.png)
> > Is this the way it should be? Without highlighting?
> 
> no. strange that's what u get it uses our tokens now
> 
> <img alt="image" width="894" src="https://user-images.githubusercontent.com/15140652/169856657-303efe3e-ca53-487b-a96e-2268df075a78.png">
> 
> <img alt="image" width="835" src="https://user-images.githubusercontent.com/15140652/169856742-d7c43537-82e7-4601-a373-f32022386969.png">

@yinonov 

Look at accordion-item: https://vivid-ft84re92m1n0.deno.dev/components/accordion-item

2022-05-24 09:14 UTC, merged