refactor(fab): migrate to fast-element
Vonage/vivid-3 pull request #347
Opened 2022-04-28 16:04 UTC by rinaok

2022-05-02 11:41 UTC, rinaok commented
The disabled fab, without connotation, is white and not grey like in vivid-2.
@rachelbt  @yinonov Can you check why?

2022-05-02 11:44 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.spec.ts
> +		it('adds an icon to the fab', async () => {
```suggestion
		it('should add an icon to the fab', async () => {
```

2022-05-02 11:44 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.spec.ts
> +		it('setting `iconTrailing` set the order of element', async () => {
```suggestion
		it('should  set icon to end when `iconTrailing` is set', async () => {
```

2022-05-02 11:45 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.spec.ts
> +		it('set label property to node', async () => {
```suggestion
		it('should set label property to node', async () => {
```

2022-05-02 11:45 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.spec.ts
> +		it('sets correct internal connotation style', async () => {
```suggestion
		it('should set correct connotation class', async () => {
```

2022-05-02 11:48 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.spec.ts
> +			expect(getControlElement(element).classList.toString()).toEqual(`control connotation-${connotation}`);
There's no need to see if there's `.control` class.
You can do something like this:
```suggestion
      const expectedConnotation = `connotation-${connotation}`;
      const hasConnotationClassBefore = getControlElement(element).classList.contains(expectedConnotation);
      
			(element as any).connotation = connotation;
			await elementUpdated(element);
			
			expect(hasConnotationClassBefore).toEqual(false);
			expect(getControlElement(element).classList.contains(expectedConnotation)).toEqual(true);
```

2022-05-02 11:49 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.spec.ts
> +			(element as any).connotation = connotation;
If you set the element to be of type `Fab` in the first place, it would obsolete the `as any`, right?

2022-05-02 11:49 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.spec.ts
> +		});
See comments regarding description and test flow in the `connotation` test

2022-05-02 11:51 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.spec.ts
> +			const appearance = 'filled';
Do we need appearance `filled` in order for `disabled` class to be added?

2022-05-02 11:51 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.ts
> +	@attr({ mode: 'fromView' }) label = '';
Why `fromView`?

2022-05-02 11:52 UTC, YonatanKra requested changes
See my comments

2022-05-02 11:53 UTC, rinaok commented on libs/components/src/lib/fab/fab.ts
> +	@attr({ mode: 'fromView' }) label = '';
@YonatanKra The linter doesn't give me another choice.

2022-05-02 11:58 UTC, rinaok commented on libs/components/src/lib/fab/fab.spec.ts
> +			const appearance = 'filled';
@YonatanKra yes

2022-05-02 12:18 UTC, rinaok commented on libs/components/src/lib/fab/fab.spec.ts
> +			const appearance = 'filled';
@yinonov Can remove the appearance from the fab? Cause it has only filled.

2022-05-02 12:22 UTC, rachelbt commented
@rinaok , @yinonov 

why aren't we using the vwc-button component?
It seems like we have duplicated code - both in the template and in the css.
we can wrap the button with div and elevation, something like this:

```
<vwc-elevation dp='4'>
<div class="control" style for control that is needed="display: inline-block; border-radius: 24px;">
<vwc-button appearance='filled' label='add to cart' size='base-large' icon="cart-line" connotation="cta" shape="pill"></vwc-button>
</div>
</vwc-elevation>
```

The thing we need to sort out is the "white" variant that is actually an alternate for button - maybe we need to add part to the button for this use case - same as popup and tooltip.

2022-05-02 12:25 UTC, rinaok commented
> @rinaok , @yinonov
> 
> why aren't we using the vwc-button component? It seems like we have duplicated code - both in the template and in the css. we can wrap the button with div and elevation, something like this:
> 
> ```
> <vwc-elevation dp='4'>
> <div class="control" style for control that is needed="display: inline-block; border-radius: 24px;">
> <vwc-button appearance='filled' label='add to cart' size='base-large' icon="cart-line" connotation="cta" shape="pill"></vwc-button>
> </div>
> </vwc-elevation>
> ```
> 
> The thing we need to sort out is the "white" variant that is actually an alternate for button - maybe we need to add part to the button for this use case - same as popup and tooltip.

I agree!

2022-05-02 12:28 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.ts
> +	@attr({ mode: 'fromView' }) label = '';
`@attr label?: string;` - this should work

2022-05-02 12:32 UTC, rachelbt commented
> The disabled fab, without connotation, is white and not grey like in vivid-2. @rachelbt @yinonov Can you check why?

because you're using appearance but the "white" one is not mapped as an appearance. Check my comment regarding using the `vwc-button.`
https://github.com/Vonage/vivid-3/pull/347#issuecomment-1114788708

2022-05-02 15:15 UTC, rinaok commented
> 

Updated it with vwc-button. I made it alternate, but it has a problem with being alternate and disabled at the same time.

2022-05-02 18:24 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.spec.ts
> +		it('sets correct internal icon-only style', async () => {
use the `should` syntax plz like above for all `it`s

2022-05-02 18:24 UTC, YonatanKra commented on libs/components/src/lib/fab/fab.spec.ts
> +			const appearance = 'filled';
This indeed looks like a non-intuitive API. Need to decide on this one...

2022-05-03 04:24 UTC, yinonov commented
A word on difference between buttons.
FAB has unique style and members which justifies its independence. Extending the fast foundation button is exactly where this fits

2022-05-03 05:34 UTC, rachelbt commented
> A word on difference between buttons. FAB has unique style and members which justifies its independence. Extending the fast foundation button is exactly where this fits

but the only difference is the "white" variation

2022-05-03 12:31 UTC, rinaok commented
> > A word on difference between buttons. FAB has unique style and members which justifies its independence. Extending the fast foundation button is exactly where this fits
> 
> but the only difference is the "white" variation

@rachelbt @yinonov 

I did it with alternate because the vwc-button has a default connotation which is primary. And there is no color white in connotation to override it. This is the only thing that differs the vwc-fab from the vwc-button.

2022-05-03 12:43 UTC, YonatanKra submitted a review, later dismissed
LGTM

2022-05-03 12:43 UTC, rachelbt reviewed
I don't think that all of the FAB buttons need the alternate - only the "primary" one need it. The cta, alert success looks off with wrong colors.

2022-05-03 12:43 UTC, rachelbt commented on libs/components/src/lib/fab/partials/variables.scss
> +$icon-gap: --fab-icon-gap;
I don't think this file is needed anymore...

2022-05-03 12:52 UTC, rinaok commented
> I don't think that all of the FAB buttons need the alternate - only the "primary" one need it. The cta, alert success looks off with wrong colors.

@rachelbt fixed it :)

2022-05-04 05:08 UTC, rachelbt requested changes
you need also to update the ui-test png :)

2022-05-04 12:38 UTC, rinaok commented on libs/components/src/lib/fab/README.md
> +<vwc-fab icon='plus-line' connotation='cta'></vwc-fab>
@rachelbt  Can you please check why the disable mode is not with a grey background?

2022-05-08 09:16 UTC, yinonov requested changes

2022-05-08 09:16 UTC, yinonov commented on libs/components/src/lib/fab/fab.scss
> +}
missing `color`

2022-05-08 09:18 UTC, yinonov requested changes

2022-05-08 09:18 UTC, yinonov commented on libs/components/src/lib/fab/fab.scss
> +	filter: var(#{theme-consts.$vvd-shadow-surface-4dp});
should have elevation changed on hover, active states

2022-05-08 09:42 UTC, rinaok commented on libs/components/src/lib/fab/fab.scss
> +	filter: var(#{theme-consts.$vvd-shadow-surface-4dp});
@yinonov In vivid-2 the elevation changes only on active state: https://vivid.vonage.com/?path=/story/alpha-components-fab--basic&args=icon:store

2022-05-09 07:09 UTC, rachelbt commented on libs/components/src/lib/fab/fab.scss
> +
```suggestion
.control:not(:disabled) {
	@include elevation.get-elevation(4);
	cursor: pointer;

	&:not([class*="connotation"]) {
		&:hover {
			background: var(#{theme-consts.$vvd-color-neutral-10});
		}
		&:active{
			background: var(#{theme-consts.$vvd-color-neutral-30});
		}
	}
	&:active{
		@include elevation.get-elevation(8);
	}
}
```
this way the hover state from appearance will work and 79-84 is not needed :)

2022-05-09 07:09 UTC, rachelbt commented on libs/components/src/lib/fab/fab.scss
> +	cursor: pointer;
```suggestion
	
```

2022-05-11 07:42 UTC, rachelbt commented on libs/components/src/lib/fab/README.md
> +- Default: `''`
```suggestion
- Default: `undefined`
```

2022-05-11 07:42 UTC, rachelbt commented on libs/components/src/lib/fab/README.md
> +- Default: `''`
```suggestion
- Default: `undefined`
```

2022-05-16 11:13 UTC, yinonov requested changes

2022-05-16 11:15 UTC, rachelbt commented on libs/components/src/lib/fab/fab.scss
> +	:not(.icon-trailing) & {
this is not needed and also `margin-inline-start: var(#{variables.$icon-gap});` is not needed. 
They both can be replaced with adding to `.control` `column-gap: var(#{variables.$icon-gap});`|
and of-course defining its value there like the block size.
If there we will not support fab sizes than you can simply write the value and not the variable :)

2022-05-16 12:37 UTC, rinaok commented on libs/components/src/lib/fab/partials/variables.scss
> +$block-size: --fab-block-size;
@rachelbt The `--fab-icon-gap` should also be with `_`?

2022-05-16 18:12 UTC, rinaok commented
@yinonov Should we disable the focus?

2022-05-16 18:44 UTC, yinonov reviewed
surface is hardly seen. is this correct? @jshenkman 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/15140652/168660967-e72f4fd5-b3e8-4aef-98d1-4a1dcd1d5dd2.png">

2022-05-17 08:59 UTC, rachelbt commented
> surface is hardly seen. is this correct? @jshenkman <img alt="image" width="468" src="https://user-images.githubusercontent.com/15140652/168660967-e72f4fd5-b3e8-4aef-98d1-4a1dcd1d5dd2.png">

maybe we need to change the "canvas" mapping:
![image](https://user-images.githubusercontent.com/7512792/168772515-d4935b56-de1a-48dc-9caf-2960a4e7a294.png)
and use the surface instead of:
`basis: theme-consts.$vvd-color-canvas`
this:
`basis: theme-consts.$color-surface-4dp`

2022-05-17 17:25 UTC, yinonov approved these changes

2022-05-17 18:07 UTC, merged