feat(workspace): upgrade nx to v14
Vonage/vivid-3 pull request #353
Opened 2022-05-02 19:31 UTC by YonatanKra

2022-05-02 19:36 UTC, yinonov requested changes

2022-05-02 19:36 UTC, yinonov commented on libs/components/.eslintrc.json
> +    "@nrwl/nx/workspace/no-attribute-default-value": "off",
really? 🤨

2022-05-03 02:52 UTC, YonatanKra commented on libs/components/.eslintrc.json
> +    "@nrwl/nx/workspace/no-attribute-default-value": "off",
Mind taking a look at it? It is broken for some reason...
Try to activate it and see.

2022-05-03 11:50 UTC, yinonov approved these changes

2022-05-03 11:54 UTC, merged