docs(workspace): 11ty generator
Vonage/vivid-3 pull request #38
Opened 2021-11-16 21:49 UTC by yinonov

2021-11-21 11:13 UTC, yinonov commented on package.json
> +    "jsdom": "^18.1.0",
```suggestion
```

2021-11-21 11:16 UTC, yinonov commented on package.json
> +    "build:docs": "eleventy",
```suggestion
  "start:dev": "npm run build:components -- --watch & npm run build:tokens -- --watch & web-dev-server --watch",
    "start": "npm run build:components && npm run build:tokens && web-dev-server",
```

2021-11-21 12:02 UTC, YonatanKra requested changes

2021-11-21 12:02 UTC, YonatanKra commented on package.json
> +    "dev": "eleventy --serve",
Eleventy is not our dev. Eleventy is our documentation.  Either `start` or `docs`, but def not `dev` on its own.

2021-11-21 12:02 UTC, YonatanKra commented on package.json
> +    "build": "npm run build:components && npm run build:tokens && npm run build:docs",
This is where I say Nx is needed... too many scripts in the build. It's like we define the dependencies on our own.

2021-11-21 12:31 UTC, yinonov commented on .eleventy.js
> +  // Return your Object options:
```suggestion
```

2021-11-21 12:46 UTC, yinonov commented on package.json
> +    "build": "npm run build:components && npm run build:tokens && npm run build:docs",
ideally we'll have only build and docs eventually

2021-11-21 13:28 UTC, yinonov commented on .eleventy.js
> +// const { EleventyRenderPlugin } = require("@11ty/eleventy");
```suggestion
```

2021-11-22 08:07 UTC, YonatanKra commented on package.json
> +    "build:docs": "eleventy",
Have you change this back?

2021-11-22 08:16 UTC, yinonov commented on package.json
> +    "build:docs": "eleventy",
```suggestion
```

2021-11-22 08:20 UTC, YonatanKra approved these changes

2021-11-22 09:55 UTC, merged