refactor(button): update docs
Vonage/vivid-3 pull request #380
Opened 2022-05-11 14:40 UTC by rinaok

2022-05-13 08:05 UTC, yinonov requested changes

2022-05-13 08:05 UTC, yinonov commented on libs/components/src/lib/button/README.md
> +Use the icon attribute to add an icon to the button. You can choose an icon from the [icons gallery](https://icons.vivid.vonage.com).
was the former paragraph illegible?

2022-05-13 10:00 UTC, rinaok commented on libs/components/src/lib/button/README.md
> +Use the icon attribute to add an icon to the button. You can choose an icon from the [icons gallery](https://icons.vivid.vonage.com).
I moved it below, didn't erase it

2022-05-13 12:58 UTC, yinonov commented on libs/components/src/lib/button/README.md
> +Use the icon attribute to add an icon to the button. You can choose an icon from the [icons gallery](https://icons.vivid.vonage.com).
oh. got it

2022-05-16 11:12 UTC, yinonov approved these changes

2022-05-16 11:44 UTC, merged