feat(textfield): add the text field component
Vonage/vivid-3 pull request #382
Opened 2022-05-12 07:14 UTC by YonatanKra

Note that `number-field` is still in debate #381 
Also need to setup the ui-tests and documentation

2022-05-13 07:50 UTC, yinonov requested changes

2022-05-13 07:50 UTC, yinonov commented on libs/components/src/lib/textfield/README.md
> +## Placeholder
text field has a vast parity with members of a native input. maybe just describe that part and link to w3c/mdn

2022-05-13 07:56 UTC, yinonov requested changes

2022-05-13 07:56 UTC, yinonov commented on libs/components/src/lib/textfield/textfield.template.ts
> +	`density-${textField.density ?? BlockSize.Normal}`,
no need to default to a class.
style defaults are handled by css & scss mixins
see
[[`shape-${shape}`, Boolean(shape)],](https://github.com/Vonage/vivid-3/blob/dac03d5be96241b8c0a3b722e4c5128c4d714449/libs/components/src/lib/badge/badge.template.ts#L14-L15)

2022-05-13 07:56 UTC, yinonov commented on libs/components/src/lib/textfield/textfield.template.ts
> +	`appearance-${textField.appearance ?? Appearance.Outlined}`,
same here

2022-05-13 07:56 UTC, yinonov commented on libs/components/src/lib/textfield/textfield.template.ts
> +	`shape-${textField.shape ?? Shape.Rounded}`,
same here

2022-05-13 08:00 UTC, yinonov commented on libs/components/src/lib/textfield/textfield.template.ts
> +			<div class="form-field">
is this extra div required? I think we can manage styling without it. let me try?

2022-05-13 08:01 UTC, yinonov commented on libs/components/src/lib/textfield/textfield.template.ts
> +	<div class="root ${getStateClasses}">
`root` is kind of wrong here. the actual root is the host. stick to `base`?

2022-05-14 19:45 UTC, yinonov requested changes

2022-05-14 19:45 UTC, yinonov commented on libs/components/src/lib/textfield/README.md
> +- Type: `'rounded'` | `'pill'`
pill is still in doubt an need to be concluded

2022-05-14 19:56 UTC, yinonov commented on libs/components/src/lib/textfield/textfield.template.ts
> +	['error', !!textField.errorValidationMessage],
not sure about performance but I use Boolean() in favor of legibility

2022-05-15 06:22 UTC, yinonov requested changes
affix pattern should be added to enable decorative icons support

2022-05-15 07:44 UTC, yinonov reviewed
why is value reflected? by fast's design?
<img width="789" alt="image" src="https://user-images.githubusercontent.com/15140652/168462634-ee82b333-e6a0-46bd-a679-9513400d1ad0.png">

2022-05-15 07:45 UTC, yinonov requested changes

2022-05-15 07:45 UTC, yinonov commented on libs/components/src/lib/textfield/textfield.template.ts
> +	['active', !!textField.value],
why not `has-value`?

2022-05-15 08:40 UTC, YonatanKra commented on libs/components/src/lib/textfield/textfield.template.ts
> +	['error', !!textField.errorValidationMessage],
No significat perf issue: https://jsben.ch/Iujqh
And a boolean would mean to "pollute" the class with another "get" as this one's a complex condition (dirty and invalid).

2022-05-15 11:38 UTC, yinonov requested changes

2022-05-15 11:38 UTC, yinonov commented on libs/components/src/lib/textfield/README.md
> +### Input types
should add also disabled

2022-05-15 16:02 UTC, yinonov requested changes

2022-05-15 16:02 UTC, yinonov commented on libs/components/src/lib/text-field/README.md
> +### char-count
```suggestion
### Character Count
```

2022-05-15 16:02 UTC, yinonov commented on libs/components/src/lib/text-field/README.md
> +### Helper-text
```suggestion
### Helper Text
```

2022-05-15 16:05 UTC, yinonov requested changes

2022-05-15 16:05 UTC, yinonov commented on libs/components/src/lib/text-field/README.md
> +### Placeholder
this is a native input member. we should mention it as part of all proxied members and link to a mdn/w3c document

2022-05-20 07:31 UTC, yinonov commented on libs/components/src/lib/text-field/README.md
> +### Input types
we should mention it as part of the proxied members and link to a mdn/w3c document

2022-05-21 21:11 UTC, yinonov requested changes

2022-05-21 21:11 UTC, yinonov commented on libs/components/src/lib/text-field/README.md
> +Use the `char-count` attribute along with the `maxlength` attribute to show a character count.
on 2nd thought, if `maxlength` is a prerequisite for `char-count`, maybe default should be true.
automatically shown unless author opts-out

2022-05-22 07:46 UTC, yinonov commented on libs/components/src/lib/text-field/README.md
> +You can validate the text field like any other native `input`.  Here's an example using `pattern`. The value is 5, which is not of the pattern `123`.  In addition, we programatically `dirtied` the fi
u meant to put dirtied in quotes? if not, is it part of the API as implied by that format?

2022-05-22 09:57 UTC, yinonov requested changes

2022-05-22 09:57 UTC, yinonov commented on libs/components/src/lib/text-field/README.md
> +### Validation
validation is eager and show error whole user focused and still inputting. I believe our spec is to have a polite message when user blurs (@jshenkman)

2022-05-22 11:15 UTC, yinonov requested changes

2022-05-22 11:15 UTC, yinonov commented on libs/components/src/lib/text-field/README.md
> +You can validate the text field like any other native `input`.  Here's an example using `pattern`. The value is 5, which is not of the pattern `123`.  In addition, we programatically `dirtied` the fi
I think u should refer to this guide
https://developer.mozilla.org/en-US/docs/web/css/:user-valid

explain that this the behavior of our text field is somewhat similar to the proposed `:user-valid`

2022-05-22 11:32 UTC, yinonov commented on libs/components/src/lib/text-field/text-field.ts
> +		return this.userValid ? '' : this.validationMessage;
could there be any way to trigger validity indication programmatically? this question was raised a couple of times.

not sure if it's a correct handling but I can think of a use-case where this is needed. WDYT?

2022-05-22 13:41 UTC, rachelbt commented
The input needs a min width - otherwise when placing the text-field inside flex it look like this:
![image](https://user-images.githubusercontent.com/7512792/169698088-e5dd6d67-e873-437c-8c0d-8778b0cb5cba.png)

2022-05-23 07:22 UTC, rachelbt commented
In Firefox the input doesn't stretch to fill the wrapper and the text is not aligned:
![image](https://user-images.githubusercontent.com/7512792/169765370-cef4108c-70a0-462c-ab95-8627e1e803a3.png)

2022-05-24 07:00 UTC, rachelbt commented
@jshenkman 
in disabled state - I think that the label should also be grayed. 
![image](https://user-images.githubusercontent.com/7512792/169968643-b20da869-6627-464b-9432-1671013dd6e4.png)

2022-05-24 09:41 UTC, jshenkman commented
> @jshenkman in disabled state - I think that the label should also be grayed. ![image](https://user-images.githubusercontent.com/7512792/169968643-b20da869-6627-464b-9432-1671013dd6e4.png)

Definitely! By design it is :) 
![Screen Shot 2022-05-24 at 12 40 39](https://user-images.githubusercontent.com/67224525/170001965-adb25e2d-a628-4243-9fd7-e010c66de403.png)
https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=9637%3A49884

2022-05-25 07:46 UTC, rachelbt commented
I think we can add some accessibility to the input as in this article:
https://www.ovl.design/text/inclusive-inputs/

2022-05-27 10:26 UTC, yinonov commented
> @YonatanKra, @yinonov I think we can add some accessibility to the input as in this article: https://www.ovl.design/text/inclusive-inputs/

can you point to a specific section?

2022-05-29 10:01 UTC, rachelbt commented
> > @YonatanKra, @yinonov I think we can add some accessibility to the input as in this article: https://www.ovl.design/text/inclusive-inputs/
> 
> can you point to a specific section?

- **Identifying Input Purpose** - adding nave - we do :)
- **Marking required** (adding an extra span for required text & hiding it for for screen readers only).
- **The required attribute** 
- **Validation** - various aria labels

2022-05-29 11:38 UTC, yinonov commented
> > > @YonatanKra, @yinonov I think we can add some accessibility to the input as in this article: https://www.ovl.design/text/inclusive-inputs/
> > 
> > 
> > can you point to a specific section?
> 
> * **Identifying Input Purpose** - adding nave - we do :)
> * **Marking required** (adding an extra span for required text & hiding it for for screen readers only).
> * **The required attribute**
> * **Validation** - various aria labels

make sense but each has a discussion of its own. I suggest merging this MVP and start iterations

2022-05-30 06:47 UTC, rachelbt commented
> https://www.ovl.design/text/inclusive-inputs/

Opened an issue for that:
https://github.com/Vonage/vivid-3/issues/419

2022-05-30 12:04 UTC, merged

2023-01-12 16:16 UTC, rinaok commented on libs/components/src/lib/textfield/README.md
> +## Placeholder
@YonatanKra @YonatanKra  I also think that we should add a link