feat(note): migrate the note component
Vonage/vivid-3 pull request #400
Opened 2022-05-23 11:52 UTC by YonatanKra

2022-05-23 12:36 UTC, rachelbt commented on libs/components/src/lib/note/note.scss
> +.note-icon {
this is the old method of class names - we don't use the "note" now, you can change it to simply icon.

2022-05-23 12:36 UTC, rachelbt commented on libs/components/src/lib/note/note.scss
> +	margin-inline-end: 16px;
add this to match the design:
```suggestion
	margin-inline-end: 16px;
	align-self: flex-start;
  font-size: 24px;
```

2022-05-23 12:36 UTC, rachelbt commented on libs/components/src/lib/note/note.scss
> +	.note-header {
```suggestion
	.heading {
```
pay in mind that this will effect your test as well :)

2022-05-23 12:36 UTC, rachelbt commented on libs/components/src/lib/note/note.scss
> +		display: block;
```suggestion
		
```

2022-05-23 12:36 UTC, rachelbt commented on libs/components/src/lib/note/note.scss
> +	display: flex;
```suggestion
	display: flex;
	gap: 4px;
```

2022-05-23 12:36 UTC, rachelbt commented on libs/components/src/lib/note/note.scss
> +		margin-block-end: 4px;
```suggestion

```
we added the gap - so this is not needed anymore

2022-05-23 12:36 UTC, rachelbt commented on libs/components/src/lib/note/note.scss
> +	min-height: 24px;
not sure why this is needed :)

2022-05-23 12:36 UTC, rachelbt commented on libs/components/src/lib/note/README.md
> +<vwc-note connotation="announcement"></vwc-note>
the preview looks strange with no text inside - I think we can add:
```suggestion
<vwc-note connotation="alert" header="alert note"></vwc-note>
<vwc-note connotation="success" header="success note"></vwc-note>
<vwc-note connotation="warning" header="warning note"></vwc-note>
<vwc-note connotation="info" header="info note"></vwc-note>
<vwc-note connotation="announcement" header="announcement note"></vwc-note>
```

2022-05-23 14:07 UTC, YonatanKra commented on libs/components/src/lib/note/note.scss
> +	min-height: 24px;
So... remove this?

2022-05-24 03:59 UTC, rachelbt commented on libs/components/src/lib/note/README.md
> +Add the `icon` attribute in order to set an icon in the note.
```suggestion
Add a icon='icon-name' attribute  in order to set an icon in the note.
```

2022-05-24 03:59 UTC, rachelbt commented on libs/components/src/lib/note/README.md
> +- Default: `null`
```suggestion
- Default: `undefined`
```

2022-05-24 03:59 UTC, rachelbt commented on libs/components/src/lib/note/README.md
> +- Default: `null`
```suggestion
- Default: `undefined`
```

2022-05-24 03:59 UTC, rachelbt commented on libs/components/src/lib/note/README.md
> +### header
```suggestion
### heading
```
the text is not really the note header but more its heading. Like in Card:
https://vivid-6066n7078jtg.deno.dev/components/card#heading
I think we need to change it and its class name :)

2022-05-24 09:23 UTC, yinonov requested changes

2022-05-24 09:23 UTC, yinonov commented on libs/components/src/lib/note/README.md
> +Add the `header` attribute in order to set a header text.
```suggestion
Add the `heading` attribute in order to set a header text.
```

2022-05-24 09:23 UTC, yinonov commented on libs/components/src/lib/note/README.md
> +Add the `icon` attribute in order to set an icon in the note.
we have so many variants of the same member. we should consolidate to one. or at least not produce more variants.

having said that, here's a new variant :D

```suggestion
Use the `icon` attribute to set a decorative icon.
Note that if not set, icon will default to the connotation-associated icon type.
```

2022-05-26 09:45 UTC, yinonov approved these changes

2022-05-26 10:13 UTC, merged