refactor(top-app-bar): migrate-to-fast-element
Vonage/vivid-3 pull request #404
Opened 2022-05-25 09:56 UTC by rinaok

2022-05-26 05:52 UTC, yinonov commented
can we have an example in **side-drawer** with top-app-bar?

2022-05-26 05:53 UTC, yinonov commented on libs/components/src/lib/top-app-bar/README.md
> +### Meta
I'm not sure that's its right name

2022-05-29 11:41 UTC, yinonov commented on libs/components/src/lib/top-app-bar/top-app-bar.scss
> +	&.shadow {
elevated?

2022-05-29 11:44 UTC, yinonov commented on libs/components/src/lib/top-app-bar/README.md
> +<style>
don't see how this helps the demo. unecessary decoration

2022-05-29 11:45 UTC, yinonov commented on libs/components/src/lib/top-app-bar/README.md
> +        background-color: var(--vvd-color-neutral-10);
again, unecessary

2022-05-29 11:45 UTC, yinonov commented on libs/components/src/lib/top-app-bar/README.md
> +<vwc-button slot="meta" icon="menu-line"></vwc-button>
what is that for? it's no js

2022-05-29 13:53 UTC, rinaok commented on libs/components/src/lib/top-app-bar/README.md
> +<style>
![Screen Shot 2022-05-29 at 16 53 09](https://user-images.githubusercontent.com/10883919/170872565-563d9239-b288-4ae5-baa0-76d7e07c145b.png)

without it, it looks like this

2022-05-29 13:54 UTC, rinaok commented on libs/components/src/lib/top-app-bar/README.md
> +        background-color: var(--vvd-color-neutral-10);
![Screen Shot 2022-05-29 at 16 53 43](https://user-images.githubusercontent.com/10883919/170872587-fd33e431-fb3f-400e-800a-dad5da340e0b.png)

with the background you can understand where is the top bar

2022-05-29 13:55 UTC, rinaok commented on libs/components/src/lib/top-app-bar/README.md
> +<vwc-button slot="meta" icon="menu-line"></vwc-button>
it's an example for a slot. Should it be html? I copied it from the side-drawer: https://vivid.deno.dev/components/side-drawer#app-content
It's `js` there too

2022-05-29 13:56 UTC, rinaok commented on libs/components/src/lib/top-app-bar/README.md
> +### Meta
what is the right name?

2022-05-29 16:55 UTC, yinonov commented on libs/components/src/lib/top-app-bar/README.md
> +            <vwc-text font-face="body-1">
wrap with layout? it's a usage example so decoration is relevant

2022-05-29 17:12 UTC, yinonov commented on libs/components/src/lib/top-app-bar/README.md
> +```js
why the duplication of source? and this ain't no JS

2022-06-02 16:47 UTC, rinaok commented
@yinonov There is only one thing left to do: choose a name instead of top-app-bar.

2022-06-02 20:52 UTC, yinonov requested changes
that effect is quite unbelievable 😁
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/15140652/171735764-ccac3556-1fbf-4e16-bad9-19ec99d43fbe.png">

2022-06-02 21:00 UTC, yinonov requested changes

2022-06-02 21:00 UTC, yinonov commented on libs/components/src/lib/top-app-bar/README.md
> +### Height
```suggestion
### Block Size
```

2022-06-03 04:18 UTC, yinonov commented on libs/components/src/lib/top-app-bar/README.md
> +### Height
is it by spec to expose block size value as a wild card?

2022-06-06 06:34 UTC, rinaok commented
> a scrolled app-header (non fixed) should scroll back instantly when page scrolls back down. start by applying the following
> 
> ```css
> position: sticky;
> top: calc(-1 * var(--top-app-bar-height));
> ```

We've already tried that. @rachelbt , can you elaborate?

2022-06-06 06:36 UTC, rinaok commented on libs/components/src/lib/top-app-bar/README.md
> +### Height
@jshenkman Should we expose the Top Bar's height to the user?

2022-06-06 07:27 UTC, yinonov commented on libs/components/src/lib/top-app-bar/README.md
> +### Height
I think it should be a `min-block-size` only. if content exceeds, the top-bar extends. naturally

2022-06-06 07:28 UTC, yinonov commented on libs/components/src/lib/top-app-bar/README.md
> +### Meta
can you provide a few from other libraries usages?

2022-06-06 09:28 UTC, rinaok commented
> that effect is quite unbelievable 😁 <img alt="image" width="1227" src="https://user-images.githubusercontent.com/15140652/171735764-ccac3556-1fbf-4e16-bad9-19ec99d43fbe.png">

@yinonov Does it look good now?

2022-06-06 09:35 UTC, rinaok commented on libs/components/src/lib/top-app-bar/README.md
> +### Height
@yinonov @rachelbt  The `top-app-bar-height` effects also on the `padding-top` of the `app-content`.
So how can I do it when the content exceeds?

2022-06-06 10:03 UTC, rinaok commented on libs/components/src/lib/top-app-bar/README.md
> +### Meta
@yinonov material calls this slot: **navigationIcon**

2022-06-06 12:28 UTC, rachelbt commented on libs/components/src/lib/top-app-bar/README.md
> +### Height
if we are using padding - we can't use the min-height. We need a predefined size either by us or by the user

2022-06-06 12:58 UTC, rachelbt commented
> > a scrolled app-header (non fixed) should scroll back instantly when page scrolls back down. start by applying the following
> > ```css
> > position: sticky;
> > top: calc(-1 * var(--top-app-bar-height));
> > ```
> 
> We've already tried that. @rachelbt , can you elaborate?

I think its the mixture of shadow & light dom that makes sticky not properly work.
It can work id we "fix" the top-app-bar host to the screen with:
```
position: fixed;
inset: 0;
overflow-y: auto;
```
But I'm not sure this is a good idea...

2022-06-06 15:27 UTC, yinonov commented on libs/components/src/lib/top-app-bar/README.md
> +### Meta
right but it's often not what it contains

2022-06-09 09:28 UTC, rinaok commented on libs/components/src/lib/top-app-bar/README.md
> +### Height
@yinonov It's not related to this PR, it should be fixed in a new PR cause it happens in all the components.


![Screen Shot 2022-06-09 at 12 28 43](https://user-images.githubusercontent.com/10883919/172814764-39bb4a5b-7541-4206-9b97-cdbe84fcc3ab.png)

2022-06-14 12:00 UTC, YonatanKra commented on libs/components/src/lib/header/header.spec.ts
> +		it('should default to no elevation with no scrolling', async function () {
I can't see any relation to scrolling in the test itself.
Maybe this is more accurate:
```suggestion
		it('should default to no elevation', async function () {
```

2022-06-14 12:00 UTC, YonatanKra commented on libs/components/src/lib/header/header.spec.ts
> +		it('should set "elevated" to true and add "elevated" class', async () => {
```suggestion
		it('should set "elevated" to true and add "elevated" class when scrolled', async () => {
```

2022-06-14 12:01 UTC, YonatanKra commented on libs/components/src/lib/header/header.spec.ts
> +		it('should remove elevated state when offset is 0', async function () {
```suggestion
		it('should remove elevated state when scroll offset is 0', async function () {
```

2022-06-15 08:52 UTC, yinonov requested changes

2022-06-15 08:52 UTC, yinonov commented on libs/components/src/lib/header/README.md
> +### Z-index
```suggestion
### Stacking Context
```

2022-06-15 08:52 UTC, yinonov commented on libs/components/src/lib/header/README.md
> +Controls the z-index of the header.
_"use the `--header-z-index` ..."_

2022-06-15 08:52 UTC, yinonov commented on libs/components/src/lib/header/README.md
> +- `--header-z-index`
```suggestion
```

2022-06-15 08:52 UTC, yinonov commented on libs/components/src/lib/header/header.template.ts
> +	['elevated', elevated],
```suggestion
	['fixed', Boolean(fixed)],
	['alternate', Boolean(alternate)],
	['elevated', Boolean(elevated)],
```

2022-06-15 08:52 UTC, yinonov commented on libs/components/src/lib/header/header.ts
> +	@attr heading?: string;
is this defined / required by design?

2022-06-15 08:52 UTC, yinonov commented on libs/components/src/lib/header/header.ts
> +	 * applies scheme alternate region
```suggestion
	 * applies scheme alternate to header region
```

2022-06-15 08:52 UTC, yinonov commented on libs/components/src/lib/header/header.ts
> +		this._elevated = !this._elevated;
if not used in template then do `#elevated`

2022-06-15 08:52 UTC, yinonov commented on libs/components/src/lib/header/header.ts
> +		window.addEventListener('scroll', this.#updateElevatedState);
this type of code will not comply to an SSR practice in future plans.
not saying no as there might not be another option. but asking, is there another option that will not throw in node run time?

2022-06-15 08:52 UTC, yinonov commented on libs/components/src/lib/header/index.ts
> +export const vividheader = header.compose<FoundationElementDefinition>({
```suggestion
export const vividHeader = Header.compose<FoundationElementDefinition>({
```

2022-06-15 09:08 UTC, rachelbt commented on libs/components/src/lib/header/README.md
> +### Z-index
I think this should come before the usage examples

2022-06-22 09:12 UTC, rinaok commented on libs/components/src/lib/header/README.md
> +### Z-index
@yinonov Why z-index is not a good title?
Side-Drawer has this property: 

![Screen Shot 2022-06-22 at 12 10 42](https://user-images.githubusercontent.com/10883919/174991225-920a4264-7860-4710-9706-e8f64a7e3515.png)

2022-06-22 09:22 UTC, rinaok commented on libs/components/src/lib/header/header.ts
> +		this._elevated = !this._elevated;
@yinonov I can't make an `@observable ` to be a private member.

2022-06-22 09:24 UTC, rinaok commented on libs/components/src/lib/header/header.ts
> +	@attr heading?: string;
@yinonov Card, Note, Calendar and Accordion have this attribute so I think that it should be consistent.

2022-06-22 10:12 UTC, rinaok commented on libs/components/src/lib/header/header.ts
> +		window.addEventListener('scroll', this.#updateElevatedState);
@yinonov How can I debug it?

2022-06-22 10:33 UTC, yinonov commented on libs/components/src/lib/header/README.md
> +### Z-index
it's not bad, thought the suggestion is better but if doesn't ring right, resolve the comment

2022-06-22 10:40 UTC, yinonov commented on libs/components/src/lib/header/header.ts
> +	@attr heading?: string;
I think we should reconsider the way we define top text hierarchy. given that _heading_ should probably introduce an actual heading element (Hx) in template.

certain cases, like note, where Hx isn't wrapping the text, title might be a better member name

<img width="219" alt="image" src="https://user-images.githubusercontent.com/15140652/175009675-91fa1b81-3b99-45c5-a97d-33bb58c7330b.png">

@rachelbt FYI. should we open this up?

2022-06-22 10:44 UTC, yinonov commented on libs/components/src/lib/side-drawer/side-drawer.scss
> +			// }
no

2022-06-22 10:56 UTC, rinaok commented on libs/components/src/lib/header/header.ts
> +	@attr heading?: string;
@yinonov @rachelbt  Maybe you should create a new PR for that and change everything there.

2022-06-22 14:42 UTC, rinaok commented on libs/components/src/lib/header/ui.test.ts
> +	const template = extractHTMLBlocksFromReadme(
@YonatanKra But what can I check there? window's pageYOffset? I check it in the unit tests

2022-06-22 16:19 UTC, yinonov commented on libs/components/src/lib/header/header.ts
> +	@attr heading?: string;
https://github.com/Vonage/vivid-3/issues/480

2022-06-23 08:56 UTC, YonatanKra approved these changes

2022-06-23 12:12 UTC, merged