fix(documentation): documentation guidelines
Vonage/vivid-3 pull request #409
Opened 2022-05-26 14:26 UTC by rachelbt

2022-05-26 14:34 UTC, rinaok commented on docs/component-guidline.md
> +## Accessibility
Should accessibility be at the end?

2022-05-26 14:35 UTC, rinaok commented on docs/component-guidline.md
> +-
```suggestion
- App Content
```

2022-05-26 14:55 UTC, rachelbt commented on docs/component-guidline.md
> +## Use Cases
yes :)

2022-05-26 14:55 UTC, rachelbt commented on docs/component-guidline.md
> +-
I'm not sure app is the right terminology for our components

2022-05-26 15:09 UTC, yinonov commented on docs/component-guidline.md
> +### Density
we also have size in some components. both are used

2022-05-26 15:10 UTC, yinonov commented on docs/component-guidline.md
> +- Use `.control` for form control such as input, buttons ect.
```suggestion
- Use `.control` for the main form control such as input, buttons etc'.
```

2022-05-26 15:10 UTC, yinonov commented on docs/component-guidline.md
> +### Do:
title as _template guide_?

2022-05-26 15:11 UTC, yinonov commented on docs/component-guidline.md
> +- Use kebab case and if containing more than one word should use hyphen.
kebab case is hypenated

2022-05-26 15:12 UTC, yinonov commented on docs/component-guidline.md
> +### Do:
add a point of how to call our class. we have _vivid{Component}_ and _VIVID{Component}_

2022-05-26 15:13 UTC, yinonov commented on docs/component-guidline.md
> +- no need for the component name in the classes
what?

2022-05-26 15:14 UTC, yinonov commented on docs/component-guidline.md
> +- `Graphic`
explain this as well. it sound similar to media

2022-05-26 15:16 UTC, yinonov commented on docs/component-guidline.md
> +-
app content is correct only in 2 places I can think of. side-drawer & top-app-bar. these are categorized as templating components

2022-05-26 15:16 UTC, yinonov commented on docs/component-guidline.md
> +One summery line
```suggestion
One summary line
```

2022-05-26 15:24 UTC, rachelbt commented
> excellent idea!

It was @rinaok idea :)

2022-05-29 07:18 UTC, rachelbt commented on docs/component-guidline.md
> +### Density
size is only in Icons.

2022-05-29 07:33 UTC, rachelbt commented on docs/component-guidline.md
> +- `Content` - should we chang to default?
opened a [separate issue](https://github.com/Vonage/vivid-3/issues/414) for that

2022-05-29 08:32 UTC, yinonov commented on docs/component-guidline.md
> +- `App-content` :for slots in components that categorized as templating components (such as side-drawer, top-app-bar)
```suggestion
- `App-content`: for slots in components that categorized as templating components (such as side-drawer, top-app-bar)
```

2022-05-29 08:33 UTC, yinonov commented on docs/component-guidline.md
> +- `Graphic` :for slots that are recommended for decorative element such as custom icon or image
```suggestion
- `Graphic` - for slots that are recommended for decorative element such as custom icon or image
```

2022-05-29 08:33 UTC, yinonov commented on docs/component-guidline.md
> +- `Media` :for slot that are recommended to contain either images or video.
```suggestion
- `Media` - for slot that are recommended to contain either images or video.
```

2022-05-29 08:35 UTC, yinonov commented on docs/component-guidline.md
> +- `Footer`
```suggestion
- `Footer` / `actions`
```

2022-05-29 09:40 UTC, rachelbt commented on docs/component-guidline.md
> +- no need for the component name in the classes
fixed

2022-06-08 10:11 UTC, rinaok submitted a review, later dismissed

2022-06-08 10:52 UTC, yinonov commented on docs/component-guidline.md
> +
```suggestion

https://github.com/Vonage/vivid-3/blob/95df74b6284f28cbf4a31279db28d2a40fbc151e/apps/docs/transformers/code-block-demo/layout.js#L7-L11
```

2022-06-08 10:55 UTC, yinonov commented on docs/component-guidline.md
> +- blocks
```suggestion
- full
- blocks
- columns
- inline (default)
- center
```

2022-06-08 10:55 UTC, yinonov commented on docs/component-guidline.md
> +https://github.com/Vonage/vivid-3/blob/95df74b6284f28cbf4a31279db28d2a40fbc151e/apps/docs/transformers/code-block-demo/layout.js#L7-L11
```suggestion
```

2022-06-08 10:58 UTC, yinonov commented on docs/component-guidline.md
> +
```suggestion
e.g.
````
```html preview blocks
<!-- content goes here -->
```
````

2022-06-08 11:09 UTC, yinonov requested changes

2022-06-08 11:09 UTC, yinonov commented on docs/component-guidline.md
> +- `.demo-gradient`
I dont think these belong in a docs. the practice of including it should be changed

2022-06-08 11:25 UTC, yinonov requested changes

2022-06-08 11:25 UTC, yinonov commented on docs/component-guidline.md
> +- `action-ites / action-items` - ?
?

2022-06-08 11:25 UTC, yinonov commented on docs/component-guidline.md
> +- `App-content` - Maybe change it to `app-main` for slots in components that categorized as templating components (such as side-drawer, top-app-bar).
this apply to only top-bar and side-drawer. let's change to `main` alone?

2022-06-08 11:25 UTC, yinonov commented on docs/component-guidline.md
> +- `media` - for slot that are recommended to contain either images or video.
```suggestion
- `media` - for a slot bound to contain visual elements; such as an illustration, video etc'.
```

2022-06-08 11:25 UTC, yinonov commented on docs/component-guidline.md
> +- `graphic` - for slots that are recommended for decorative element such as custom icon or image
```suggestion
- `graphic` - for a slot bound to contain a decorative figure; such as a custom icon or image
```

2022-06-08 11:25 UTC, yinonov commented on docs/component-guidline.md
> +- `content`
remove in favor of main?

2022-06-08 11:25 UTC, yinonov commented on docs/component-guidline.md
> +## properties
consider?
```suggestion
## Members (properties / attributes)
```

2022-06-08 11:25 UTC, yinonov commented on docs/component-guidline.md
> +lorem ipsum
```suggestion

`{{ description }}`

- type: `{{ type }}`
- default: `{{ default }}`
lorem ipsum
```

2022-06-08 17:00 UTC, rachelbt commented on docs/component-guidline.md
> +## Accessibility
its not at the end - its the first issue to come after all the API members (properties, slots, css variables)

2022-06-12 06:08 UTC, yinonov requested changes

2022-06-12 06:08 UTC, yinonov commented on docs/component-guidline.md
> +### CSS Class Names
The following headers should be grouped under **Terminology**

2022-06-15 09:58 UTC, yinonov commented on docs/component-guidline.md
> +- `App-content` - Maybe change it to `app-main` for slots in components that categorized as templating components (such as side-drawer, top-app-bar).
yeah

2022-06-15 10:02 UTC, rachelbt commented on docs/component-guidline.md
> +### CSS Class Names
you mean another sub-title? or instead of _CSS Class Names_?

2022-06-15 18:16 UTC, yinonov commented on docs/component-guidline.md
> +- `.demo-gradient`
and extracted to code fence attributes (as we did recently)

2022-06-20 07:09 UTC, rachelbt commented on docs/component-guidline.md
> +- `action-ites / action-items` - ?
typo 😆

2022-06-20 20:10 UTC, yinonov approved these changes

2022-06-21 08:52 UTC, merged