fix (card): change content slot to default
Vonage/vivid-3 pull request #418
Opened 2022-05-29 13:38 UTC by rachelbt

2022-05-30 20:24 UTC, yinonov requested changes

2022-05-30 20:24 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +<div slot="default">If you need different structure - use this slot</div>
default slot just picks any nested content which doesn't have a named slot attribute
```suggestion
<div>If you need different structure - use this slot</div>
```

2022-05-30 20:24 UTC, yinonov commented on libs/components/src/lib/card/card.template.ts
> +					<slot name="default">
```suggestion
					<slot>
```

2022-05-31 08:46 UTC, yinonov requested changes

2022-05-31 08:46 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +<div style="inline-size: 300px;">
still needed?

2022-05-31 08:46 UTC, yinonov commented on libs/components/src/lib/card/README.md
>  <vwc-card heading="Card with Media" text="here is the card text">
try to keep formatting (indentation) clear for readers

2022-06-01 11:09 UTC, yinonov requested changes

2022-06-01 11:09 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +main slot is for overriding the content structure of the main card area.
maybe elaborate on why. we have our opinionated style which can sometimes require overriding etc'.

2022-06-01 11:11 UTC, yinonov commented on libs/components/src/lib/card/ui.test.ts
> +const components = ['card', 'button', 'layout'];
where do we use layout?

2022-06-02 11:45 UTC, yinonov requested changes

2022-06-02 11:45 UTC, yinonov commented on libs/components/src/lib/card/ui.test.ts
> +const components = ['card', 'button', 'layout'];
I'm importing layout in the base file now

2022-06-06 15:24 UTC, yinonov requested changes

2022-06-08 09:16 UTC, rachelbt commented on libs/components/src/lib/card/README.md
> +  <vwc-layout slot="main">
why should we add that?

2022-06-12 10:39 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +  <vwc-layout slot="main">
then why are you using layout if it applies no style?

2022-06-12 11:03 UTC, rachelbt commented on libs/components/src/lib/card/README.md
> +  <vwc-layout slot="main">
there was vwc-text margin so I didn't notice this is needed :woman-facepalming

2022-06-12 11:08 UTC, yinonov submitted a review, later dismissed

2022-06-12 12:55 UTC, yinonov approved these changes

2022-06-12 13:00 UTC, merged