chore(scripts): add scripts
Vonage/vivid-3 pull request #426
Opened 2022-05-31 17:57 UTC by rinaok

2022-06-01 15:29 UTC, yinonov reviewed
@YonatanKra objected this. lets hear is word on this

2022-06-06 07:06 UTC, YonatanKra commented
I don't mind actually. If it helps most then we can go for it.

2022-06-06 07:07 UTC, YonatanKra requested changes

2022-06-06 07:07 UTC, YonatanKra commented on package.json
> +    "build": "npx nx build docs && npx nx build components",
I think components should be built first

2022-06-06 07:23 UTC, rinaok commented on package.json
> +    "build": "npx nx build docs && npx nx build components",
@YonatanKra updated

2022-06-06 07:29 UTC, yinonov commented on package.json
> +    "build": "npx nx build docs && npx nx build components",
but why the redundancy? doesn't doc build components? it slows things down

2022-06-06 10:30 UTC, YonatanKra commented on package.json
> +    "build": "npx nx build docs && npx nx build components",
I think so. That's why these commands are redundant :)
I mean - what does this save you? Not much.
`npx nx build docs` => `npm run build`
Less declarative and and less `monorepo-ish` cause we have several builds. So what are you building? The components? the docs? the react demo app? the angular demo app?
The only thing I can agree upon is the `change` command which can be really annoying :)

2022-06-06 10:55 UTC, rinaok commented on package.json
> +    "build": "npx nx build docs && npx nx build components",
I don't mind about the build but `npm start` vs `npx nx run docs:serve` saves me a lot.

2022-06-06 11:04 UTC, YonatanKra commented on package.json
> +    "build": "npx nx build docs && npx nx build components",
@rinaok - ok, so let's remove the `build` command as it is redundant and leave `npm start` as an alias to the `docs:serve` command.
And another thing - if you are running commands from an `npm script` you don't need `npx` - just run `nx run docs:serve` and it'll work.
`npx` is when you are running from command line and unsure if you have the target library installed.

2022-06-06 11:16 UTC, rinaok commented on package.json
> +    "build": "npx nx build docs && npx nx build components",
@YonatanKra removed the build

2022-06-09 06:45 UTC, YonatanKra approved these changes

2022-06-09 07:06 UTC, merged