docs(components): refine side-drawer page
Vonage/vivid-3 pull request #428
Opened 2022-06-01 15:54 UTC by rinaok

2022-06-02 05:38 UTC, rachelbt reviewed
LGTM
I'm just wondering wether we should wrap the "app-content" in code preview with layout for spacing or it will make the code snippet bloated.
WDYT?

2022-06-02 05:38 UTC, rachelbt commented on libs/components/src/lib/side-drawer/README.md
> +## Properties
🦾

2022-06-02 11:24 UTC, rinaok commented on libs/components/src/lib/side-drawer/README.md
> +## Properties
@rachelbt Added layout

2022-06-03 07:07 UTC, yinonov requested changes

2022-06-03 07:07 UTC, yinonov commented on apps/docs/_data/components.json
> +      "/assets/modules/components/layout/index.js"
you don't use layout explicitly in your doc. no reason to import it here

2022-06-03 07:07 UTC, yinonov commented on apps/docs/_data/components.json
>        "/assets/modules/components/icon/index.js",
you don't use icon explicitly in your docs. button already side-effect-imports it

2022-06-06 06:22 UTC, rinaok commented on apps/docs/_data/components.json
> +      "/assets/modules/components/layout/index.js"
@yinonov I'm using layout

2022-06-06 06:25 UTC, rinaok commented on apps/docs/_data/components.json
>        "/assets/modules/components/icon/index.js",
@yinonov removed

2022-06-06 07:25 UTC, yinonov commented on apps/docs/_data/components.json
> +      "/assets/modules/components/layout/index.js"
where?

2022-06-06 10:57 UTC, rinaok commented on apps/docs/_data/components.json
> +      "/assets/modules/components/layout/index.js"
@yinonov inside the side-drawer, see @rachelbt's comment: https://github.com/Vonage/vivid-3/pull/428#pullrequestreview-993012153

2022-06-07 10:56 UTC, rachelbt reviewed
I think you need to update the ui png's

2022-06-07 10:56 UTC, rachelbt commented on libs/components/src/lib/side-drawer/README.md
the Top Bar should be:
### Top-Bar

2022-06-08 13:53 UTC, merged