chore(workspace): fix deploy even with bump failure
Vonage/vivid-3 pull request #433
Opened 2022-06-06 13:19 UTC by YonatanKra

2022-06-06 13:43 UTC, yinonov requested changes
it wont hurt but what's the reason behind "always deploy"

2022-06-06 13:43 UTC, yinonov commented on .github/workflows/pull-request.yml
> +          npx beachball bump -m "Publishing a new version" --no-push -y > tmp.txt
does this actually commit?

2022-06-06 13:48 UTC, YonatanKra commented on .github/workflows/pull-request.yml
> +          npx beachball bump -m "Publishing a new version" --no-push -y > tmp.txt
Don't look at it - I'm testing now. The PR file changes will be reverted.

2022-06-07 07:56 UTC, yinonov approved these changes

2022-06-07 10:45 UTC, merged