fix(layout): docs
Vonage/vivid-3 pull request #434
Opened 2022-06-07 11:27 UTC by rinaok

2022-06-08 11:16 UTC, yinonov requested changes
as mentioned before, I believe the gradient div & class doesn't belong inside the exposed doc.

in the future we should enable that from another preview attribute

2022-06-08 11:16 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +  }
is this required?

2022-06-08 11:16 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +  }
is this required?

2022-06-08 11:16 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +  }
is this required?

2022-06-08 11:16 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +  }
is this required?

2022-06-08 11:16 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +  }
is this required?

2022-06-08 11:16 UTC, yinonov commented on libs/components/src/lib/layout/README.md
>      <vwc-card elevation="2" text="default"></vwc-card>
adding redundant members, such as elevation here, only affect the looks and beautifies the docs but functionality-wise it reduces the readability and dev experience

2022-06-08 11:53 UTC, rinaok commented on libs/components/src/lib/layout/README.md
> +  }
@yinonov yes, it doesn't look good without it

2022-06-08 12:23 UTC, rachelbt commented on libs/components/src/lib/layout/README.md
>      <vwc-card elevation="2" text="default"></vwc-card>
it's not elevation its card inside layout. 
There's no need for layout if there are no components inside it :)

2022-06-08 13:54 UTC, rinaok commented on libs/components/src/lib/layout/README.md
>      <vwc-card elevation="2" text="default"></vwc-card>
@yinonov  It was a div before and you requested that it be changed to a card component.

2022-06-13 12:22 UTC, rinaok commented on libs/components/src/lib/layout/README.md
> +  }
@yinonov yes, it doesn't look good without it

2022-06-13 12:22 UTC, rinaok commented on libs/components/src/lib/layout/README.md
> +  }
@yinonov yes, it doesn't look good without it

2022-06-13 12:23 UTC, rinaok commented on libs/components/src/lib/layout/README.md
> +  }
@yinonov yes, it doesn't look good without it

2022-06-13 20:21 UTC, yinonov commented on libs/components/src/lib/layout/README.md
> +  }
I don't get it. why we need to apply size to html here?

2022-06-14 08:53 UTC, rinaok commented on libs/components/src/lib/layout/README.md
> +  }
@yinonov What would be a better solution?

2022-06-14 09:08 UTC, rinaok commented on libs/components/src/lib/layout/README.md
> +  }
![Screen Shot 2022-06-14 at 12 08 49](https://user-images.githubusercontent.com/10883919/173539883-179b0068-8d9f-4fe1-8dab-cf4507b2b0d8.png)

2022-06-14 09:09 UTC, rinaok commented on libs/components/src/lib/layout/README.md
> +  }
![Screen Shot 2022-06-14 at 12 09 13](https://user-images.githubusercontent.com/10883919/173539958-bc5df21e-0090-4d21-8ecb-158b341aab02.png)

2022-06-14 09:09 UTC, rinaok commented on libs/components/src/lib/layout/README.md
> +  }
![Screen Shot 2022-06-14 at 12 09 30](https://user-images.githubusercontent.com/10883919/173540013-94fef748-46ac-42d2-8354-db25931c841d.png)

2022-06-14 09:09 UTC, rinaok commented on libs/components/src/lib/layout/README.md
> +  }
![Screen Shot 2022-06-14 at 12 09 50](https://user-images.githubusercontent.com/10883919/173540097-5caae0b0-0d7e-4d10-a751-08ea5f26a6e2.png)

2022-06-14 09:39 UTC, closed without merging