fix(action-group): refine tests
Vonage/vivid-3 pull request #444
Opened 2022-06-09 06:01 UTC by rachelbt

2022-06-09 06:43 UTC, YonatanKra requested changes

2022-06-09 06:43 UTC, YonatanKra commented on libs/components/src/lib/action-group/action-group.spec.ts
> +		it('should set the appearance-fieldset or ghost class on the base', async function () {
What is `ghost` doing here? Is it a different use case?

2022-06-09 08:32 UTC, rachelbt commented on libs/components/src/lib/action-group/action-group.spec.ts
> +		it('should set the appearance-fieldset or ghost class on the base', async function () {
can't we just check weather theres an appearance class?
fieldset & ghost are classes related to appearance.
Same for shape - it can be either none defined - than it is rounded and can be set to pill

2022-06-10 10:40 UTC, YonatanKra commented on libs/components/src/lib/action-group/action-group.spec.ts
> +		it('should set the appearance-fieldset or ghost class on the base', async function () {
The unit test shouldn't care about appearance values. That's our concern. The logic is to just reflect the value in the class (see example [here](https://github.com/Vonage/vivid-3/blob/main/libs/components/src/lib/banner/banner.spec.ts#L214)).

2022-06-12 09:11 UTC, rachelbt commented on libs/components/src/lib/action-group/action-group.spec.ts
> +		it('should set the appearance-fieldset or ghost class on the base', async function () {
so the test it OK but the description should be: 
`should set the appearance class on the base`
?

2022-06-12 09:17 UTC, YonatanKra commented on libs/components/src/lib/action-group/action-group.spec.ts
> +		it('should set the appearance-fieldset or ghost class on the base', async function () {
Yeap!

2022-06-13 15:12 UTC, YonatanKra approved these changes

2022-06-14 07:31 UTC, merged