fix(text-field): make sure validation is not eager
Vonage/vivid-3 pull request #454
Opened 2022-06-10 05:41 UTC by YonatanKra

2022-06-11 17:53 UTC, yinonov commented on libs/components/src/lib/calendar-event/ui.test.ts
> +test('should show the component', async ({ page }: { page: Page }) => {
sorry 😬

2022-06-11 18:06 UTC, yinonov requested changes

2022-06-11 18:06 UTC, yinonov commented on libs/components/src/lib/text-field/text-field.ts
> +			this.userValid = (this.#blurred && this.dirtyValue) ? !this.validationMessage : true;
this assigns it wrong according to https://developer.mozilla.org/en-US/docs/web/css/:user-valid.
I think the composite condition should be assigned to a `reflectInvalid` flag instead

2022-06-14 09:30 UTC, YonatanKra commented on libs/components/src/lib/text-field/text-field.ts
> +			this.userValid = (this.#blurred && this.dirtyValue) ? !this.validationMessage : true;
@yinonov - this actually follows the `user-valid` spec as we discussed.

2022-06-19 06:24 UTC, yinonov commented on libs/components/src/lib/text-field/text-field.ts
> +			this.userValid = (this.#blurred && this.dirtyValue) ? !this.validationMessage : true;
yes we discussed it after this comment. resolving

2022-06-19 06:26 UTC, yinonov commented on libs/components/src/lib/text-field/text-field.spec.ts
> +		it('should add class error to base if invalid', async function () {
maybe the intent is wrong. maybe it should be adding `user-not-valid` class to be completely correct

2022-06-19 06:26 UTC, yinonov commented on libs/components/src/lib/text-field/text-field.spec.ts
> +		it('should add class error to base if invalid', async function () {
notice it is `not-valid` rather than `invalid`

2022-06-22 14:39 UTC, YonatanKra commented on libs/components/src/lib/text-field/text-field.spec.ts
> +		it('should add class error to base if invalid', async function () {
@yinonov 
Looked a bit deeper.
Do we really need the `user-not-valid` class?
We already have the semantic `error` error class that speaks our css design system language.

2022-06-28 11:38 UTC, merged