480-reassess-top-text-terminology-according-to-context
Vonage/vivid-3 pull request #484
Opened 2022-06-22 19:56 UTC by yinonov

2022-07-05 06:08 UTC, yinonov reviewed
is this still WIP? the PR title somewhat differs from the change file title

2022-07-05 06:09 UTC, yinonov reviewed
@rachelbt card and note are the only affected components?

2022-07-18 06:08 UTC, YonatanKra requested changes
@rinaok - it seems like you've deleted the `contributing` and `ui-tests` docs in this PR. Have you moved them someplace else?

2022-07-18 06:08 UTC, YonatanKra commented on README.md
> +#### Generator a new component
```suggestion
#### Generate a new component
```

2022-07-18 08:57 UTC, rinaok commented
> @rinaok - it seems like you've deleted the `contributing` and `ui-tests` docs in this PR. Have you moved them someplace else?

@YonatanKra Deleted by mistake

2022-07-18 09:43 UTC, rachelbt commented
> > @rinaok - it seems like you've deleted the `contributing` and `ui-tests` docs in this PR. Have you moved them someplace else?
> 
> @YonatanKra Deleted by mistake

I added them back :)

2022-07-19 08:59 UTC, rinaok approved these changes

2022-07-19 09:18 UTC, merged