[sidenav] new component
Vonage/vivid-3 pull request #495
Opened 2022-06-27 08:14 UTC by rinaok

2022-06-27 12:19 UTC, yinonov requested changes

2022-06-27 12:19 UTC, yinonov commented on libs/components/src/lib/sidenav/README.md
> +
what?

2022-06-27 12:19 UTC, yinonov commented on libs/components/src/lib/sidenav/README.md
> +# sidenav
```suggestion
# Side Navigation
```

2022-06-27 12:19 UTC, yinonov commented on libs/components/src/lib/sidenav/README.md
> +### SideNavHeading
maybe this belongs to future side navigation heading page

2022-06-27 12:19 UTC, yinonov commented on libs/components/src/lib/sidenav/README.md
> +### SideNavItem
fix all headings to readable titles?
```suggestion
### Side Navigation Item
```

2022-06-27 12:19 UTC, yinonov commented on libs/components/src/lib/sidenav/README.md
> +### SideNavItem
but this belongs to side navigation page. have a look at calendar and calendar event

2022-06-27 12:19 UTC, yinonov commented on libs/components/src/lib/sidenav/README.md
> +
I think this should describe what the custom element is. as in other elements docs. and what it adds semantically

2022-06-29 15:00 UTC, yinonov reviewed
Maybe break sidenav and sidenav disclosure to 2 different PRs?

2022-06-29 15:19 UTC, rinaok commented
> Maybe break sidenav and sidenav disclosure to 2 different PRs?

ok

2022-07-03 21:16 UTC, yinonov commented on change/@vonage-vivid-eb2e0c3d-1467-441c-a29f-6d551407e326.json
> +  "dependentChangeType": "none"
it's a prerelease. comment can be more explanatory

2022-07-03 21:18 UTC, yinonov commented on libs/components/src/lib/sidenav-item/sidenav-item.ts
> +export interface SidenavItem extends AffixIcon { }
lint? 🤔

2022-07-03 21:18 UTC, yinonov requested changes

2022-07-03 21:18 UTC, yinonov commented on apps/docs/_data/components.json
> +      "/assets/modules/components/text/index.js"
why the text?

2022-07-05 06:11 UTC, yinonov requested changes

2022-07-05 06:11 UTC, yinonov commented on apps/docs/_data/components.json
> +      "/assets/modules/components/text/index.js"
why text?

2022-07-05 06:15 UTC, yinonov requested changes

2022-07-05 06:15 UTC, yinonov commented on libs/components/src/lib/sidenav/README.md
> +Represents a sidenav custom element.
```suggestion
Represents a side navigation custom element.
```

2022-07-05 06:15 UTC, yinonov commented on libs/components/src/lib/sidenav/README.md
> +    <vwc-sidenav-item href="#" text="lorem ipsum"></vwc-sidenav-item>
can u adjust ur workspace to apply indentation tab by 2? not sure why we our lint doesn't operate on that

2022-07-05 06:15 UTC, yinonov commented on libs/components/src/lib/sidenav/sidenav.spec.ts
> +
maybe we should have a11y automated test. include items in sidenav.
see in calendar

2022-07-07 19:50 UTC, yinonov approved these changes

2022-07-07 19:55 UTC, yinonov submitted a review, later dismissed

2022-07-07 19:57 UTC, yinonov approved these changes

2022-07-07 21:30 UTC, merged