docs(side-drawer): add an example with the header component
Vonage/vivid-3 pull request #497
Opened 2022-06-27 09:48 UTC by rinaok

2022-06-27 10:59 UTC, rachelbt reviewed
- the links in both readme doesn't work.
- There's something strange in the background of the code preview when scrolling - half is transparent and half has white bg.

2022-06-27 10:59 UTC, rachelbt commented on libs/components/src/lib/side-drawer/README.md
> +### Side-drawer wrapping a [Header](../header)
I know this is the correct hierarchy but the text looks really big :(

2022-06-27 11:02 UTC, rinaok commented
> * the links in both readme doesn't work.
> * There's something strange in the background of the code preview when scrolling - half is transparent and half has white bg:
>   ![image](https://user-images.githubusercontent.com/7512792/175926635-966eda31-2f5f-40ab-9a11-ffb01d439534.png)

@rachelbt The links work in localhost, so it's strange.

2022-06-27 11:03 UTC, yinonov commented on libs/components/src/lib/side-drawer/README.md
> +### Side-drawer wrapping a [Header](../header)
what do u suggest? keeping the text short? or resizing the font size?

2022-06-27 12:07 UTC, yinonov commented
@AyalaBu u might wanna join in the review

2022-06-28 08:31 UTC, rinaok commented on apps/docs/assets/styles/main.css
> +  height: 100%;
@yinonov It fixed the mobile view issue. Send me a screenshot if you see any other issues.

2022-06-28 09:07 UTC, yinonov requested changes
part of the aside body in now hidden. notice the design system heading is not shown
<img width="324" alt="image" src="https://user-images.githubusercontent.com/15140652/176140356-cea19eee-0970-4950-a7db-ca0a1f9547ce.png">

2022-06-28 09:43 UTC, rinaok commented
> part of the aside body in now hidden. notice the design system heading is not shown <img alt="image" width="324" src="https://user-images.githubusercontent.com/15140652/176140356-cea19eee-0970-4950-a7db-ca0a1f9547ce.png">

@yinonov changed it to be: calc(100% - 64px)

2022-06-28 09:44 UTC, rinaok commented on apps/docs/assets/styles/main.css
> +  height: 100%;
@yinonov changed it to: `height: calc(100% - 64px)`

2022-06-28 11:14 UTC, yinonov requested changes

2022-06-28 13:49 UTC, rinaok commented on libs/components/src/lib/header/README.md
> +### Header wrapping a [Side-drawer](../../components/side-drawer)
@yinonov  This is the title? `Header as Primary`

2022-07-08 15:21 UTC, yinonov commented
think this should be closed considering #502?

2022-07-10 08:07 UTC, closed without merging