refactor(sidenav-disclosure): add new component
Vonage/vivid-3 pull request #503
Opened 2022-06-30 09:44 UTC by rinaok

2022-06-30 16:13 UTC, yinonov reviewed
looking great!

that's how the a11y tree look
<img width="466" alt="image" src="https://user-images.githubusercontent.com/15140652/176726474-4bfeb4e3-dc68-4d5d-a693-0070de130c6a.png">

honestly this doesn't violate anything as far as I can tell, but there should be some research on whether this is a good UX. can we extract some data? ask around? see other implementations? go over it with SR?

2022-06-30 16:15 UTC, yinonov commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.template.ts
> +        <summary class="${getClasses}"
noticed the exact style as _sidenav-item_ is now set on this summary tag. was it a small chunk of style? since we already have that same style on sidenav-item, do we want to extract a pattern here?

2022-07-03 12:32 UTC, rinaok commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.template.ts
> +        <summary class="${getClasses}"
@yinonov It's the same style cause the first item (the button) should look and feel the same as it's children (the sidenav-items). I copied it from sidenav-item's control class. It is the same style in two components, do you think it's something worth to extract?

2022-07-03 21:21 UTC, yinonov commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.template.ts
> +        <summary class="${getClasses}"
yes, I think this could be used in options, list items etc'.

2022-07-07 14:37 UTC, rinaok commented
> looking great!
> 
> that's how the a11y tree look <img alt="image" width="466" src="https://user-images.githubusercontent.com/15140652/176726474-4bfeb4e3-dc68-4d5d-a693-0070de130c6a.png">
> 
> honestly this doesn't violate anything as far as I can tell, but there should be some research on whether this is a good UX. can we extract some data? ask around? see other implementations? go over it with SR?

@yinonov 

All the sidenavs I've found use lists as their implementation of this. Even [Fast](https://github.com/microsoft/fast/blob/5b313a3262b977acbee3c2efac87d0d14a82f792/sites/fast-website/src/app/components/side-navigation/side-navigation.template.ts). 
As far as I can tell, I haven't found a single example with summary and details.

In other design systems, summary details are simply a component but they don't use it inside other components.

2022-07-12 14:46 UTC, yinonov requested changes

2022-07-12 14:46 UTC, yinonov commented on libs/components/src/lib/sidenav-disclosure/README.md
> +</vwc-sidenav-disclosure>
there's so much noise here. plainly focus on showing the label

2022-07-12 14:46 UTC, yinonov commented on libs/components/src/lib/sidenav-disclosure/README.md
> +</vwc-sidenav-disclosure>
same goes for the rest of the sections

2022-07-12 14:46 UTC, yinonov commented on libs/components/src/lib/sidenav-disclosure/index.ts
> +import { Disclosure } from './sidenav-disclosure';
```suggestion
import { SidenavDisclosure } from './sidenav-disclosure';
```

2022-07-12 14:46 UTC, yinonov commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.template.ts
> +            <slot name="start">${x => affixIconTemplate(x.icon)}</slot>
we don't want to allow this

2022-07-12 14:46 UTC, yinonov commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.template.ts
> +            <slot name="end">
or this

2022-07-12 14:46 UTC, yinonov commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.ts
> +export class Disclosure extends FoundationDisclosure {
```suggestion
export class SidenavDisclosure extends FoundationDisclosure {
```

2022-07-12 14:46 UTC, yinonov commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.ts
> +export class Disclosure extends FoundationDisclosure {
I dont think we need to extend foundation disclosure. it adds nothing as it rely itself on html disclosure

2022-07-14 07:14 UTC, rachelbt reviewed
looks good :)
Maybe we can consider adding animation for the open close details content.
https://css-tricks.com/how-to-animate-the-details-element/
There are sone only-css options in the comments.
Maybe its for a separate PR...

2022-07-14 07:14 UTC, rachelbt commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.scss
> +		right: 16px;
why absolute? Its parent is flex- we can set it to be on the right like this:
```suggestion
		margin-inline-start: auto;
```

2022-07-14 07:14 UTC, rachelbt commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.scss
> +	position: relative;
```suggestion

```
if we remove the position absolute for the chevron we don't need this

2022-07-14 07:14 UTC, rachelbt commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.scss
> +	display: inline-flex;
```suggestion
	display: flex;
```

2022-07-14 07:14 UTC, rachelbt commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.scss
> +	padding-block: 10px;
```suggestion

```
I'm not sure this is needed because we are setting height to the row and aligning its children to be centered

2022-07-14 07:14 UTC, rachelbt commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.scss
> +	}
```suggestion

```
this one is linked to nothing so has no effect on nothing. I don't think it is needed at all.

2022-07-14 08:43 UTC, rachelbt commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.scss
> +		right: 16px;
I don't see a chevron there...

2022-07-14 09:51 UTC, rinaok commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.scss
> +		right: 16px;
@rachelbt Right, not the chevron but all your other comments

2022-07-14 10:14 UTC, rinaok commented
> looks good :) Maybe we can consider adding animation for the open close details content. https://css-tricks.com/how-to-animate-the-details-element/ There are sone only-css options in the comments. Maybe its for a separate PR...

@yinonov Said that we can add it later

2022-07-14 11:10 UTC, rinaok commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.scss
> +	position: relative;
@rachelbt When I removed it, the focus became on the details tag rather than the summary tag.

2022-07-14 11:11 UTC, rinaok commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.scss
> +	position: relative;
![Screen Shot 2022-07-14 at 14 11 49](https://user-images.githubusercontent.com/10883919/178969880-5112547a-c0fd-40b6-810a-3bed8d21fcb8.png)

2022-07-17 10:41 UTC, YonatanKra requested changes

2022-07-17 10:41 UTC, YonatanKra commented on change/@vonage-vivid-7799b301-8f1d-4b08-8bef-001a8cbd785c.json
> +  "type": "none",
It is a `prerelease` as it adds a new component/feature.

2022-07-17 10:41 UTC, YonatanKra commented on libs/components/src/lib/sidenav-disclosure/README.md
> +## Members
I'm missing real-life examples using the side-nav with content. Can you add one?
In addition, this cool little component works with indefinite levels - so one can create a nested nav system:
```
<vwc-sidenav>
    <vwc-sidenav-disclosure label="1st level item">
<vwc-sidenav-disclosure label="Thirst level item">
        <vwc-sidenav-item href="#" text="2nd level item"></vwc-sidenav-item>
 </vwc-sidenav-disclosure>
    </vwc-sidenav-disclosure>
<vwc-sidenav>
</vwc-sidenav></vwc-sidenav>
```
 is that a use case? @jshenkman ?

2022-07-17 10:41 UTC, YonatanKra commented on libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.spec.ts
> +			expect(getBaseElement(element).attributes.getNamedItem('open')).toBeFalsy();
Is this the same as writing:
`getBaseElement(element).hasAttribute('open')`?
If so, we should apply the simpler code in favor of the more complex one.
Also apply to rest of the code.

2022-07-17 11:22 UTC, rinaok commented on libs/components/src/lib/sidenav-disclosure/README.md
> +## Members
@YonatanKra There were real-life examples of nested sidenavs. However, Yinon prefers examples with few contents. The sidenav readme includes an example of this.

2022-07-17 12:02 UTC, YonatanKra approved these changes
LGTM

2022-07-17 12:07 UTC, merged