feat(dialog): migrate the dialog component
Vonage/vivid-3 pull request #505
Opened 2022-06-30 12:40 UTC by YonatanKra

2022-06-30 15:55 UTC, yinonov requested changes

2022-06-30 15:55 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +```html preview
use this practice to control the iframe block size
https://github.com/Vonage/vivid-3/blob/6661b5639a9aa553758c1359fce94b531442056b/libs/components/src/lib/header/README.md#L19-L23

2022-06-30 15:55 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.template.ts
> +		<vwc-text font-face="subtitle-2" class="heading">
within components it's better to address typography by css only
text component have issues anyway and might be discouraged
see #507

2022-06-30 15:55 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.ts
> +	@attr({mode: 'boolean'}) stacked = false;
what's that about?

2022-06-30 15:55 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.ts
> +	@attr({attribute: 'return-value'}) returnValue?: string;
is that by native spec?

2022-06-30 15:55 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.ts
> +	@attr heading?: string;
remember to keep it close to card practice with props and wrapping main slot.
I'd dare an say it's even a pattern now

2022-06-30 15:55 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.ts
> +		this.dispatchEvent(new CustomEvent('close', {bubbles: true, composed: true, detail: this.returnValue}));
we wanna prefix that event name? maybe we can have a shared file that holds all event consts...

2022-06-30 15:58 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.ts
> +	@attr({mode: 'boolean'}) stacked = false;
See Figma - footer has stacked and non stacked forms

2022-06-30 15:58 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.ts
> +	@attr({attribute: 'return-value'}) returnValue?: string;
Yes

2022-06-30 17:14 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.ts
> +		this.dispatchEvent(new CustomEvent('close', {bubbles: true, composed: true, detail: this.returnValue}));
so `vwc:dialog:close`? Or just `vwc:close`?

2022-07-05 08:42 UTC, yinonov requested changes

2022-07-05 08:42 UTC, yinonov commented on change/@vonage-vivid-86f6e2a8-1642-47c7-a3d5-ec0ba3e525a9.json
> +  "comment": "Add the dialog component",
```suggestion
  "comment": "Migrate dialog component to fast",
```

2022-07-05 08:49 UTC, yinonov requested changes

2022-07-05 08:49 UTC, yinonov commented on libs/components/src/lib/header/header.ts
>  	/**
better to revert any change to header as a big PR is on the way. don't need this to conflict

2022-07-05 08:49 UTC, yinonov commented on libs/components/src/lib/text-field/text-field.spec.ts
> +		 */
revert?
```suggestion
```

2022-07-05 08:49 UTC, yinonov commented on libs/components/src/types/style.d.ts
> +
where did u encounter such import problem? are u using import css assert?

2022-07-05 08:49 UTC, yinonov commented on libs/components/tsconfig.json
> +    "module": "ESNext",
relates to dialog?

2022-07-05 11:12 UTC, YonatanKra commented on libs/components/src/types/style.d.ts
> +
Yes - importing the polyfill `css`.

2022-07-05 11:12 UTC, YonatanKra commented on libs/components/tsconfig.json
> +    "module": "ESNext",
No. Just bumping it up and everything works :)

2022-07-05 11:13 UTC, YonatanKra commented on package.json
> +    "dialog-polyfill": "^0.5.6",
Support for Safari 14

2022-07-06 21:18 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +.demo-footer {
adding the following will affect the iframe height
```css
html {
  block-size: 200px;
}
```

2022-07-07 07:00 UTC, yinonov requested changes

2022-07-07 07:00 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +### returnValue
```suggestion
### Return Value
```

2022-07-07 07:00 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +### open
```suggestion
### Open
```

2022-07-07 07:00 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +### show
```suggestion

### Show
```

2022-07-07 07:00 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +### showModal
```suggestion
### Show Modal
```

2022-07-07 07:00 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +### showModal
our convention is to title nicely and include the code name in description. if we wanna deviate we need to align everywhere

2022-07-07 09:00 UTC, yinonov requested changes

2022-07-07 09:08 UTC, YonatanKra commented on libs/components/src/lib/dialog/README.md
> +    block-size: 200px;
On my screen it looks good with 200

2022-07-07 12:20 UTC, yinonov commented
few questions before merge -
- should there be a way to prevent light dismiss?
- should the dialog align to top or be positioned in the center? remember past request to allow both

2022-07-10 09:15 UTC, jshenkman commented
> few questions before merge -
> 
> * should there be a way to prevent light dismiss?
> * should the dialog align to top or be positioned in the center? remember past request to allow both

I think we should keep both positions of the dialog (top and center) as we had in vivid2, as Yinon mentioned it was a request that came from users and was an essential addition for them. Can we add the `topPosition` property as we had in vivid-2?

https://vivid.vonage.com/?path=/story/components-dialog--top-position&args=topPosition:xlarge
Maybe we don't need all values (4 sizes)

2022-07-10 09:52 UTC, yinonov commented
> > few questions before merge -
> > 
> > * should there be a way to prevent light dismiss?
> > * should the dialog align to top or be positioned in the center? remember past request to allow both
> 
> I think we should keep both positions of the dialog (top and center) as we had in vivid2, as Yinon mentioned it was a request that came from users and was an essential addition for them. Can we add the `topPosition` property as we had in vivid-2?
> 
> https://vivid.vonage.com/?path=/story/components-dialog--top-position&args=topPosition:xlarge Maybe we don't need all values (4 sizes)

notice we are discussing a position terminology at [Consolidate position terminology](https://github.com/Vonage/vivid-3/issues/510)

2022-07-10 10:40 UTC, yinonov requested changes
strange color change on activate button

https://user-images.githubusercontent.com/15140652/178141413-967b8c36-7d9c-4fe5-92b2-cd6ebc344c67.mov

2022-07-10 10:40 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +        margin-left: 8px;
why not gap?

2022-07-10 10:42 UTC, yinonov requested changes

2022-07-10 10:42 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +Use the `top-oposition` attribute or the `topPosition` property to override the dialog centering to the screen and allow setting a unique top.
this terminology doesn't align with other components. review #510

2022-07-10 10:44 UTC, yinonov requested changes

2022-07-10 10:44 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +- Default: `false`
in style, top position is default

2022-07-10 10:48 UTC, yinonov requested changes

2022-07-10 10:48 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +Use the `headline` attribute to set the dialog's title.
in some scope _headline_ may equal _title_ but I'm not sure we should use it as equivalent term

2022-07-10 10:48 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +            headline="This is the title">app
here too

2022-07-10 10:48 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +</script>
couldn't tell it logs something to console. maybe print something to DOM? and the closing button might be redundant to reader here. simply close by the exist button of the dialog as above snippets

2022-07-10 10:50 UTC, yinonov requested changes

2022-07-10 10:50 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +Shows the dialog and makes it the top-most modal dialog.
what other value does it feature? no light dismiss, different role? maybe add a couple of paragraphs and a reference to read more on the topic?

2022-07-10 10:52 UTC, yinonov requested changes

2022-07-10 10:52 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +### Content
in Card the term is _text_

2022-07-10 10:57 UTC, yinonov requested changes

2022-07-10 10:57 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +            headline="Open Dialog">
maybe remove headline to focus on the _graphic_ only?

2022-07-10 10:57 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +### Graphics
align to _graphic_ (no 's'). as in card
https://github.com/Vonage/vivid-3/blob/d411e3363c233187f29a21cb5bc0b7e3e7323f8f/libs/components/src/lib/card/README.md#L70

2022-07-10 10:59 UTC, yinonov requested changes

2022-07-10 10:59 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +```
use our layout instead of arbitrary code
https://github.com/Vonage/vivid-3/blob/d411e3363c233187f29a21cb5bc0b7e3e7323f8f/libs/components/src/lib/card/README.md#L117-L126

2022-07-10 11:05 UTC, yinonov requested changes

2022-07-10 11:05 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +### Inline-size
not sure that's enough anymore in terms of fluidness. max/min size would probably be needed. given that also some requests regarding position were raised, the necessity of stacking context manoeuvres, the inability to apply styles on host (which contains both backdrop and the actual nested dialog), and the fact that dialog is partially categorized as layout, maybe _part_ access would be ideal?

2022-07-10 11:06 UTC, YonatanKra commented on libs/components/src/lib/dialog/README.md
> +Use the `top-oposition` attribute or the `topPosition` property to override the dialog centering to the screen and allow setting a unique top.
`placement` then?

2022-07-10 11:11 UTC, YonatanKra commented on libs/components/src/lib/dialog/README.md
> +- Default: `false`
I do not understand the comment. What do you mean? The default is `no top position`.
For `modal` it is the center of the screen, for `non-modal` it is top.

2022-07-10 11:20 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +- Default: `false`
why the difference?

2022-07-10 11:28 UTC, YonatanKra commented on libs/components/src/lib/dialog/README.md
> +- Default: `false`
See HTML spec

2022-07-10 11:29 UTC, YonatanKra commented on libs/components/src/lib/dialog/README.md
> +Use the `top-oposition` attribute or the `topPosition` property to override the dialog centering to the screen and allow setting a unique top.
#510 resolution should include the dialog.

2022-07-10 11:32 UTC, YonatanKra commented on libs/components/src/lib/dialog/README.md
> +        margin-left: 8px;
Have no idea. It works like that... if you want me to change to something, I will. I am not attached :)

2022-07-10 11:33 UTC, YonatanKra commented on libs/components/src/lib/dialog/README.md
> +```
It is intentional not to use layout to show how one can add a custom padding.

2022-07-10 11:37 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +        margin-left: 8px;
so refactor to align with header action items and the likes...

2022-07-10 12:15 UTC, YonatanKra commented on libs/components/src/lib/dialog/README.md
> +### Inline-size
Maybe wait and see if feedback requires this before comitting to an API?
Or remove the `inline`?

2022-07-10 12:38 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +### Inline-size
Remove inline for now to avoid introducing breaking changes. I expect we will revisit this very soon

2022-07-10 12:55 UTC, rachelbt commented on libs/components/src/lib/dialog/README.md
> +Use the `headline` attribute to set the dialog's title.
so we should write:
```suggestion
Use the `headline` attribute to set the dialog's headline.
```

2022-07-10 13:00 UTC, rachelbt commented on libs/components/src/lib/dialog/README.md
> +        margin-left: 8px;
@yinonov if you are referring to the margin left of the button - than yes, I've forgot gap :(

Regarding the footer - the slot is always there - so if we will use gap - than we will always have it - even if not needed.
Wondering if we need to add margin-top to slotted items. Not sure its the right way.

2022-07-10 13:02 UTC, rachelbt commented on libs/components/src/lib/dialog/README.md
> +        margin-left: 8px;
```suggestion
        column-gap: 8px;
        margin-top: 16px;

```

2022-07-10 19:22 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +- Type: `string`
I'm not sure the type is always a string. value of dialog might return a string representation of returnValue

2022-07-10 19:23 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +```html preview
note to follow mdn's example
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/returnValue#examples

2022-07-11 13:41 UTC, rachelbt commented
> strange color change on activate button
> 
>  Screen.Recording.2022-07-10.at.13.39.08.mov

It is as all buttons are. 
Try adding `rgb(42, 42, 42)` that is the value for ` --vvd-color-surface-12dp `background color to buttons wrapper div

2022-07-15 07:32 UTC, yinonov approved these changes
there are still issues which can be addressed in another scope -

- elborate docs
- dialog box flexibility, including size & proportions

2022-07-17 08:57 UTC, rachelbt approved these changes

2022-07-17 09:56 UTC, rachelbt approved these changes

2022-07-17 09:59 UTC, merged