fix(divider): migrate fast component
Vonage/vivid-3 pull request #509
Opened 2022-07-03 09:43 UTC by rachelbt

2022-07-03 21:30 UTC, yinonov commented on docs/ui-tests/readme.md
> +PRO TIP: utilizing the _component_ generator (`npx nx g @vonage/nx-vivid:component my-component`) will populate basic `ui.test.ts` to get you up and running with ui-tests.
👌

2022-07-03 21:32 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +A role of `presentation` implies that the divider is a visual treatment only so the contrast requirement does not apply in that case.
🦄

2022-07-03 21:32 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +A role of `presentation` implies that the divider is a visual treatment only so the contrast requirement does not apply in that case.
very nice

2022-07-03 21:36 UTC, yinonov requested changes

2022-07-03 21:36 UTC, yinonov commented on libs/components/src/lib/divider/divider.ts
> +	@attr dividerOrientation?: string;
```suggestion
	@attr orientation?: string;
```

2022-07-04 05:46 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +A role of `presentation` implies that the divider is a visual treatment only so the contrast requirement does not apply in that case.
I copy pated from fast 😊 
I did as in fast component - that if none is set than it gets `role="separator"`

2022-07-04 05:47 UTC, rachelbt commented on libs/components/src/lib/divider/divider.ts
> +	@attr dividerOrientation?: string;
had trouble with it in the beginning and forgot to change it back. Thanks!

2022-07-04 06:13 UTC, yinonov requested changes

2022-07-04 06:13 UTC, yinonov commented on change/@vonage-vivid-cea1c228-7bfa-4619-913b-3cae63801455.json
> +{
it's a prerelease

2022-07-04 06:14 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +A role of `presentation` implies that the divider is a visual treatment only so the contrast requirement does not apply in that case.
presentation makes sense, but was these 2 the only options in fast interface?

2022-07-04 07:05 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +A role of `presentation` implies that the divider is a visual treatment only so the contrast requirement does not apply in that case.
https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/divider/divider.spec.md#accessibility

2022-07-04 08:52 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +A role of `presentation` implies that the divider is a visual treatment only so the contrast requirement does not apply in that case.
> a role of `presentation` MAY be applied

notice it is a suggestion for a use-case. it's not a predefined value for the role. only `separator` is a default.
maybe we can permalink the fast accessibility section directly?

2022-07-07 09:04 UTC, rachelbt commented on change/@vonage-vivid-cea1c228-7bfa-4619-913b-3cae63801455.json
> +{
the type?

2022-07-07 12:32 UTC, yinonov commented on change/@vonage-vivid-cea1c228-7bfa-4619-913b-3cae63801455.json
> +{
yeah. u can totally delete the file and create a new one if need

2022-07-07 13:09 UTC, rachelbt commented on change/@vonage-vivid-cea1c228-7bfa-4619-913b-3cae63801455.json
> +{
changed :)

2022-07-07 14:08 UTC, yinonov requested changes

2022-07-07 14:08 UTC, yinonov commented on change/@vonage-vivid-cea1c228-7bfa-4619-913b-3cae63801455.json
> +  "dependentChangeType": "none"
```suggestion
  "dependentChangeType": "patch"
```

2022-07-10 08:29 UTC, rinaok requested changes

2022-07-10 08:45 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +    <vwc-divider orientation="vertical"></vwc-divider>
I feel like it's not that needed. Especially when the previous code snippet is horizontla

2022-07-10 08:46 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +```
Good point. I'll talk to @jshenkman about an example for that

2022-07-10 08:47 UTC, rachelbt commented on libs/components/src/lib/divider/divider.spec.ts
> +			expect(element).toBeInstanceOf(Divider);
I removed that property :)

2022-07-10 09:50 UTC, yinonov commented on libs/components/src/lib/divider/divider.spec.ts
> +			expect(element).toBeInstanceOf(Divider);
why?

2022-07-10 10:27 UTC, rachelbt commented on libs/components/src/lib/divider/divider.ts
> +	@attr dividerOrientation?: string;
I removed this property

2022-07-10 10:28 UTC, rachelbt commented on libs/components/src/lib/divider/divider.spec.ts
> +			expect(element).toBeInstanceOf(Divider);
because I'm using the build-in orientation from fast :)

2022-07-10 11:50 UTC, yinonov requested changes

2022-07-10 11:50 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +
breaks 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/15140652/178143637-e71ecfe4-a8cf-4dc5-9937-5b6f0a14de5f.png">

```suggestion
```
```

2022-07-10 11:52 UTC, yinonov requested changes

2022-07-10 11:52 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +### Role
this is not an API to expose naturally.

See how spectrum addresses such cases

https://opensource.adobe.com/spectrum-web-components/components/toast/#accessibility

2022-07-10 19:47 UTC, yinonov commented
we might want to support the following

![IMG_83B28274C267-1](https://user-images.githubusercontent.com/15140652/178159870-476bc791-48ee-4274-bf42-087711131691.jpeg)

2022-07-11 09:30 UTC, rachelbt commented
> we might want to support the following
> 
> ![IMG_83B28274C267-1](https://user-images.githubusercontent.com/15140652/178159870-476bc791-48ee-4274-bf42-087711131691.jpeg)

this looks more of a styled headline than a divider...

2022-07-12 15:06 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +### Role
I changed the documentation :)

2022-07-12 15:06 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +    <vwc-divider orientation="vertical"></vwc-divider>
@rinaok - I added :)

2022-07-13 09:58 UTC, yinonov requested changes
while at it, wanna update action-group as well?
<img width="733" alt="image" src="https://user-images.githubusercontent.com/15140652/178706992-d3e911ce-50f7-41f9-8dd7-8907d1727fc7.png">

2022-07-13 09:58 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +</vwc-card>
not sure if this is an example we should present. it doesn't look right
<img width="429" alt="image" src="https://user-images.githubusercontent.com/15140652/178705630-ff36159e-a965-4d54-89ad-6ff86c265ebd.png">

2022-07-13 09:58 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +<vwc-layout column-basis="block" column-spacing="small" gutters="small">
why not using the _block_ preview attribute?

2022-07-13 09:58 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +```html preview
maybe try center?
```suggestion
```html preview center
```

2022-07-13 09:58 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +  <div style="block-size: 40px;">
can block-size be applied on the divider itself?

2022-07-13 10:04 UTC, yinonov requested changes

2022-07-13 10:04 UTC, yinonov commented on libs/components/src/lib/action-group/action-group.scss
> +// Remove this after divider is merged and action-group is updated(https://github.com/Vonage/vivid-3/issues/508)
can already be replaced in this PR. why not?

2022-07-13 10:22 UTC, rinaok commented on libs/components/src/lib/divider/README.md
> +[for further reading about divider foundational role & accessibility](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/divider/divider.spec.md#accessibility)
```suggestion
## Accessibility
A `<vwc-divider>` element is by default rendered with a role of `'separator'`.  
When using `<vwc-divider>` as a decorative element the role should be set as `'presentation'`.

[For further reading about divider foundational role & accessibility](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/divider/divider.spec.md#accessibility)
```

I think that it would be better to explain more about it here in the docs, and the link should lead to https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/separator_role

2022-07-13 10:31 UTC, rachelbt commented on apps/docs/_data/components.json
> +      "/assets/modules/components/text/index.js"
@yinonov said it is not needed to add it here. Am I wrong?

2022-07-13 10:32 UTC, rachelbt commented on libs/components/src/lib/action-group/action-group.scss
> +// Remove this after divider is merged and action-group is updated(https://github.com/Vonage/vivid-3/issues/508)
because it makes the PR bigger. I prefer separating it.

2022-07-13 10:33 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +</vwc-card>
@jshenkman sait its OK :)

2022-07-13 10:39 UTC, rinaok commented on libs/components/src/lib/divider/ui.test.ts
> +const components = ['divider', 'button', 'action-group', 'text', 'card'];
```suggestion
const components = ['divider', 'button', 'action-group', 'text', 'card', 'layout'];
```

2022-07-13 10:41 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +```html preview
blocks works great! thanks

2022-07-13 10:42 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +  <div style="block-size: 40px;">
why? the divider by default is 100% and consumer can restrain it by adding ` block-size` if needed

2022-07-13 10:44 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +[for further reading about divider foundational role & accessibility](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/divider/divider.spec.md#accessibility)
I kept is simple as in spectum:
https://opensource.adobe.com/spectrum-web-components/components/toast/#accessibility

2022-07-13 10:50 UTC, rinaok commented on libs/components/src/lib/divider/README.md
> +[for further reading about divider foundational role & accessibility](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/divider/divider.spec.md#accessibility)
It's okay, but I still think we should link to official websites rather than other design systems.

2022-07-13 10:56 UTC, rachelbt commented
> while at it, wanna update action-group as well? <img alt="image" width="733" src="https://user-images.githubusercontent.com/15140652/178706992-d3e911ce-50f7-41f9-8dd7-8907d1727fc7.png">

will do - but it a separate PR

2022-07-13 13:56 UTC, rinaok commented on libs/components/src/lib/divider/README.md
> +[for further reading about divider foundational role & accessibility](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/divider/divider.spec.md#accessibility)
The link you provided does not mention role="presentation".
This is why I suggested https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/separator_role

2022-07-13 13:58 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +[for further reading about divider foundational role & accessibility](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/divider/divider.spec.md#accessibility)
no idea how I inserted the wrong link 😮

2022-07-13 15:06 UTC, yinonov commented on apps/docs/_data/components.json
> +      "/assets/modules/components/text/index.js"
Right. U don't need to use it. It's added behind the scenes

2022-07-13 15:07 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +  <div style="block-size: 40px;">
Right but why not on the host itself?

2022-07-14 08:26 UTC, rinaok approved these changes

2022-07-14 09:56 UTC, rachelbt commented on libs/components/src/lib/divider/README.md
> +  <div style="block-size: 40px;">
my mistake. Removed the div.

2022-07-14 11:47 UTC, yinonov requested changes

2022-07-14 11:47 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +
```suggestion
```html preview
<style>
.decorative-divider {
    display: grid;
    grid-template-columns: 1fr auto 1fr;
    align-items: center;
}

vwc-text {
  padding: 0 32px;
}
</style>

<div class="decorative-divider">
  <vwc-divider role="presentation"></vwc-divider>
  <vwc-text>More Info</vwc-text>
  <vwc-divider role="presentation"></vwc-divider>
</div>
```

2022-07-14 14:01 UTC, yinonov approved these changes

2022-07-14 15:41 UTC, yinonov requested changes

2022-07-14 15:41 UTC, yinonov commented on libs/components/src/lib/divider/README.md
> +```
actually, thinking again, there's a magic value here (32px). wouldn't it be better to utilize vwc-layout passing the `grid-template-columns` to its the exposed css variable?
that way we still get spacing defined by tokens

2022-07-15 07:24 UTC, yinonov submitted a review, later dismissed

2022-07-15 07:25 UTC, yinonov submitted a review, later dismissed

2022-07-17 08:50 UTC, YonatanKra commented on docs/ui-tests/readme.md
> +PRO TIP: utilizing the _component_ generator (`npx nx g @vonage/nx-vivid:component my-component`) will populate basic `ui.test.ts` to get you up and running with ui-tests.
![image](https://user-images.githubusercontent.com/6459899/179391088-9061b562-a9e4-4b11-ad6f-cc7520c92b0d.png)

2022-07-17 08:51 UTC, YonatanKra approved these changes

2022-07-17 08:52 UTC, merged