fix(breadcrumb): change template to nav
Vonage/vivid-3 pull request #515
Opened 2022-07-05 13:33 UTC by YonatanKra

2022-07-05 13:36 UTC, yinonov commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.spec.ts
> +			const results = await axe(shadowRoot.innerHTML, {
Can we check breadcrumb with its items?
Need to check how's it testing the items templates as well

2022-07-05 13:59 UTC, YonatanKra commented on libs/components/src/lib/breadcrumb/breadcrumb.template.ts
> +        <div role="list" class="list" part="list">
Yes - this is how `fast` implemented it.
I think UL might be more fitting, but don't we go with `fast` on such decisions?

2022-07-05 14:30 UTC, YonatanKra commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.spec.ts
> +			const results = await axe(shadowRoot.innerHTML, {
It is tested with its children:
```
<vwc-breadcrumb>
 <vwc-breadcrumb-item href="#" text="breadcrumb"></vwc-breadcrumb-item>
    <vwc-breadcrumb-item text="..."></vwc-breadcrumb-item>
    <vwc-breadcrumb-item href="#" text="breadcrumb"></vwc-breadcrumb-item>
    <vwc-breadcrumb-item text="breadcrumb"></vwc-breadcrumb-item>
<vwc-breadcrumb>
```

2022-07-06 06:37 UTC, yinonov requested changes

2022-07-06 06:37 UTC, yinonov commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.spec.ts
> +		it('should pass accessibility test', async () => {
this should actually fail cause list items with aren't nested in list are wrong

2022-07-06 06:40 UTC, YonatanKra commented on libs/components/src/lib/breadcrumb-item/breadcrumb-item.spec.ts
> +		it('should pass accessibility test', async () => {
It doesn't fail though... an issue with `axe`?

2022-07-06 14:21 UTC, yinonov approved these changes

2022-07-06 14:22 UTC, merged