chore(documentation): meta tags
Vonage/vivid-3 pull request #525
Opened 2022-07-07 13:35 UTC by rachelbt

2022-07-10 09:37 UTC, jshenkman commented on apps/docs/_layouts/base.njk
> +    <meta property="og:image" content="../../../vivid-logo.svg">
> @jshenkman @AyalaBu should we have a dedicated image for this social sharing banner?

nope, but I'll make one! 
What do you want it to say? Vivid web components? @yinonov

2022-07-10 10:18 UTC, yinonov commented on apps/docs/_layouts/base.njk
> +    <meta property="og:image" content="../../../vivid-logo.svg">
just some nice image, no text. we'll add the text

2022-09-11 21:14 UTC, yinonov approved these changes

2022-09-11 21:21 UTC, yinonov requested changes

2022-09-11 21:21 UTC, yinonov commented on apps/docs/_layouts/base.njk
> +    <meta property="og:image" content="../../../vivid-logo.png">
reduce file size
```suggestion
    <meta property="og:image" content="../../../vivid-logo.jpg">
```

2022-09-11 21:21 UTC, yinonov commented on apps/docs/_layouts/base.njk
> +    <meta property="og:image" content="../../../vivid-logo.png">
I also think it should be full url and not a relative path

2022-09-12 10:06 UTC, rachelbt commented on apps/docs/_layouts/base.njk
> +    <meta property="og:image" content="../../../vivid-logo.png">
I will check it once the deploy will work :)

2022-09-14 05:24 UTC, yinonov approved these changes

2022-09-14 07:23 UTC, merged