fix(tooltip): accessibility
Vonage/vivid-3 pull request #533
Opened 2022-07-10 21:24 UTC by rinaok

2022-07-11 10:45 UTC, rinaok commented
@yinonov We should add an accessibility section to popup's readme as well, but I'm not sure about the ARIA role it should have.

2022-07-11 12:06 UTC, yinonov requested changes

2022-07-11 12:06 UTC, yinonov commented on libs/components/src/lib/tooltip/tooltip.template.ts
>  <vwc-popup class="${getClasses}" arrow alternate="true"
`alternate="true"` can just be `alternate`

2022-07-11 12:06 UTC, yinonov commented on libs/components/src/lib/tooltip/tooltip.template.ts
> +  exportparts="vvd-theme-alternate" role="tooltip">
sorry to bring this up, unrelated to changes - is `exportparts` required?

2022-07-12 08:34 UTC, rinaok commented on libs/components/src/lib/tooltip/tooltip.template.ts
> +  exportparts="vvd-theme-alternate" role="tooltip">
@yinonov yes, without it tooltip can't be alternate

2022-07-12 08:36 UTC, rinaok commented on libs/components/src/lib/popup/popup.ts
> +				this.#anchorEl?.addEventListener('keydown', (e) => this.#handleKeydown(e as KeyboardEvent));
@yinonov we have the cleanup method. Do you think we should remove it anyways?

2022-07-12 10:48 UTC, rinaok commented on libs/components/src/lib/popup/popup.ts
> +				this.#anchorEl?.addEventListener('keydown', (e) => this.#handleKeydown(e as KeyboardEvent));
removed it at disconnectedCallback

2022-07-13 13:07 UTC, rachelbt approved these changes
LGTM

2022-07-13 17:19 UTC, yinonov commented on libs/components/src/lib/popup/README.md
> +Popup component is a low level element, unaware of its document context, but in most cases required to overlay on top of all elements.
adjusting the syntax. this is copied from another page right? can u align with this?
```suggestion
Popup component is a low level element, unaware of its document context, but is, in most cases, required to overlay on top of all elements.
```

2022-07-14 13:07 UTC, yinonov commented on libs/components/src/lib/popup/README.md
> +## Caveat
maybe we should have it in tooltip too?

2022-07-14 13:27 UTC, rinaok commented on libs/components/src/lib/popup/README.md
> +## Caveat
I'm not sure, maybe @rachelbt @YonatanKra have an opinion about it?

2022-07-14 13:46 UTC, yinonov commented on libs/components/src/lib/popup/README.md
> +## Caveat
with pleasure
https://github.com/material-components/material-web/issues/832

in fast doc -
https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/dialog/dialog.spec.md#caveat

there are dozen more if need

2022-07-14 13:56 UTC, rinaok commented on libs/components/src/lib/popup/README.md
> +## Caveat
@yinonov OK, added the Caveat to tooltip as well

2022-07-14 16:17 UTC, yinonov approved these changes

2022-07-14 16:18 UTC, merged