refactor(tokens): migrate design tokens renderers to next
Vonage/vivid-3 pull request #535
Opened 2022-07-12 06:08 UTC by yinonov

2022-07-31 14:49 UTC, YonatanKra commented on libs/components/project.json
> +  "implicitDependencies": ["tokens"]
About time!!!
![image](https://user-images.githubusercontent.com/6459899/182031946-7117109b-6b78-4f2d-8704-939f7f354435.png)

2022-07-31 14:50 UTC, YonatanKra commented on libs/tokens/.babelrc
> +	"presets": [["@nrwl/web/babel", { "useBuiltIns": "usage" }]]
What does this do?

2022-07-31 14:50 UTC, YonatanKra commented on libs/tokens/README.md
> +# tokens
Is this a good readme?

2022-07-31 14:51 UTC, YonatanKra commented on libs/tokens/src/lib/build.ts
> +const sourceOnly = require('./filters/source-only');
Why are we using `require` here?

2022-07-31 14:52 UTC, YonatanKra commented on libs/tokens/src/lib/formatters/constants.ts
> +const { formatHelpers: { fileHeader } } = require('style-dictionary');
How does this work? It doesn't look like constants... maybe constants generator?

2022-07-31 14:53 UTC, YonatanKra commented on libs/tokens/src/lib/filters/source-only.ts
> +module.exports = {
When there's no test, I need to guess as to how this filter should work.

2022-07-31 14:54 UTC, YonatanKra commented on libs/tokens/src/lib/tokens.spec.ts
> +import { tokens } from './tokens';
This file disturbs my sleep... :)
Let's talk about it when in office

2022-07-31 14:54 UTC, YonatanKra commented on libs/tokens/src/lib/tokens.ts
> +export function tokens(): string {
?

2022-07-31 14:55 UTC, YonatanKra commented on libs/tokens/src/lib/transforms/shadow-shorthand.ts
> +const { transform } = require('style-dictionary');
Why require?
Also, what `shadow-shorthand` stands for?
When there aren't tests, ppl get lost...

2022-07-31 14:56 UTC, YonatanKra requested changes
Missing tests. Let's talk about it offline and get it together.

2022-07-31 15:47 UTC, yinonov commented on libs/tokens/.babelrc
> +	"presets": [["@nrwl/web/babel", { "useBuiltIns": "usage" }]]
Have no idea. Nx did that

2022-07-31 18:15 UTC, yinonov commented on libs/tokens/README.md
> +# tokens
it's not wrong :D

2022-07-31 18:17 UTC, yinonov commented on libs/tokens/src/lib/formatters/constants.ts
> +const { formatHelpers: { fileHeader } } = require('style-dictionary');
the correct term according to SD is formatter. thus, within formatters folder

2022-07-31 18:18 UTC, yinonov commented on libs/tokens/src/lib/tokens.spec.ts
> +import { tokens } from './tokens';
this is generated by nx. not sure I want it. do we have any convention calling the entry point file as the lib itself?

2022-07-31 18:19 UTC, yinonov commented on libs/tokens/src/lib/tokens.ts
> +export function tokens(): string {
same as https://github.com/Vonage/vivid-3/pull/535#discussion_r934022250

2022-07-31 18:20 UTC, yinonov commented on libs/tokens/src/lib/transforms/shadow-shorthand.ts
> +const { transform } = require('style-dictionary');
SD is documented at its core as commonjs.
yes this can sure get itself tested

2022-08-01 13:38 UTC, yinonov commented on libs/tokens/src/lib/build.ts
> +const sourceOnly = require('./filters/source-only');
SD is a commonjs lib

2022-08-01 18:42 UTC, yinonov commented on libs/tokens/src/lib/build.ts
> +const sourceOnly = require('./filters/source-only');
@YonatanKra having and this file is the main entry for tokens package, therefore is self explanatory, and is responsible for generating scss constants & css variables that components rely on, I found creating a test for it fails a DRY principal where the test file was simply copying this same context.

failure to run will fail build / visual regression tests.

still think of any reasonable sanity tests here?

2022-08-01 18:44 UTC, yinonov commented on libs/tokens/src/lib/formatters/constants.ts
> +const { formatHelpers: { fileHeader } } = require('style-dictionary');
should filename itself explicitly state it being a formatter?

2022-08-04 20:26 UTC, YonatanKra commented on libs/tokens/src/lib/formatters/constants.spec.ts
> +		expect(formatter(token)).toContain(`$vvd-color-canvas: --vvd-color-canvas;`);
Why is it called `formatter` then? Wouldn't a name like `tokenToScssConstant` be clearer?

2022-08-04 20:31 UTC, YonatanKra commented on libs/tokens/src/lib/build.ts
> +		dev: {
What's the `dev` platform for? How do I use it?

2022-08-04 20:31 UTC, YonatanKra commented on libs/tokens/src/lib/build.ts
> +const sourceOnly = require('./filters/source-only');
It's not test as much as documentation.
How do I use this file? Can I set env variables that will make it behave differently?

2022-08-04 20:38 UTC, yinonov commented on libs/tokens/src/lib/formatters/constants.spec.ts
> +		expect(formatter(token)).toContain(`$vvd-color-canvas: --vvd-color-canvas;`);
It's a member of an object with specific interface. Same as in connectedCallback

2022-08-04 20:40 UTC, yinonov commented on libs/tokens/src/lib/build.ts
> +		dev: {
Web platform build the tokens.
Dev builds constants we use only in development and aren't being used at run-time

2022-08-05 06:34 UTC, YonatanKra commented on libs/tokens/src/lib/build.ts
> +		dev: {
I could tell that from the name but - how do I use it? Why would dev mode need to build constants that aren't used at run-time? And what do you mean by `run-time` - is it the components' runtime or the tokens' runtime (which is the components' build time)?

2022-08-05 09:08 UTC, yinonov commented on libs/tokens/src/lib/build.ts
> +		dev: {
that's what dev outputs for scss variables, it's only for our safety. it may also build types in the future. these are only used in development. they run **once** to provide a mapping for variables.

```css
$vvd-color-on-cta: --vvd-color-on-cta;
$vvd-color-cta-10: --vvd-color-cta-10;
$vvd-color-cta-20: --vvd-color-cta-20;
$vvd-color-cta-30: --vvd-color-cta-30;
$vvd-color-cta-70: --vvd-color-cta-70;
$vvd-color-cta-90: --vvd-color-cta-90;
```

actual tokens (web) run a different formatting and iterate over themes (**more than once**).
they output the following (more extensibly)
```css
@mixin variables {
	--vvd-sizing-4px-scale-3xs: 8px;
	--vvd-sizing-4px-scale-2xs: 12px;
	--vvd-sizing-4px-scale-xs: 16px;
	--vvd-sizing-4px-scale-sm: 20px;
	--vvd-sizing-4px-scale-md: 24px;
	--vvd-sizing-4px-scale-lg: 28px;
	--vvd-sizing-4px-scale-xl: 32px;
	--vvd-sizing-4px-scale-2xl: 36px;
	--vvd-sizing-4px-scale-3xl: 40px;
	--vvd-sizing-8px-scale-3xs: 8px;
	--vvd-sizing-8px-scale-2xs: 16px;
	--vvd-sizing-8px-scale-xs: 24px;
	--vvd-sizing-8px-scale-sm: 32px;
	--vvd-sizing-8px-scale-md: 40px;
	--vvd-sizing-8px-scale-lg: 48px;
	--vvd-sizing-8px-scale-xl: 56px;
	--vvd-sizing-8px-scale-2xl: 64px;
	--vvd-sizing-8px-scale-3xl: 72px;
	--vvd-color-surface-0dp: rgba(255, 255, 255, 1);
	--vvd-color-surface-2dp: rgba(255, 255, 255, 1);
	--vvd-color-surface-4dp: rgba(255, 255, 255, 1);
	--vvd-color-surface-8dp: rgba(255, 255, 255, 1);
	--vvd-color-surface-12dp: rgba(255, 255, 255, 1);
	--vvd-color-surface-16dp: rgba(255, 255, 255, 1);
	--vvd-color-surface-24dp: rgba(255, 255, 255, 1);
}
```

2022-08-05 09:13 UTC, yinonov commented on libs/tokens/src/lib/build.ts
> +const sourceOnly = require('./filters/source-only');
not sure what u mean. how are env variables related? to affect the file system? I tried creating a test but it resulted in almost the same code. is it worth creating a test just for the sake of its definition? just for having a clear statement of what it is? then let's just have a comment stating the same thing.

if this code breaks or doesn't provide exactly what it needs to, our whole build of components will fail. there's no way this goes under the radar

2022-08-07 11:04 UTC, YonatanKra approved these changes
I'll take the test as a side project

2022-08-07 11:35 UTC, merged