chore(docs): drawer modal conditional to desktop or mobile
Vonage/vivid-3 pull request #538
Opened 2022-07-12 10:46 UTC by yinonov

2022-07-24 11:41 UTC, rachelbt requested changes

2022-07-24 11:41 UTC, rachelbt commented on apps/docs/assets/scripts/viewport-handler.js
> +(function () {
this doesn't work - the drawer stays open :(

2022-07-24 14:12 UTC, yinonov commented on apps/docs/assets/scripts/viewport-handler.js
> +(function () {
This only occurs on init

2022-07-25 05:20 UTC, rachelbt approved these changes
LGTM

2022-07-25 09:23 UTC, merged