fix(docs): site layout
Vonage/vivid-3 pull request #560
Opened 2022-07-21 08:43 UTC by rachelbt

2022-07-21 10:29 UTC, jshenkman commented
Looks great in both schemes !! Thanks @rachelbt for the fix :)

2022-07-21 11:18 UTC, yinonov commented on apps/docs/_layouts/base.njk
> +       <img src="/vivid-logo.svg" style="" alt="Vivid Logo" width="40">
Works in both dark / light?

2022-07-21 11:21 UTC, yinonov requested changes

2022-07-21 11:21 UTC, yinonov commented on apps/docs/assets/styles/main.css
>    position: sticky;
This bounces with elements in the web kit bouncing scroll behavior

2022-07-21 11:26 UTC, yinonov requested changes
Looks a bit damaged in mobile. Suggesting to focus and merge #538 first
![image](https://user-images.githubusercontent.com/15140652/180202540-9ce1fa1c-c4d7-4966-aa7c-bb306cdf5384.png)

2022-07-24 12:03 UTC, rachelbt commented
> Looks a bit damaged in mobile. Suggesting to focus and merge #538 first ![image](https://user-images.githubusercontent.com/15140652/180202540-9ce1fa1c-c4d7-4966-aa7c-bb306cdf5384.png)

didn't happen to me. 
There are no fonts in your print screen - maybe it wasn't fully loaded?
It looks OK once the drawer is closed :)
![image](https://user-images.githubusercontent.com/7512792/180646108-d75506e9-7d0f-4a61-9050-432c51cd57cf.png)

2022-07-25 09:32 UTC, rachelbt commented on apps/docs/_layouts/base.njk
> +       <img src="/vivid-logo.svg" style="" alt="Vivid Logo" width="40">
yes. Its only the image and not the text

2022-07-25 09:33 UTC, rachelbt commented on apps/docs/assets/styles/main.css
>    position: sticky;
> This bounces with elements in the web kit bouncing scroll behavior ![image](https://user-images.githubusercontent.com/15140652/180202105-4dd46151-8ee5-47e3-9b86-e0ac463c8bec.png)

didn't happen to me. mind that theres no fonts in your printscreen. Maybe its not fully loaded.

2022-07-25 14:34 UTC, rachelbt commented
@yinonov - ready for re-check.
One thing though - there's a horizontal scroll in mobile because of long headline combined with too big font.
When theres scroll than the side -drawer and the header breaks.
We have a typography PR so I'm leaving it for now.

2022-07-28 07:37 UTC, rachelbt commented
@jshenkman 
for Visual QA:
- now the header is starched above the side-drawer
- in main page: added the grey in the first part
- in all component page - added bg to the component name. (didn't add the image - leaving it to another PR).
- please check both desktop & mobile
- there might be some breaking in mobile due to the typography and lone names of the components member (e.g. Accessibility).
Thanks

2022-07-28 12:33 UTC, yinonov approved these changes

2022-07-31 09:21 UTC, merged