fix(layout): inline & block gutters
Vonage/vivid-3 pull request #573
Opened 2022-07-27 08:33 UTC by rachelbt

2022-07-27 08:49 UTC, rinaok requested changes
Didn't understand the example. Maybe it should be two examples? One with `inline` sizes and one with `block` sizes?

2022-07-27 09:12 UTC, yinonov requested changes

2022-07-27 09:12 UTC, yinonov commented on libs/components/src/lib/layout/README.md
>  - Default: `undefined`
Can this be define as none in docs?

2022-07-27 12:05 UTC, rachelbt commented on libs/components/src/lib/layout/README.md
>  - Default: `undefined`
done

2022-07-27 12:06 UTC, rachelbt commented
> Didn't understand the example. Maybe it should be two examples? One with `inline` sizes and one with `block` sizes?

@yinonov @rinaok 
I added dividers, I think now its better, no?

2022-07-27 13:41 UTC, rinaok commented
> > Didn't understand the example. Maybe it should be two examples? One with `inline` sizes and one with `block` sizes?
> 
> @yinonov @rinaok I added dividers, I think now its better, no?

@rachelbt I still think that it would be better with two different examples

2022-07-27 14:56 UTC, rinaok commented
> > > Didn't understand the example. Maybe it should be two examples? One with `inline` sizes and one with `block` sizes?
> > 
> > 
> > @yinonov @rinaok I added dividers, I think now its better, no?
> 
> @rachelbt Looks better, but I still think that it would be better with two different examples

@rachelbt Added a change, what do you think? I think that it's more clear now

2022-07-27 17:22 UTC, rachelbt commented
> > > > Didn't understand the example. Maybe it should be two examples? One with `inline` sizes and one with `block` sizes?
> > > 
> > > 
> > > @yinonov @rinaok I added dividers, I think now its better, no?
> > 
> > 
> > @rachelbt Looks better, but I still think that it would be better with two different examples
> 
> @rachelbt Added a change, what do you think? I think that it's more clear now

its more clear but it makes the preview code very big. 
@yinonov what do you say?

2022-07-28 07:48 UTC, rinaok commented
> > > > > Didn't understand the example. Maybe it should be two examples? One with `inline` sizes and one with `block` sizes?
> > > > 
> > > > 
> > > > @yinonov @rinaok I added dividers, I think now its better, no?
> > > 
> > > 
> > > @rachelbt Looks better, but I still think that it would be better with two different examples
> > 
> > 
> > @rachelbt Added a change, what do you think? I think that it's more clear now
> 
> its more clear but it makes the preview code very big. @yinonov what do you say?

@rachelbt Maybe you can move the gutters examples below the Column Basis example and then it will look better?

2022-07-28 09:09 UTC, yinonov approved these changes

2022-07-28 09:25 UTC, rinaok submitted a review, later dismissed

2022-07-28 09:52 UTC, rinaok approved these changes

2022-07-28 11:19 UTC, merged