feat(number-field): add number-field component
Vonage/vivid-3 pull request #584
Opened 2022-08-02 06:44 UTC by YonatanKra

2022-10-02 20:11 UTC, yinonov requested changes

2022-10-02 20:11 UTC, yinonov commented on libs/components/src/lib/number-field/number-field.template.ts
> +	  ${when(x => !x.errorValidationMessage && x.helperText?.length, renderHelperText())}
is this our implementation? if so, should be reference by the input element `describedBy`?

2022-10-02 20:15 UTC, yinonov requested changes

2022-10-02 20:15 UTC, yinonov commented on libs/components/src/lib/number-field/number-field.template.ts
> +				<vwc-button id="subtract" icon="minus-line"
use context to retrieve actual tag as in
https://github.com/Vonage/vivid-3/blob/1080172e759f42f3a73e2138e23a52043efcc439/libs/components/src/lib/checkbox/checkbox.template.ts#L37-L38

2022-10-02 20:17 UTC, yinonov requested changes

2022-10-02 20:17 UTC, yinonov commented on libs/components/src/lib/number-field/number-field.template.ts
> +function numberControlButtons() {
not sure whether this is a valid pattern but worth examination - buttons are controlling the number input
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls

2022-10-02 21:38 UTC, yinonov requested changes

2022-10-02 21:38 UTC, yinonov commented on libs/components/src/lib/number-field/README.md
> +```
when disabled, should buttons be disabled as well? or at least set to `pointer-events: none`? should examine from an a11y perspective.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/15140652/193477349-70d647ca-1f34-4985-baa6-a02dfcfc5022.png">

2022-10-02 21:39 UTC, yinonov requested changes

2022-10-02 21:39 UTC, yinonov commented on libs/components/src/lib/number-field/README.md
> +```
was still able to modify value
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/15140652/193477453-3f332d8c-e23b-4536-89d3-88201b515bf3.png">

2022-10-02 21:45 UTC, yinonov requested changes

2022-10-02 21:45 UTC, yinonov commented on libs/components/src/lib/number-field/index.ts
> +	});
it's either we set focus delegation here or remove from text field & text area

2022-10-03 04:59 UTC, AyalaBu commented
@YonatanKra 
Looks great!

2022-10-03 13:02 UTC, YonatanKra commented on libs/components/src/lib/number-field/number-field.template.ts
> +function numberControlButtons() {
Not relevant - as buttons are not input elements IMO.

2022-10-03 13:23 UTC, YonatanKra commented on libs/components/src/lib/number-field/README.md
> +Represents a number-field custom element. Follows the [`HTMLInput` of `type=text` specifications](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text).
Well... we follow two things:
1. Fast
2. https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

2022-10-03 13:28 UTC, YonatanKra commented on libs/components/src/lib/number-field/README.md
> +Represents a number-field custom element. Follows the [`HTMLInput` of `type=text` specifications](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text).
Added to readme

2022-10-03 21:04 UTC, yinonov commented on libs/components/src/lib/number-field/number-field.template.ts
> +				            @click="${x => adjustValueByStep(x, SUBTRACT)}"></${buttonTag}>
native number controls feature a behavior that isn't supported here. holding mousedown should increment / decrement numbers repeatedly

2022-10-03 21:07 UTC, yinonov commented on libs/components/src/lib/number-field/number-field.template.ts
> +function numberControlButtons() {
they control the value of the input. is there no recommended aria pattern to reflect that relationship?

2022-10-03 21:09 UTC, yinonov requested changes
still -
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/15140652/193683034-bc6911e2-9e9c-4d53-95fb-8016356d1cef.png">

2022-10-04 14:54 UTC, yinonov approved these changes

2022-10-04 14:56 UTC, yinonov commented
I noticed on mobile that when clicking on the controls it blurs out of control focus

2022-10-04 14:57 UTC, yinonov commented
Question to ask ourselves. Is helper text equivalent to tooltip?

2022-10-12 06:50 UTC, merged