feat(avatar): migrate new component
Vonage/vivid-3 pull request #594
Opened 2022-08-02 13:56 UTC by rachelbt

STILL IN WORK

2022-09-04 14:20 UTC, yinonov requested changes

2022-09-04 14:20 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +Use the `default` slot to have an image avatar.
```suggestion
Use the `default` slot to set a graphic media of any kind (e.g. image, illustration etc'.)
```

2022-09-04 14:20 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +### Icon
what about?
```js
- Type: `string`
- Default: `''`
```

2022-09-04 14:20 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +### Icon
maybe something like
https://github.com/Vonage/vivid-3/blob/a8a8db32b29ae377e8b34188e06ef0265266ffb4/libs/components/src/lib/nav-item/README.md#L27-L35

2022-09-04 14:20 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +still in progress
```suggestion
<!-- 
### Acronym
still in progress
-->
```

2022-09-04 14:20 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +The `connotation` attribute sets the colors according to the wanted connotation.
```suggestion

Use the `connotation` attribute to set the avatar's color.
```

2022-09-04 14:44 UTC, yinonov requested changes

2022-09-04 14:44 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +<img src="https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80" alt="woman"/>
maybe something not as bloated?

2022-09-04 14:53 UTC, yinonov commented on libs/components/src/lib/avatar/avatar.scss
> +		inline-size: 100%;
wouldn't it damage the proportions? isn't object-fit enough?

2022-09-05 19:53 UTC, yinonov commented on libs/components/src/lib/avatar/avatar.scss
> +		inline-size: 100%;
would a non-square image be ok?

2022-09-05 19:57 UTC, yinonov commented on libs/components/src/lib/avatar/avatar.scss
> +		inline-size: 100%;
yes, checked.

2022-09-05 19:59 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +### Icon
must it always be a human name?

2022-09-05 20:09 UTC, rachelbt commented on libs/components/src/lib/avatar/avatar.scss
> +		inline-size: 100%;
that what object-fit is for :)

2022-09-05 20:12 UTC, rachelbt commented on libs/components/src/lib/avatar/README.md
> +### Icon
Don't know... 
The thing is - if we have an image or an icon - it will be nice of us to help the user add the title. 
The only problem that I'm thinking of is with acronym.
Maybe we should leave this for now and decide about it after acronym in added.
WDYT?

2022-09-05 20:22 UTC, yinonov commented on libs/components/src/lib/avatar/avatar.scss
> +	outline: 1px solid var(#{appearance.get-appearance-token(outline)});
I know I suggested it but now it feels hacky as outline accees top-layer. We should simply contain the image area to allow the box shadow to appear or simply border with box sizing. Although box Shadow is our convention

2022-09-06 11:18 UTC, AyalaBu commented on libs/components/src/lib/avatar/README.md
> +When using an image make sure `appearance` is not `outlined`
I think it looks ok,
in case that it's outline appearance is consistent with the other avatar types

2022-09-06 13:25 UTC, yinonov requested changes

2022-09-06 13:25 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +- Default: `'filled'`
Shouldn't ghost be default?

2022-09-06 13:25 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +### Icon
This can fire back. Imagine we add our opinionated representation and automatic checks doesn't throw any violations due to it. Authors wouldn't be aware of the problem and that they need to add their context. We had that same issue with icon button. I think the best alternative is us handling docs with that in mind and provide snippets with aria context

2022-09-06 14:17 UTC, rachelbt commented on libs/components/src/lib/avatar/README.md
> +- Default: `'filled'`
whats the meaning of ghost avatar? it looks strange just an icon or letters without bg or outline....

2022-09-06 14:20 UTC, rachelbt commented on libs/components/src/lib/avatar/README.md
> +### Icon
OK then. we will stay with our text about it in the docs :)

2022-09-06 21:44 UTC, yinonov approved these changes

2022-09-07 05:24 UTC, merged