chore(docs): update docs with the CDN links
Vonage/vivid-3 pull request #596
Opened 2022-08-03 11:02 UTC by YonatanKra

2022-08-03 15:15 UTC, yinonov commented on apps/docs/index.njk
>  permalink: /
Maybe the package should be called components docs?

2022-08-03 17:28 UTC, yinonov requested changes

2022-08-03 17:28 UTC, yinonov commented on libs/components/README.md
> +You can import vivid components from CDN.
```suggestion

You can import vivid components from a CDN.

```

2022-08-03 17:28 UTC, yinonov commented on libs/components/README.md
> +- https://cdn.jsdelivr.net/npm/@vonage/vivid@next
it feels like taking credit for these services. maybe we need to shortly introduce the services and credit them

2022-08-03 17:28 UTC, yinonov commented on libs/components/README.md
> +- https://cdn.jsdelivr.net/npm/@vonage/vivid@next
url import requires the full file path. paste these in browser's url and copy the file path result

2022-08-03 17:28 UTC, yinonov commented on libs/components/README.md
> +Note that in addition to importing the JS files, you also need to add the CSS.
this is being documented at #595. refer once merged? or refer to the expected path

2022-08-04 07:16 UTC, YonatanKra commented on apps/docs/index.njk
>  permalink: /
I don't follow this line of thought. What package?

2022-08-04 07:32 UTC, YonatanKra commented on libs/components/README.md
> +- https://cdn.jsdelivr.net/npm/@vonage/vivid@next
You don't really need the file path result because if you import just `@next` you get the main `index` file which brings the whole package for you.
You could import a single file - I'll add this example

2022-08-04 08:49 UTC, rinaok requested changes

2022-08-04 08:49 UTC, rinaok commented on libs/components/README.md
> +`npx nx run components:test` will run unit tests for the components.
```suggestion
`npx nx run components:test` or `npm test` will run unit tests for the components.
```

2022-08-04 08:49 UTC, rinaok commented on libs/components/README.md
> +
```suggestion
* [floating-ui](https://floating-ui.com/)
```

2022-08-04 08:55 UTC, rinaok commented on libs/components/README.md
> +- https://cdn.jsdelivr.net/npm/@vonage/vivid@next
```suggestion
- [https://unpkg.com/@vonage/vivid@next](https://unpkg.com/@vonage/vivid@next)
- [https://cdn.jsdelivr.net/npm/@vonage/vivid@next](https://cdn.jsdelivr.net/npm/@vonage/vivid@next)
```

2022-08-04 09:00 UTC, rinaok commented on libs/components/README.md
> +
Vivid project components' view link doesn't work

2022-08-04 09:03 UTC, rinaok commented on libs/components/README.md
> +Feel free to check [issues page](https://github.com/Vonage/vivid-3/issues). You can also take a look at the [contributing guide](.github/CONTRIBUTING.md).
There are two references to the issue page link. On the Roadmap page and on the Contributing page.

2022-08-04 09:04 UTC, rinaok commented on libs/components/README.md
> +See the [ui-tests docs](docs/ui-tests/readme.md) for how to run visual tests.
ui-tests docs page not found

2022-08-04 09:05 UTC, rinaok commented on libs/components/README.md
> +Give a ⭐️ if this project helped you!
```suggestion
Give a [⭐️](https://github.com/Vonage/vivid-3/stargazers) if this project helped you!
```

2022-08-04 09:16 UTC, YonatanKra commented on libs/components/README.md
> +Feel free to check [issues page](https://github.com/Vonage/vivid-3/issues). You can also take a look at the [contributing guide](.github/CONTRIBUTING.md).
That's ok. Two different contexts.

2022-08-04 10:30 UTC, YonatanKra commented
@yinonov @rinaok 
I've handled all the points methinks.
Can you reevaluate please?

2022-08-04 11:11 UTC, rinaok requested changes

2022-08-04 11:11 UTC, rinaok commented on libs/components/README.md
> +[view components status](https://github.com/orgs/Vonage/projects/3)
the link doesn’t lead to the component's status page

2022-08-04 11:11 UTC, rinaok commented on libs/components/README.md
> +Feel free to check [issues page](https://github.com/Vonage/vivid-3/issues). You can also take a look at the [contributing guide](.github/CONTRIBUTING.md).
`contributing guide` page not found

2022-08-04 11:16 UTC, rinaok requested changes

2022-08-04 11:16 UTC, rinaok commented on libs/components/README.md
> +`npx run nx g @vonage/nx-vivid:component my-component`
```suggestion
```bash
npx run nx g @vonage/nx-vivid:component my-component
```
```

2022-08-04 11:16 UTC, rinaok commented on libs/components/README.md
> +`npx nx run components:test` or `npm test` will run unit tests for the components.
```suggestion
```bash
npx nx run components:test
```
 or  
```bash
npm test
```
will run unit tests for the components.
```

2022-08-04 11:16 UTC, rinaok commented on libs/components/README.md
> +See the [ui-tests docs](../../docs/ui-test/readme.md) for how to run visual tests.
`ui-tests docs` page not found

2022-08-04 11:58 UTC, YonatanKra commented on libs/components/README.md
> +`npx nx run components:test` or `npm test` will run unit tests for the components.
I don't think this is a good change. It is one sentence and not a code example.  Does splitting it to two bash commands seem clearer to you?
In addition, this is beyond the scope of this PR to fix all the ailes of this files. See the title :)

2022-08-04 11:59 UTC, YonatanKra commented on libs/components/README.md
> +See the [ui-tests docs](../../docs/ui-test/readme.md) for how to run visual tests.
It is found in my local env. Where do you try it?

2022-08-04 12:03 UTC, rinaok commented on libs/components/README.md
> +`npx nx run components:test` or `npm test` will run unit tests for the components.
idk if it's the best solution but it doesn't look good:
<img width="904" alt="Screen Shot 2022-08-04 at 15 02 57" src="https://user-images.githubusercontent.com/10883919/182842312-6c3f143b-54af-475d-9ee8-83dc428966d5.png">

2022-08-04 12:03 UTC, rinaok commented on libs/components/README.md
> +`npx nx run components:test` or `npm test` will run unit tests for the components.
<img width="1341" alt="Screen Shot 2022-08-04 at 15 03 20" src="https://user-images.githubusercontent.com/10883919/182842373-b879b3ec-64d5-4451-9076-d63fc1bc418f.png">
this looks much nicer

2022-08-04 12:06 UTC, YonatanKra commented on libs/components/README.md
> +`npx nx run components:test` or `npm test` will run unit tests for the components.
The whole page looks uninviting...
The contribution part should be taken out of here altogether. It has no place on the front page.
All I wanted was to add the CDN links :)
If that's OK, I think we can create a new issue with ALL the remarks one might have on how the page looks like in the past 3-4 months :)

2022-08-04 12:18 UTC, rinaok commented on libs/components/README.md
> +See the [ui-tests docs](../../docs/ui-test/readme.md) for how to run visual tests.
https://vivid-7a271fg664xg.deno.dev/

2022-08-12 07:24 UTC, yinonov commented on libs/components/README.md
> +Global content delivery networks can help with fast integration within a html pages, fetching content from an URL, skipping local builds entirely.
```suggestion
Global content delivery networks can help quickly integrate content within html pages, fetching content from an URL, skipping local builds entirely.
```

2022-08-12 07:25 UTC, yinonov approved these changes

2022-08-12 07:26 UTC, merged