chore(docs): add aria-current to main side-drawer
Vonage/vivid-3 pull request #603
Opened 2022-08-04 14:55 UTC by rinaok

2022-08-05 08:24 UTC, yinonov requested changes
by replicating the same code to both layout pages in a script we ignore a principal of DRY.
perhaps we can create a new js dedicated file for this purpose. I expect it to scale as we might even need to consider some links are disclosed by default and will need to be undisclosed on load

2022-08-24 11:15 UTC, rinaok commented
> 

@yinonov 

I added a scrollTop for the sideDrawer, now it saves the last scrollTop in localStorage and know where to scroll.

We don't have disclosures yet so I think that it's fine for now, and when the day will come we can add some more functionalities.

2022-08-24 15:44 UTC, yinonov commented
> > 
> 
> 
> 
> @yinonov 
> 
> 
> 
> I've added a scrollTop for the sideDrawer, now it saves the last scrollTop in localStorage and know where to scroll.
> 
> 
> 
> We don't have disclosures yet so I think that it's fine for now, and when the day will come we can add some more functionalities.

Come to think of it, this is a common use case for SPA. Could there be a library servicing this specifically? Maybe we can unload this to a 3rd party

2022-09-06 14:48 UTC, yinonov commented on apps/docs/assets/scripts/scroll-handler.js
> +	}
what for?

2022-09-06 14:49 UTC, yinonov commented on apps/docs/_includes/navigation.njk
>  {% block content %}
does links scroll into view by default with the aria-current? 🤔

2022-09-06 14:53 UTC, rinaok commented on apps/docs/_includes/navigation.njk
>  {% block content %}
@yinonov no

2022-09-06 14:53 UTC, rinaok commented on apps/docs/assets/scripts/scroll-handler.js
> +	}
it saves the scroll, I need to change it to scrollIntoView

2022-09-07 09:38 UTC, yinonov requested changes

2022-09-07 09:38 UTC, yinonov commented on apps/docs/pages/designs.njk
> +<script>
repeating the same code is probably anti-pattern.
you can, alternatively, observe [mutations to the DOM](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)

2022-09-07 09:40 UTC, yinonov commented on apps/docs/pages/designs.njk
> +<script>
maybe a less "expensive" implementation would be to simply run query selector whenDefined (`vwc-nav-item`)

2022-09-07 11:56 UTC, rinaok commented on apps/docs/pages/designs.njk
> +<script>
@yinonov added a navigation handler

2022-09-08 10:04 UTC, rachelbt approved these changes
LGTM
Love the fact that we have indication to which component are we seeing in the docs 🥳

2022-09-08 10:10 UTC, merged