chore(list-item): migrate
Vonage/vivid-3 pull request #612
Opened 2022-08-10 14:56 UTC by rinaok

2022-08-17 08:58 UTC, yinonov commented on libs/components/src/lib/list-item/list-item.template.ts
> +		<slot name="end"><slot name="meta"></slot></slot>
2 slots?

2022-08-17 09:21 UTC, rinaok commented on libs/components/src/lib/list-item/list-item.template.ts
> +		<slot name="start">${x => affixIconTemplate(x.icon)}</slot>
@yinonov We don't have to use them.
It's from fasts listbox-option api:

![Screen Shot 2022-08-17 at 12 21 19](https://user-images.githubusercontent.com/10883919/185083449-57b4fc10-6c3a-4e51-bf9b-7115266b2ba1.png)

2022-08-17 09:22 UTC, rinaok commented on libs/components/src/lib/list-item/list-item.template.ts
> +		<slot name="end"><slot name="meta"></slot></slot>
@yinonov I wanted to use fast's slots from their API but didn't want to use the name "end" for our api.
Will it be better to leave just our slots?

![image](https://user-images.githubusercontent.com/10883919/185083677-64a32b21-1ba9-48d3-ae9f-8fdd0bd20269.png)

2022-08-17 10:41 UTC, rinaok commented
@yinonov @jshenkman @AyalaBu 

This is how the button inside a list-item looks in vivid-2, how should it look in vivid-3?

![image](https://user-images.githubusercontent.com/10883919/185099153-7163b740-8ac6-4ba2-930e-0a4ae4ace0a0.png)

2022-08-30 13:03 UTC, rachelbt commented on libs/components/src/lib/listbox-option/listbox-option.template.ts
> +			role="option">
maybe all these one needs to move to the upper div as the css classes moved

2022-08-30 13:03 UTC, rachelbt commented on libs/components/src/lib/listbox-option/listbox-option.scss
> +		display: inline-flex;
```suggestion
		display: flex;
```

2022-08-30 14:00 UTC, rinaok commented on libs/components/src/lib/listbox-option/listbox-option.template.ts
> +			role="option">
Yes I'll move it

2022-09-20 06:50 UTC, yinonov requested changes

2022-09-20 06:50 UTC, yinonov commented on libs/components/src/lib/listbox-option/index.ts
> +	baseName: 'listbox-option',
should simply be named option as is also used within select component
```suggestion
	baseName: 'option',
```

2022-10-26 13:05 UTC, closed without merging