refactor(styles): extract fonts assets to be handled by authors
Vonage/vivid-3 pull request #617
Opened 2022-08-14 10:46 UTC by yinonov

2022-08-16 20:28 UTC, yinonov commented
blocked by #621

2022-09-01 10:14 UTC, rachelbt reviewed
tried to go over all the files - wasn't easy :)
I'm sure I haven't gone through all of the files. this is what I got:

some question regarding the changes:
1. you switched the background-color to background. Why is it better or necessary? 
2. the warning orange color changes and it looks strange. I get that it aligns with the scheme but its a strange and to my opinion a bit ugly color...
3. the new font acts differently - so if we are using it with 12px font-weight 600 isn't enough and 700 is needed. Tat effects the badge for example.
4.Say one day we will switch the base font to 16px, so the condense can be 14px. do we have a name for 12px? if that will be needed.

2022-09-01 10:14 UTC, rachelbt commented on apps/docs/assets/styles/main.css
> -article > vwc-text[font-face="headline-1"] {
why did you removed it completely? can be changed to h1, no?

2022-09-01 10:28 UTC, yinonov commented on apps/docs/assets/styles/main.css
> -article > vwc-text[font-face="headline-1"] {
there's no `vwc-text` anymore

2022-09-01 10:29 UTC, yinonov commented on apps/docs/assets/styles/main.css
> -article > vwc-text[font-face="headline-1"] {
ah ok I get you

2022-09-01 10:33 UTC, yinonov commented on libs/components/src/lib/elevation/elevation.scss
>  		transition: background-color 0.15s linear, filter 0.15s linear;
using what? the transition? FAB is an example, when hovered, it changes elevation background color (only in dark theme)

2022-09-01 10:34 UTC, yinonov commented on libs/components/src/lib/layout/partials/_variables.scss
>  	block: 1fr
why? I don't get it

2022-09-01 10:36 UTC, yinonov commented
> * you switched the background-color to background. Why is it better or necessary?
background simply shorthands the background-image and background color we need to apply that mix of color values.
I'm thinking of having this mix to be rendered server side in the near future. and result in plain old background color

2022-09-01 10:38 UTC, yinonov commented
> 



> * the warning orange color changes and it looks strange. I get that it aligns with the scheme but its a strange and to my opinion a bit ugly color...

I'm with you on that. shouldn't block this PR but @AyalaBu should revisit this shade. review [snapshots changes](https://github.com/Vonage/vivid-3/pull/617/files?file-filters%5B%5D=.png&show-deleted-files=true&show-viewed-files=true)

2022-09-01 11:02 UTC, rachelbt commented on libs/components/src/lib/elevation/elevation.scss
>  		transition: background-color 0.15s linear, filter 0.15s linear;
the fab is not OK... doesnt have background
![image](https://user-images.githubusercontent.com/7512792/187899040-b7273add-4c2e-4895-b3fa-ac928f9f1598.png)

2022-09-01 11:40 UTC, rachelbt commented
> > 
> 
> > * the warning orange color changes and it looks strange. I get that it aligns with the scheme but its a strange and to my opinion a bit ugly color...
> 
> I'm with you on that. shouldn't block this PR but @AyalaBu should revisit this shade. review [snapshots changes](https://github.com/Vonage/vivid-3/pull/617/files?file-filters%5B%5D=.png&show-deleted-files=true&show-viewed-files=true)

 I saw the print-screen. I don't like them.
 But I agree - this shouldn't stop this PR

2022-09-01 11:41 UTC, yinonov commented on libs/components/src/lib/elevation/elevation.scss
>  		transition: background-color 0.15s linear, filter 0.15s linear;
that's why we need dark theme visual regression tests

2022-09-01 11:42 UTC, yinonov commented on libs/components/src/lib/elevation/elevation.scss
>  		transition: background-color 0.15s linear, filter 0.15s linear;
fixed

2022-09-01 11:43 UTC, yinonov commented
> > > 
> > 
> > 
> > > * the warning orange color changes and it looks strange. I get that it aligns with the scheme but its a strange and to my opinion a bit ugly color...
> > 
> > 
> > I'm with you on that. shouldn't block this PR but @AyalaBu should revisit this shade. review [snapshots changes](https://github.com/Vonage/vivid-3/pull/617/files?file-filters%5B%5D=.png&show-deleted-files=true&show-viewed-files=true)
> 
> I saw the print-screen. I don't like them. But I agree - this shouldn't stop this PR

I mean @AyalaBu should review the snapshots

2022-09-01 12:22 UTC, YonatanKra requested changes

2022-09-01 12:22 UTC, YonatanKra commented on libs/shared/src/lib/sass/mixins/connotation/_variables.scss
> +    primary-text: #{utils.get-color-token(canvas)},//! missing on- token
Where does `canvas` come from?

2022-09-01 12:22 UTC, YonatanKra commented on libs/shared/src/lib/sass/mixins/scrim.scss
> +	background-color: var(#{utils.get-color-token(canvas-text/*neutral-100*/)});
What do we need `/*neutral-100*/` for?

2022-09-01 12:22 UTC, YonatanKra commented on libs/shared/src/lib/sass/mixins/typography/_index.scss
> +// @use '../../../../../../../node_modules/@vonage/vivid-tokens/dist/sass/typography/web' as font-faces;
If commented, can be removed

2022-09-01 12:22 UTC, YonatanKra commented on libs/shared/src/lib/sass/mixins/typography/_index.scss
> +// $slash-char: '/';
Commented code. What for?

2022-09-01 12:22 UTC, YonatanKra commented on libs/shared/src/lib/sass/mixins/typography/_index.scss
> +// 	$category-map: map.get(font-faces.$typography-category-list, $category);
Commented code - hurts the eyes

2022-09-01 12:22 UTC, YonatanKra commented on libs/shared/src/lib/sass/mixins/typography/_index.scss
> +// }
Commented code - is a cause for heart attack

2022-09-01 12:22 UTC, YonatanKra commented on libs/shared/src/lib/sass/mixins/typography/_index.scss
> +// 	$category-map: map.get(font-faces.$typography-category-list, $category);
Commented co...

2022-09-01 12:22 UTC, YonatanKra commented on libs/shared/src/lib/sass/mixins/typography/_index.scss
> +// }
Comme....

2022-09-01 12:22 UTC, YonatanKra commented on libs/styles/src/lib/typography/desktop.scss
> +
Either needed or not. Uncomment or remove.

2022-09-01 12:22 UTC, YonatanKra commented on libs/styles/src/lib/typography/desktop.scss
> +	// 	@include typography.typography-cat-shorthand(headline-1);
Why all the comments in this file? Can we remove them? It is confusing

2022-09-01 12:22 UTC, YonatanKra commented on libs/tokens/src/lib/configurations/theme.ts
> +module.exports = (theme: string) => ({
I don't really understand.
We have `constants` file and `theme` file. They have the same field.
`constants` is too generic name without meaning. 
Can the files be given more explicit names?

2022-09-01 12:22 UTC, YonatanKra commented on libs/tokens/src/lib/transforms/font-shorthand.ts
> +// const { transformer: sizeToPx } = transform['size/px'];
Comments are for the weak. We have `source control`!

2022-09-01 12:22 UTC, YonatanKra commented on libs/tokens/src/lib/transforms/shadow-shorthand.ts
>  const { transform } = require('style-dictionary');
What is a `shorthand` in our context?

2022-09-01 12:27 UTC, yinonov commented on libs/components/src/lib/dialog/index.ts
> +import '../elevation';
yes. I actually missed it at first, which got me quite dazzled with some issue I had

2022-09-01 12:29 UTC, yinonov commented on libs/components/src/lib/layout/partials/_variables.scss
> +	large: 380px,
rem was indeterministic as I presumed the baseline (root) is 16px which isn't in every case. change the baseline now broke the UI tests. this would need a revisit to determine the best bases for each

2022-09-01 12:30 UTC, yinonov commented on libs/shared/src/lib/sass/mixins/connotation/_variables.scss
> +    primary-text: #{utils.get-color-token(canvas)},//! missing on- token
it just returns `--vvd-color-canvas` which is a token

2022-09-01 12:33 UTC, yinonov commented on libs/shared/src/lib/sass/mixins/scrim.scss
> +	background-color: var(#{utils.get-color-token(canvas-text/*neutral-100*/)});
we probably don't

2022-09-01 12:33 UTC, yinonov commented on libs/shared/src/lib/sass/mixins/typography/_index.scss
> +// $slash-char: '/';
it's gone

2022-09-01 12:33 UTC, yinonov commented on libs/shared/src/lib/sass/mixins/typography/_index.scss
> +// @use '../../../../../../../node_modules/@vonage/vivid-tokens/dist/sass/typography/web' as font-faces;
file is gone

2022-09-01 12:35 UTC, yinonov commented on libs/styles/src/lib/typography/desktop.scss
> +
this is still a work in progress and needs a revisit very soon. there are ideas in these comments. will be cleared very soon

2022-09-01 12:35 UTC, yinonov commented on libs/styles/src/lib/typography/desktop.scss
> +	// 	@include typography.typography-cat-shorthand(headline-1);
https://github.com/Vonage/vivid-3/pull/617#discussion_r960599428

2022-09-01 12:39 UTC, yinonov commented on libs/tokens/src/lib/configurations/theme.ts
> +module.exports = (theme: string) => ({
we changed them together. am trying to keep it simple.
what do u suggest? constants outputs scss constants of all tokens variable names. theme outputs theme (dark, light) tokens

2022-09-01 12:41 UTC, yinonov commented on libs/tokens/src/lib/transforms/shadow-shorthand.ts
>  const { transform } = require('style-dictionary');
<img width="615" alt="image" src="https://user-images.githubusercontent.com/15140652/187916147-2b02ce9d-c5d8-4431-a6f1-6456013a55bc.png">

2022-09-01 13:02 UTC, YonatanKra commented on libs/tokens/src/lib/configurations/theme.ts
> +module.exports = (theme: string) => ({
Ok - see. This is an example of bad naming. We did this together, and I didn't remember.
Actually - I think we talked about changing the name to `scssConstants`. I can't be sure of that, so won't say we did 100% ;)
But here I am, a few weeks later, and I can't understand what `constants` mean.

2022-09-01 13:11 UTC, YonatanKra approved these changes
Ok, just notice:
1. https://github.com/Vonage/vivid-3/pull/617#discussion_r960520537 - maybe create a new issue (can assign it to me) if you think you can define a rule for this behavior.
2. https://github.com/Vonage/vivid-3/pull/617#discussion_r960627772 - consider renaming the file. Not necessary and definitely not a blocker.

2022-09-01 13:22 UTC, merged