Listbox
Vonage/vivid-3 pull request #635
Opened 2022-08-28 17:02 UTC by rinaok

2022-09-14 18:40 UTC, yinonov requested changes
@rinaok there are 2 issues with focus needs fixing
- [ ] clicking on listbox items doesn't activate (focus) listbox
- [ ] when extending listboxElement, listbox element isn't activated (focused). extending listbox enabling it to be activated

2022-09-15 06:00 UTC, yinonov commented
listbox options, when are selected / checked, are styled by background color only. does it comply with rules? should we add another indicator?

<img width="171" alt="image" src="https://user-images.githubusercontent.com/15140652/190326084-42060531-8f36-4eac-ae51-b168da43d925.png">

2022-10-27 07:51 UTC, rinaok commented on libs/components/src/lib/listbox-option/listbox-option.scss
> +	$states: idle hover disabled active selected selectedAndHover,
There is a new PR for option, it's better to make the changes there. 
https://github.com/Vonage/vivid-3/pull/760

2022-11-02 09:35 UTC, rinaok commented on libs/components/src/lib/listbox-option/listbox-option.scss
> +	position: relative;
@rachelbt @yinonov This had to be returned. Without it, the `Multiple selection` is not working.

2022-11-02 12:00 UTC, rachelbt commented on libs/components/src/lib/listbox/listbox.scss
> +	display: inline-flex;
```suggestion

```
I don't think this is needed, and this prevent the list-box getting its parent width

2022-11-02 12:01 UTC, yinonov commented on libs/components/src/lib/listbox-option/listbox-option.scss
> +	position: relative;
and the focus indicator needs it as well

2022-11-02 13:55 UTC, olaf-k requested changes

2022-11-02 13:55 UTC, olaf-k commented on libs/components/src/lib/listbox/listbox.ts
> +		switch (name) {
a simple `if` should be enough for the time being

2022-11-02 14:24 UTC, olaf-k submitted a review, later dismissed
👍

2022-11-03 11:35 UTC, yinonov requested changes
wait for #750

2022-11-03 17:53 UTC, rinaok commented
> wait for #750

merged

2022-11-03 23:39 UTC, yinonov requested changes
mouse click on an option should set focus on listbox. additional keyboard events like arrow navigation should continue navigating through other options but it doesn't

2022-11-06 09:12 UTC, rinaok commented
> mouse click on an option should set focus on listbox. additional keyboard events like arrow navigation should continue navigating through other options but it doesn't

@yinonov @rachelbt If I return [this](https://github.com/Vonage/vivid-3/pull/635/commits/1c0ca1ffcdfda0e5164c722584d57ce957082eda) , it fixes the problem.

2022-11-06 10:20 UTC, rachelbt approved these changes
LGTM

2022-11-06 13:54 UTC, rinaok commented
@yinonov The [refactor](https://github.com/Vonage/vivid-3/commit/2e55fe2331d0d07bd0a88650a3cbf4586a308499#diff-590cb97e4da80dd05a7a1d55cd2d0a3ab33e35cdc20e565a834b949c622a63e7) in fieldset broke the listbox. Can you take a look?

2022-11-07 11:05 UTC, yinonov approved these changes

2022-11-07 11:06 UTC, merged