refactor(components): menu migrate to fast
Vonage/vivid-3 pull request #636
Opened 2022-08-29 09:21 UTC by yinonov

2022-09-09 07:15 UTC, yinonov commented on libs/components/src/lib/menu-item/index.ts
> +	styles,
```suggestion
	styles,
	shadowOptions: {
		delegatesFocus: true,
	},
```

2022-09-12 10:26 UTC, rinaok commented on libs/components/src/lib/menu-item/README.md
> + <vwc-menu-item disabled>Disabled Menu item</vwc-menu-item>
I still have mouse cursor on the disabled item.

2022-09-12 10:49 UTC, rinaok requested changes

2022-09-12 10:49 UTC, rinaok commented on libs/components/src/lib/menu-item/README.md
> + <vwc-menu-item disabled>Disabled Menu item</vwc-menu-item>
I still have mouse cursor on the disabled item.

2022-09-12 10:49 UTC, rinaok commented on libs/components/src/lib/menu-item/README.md
> +Fires a custom 'change' event when a non-submenu item with a role of `menuitemcheckbox`, `menuitemradio`, or `menuitem` is invoked
why do you have two examples for radio role?

2022-09-12 10:49 UTC, rinaok commented on libs/components/src/lib/menu/README.md
>  ## Members
The 3 links to the underlying popup element don't work. I think that we should add the description as in other components instead of the links. It is not convenient for the user to jump back and forth to read about every member.

2022-09-12 10:49 UTC, rinaok commented on libs/components/src/lib/menu/README.md
> +<vwc-menu id="menu" text="Focus or hover to open." open>
The examples will look better with an outlined button.

2022-09-12 10:49 UTC, rinaok commented on libs/components/src/lib/menu/README.md
> +  <vwc-menu id="menu" anchor="button" text="Focus or hover to open." open>
Where should I see this `Focus or hover to open.` text?

2022-09-12 10:49 UTC, rinaok commented on libs/components/src/lib/menu/README.md
>  ```
The menu is missing `disabled` attribute

2022-09-12 10:49 UTC, rinaok commented on libs/components/src/lib/menu/menu.spec.ts
> +import '../menu-item';
The `show` and `hide` tests don't check whether the menu has been changed. Look at the `show` and `hide` tests in popup.

2022-09-12 10:49 UTC, rinaok commented on apps/docs/_layouts/base.njk
> +    <link rel="preload" href="/assets/styles/fonts/SpeziaCompleteVariableItalicWeb.woff2" as="font" type="font/woff2" crossorigin>
not connected to this PR

2022-09-12 10:49 UTC, rinaok commented on apps/docs/_layouts/base.njk
> +    <dark-mode-toggle	slot="action-items" appearance="toggle" permanent></dark-mode-toggle>
not connected to this PR

2022-09-16 15:21 UTC, yinonov commented on libs/components/src/lib/menu-item/README.md
> +Fires a custom 'change' event when a non-submenu item with a role of `menuitemcheckbox`, `menuitemradio`, or `menuitem` is invoked
to show that dividing the two implicitly set a scope for each. they're not all grouped

2022-09-16 15:22 UTC, yinonov commented on libs/components/src/lib/menu/README.md
>  ```
there's no disabled to menu, it's not a form associated element

2022-09-16 15:24 UTC, yinonov commented on libs/components/src/lib/menu/README.md
>  ## Members
it is explored in #684 and described in whatwg/html#8287

2022-09-18 09:10 UTC, yinonov commented on libs/components/src/lib/menu/README.md
> +  <vwc-menu id="menu" anchor="button" text="Focus or hover to open." open>
removed

2022-09-18 09:12 UTC, yinonov commented on libs/components/src/lib/menu/menu.spec.ts
> +import '../menu-item';
there are no `show` / `hide` methods in _menu_. should there be?

2022-09-18 09:28 UTC, yinonov commented on libs/components/src/lib/menu/README.md
>  ## Members
for now I hardcoded the description

2022-09-19 05:45 UTC, rachelbt reviewed
not relevant to this issue but very noticeable here - the block-padding on the menu is not needed - it creates an un-needed space at the top & the bottom

2022-09-19 05:45 UTC, rachelbt commented on libs/components/src/lib/menu-item/menu-item.scss
> +
the icon only is either missing in the template & readme or is not needed in the css.

2022-09-19 05:45 UTC, rachelbt commented on libs/components/src/lib/menu-item/menu-item.scss
> +	position: relative;
why do we need `position: relative;` ?

2022-09-19 05:45 UTC, rachelbt commented on libs/components/src/lib/menu-item/menu-item.template.ts
> +	['expanded', Boolean(expanded)],
cant see any change in the css or usage of this class

2022-09-19 05:45 UTC, rachelbt commented on libs/components/src/lib/menu-item/menu-item.template.ts
> +	`indent-${startColumnCount}`,
cant see any change in the css or usage of this class

2022-09-19 11:39 UTC, yinonov commented on libs/components/src/lib/menu-item/menu-item.scss
> +	position: relative;
for focus component

2022-09-19 11:40 UTC, yinonov commented on libs/components/src/lib/menu-item/menu-item.template.ts
> +	['expanded', Boolean(expanded)],
there will be. the menu features cascading menu

2022-09-19 11:41 UTC, yinonov commented on libs/components/src/lib/menu-item/menu-item.template.ts
> +	`indent-${startColumnCount}`,
true, it's a fast feature to align the text horizontally in all items. removing

2022-09-20 02:19 UTC, yinonov commented on libs/components/src/lib/menu-item/menu-item.scss
> +
true. not needed at this point

2022-09-20 02:25 UTC, yinonov commented
> not relevant to this issue but very noticeable here - the block-padding on the menu is not needed - it creates an un-needed space at the top & the bottom

as in vivid-2
<img width="829" alt="image" src="https://user-images.githubusercontent.com/15140652/191153266-8aff4367-af36-43e0-9c93-6b4ad1c2cc43.png">

2022-09-20 09:38 UTC, rachelbt commented on libs/components/src/lib/menu-item/README.md
> + <vwc-menu-item>Menu item</vwc-menu-item>
```suggestion
<vwc-menu-item role="menuitem" text="Menu item 1"></vwc-menu-item>
```
without it, it looks strange:

![image](https://user-images.githubusercontent.com/7512792/191219655-f5c9b2c9-8c51-436a-b6be-6dfc6e3c502b.png)

2022-09-20 09:38 UTC, rachelbt commented on libs/components/src/lib/menu-item/menu-item.scss
> +	block-size: $min-block-size;
if there's break-word than we cant have a block-size. maybe min-block-size?
![image](https://user-images.githubusercontent.com/7512792/191222573-72f345f6-49b8-4696-b5c6-f86cb3d53bc0.png)

in vivid-2 we do not break lines, but have ellipses

2022-09-20 09:38 UTC, rachelbt commented on libs/components/src/lib/menu-item/menu-item.scss
> +	inline-size: 100%;
this is great - but doesn't get the width that is set on menu....
The menu width + line break is not working well :(

2022-09-20 09:38 UTC, rachelbt commented on libs/components/src/lib/menu/README.md
>  <div style="position: relative">
the preview is cut off - maybe add style for the html to set a preloaded height:

![image](https://user-images.githubusercontent.com/7512792/191223851-420c0437-4754-4b54-9fec-8a6ef0372ebd.png)

2022-09-20 10:49 UTC, yinonov commented on libs/components/src/lib/menu/README.md
> +`placement` property from _popup_ propagate through _menu_ and sets its position in accordance to its anchor.
Issue in popup?

2022-09-20 12:25 UTC, rachelbt commented on libs/components/src/lib/menu/README.md
> +`placement` property from _popup_ propagate through _menu_ and sets its position in accordance to its anchor.
I think the popup is OK, it sets the position relative to the anchor and the `vwc-button` as an anchor had a strange height cause its not "block" element.

2022-09-20 20:39 UTC, yinonov commented on libs/components/src/lib/menu/README.md
> +`placement` property from _popup_ propagate through _menu_ and sets its position in accordance to its anchor.
oh, should be fixed in button then

2022-09-21 14:55 UTC, rachelbt submitted a review, later dismissed
saw the related issues that you open regarding issues related.
LGTM at this point :)

2022-09-22 14:20 UTC, merged