Create build.yml
Vonage/vivid-3 pull request #65
Opened 2021-11-30 09:53 UTC by yinonov

2021-12-04 07:42 UTC, yinonov commented on .github/workflows/pre-release.yml
> +  call-pre-release:
```suggestion
  call-publish-package:
```

2021-12-04 07:43 UTC, yinonov commented on .github/workflows/_publish-package.yml
> +          scope: '@vonage'
```suggestion
```

2021-12-07 19:22 UTC, YonatanKra commented on .github/workflows/_publish-package.yml
> +name: '📦 Publish Package'
I think a better name would be `Publish Vivid`

2021-12-07 19:23 UTC, YonatanKra commented on .github/workflows/_publish-package.yml
> +    name: Publish
`Publish Vivid`

2021-12-07 19:24 UTC, YonatanKra commented on .github/workflows/_unit-tests.yml
> +      name: "Test Components on ${{ matrix.browser_name }}"
We don't need the matrix anymore.  Use this inside the main file with variables instead of this matrix.

2021-12-07 19:24 UTC, YonatanKra commented on .github/workflows/_upload-artifact.yml
> +        if: always()
?

2021-12-07 19:28 UTC, YonatanKra commented on .github/workflows/pull-request.yml
>    test:
We already have unit tests - why is this code duplicate?

2021-12-07 19:29 UTC, YonatanKra commented on .gitignore
> +_site
What is `_site`?

2021-12-08 07:14 UTC, yinonov commented on .github/workflows/pre-release.yml
> +    uses: vonage/vivid-3/.github/workflows/_lint-and-build.yml
```suggestion
    uses: ./.github/workflows/_lint-and-build.yml
```

2021-12-08 07:14 UTC, yinonov commented on .github/workflows/pre-release.yml
> +    uses: vonage/vivid-3/.github/workflows/_unit-tests.yml
```suggestion
    uses: ./.github/workflows/_unit-tests.yml
```

2021-12-08 07:14 UTC, yinonov commented on .github/workflows/pre-release.yml
> +    uses: vonage/vivid-3/.github/workflows/_upload-artifact.yml
```suggestion
    uses: ./.github/workflows/_upload-artifact.yml
```

2021-12-08 07:14 UTC, yinonov commented on .github/workflows/pre-release.yml
> +    uses: vonage/vivid-3/.github/workflows/_publish-package.yml
```suggestion
    uses: ./.github/workflows/_publish-package.yml
```

2021-12-08 12:58 UTC, yinonov commented on .github/workflows/_publish-package.yml
> +name: '📦 Publish Package'
```suggestion
name: '📦 Publish Vivid'
```

2021-12-08 13:00 UTC, yinonov commented on .github/workflows/_upload-artifact.yml
> +        if: always()
copied previous implementation. documentation only instruct the `failure()` check. what the success equivalent? `success()`?

2021-12-08 13:02 UTC, yinonov commented on .github/workflows/pull-request.yml
>    test:
it's ure code. I didn't analyze it

2021-12-08 13:03 UTC, yinonov commented on .gitignore
> +_site
11ty build
what is `+site`?

2021-12-08 18:43 UTC, yinonov commented on .github/workflows/_unit-tests.yml
> +      name: "Test Components on ${{ matrix.browser_name }}"
care to explain? or just hop on?

2021-12-08 18:54 UTC, yinonov commented on .github/workflows/_upload-artifact.yml
> +        if: always()
never mind removing
```suggestion
```

2021-12-14 15:16 UTC, YonatanKra commented on .github/workflows/_publish-package.yml
> +    name: Publish
```suggestion
```

2021-12-14 15:17 UTC, YonatanKra approved these changes

2021-12-14 15:18 UTC, YonatanKra requested changes
Wait

2021-12-15 10:13 UTC, YonatanKra approved these changes

2021-12-15 10:46 UTC, merged