feature(text-area): add text area component
Vonage/vivid-3 pull request #653
Opened 2022-09-06 11:01 UTC by YonatanKra

2022-09-06 12:59 UTC, rachelbt reviewed
after you'll add let me know I'll double check the design :)

2022-09-06 12:59 UTC, rachelbt commented on libs/components/src/lib/text-area/README.md
> +Add a `label` attribute to add label to the text field.
```suggestion
Add a `label` attribute to add label to the text area.
```

2022-09-06 12:59 UTC, rachelbt commented on libs/components/src/lib/text-area/README.md
> +Add a `placeholder` attribute to add placeholder text to the text field.
```suggestion
Add a `placeholder` attribute to add placeholder text to the text area.
```

2022-09-06 12:59 UTC, rachelbt commented on libs/components/src/lib/text-area/README.md
> +# text-area
```suggestion
# Text-area
```

2022-09-06 12:59 UTC, rachelbt commented on libs/components/src/lib/text-area/README.md
> +Set the `value` attribute to set the default value for the text field. Setting the property on the element will not change the default value, but will change the value shown in the view as well as th
```suggestion
Set the `value` attribute to set the default value for the text area. Setting the property on the element will not change the default value, but will change the value shown in the view as well as the submitted value in a form (imitating the native behavior).
```

2022-09-06 12:59 UTC, rachelbt commented on libs/components/src/lib/text-area/README.md
> +Add the `helper-text` to add some helper text below the text field.
```suggestion
Add the `helper-text` to add some helper text below the text area.
```

2022-09-06 12:59 UTC, rachelbt commented on libs/components/src/lib/text-area/README.md
> +Add the `readonly` attribute to restrict user from changing the text field's value.
```suggestion
Add the `readonly` attribute to restrict user from changing the text area's value.
```

2022-09-06 12:59 UTC, rachelbt commented on libs/components/src/lib/text-area/text-area.scss
> +  block-size: 100%;
Its parent don't have a height but only min-height, so this is the reason we need it here.
I think that its better to use the 40px as a variable

2022-09-06 12:59 UTC, rachelbt commented on libs/components/src/lib/text-area/text-area.scss
> +.error-message {
do we need it here?

2022-09-06 14:40 UTC, rachelbt commented on libs/components/src/lib/text-area/text-area.scss
> +  padding-block-start: 8px;
```suggestion

```

2022-09-06 14:40 UTC, rachelbt commented on libs/components/src/lib/text-area/text-area.scss
> +  min-block-size: 32px;
```suggestion
  min-block-size: 40px;
```

2022-09-07 10:17 UTC, rachelbt commented on libs/components/src/lib/text-area/README.md
> +```html preview blocks
```suggestion
```html preview 
```

2022-09-07 10:17 UTC, rachelbt commented on libs/components/src/lib/text-area/README.md
> +```html preview blocks
```suggestion
```html preview
```

2022-09-07 11:54 UTC, rachelbt reviewed
in vivid-2 we have auto focus that we don't have here, and we don't have here dense.

2022-09-07 11:54 UTC, rachelbt commented on libs/components/src/lib/text-area/text-area.scss
> +	border-radius: 6px;
```suggestion
	border-radius: inherit;
```

2022-09-07 11:54 UTC, rachelbt commented on libs/components/src/lib/text-area/text-area.scss
> +
```suggestion
  border-radius: 6px; 
  
```

2022-09-07 11:54 UTC, rachelbt commented on libs/components/src/lib/text-area/text-area.scss
> +	box-shadow: 0 0 0 1px var(#{appearance.get-appearance-token(outline)});
```suggestion
	box-shadow: inset 0 0 0 1px var(#{appearance.get-appearance-token(outline)});
```

2022-09-07 11:54 UTC, rachelbt commented on libs/components/src/lib/text-area/text-area.scss
> +	box-shadow: 0 0 0 1px var(#{appearance.get-appearance-token(outline)});
the inset + the change in border-radius is to make the focus nice the same as it in text-field. Basically - its aligning back to what it was before we changed and reverted :)

2022-09-07 11:54 UTC, rachelbt commented on libs/components/src/lib/text-area/README.md
> +- rows 3 and on will add 20 pixels each (lineheight)
```suggestion
`rows="1"` will have a height of 40 pixels (which is the minimum height). 
`rows="2"` will have a height of 48 pixels. 
`rows` 3 and on will add 20 pixels each (lineheight). 
```
removing the list so it will not be as the type + default.

2022-09-07 11:54 UTC, rachelbt commented on libs/components/src/lib/text-area/text-area.ts
> +type TextAreaDensity = Extract<Density, Density.Normal | Density.Extended>;
we are not using the dens one....

2022-09-08 06:22 UTC, rachelbt submitted a review, later dismissed

2022-09-09 04:52 UTC, rachelbt approved these changes

2022-09-09 05:08 UTC, yinonov requested changes

2022-09-09 05:08 UTC, yinonov commented on libs/components/src/lib/text-area/text-area.scss
> +	pointer-events: none;
Why? It has not interactive behavior

2022-09-09 05:08 UTC, yinonov commented on libs/components/src/lib/text-area/text-area.spec.ts
> +				.toBeInstanceOf(TextArea);
Don't we usually check api members defaults here?

2022-09-09 05:08 UTC, yinonov commented on libs/components/src/lib/text-area/text-area.ts
> +type TextAreaWrap = 'hard' | 'soft' | 'off';
What's this?

2022-09-09 05:08 UTC, yinonov commented on libs/components/src/lib/text-area/ui.test.ts
> +import * as path from 'path';
Can narrow the viewport? Bigger image may take longer to read

2022-09-09 05:08 UTC, yinonov commented on tsconfig.base.json
>  {
Convert back indentation?

2022-09-09 05:25 UTC, YonatanKra commented on libs/components/src/lib/text-area/README.md
> +Note that the text area has padding-block of 4 pixels and minimum height of 40 pixels.
This is unexpected behavior. It explains why 1 row is not half of 2 rows.

2022-09-09 05:26 UTC, YonatanKra commented on libs/components/src/lib/text-area/text-area.scss
> +	pointer-events: none;
Why what? Please explain. This pattern was taken from `text-field` styles.

2022-09-09 05:27 UTC, YonatanKra commented on libs/components/src/lib/text-area/text-area.spec.ts
> +				.toBeInstanceOf(TextArea);
I test each default in its own describe if it has any.
Would you like me to add it here as well?

2022-09-09 05:28 UTC, YonatanKra commented on libs/components/src/lib/text-area/text-area.ts
> +type TextAreaWrap = 'hard' | 'soft' | 'off';
Implementation of the `wrap` attribute of the native `text-area`

2022-09-09 05:31 UTC, YonatanKra commented on libs/components/src/lib/action-group/ui.test.ts
> +					maxDiffPixelRatio: 0.02
Lax the pixel matching on action-group to prevent flakiness due to one pixel motion

2022-09-09 06:04 UTC, yinonov commented on libs/components/src/lib/text-area/README.md
> +Note that the text area has padding-block of 4 pixels and minimum height of 40 pixels.
is it introducing a new behavior different than native text area?

2022-09-09 06:07 UTC, yinonov commented on libs/components/src/lib/text-area/text-area.scss
> +	pointer-events: none;
oh to avoid blocking the input

2022-09-09 06:29 UTC, yinonov commented on libs/components/src/lib/text-area/text-area.spec.ts
> +				.toBeInstanceOf(TextArea);
yeah, it's also easy to understand the members up front. like an index

2022-09-09 07:22 UTC, yinonov requested changes

2022-09-09 07:22 UTC, yinonov commented on libs/components/src/lib/text-area/index.ts
> +	styles,
```suggestion
	styles,
	shadowOptions: {
		delegatesFocus: true,
	},
```

2022-09-09 09:30 UTC, YonatanKra commented on libs/components/src/lib/text-area/index.ts
> +	styles,
Why do we need to delegate the focus? It works without it.

2022-09-09 09:31 UTC, YonatanKra commented on libs/components/src/lib/text-area/README.md
> +Note that the text area has padding-block of 4 pixels and minimum height of 40 pixels.
Yes. Our design behavior.

2022-09-09 10:03 UTC, yinonov approved these changes

2022-09-09 10:19 UTC, merged