chore: document the development experience for a component
Vonage/vivid-3 pull request #67
Opened 2021-12-01 07:53 UTC by YonatanKra

Closes #30

2021-12-01 08:51 UTC, yinonov requested changes

2021-12-01 08:51 UTC, yinonov commented on docs/development-process.md
> +Please watch [the following video](https://drive.google.com/file/d/1pvSKmGAm-uoIfKyZBarrapwm5q_wzAs5/view) in order to understand the development process.
paste the video right here?

2021-12-01 08:51 UTC, yinonov commented on docs/development-process.md
> +   1. Make sure to that the `afterEach` that clears the DOM from the tests' artifacts is not active.
```suggestion
   1. Make sure that the `afterEach` that clears the DOM from the tests' artifacts is not active.
```

2021-12-01 08:51 UTC, yinonov commented on docs/development-process.md
> +   1. Make sure to that the `afterEach` that clears the DOM from the tests' artifacts is not active.
maybe rephrase that?
Ensure `afterEach` method (that clears the DOM from the tests' artifacts) is inactive

2021-12-01 08:51 UTC, yinonov commented on docs/development-process.md
> +5. In webstorm, use `cmd` + `shift` + `t` in order to toggle between the test and the business logic file.
webstorm related? u can toggle in vscode as well with cmd + p. important here?

2021-12-01 08:51 UTC, yinonov commented on karma.conf.ts
> +                watched: true
we still need to decide if this is a coupled API or a "3rd party asset" what if we have more assets to observe?

2021-12-01 08:51 UTC, yinonov commented on karma.conf.ts
> +            'src/core/theme/**/*.scss': ['scss']
(same)

2021-12-01 08:51 UTC, yinonov commented on src/components/badge/badge.scss
> +.badge.layout-filled, .badge:not(.layout-outlined):not(.layout-soft) {
I wouldn't do that just yet. we'll have stylelint to do that for us

2021-12-01 08:51 UTC, yinonov commented on package.json
> +    "node-sass": "^6.0.1",
where do we use this?

2021-12-01 09:44 UTC, YonatanKra commented on docs/development-process.md
> +5. In webstorm, use `cmd` + `shift` + `t` in order to toggle between the test and the business logic file.
that's different. cmd + p is to search for files. In webstorm you toggle between code and its test file.

2021-12-01 09:44 UTC, YonatanKra commented on karma.conf.ts
> +                watched: true
If we have more assets, we will bring them here. Right now this is the setup :)

2021-12-01 09:44 UTC, YonatanKra commented on karma.conf.ts
> +            'src/core/theme/**/*.scss': ['scss']
(same) :)

2021-12-01 09:44 UTC, YonatanKra commented on package.json
> +    "node-sass": "^6.0.1",
Inside karma

2021-12-01 09:45 UTC, YonatanKra commented on docs/development-process.md
> +Please watch [the following video](https://drive.google.com/file/d/1pvSKmGAm-uoIfKyZBarrapwm5q_wzAs5/view) in order to understand the development process.
Care to show me how?
The only way I saw was to add an image that is a link to the video.

2021-12-01 13:14 UTC, yinonov commented on docs/development-process.md
> +Please watch [the following video](https://drive.google.com/file/d/1pvSKmGAm-uoIfKyZBarrapwm5q_wzAs5/view) in order to understand the development process.
edit in GitHub
![image](https://user-images.githubusercontent.com/15140652/144240772-8f90b47a-80a0-4831-9049-2fdfab8767b5.png)

2021-12-01 13:18 UTC, yinonov commented on docs/development-process.md
> +5. In webstorm, use `cmd` + `shift` + `t` in order to toggle between the test and the business logic file.
toggle between symbols in page is also available. I just think it's an IDE related
if must, add it as a small caption hint/tip?
`CMD` + `SHIFT` + `O`
![image](https://user-images.githubusercontent.com/15140652/144241327-920f5d54-1b5f-4d9a-aec1-df5afa1a0197.png)

2021-12-01 13:19 UTC, yinonov commented on package.json
> +    "node-sass": "^6.0.1",
why not use the sass that is already a dependency? is it Karma's peer d.?

2021-12-01 14:00 UTC, YonatanKra commented on package.json
> +    "node-sass": "^6.0.1",
It's the karma processor peer. I could write my own karma-sass processor, but thought to take this shortcut. It is a peer dependency of the karma-sass-processor package I'm using here.

2021-12-08 19:29 UTC, yinonov approved these changes
I still believe the 5th point is a little off

2022-02-06 04:27 UTC, closed without merging