fix(documentation): native attributes
Vonage/vivid-3 pull request #679
Opened 2022-09-13 11:51 UTC by rachelbt

2022-09-13 12:41 UTC, rinaok requested changes

2022-09-13 12:41 UTC, rinaok commented on libs/components/src/lib/text-field/README.md
> +789# Text Field
```suggestion
# Text Field
```

2022-09-13 12:42 UTC, rinaok requested changes

2022-09-13 12:42 UTC, rinaok commented on libs/components/src/lib/dialog/README.md
> +All native attributes of `checkbox` are supported as well as some enhancements.
checkbox?

2022-09-14 07:25 UTC, rachelbt commented on libs/components/src/lib/dialog/README.md
> +All native attributes of `checkbox` are supported as well as some enhancements.
> checkbox?

```suggestion
All native attributes of `dialog` are supported as well as some enhancements.
```

2022-09-14 09:01 UTC, yinonov approved these changes

2022-09-14 20:00 UTC, yinonov approved these changes

2022-09-19 07:37 UTC, merged