chore(ui-tests): extract test use cases from readme
Vonage/vivid-3 pull request #68
Opened 2021-12-02 06:35 UTC by YonatanKra

2021-12-02 07:17 UTC, yinonov requested changes

2021-12-02 07:17 UTC, yinonov commented on package.json
> +    "extract-gfm": "^0.1.0",
not sure if explored already but this lib's last publish is 7 years old.
this seem more recent https://github.com/earldouglas/codedown
(your call)

2021-12-02 07:17 UTC, yinonov commented on src/components/badge/ui.test.ts
> +	const template = extractHTMLBlocksFromReadme(path.join(__dirname, 'README.md')).reduce((accumulator: string, block: string) => {
funny that the eslint threw on reduce's acc

2021-12-02 07:17 UTC, yinonov commented on src/components/badge/ui.test.ts
> +	const template = extractHTMLBlocksFromReadme(path.join(__dirname, 'README.md')).reduce((accumulator: string, block: string) => {
filters to only fetch html snippets?

2021-12-02 13:21 UTC, YonatanKra commented on src/components/badge/ui.test.ts
> +	const template = extractHTMLBlocksFromReadme(path.join(__dirname, 'README.md')).reduce((accumulator: string, block: string) => {
It's more funny since I put a rule to overule this throw... didn't give it too much effort though. Maybe you can come up with something (look at the eslint change).
I take only `html`.  Do you have a use case for `JS`? That's a bit more complex I think and not cost effective...

2021-12-03 06:12 UTC, yinonov requested changes

2021-12-03 06:12 UTC, yinonov commented on src/components/badge/ui.test.ts
> +	const template = extractHTMLBlocksFromReadme(path.join(__dirname, 'README.md')).reduce((accumulator: string, block: string) => {
you could reduce over a nodeList which is more explicit.
there's [this](https://stackoverflow.com/a/66902167/3027703) solution but it's too TAFUR for the specific use-case.
alternatively just do
```js
const template = extractHTMLBlocksFromReadme(path.join(__dirname, 'README.md'))
		.reduce((accumulator: string, block: string) => `${accumulator} <div style="margin: 5px;">${block}</div>`, '');
```

2021-12-06 16:15 UTC, YonatanKra commented on package.json
> +    "extract-gfm": "^0.1.0",
`codedown` doesn't have exposed API.  I could make a PR on their repository (or fork theirs and take over it).

2021-12-06 17:07 UTC, yinonov requested changes

2021-12-06 17:07 UTC, yinonov commented on .eslintrc
> +    ],
no longer needed right?

2021-12-07 05:42 UTC, YonatanKra commented on .eslintrc
> +    ],
It actually didn't work, so can remove

2021-12-07 11:51 UTC, yinonov approved these changes

2021-12-07 11:51 UTC, merged