add new component
Vonage/vivid-3 pull request #682
Opened 2022-09-15 08:55 UTC by rachelbt

2022-09-17 18:18 UTC, yinonov reviewed
I don't recall if we discussed this as an independent component. it could rather be a service / utility.

have any other examples for components using initials?

2022-09-17 18:21 UTC, yinonov requested changes

2022-09-17 18:21 UTC, yinonov commented on libs/components/src/lib/initials/initials.template.ts
> +	const letterTrimming = theName.split(' ')[0].charAt(0).toUpperCase() + theName.split(' ')[1].charAt(0).toUpperCase();
there could probably a stable open source service out-there. let's adopt tooling here rather than try and maintain assertion, casing, formatting etc'.

2022-09-18 10:30 UTC, rachelbt commented on libs/components/src/lib/initials/initials.template.ts
> +	const letterTrimming = theName.split(' ')[0].charAt(0).toUpperCase() + theName.split(' ')[1].charAt(0).toUpperCase();
something like this:
https://www.npmjs.com/package/initials
?

2022-09-18 11:13 UTC, yinonov commented on libs/components/src/lib/initials/initials.template.ts
> +	const letterTrimming = theName.split(' ')[0].charAt(0).toUpperCase() + theName.split(' ')[1].charAt(0).toUpperCase();
Exactly, although I don't see support for more than 2 names. Some people have more. Are there any others? If not let's start with it and even contribute

2022-09-19 07:15 UTC, rachelbt commented
> I don't recall if we discussed this as an independent component. it could rather be a service / utility.
> 
> have any other examples for components using initials?
we talked about it as a separate component but related to the avatar.
Maybe its more accurate to call it - avatar-initials

2022-09-19 07:48 UTC, rachelbt commented on libs/components/src/lib/initials/initials.template.ts
> +	const letterTrimming = theName.split(' ')[0].charAt(0).toUpperCase() + theName.split(' ')[1].charAt(0).toUpperCase();
I found 2 others but the last update was more that 5 years ago...
I don't think we need to support more than 2 letters. It will break the design.

2022-09-29 13:20 UTC, rachelbt commented
no need for a separate component.

2022-09-29 13:20 UTC, closed without merging