refactor(docs): remove duplications from main style
Vonage/vivid-3 pull request #689
Opened 2022-09-18 18:01 UTC by yinonov

2022-09-19 06:00 UTC, rachelbt requested changes

2022-09-19 06:00 UTC, rachelbt commented on apps/docs/_layouts/base.njk
> +  <vwc-side-drawer open slot="app-content">
```suggestion
  <vwc-side-drawer open id="sidedrawer"  slot="app-content">
```

2022-09-19 12:37 UTC, rachelbt commented on apps/docs/assets/styles/main.css
>    padding-block-start: 40px;
```suggestion
  padding-block-start: 20px;
```
there's too much extra space at the top

2022-09-20 01:02 UTC, yinonov commented on apps/docs/assets/styles/main.css
>    padding-block-start: 40px;
unrelated to this scope

2022-09-20 01:06 UTC, vng-vivid requested changes

2022-09-20 01:06 UTC, vng-vivid commented on apps/docs/_layouts/base.njk
> +  <vwc-side-drawer open id="sidedrawer"  slot="app-content">
```suggestion
  <vwc-side-drawer id="sidedrawer" open slot="app-content">
```

2022-09-20 01:06 UTC, vng-vivid commented on apps/docs/_layouts/base.njk
> +<vwc-header id="header-main"  slot="app-content">
```suggestion
<vwc-header id="header-main" slot="app-content">
```

2022-09-20 01:09 UTC, vng-vivid approved these changes

2022-09-20 01:45 UTC, merged