feat(components): add radio button
Vonage/vivid-3 pull request #696
Opened 2022-09-22 09:51 UTC by olaf-k

2022-09-22 10:02 UTC, yinonov requested changes

2022-09-22 10:02 UTC, yinonov commented on libs/components/package.json
>  {
can u align with the existing format (space / tabs)? just not to generate irrelevant changes

2022-09-22 10:02 UTC, yinonov commented on libs/components/src/lib/radio/radio.template.ts
> +		@click="${(x, c) => x.clickHandler(c.event as MouseEvent)}"
these belong on the control

2022-09-22 10:02 UTC, yinonov requested changes
should also add exporting from `components.ts`

2022-09-22 12:31 UTC, olaf-k commented on libs/components/package.json
>  {
sure, no idea what happened here.

2022-09-22 12:33 UTC, olaf-k commented on libs/components/src/lib/radio/radio.template.ts
> +		@click="${(x, c) => x.clickHandler(c.event as MouseEvent)}"
Shouldn't all this apply to the entire component, control + label included? The checkbox is also designed like this.

2022-09-23 07:19 UTC, yinonov commented on libs/components/src/lib/radio/radio.template.ts
> +		@click="${(x, c) => x.clickHandler(c.event as MouseEvent)}"
true 🤔

2022-09-23 07:23 UTC, yinonov commented on libs/components/src/lib/radio/README.md
> +Radio components on their own do not make sense. They should always be used inside `radio-group` containers.
maybe quote an aria definition

2022-09-28 12:00 UTC, yinonov commented on libs/components/src/lib/radio/index.ts
> +	shadowOptions: {
what made u eventually choose focus delegation?

2022-09-28 12:03 UTC, yinonov requested changes

2022-09-28 12:03 UTC, yinonov commented on libs/components/src/lib/radio/radio.scss
> +		box-shadow: inset 0 0 0 $selected-border var(#{appearance.get-appearance-token(fill)});
this is already handled by the appearance mixin

https://github.com/Vonage/vivid-3/blob/3720d1b346de4c732b72266b2e6520c7a8ea3fb5/libs/shared/src/lib/sass/mixins/appearance/_mixins.scss#L12-L31

2022-09-28 12:09 UTC, olaf-k commented on libs/components/src/lib/radio/index.ts
> +	shadowOptions: {
this avoids the vwc-radio from getting focus (outlining control + label) and keep it around the control

2022-09-28 12:11 UTC, yinonov commented on libs/components/src/lib/radio/radio.spec.ts
> +import { createFormHTML, elementUpdated, fixture, getBaseElement, listenToFormSubmission } from '@vivid-nx/shared';
in general, u can review and even extract tests from https://github.com/microsoft/fast/blob/8711e8ad82f13c6c67007b43f910b72c27494343/packages/web-components/fast-foundation/src/radio/radio.pw.spec.ts

2022-09-28 12:12 UTC, olaf-k commented on libs/components/src/lib/radio/radio.scss
> +		box-shadow: inset 0 0 0 $selected-border var(#{appearance.get-appearance-token(fill)});
well that's what I thought but I spent a loooong time trying to figure out a combination of appearance tokens that would match all the states to no avail.
this was the least verbose override I could come up with.

2022-09-28 12:13 UTC, olaf-k commented on libs/components/src/lib/radio/radio.spec.ts
> +import { createFormHTML, elementUpdated, fixture, getBaseElement, listenToFormSubmission } from '@vivid-nx/shared';
👍 will have a look!

2022-09-28 20:15 UTC, yinonov commented on libs/components/src/lib/radio/radio.scss
> +	}
```suggestion

	@supports selector(:focus-visible) {
		&:focus {
			outline: none;
		}
	}

	@supports (user-select: none) {
		user-select: none;
	}

	&:not(.disabled) {
		cursor: pointer;
	}

	&.disabled {
		cursor: not-allowed;
	}
```

2022-09-29 10:13 UTC, rachelbt commented on libs/components/src/lib/radio/radio.scss
> +$control-size: 20px;
in Vivid-2 the radio size is 22px and the gap is 10px, in Figam the size is 20px and gap is 8px. 
@yinonov which design are we following here?

2022-09-29 11:34 UTC, yinonov commented on libs/components/src/lib/radio/radio.scss
> +$control-size: 20px;
most consistent form is 20px
https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=1987%3A24620

2022-09-29 12:15 UTC, rachelbt commented on libs/components/src/lib/radio/radio.scss
> +$control-size: 20px;
than gap need to be 8px :)

2022-09-29 12:16 UTC, rachelbt commented on libs/components/src/lib/radio/radio.scss
> +	gap: 10px;
```suggestion
	gap: 8px;
```

2022-10-05 10:44 UTC, olaf-k commented
a11y validation fails because Axe considers that radio components should not be made read-only (but doesn't complain for checkboxes 🤷‍♀️)

2022-10-11 12:26 UTC, yinonov commented on libs/components/src/lib/radio/radio.template.ts
> +	<span class="${getClasses}"
mind the pitfall where radio-group sets certain attributes (instead of a better practice of properties) on host that correlate with other aria attributes which here are set on inner part.
if they are not set on the same element, they might not make any sense to assistive technology.
we might wanna add dedicated a11y unit tests on radio group to validate such mutations

2022-10-11 13:05 UTC, yinonov requested changes

2022-10-11 13:05 UTC, yinonov commented on libs/components/src/lib/radio/radio.spec.ts
> +	});
remove?

2022-10-12 08:38 UTC, yinonov requested changes

2022-10-12 08:38 UTC, yinonov commented on libs/components/src/lib/radio/radio.spec.ts
> +			expect(classes.contains('readonly')).toBeTruthy();
as radio button won't support `readonly`, it doesn't make sense to test it here.

instead, test readonly functionality within radio group. when readio group is set to readonly, any interaction to its radio buttons won't change anything

2022-10-12 13:37 UTC, yinonov approved these changes

2022-10-13 08:19 UTC, merged