fix(components): consistent size for checkbox and radio
Vonage/vivid-3 pull request #697
Opened 2022-09-22 13:42 UTC by olaf-k

The current Figma file makes the checkbox and the radio controls 20×20px with a 10px gap from the label.
I can either update my current PR for the radio and align it with the checkbox or merge this to change the checkbox.

2022-09-29 13:09 UTC, olaf-k commented on libs/components/src/lib/checkbox/checkbox.scss
> +	color: var(#{appearance.get-appearance-token(text)});
see https://github.com/Vonage/vivid-3/pull/696#discussion_r983487597

2022-09-29 14:44 UTC, rachelbt reviewed
you are missing ui test png's :)

2022-09-29 14:44 UTC, rachelbt commented on libs/components/src/lib/checkbox/checkbox.scss
> +	color: var(#{appearance.get-appearance-token(text)});
this causes the text to be white when the chackbox is checked:
![Uploading image.png…]()

2022-09-30 09:40 UTC, yinonov requested changes

2022-09-30 09:40 UTC, yinonov commented on libs/components/src/lib/checkbox/checkbox.scss
> +	color: var(#{appearance.get-appearance-token(text)});
this PR should scope the consistence in sizing. I created another PR to modify checkbox styling Vonage/vivid-3#705

2022-09-30 15:06 UTC, yinonov approved these changes

2022-09-30 16:29 UTC, merged