refactor(components): migrate tabs to fast
Vonage/vivid-3 pull request #699
Opened 2022-09-22 16:51 UTC by yinonov

2022-11-23 11:28 UTC, AyalaBu commented
@rinaok 
In the vertical tabs component "hover"/"selected" indication must always be the same width,
like in this example:

![Screenshot 2022-11-23 at 13 26 39](https://user-images.githubusercontent.com/106529909/203535679-e3bf204f-d8e2-4c5e-be6c-27e64e40fcad.png)

This is the link to Figma:
https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19097%3A81830&t=pYTzgCh1RB4ypPYV-1

2022-11-24 11:53 UTC, AyalaBu commented
@rinaok 
I made some changes to the info connotation in tabs text 
for it to be in line with the other elements with ghost appearance,
Please take a look and change accordingly:

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19097%3A81791&t=n460dkt4vqkK2LqH-1

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19097%3A81745&t=n460dkt4vqkK2LqH-1

2022-11-24 16:14 UTC, rachelbt commented on libs/components/src/lib/tab/tab.scss
> +	display: inline-flex;
```suggestion
	display: flex;
```

2022-11-24 17:10 UTC, rinaok commented
@rachelbt @yinonov @AyalaBu 

I think that the PR is ready :)

2022-11-24 17:21 UTC, AyalaBu commented
@rinaok @yinonov 
The developed tabs don't look like a design I created at all.

These are the links to Figma:
https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19097%3A81745&t=n460dkt4vqkK2LqH-1

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19097%3A81791&t=n460dkt4vqkK2LqH-1

The appearance is ghost, 
with bg 50 in hover state, and 100 in enabled state.
This pattern should repeat in all the ghost component.

Also the indicator is way under the tab itself,
it's supposed to be 1px in & 1px out.

Also,
the padding is not like in design at all.

2022-11-27 13:39 UTC, rinaok approved these changes

2022-12-20 15:33 UTC, rinaok approved these changes

2022-12-21 12:29 UTC, yinonov commented on libs/components/src/lib/components.ts
> +export * from './tabs/definition';
what about `tab` and `tab-panel`?

2022-12-21 14:06 UTC, rinaok approved these changes

2022-12-22 11:28 UTC, rachelbt reviewed
@rinaok - I went over and remembered why this is not done yet :) 
visual things that are still need to be tended:

- the focus ring need to be on only when keyboard navigation
- not sure about the vertical design. Maybe we should remove it for now? in Vivid-2 we do not have it
- the selected underline transition is not fixed yet (get offset width and position and after a split second its OK)

2022-12-22 11:28 UTC, rachelbt commented on libs/components/src/lib/tab-panel/README.md
> +## Use Cases
```suggestion

```

2022-12-25 12:44 UTC, rinaok commented
> @rinaok - I went over and remembered why this is not done yet :) visual things that are still need to be tended:
> 
> * the focus ring need to be on only when keyboard navigation
> * not sure about the vertical design. Maybe we should remove it for now? in Vivid-2 we do not have it
> * the selected underline transition is not fixed yet (get offset width and position and after a split second its OK)

@rachelbt @yinonov 

1. Why the focus ring should be only on navigation? In vwc-option for example the focus ring is activated on click.
2. Why should we remove the vertical design? I don't remember that we talked about it.
3. I think that the selected underline should be fixed with css, right?

2022-12-26 15:54 UTC, yinonov reviewed
Tab-panel documentation is missing. There's no recollection of it, what it's for or how to use it

2022-12-26 15:54 UTC, yinonov reviewed
Tab-panel documentation is missing. There's no recollection of it, what it's for or how to use it

2022-12-27 09:28 UTC, yinonov reviewed
there's an issue with tabs foundation enforcing `activeindicator` property which lets authors remove the indicator if they wish to.
we need to reinforce the indicator to always show

https://github.com/microsoft/fast/blob/6ebb5ec7bdb7666f49ddc524bc56f70a2e8aa574/packages/web-components/fast-foundation/src/tabs/tabs.ts#L139-L146

2022-12-27 10:05 UTC, rinaok commented
> Tab-panel documentation is missing. There's no recollection of it, what it's for or how to use it

2022-12-27 10:09 UTC, rinaok commented
> Tab-panel documentation is missing. There's no recollection of it, what it's for or how to use it

@yinonov I don't think that we should have tab-panel readme file. It cannot live without the tabs and the tab. Therefore, it will look exactly the same as tabs readme.

2022-12-27 11:58 UTC, yinonov commented on libs/components/src/lib/tabs/tabs.scss
> +		box-shadow: 1px 0 0 0 var(--vvd-color-neutral-300);
magic strings

2022-12-27 11:58 UTC, yinonov commented on libs/components/src/lib/tabs/tabs.scss
> +		border-bottom: 1px solid var(--vvd-color-neutral-300);
magic strings

2022-12-27 13:44 UTC, yinonov commented
partially patched up the janky transitioned active-indicator -
width is now determined by css variable assigned with the current active tab `getClientRect().width`.
The tabs container active-indicator is responsible for the smooth animation of transitioning from 1 active tab to another active tab when changed.
this active-indicator element is only visible when transitioned. this requires each of the individual child tabs to set their own active-indicator style when they're active. reason is to support edge case of a tab character data mutation. otherwise the animated active-indicator requires a mutation observer of character data. seem like a complete overkill when there are feasible css hacks around that.

there's still an issue of first change not well baked by fast.
indicator offsets unexpectedly outside horizontal boundaries. `.active-indicator` element seem to require an initial setting of
```css
grid-column: ...;
transform: translateX(...);
```
<img width="810" alt="image" src="https://user-images.githubusercontent.com/15140652/209675028-5dd5140b-bc77-441b-ac94-1ab44c6e3d58.png">

2023-01-04 08:14 UTC, yinonov commented
> > Tab-panel documentation is missing. There's no recollection of it, what it's for or how to use it
> 
> @yinonov I don't think that we should have tab-panel readme file. It cannot live without the tabs and the tab. Therefore, it will look exactly the same as tabs readme.

not a readme, but a mention in tabs, at least. on why is it there?

2023-01-05 16:10 UTC, olaf-k commented on libs/components/src/lib/tabs/tabs.ts
> +		if (this.orientation === 'vertical') {
```suggestion
		if (this.orientation === TabsOrientation.vertical) {
```
(requires adding `TabsOrientation` to the imports)

2023-01-08 11:59 UTC, yinonov commented on libs/components/src/lib/tabs/tabs.scss
> +		border-bottom: 1px solid var(--vvd-color-neutral-300);
```suggestion
		border-bottom: 1px solid var(#{constants.$vvd-color-neutral-300});
```

2023-01-09 09:24 UTC, rinaok commented
@YonatanKra Do you have any idea why the test is failing?

2023-01-09 10:28 UTC, olaf-k commented
About the UT failure: you can't retrieve a custom CSS var, [it's a jsdom limitation](https://github.com/jsdom/cssstyle/issues/89#issuecomment-1316428531).

2023-01-09 11:13 UTC, yinonov commented
> > @YonatanKra Do you have any idea why the test is failing?
> 
> 
> 
> About the UT failure: you can't retrieve a custom CSS var, [it's a jsdom limitation](https://github.com/jsdom/cssstyle/issues/89#issuecomment-1316428531).

Oh. Is there a workaround?

2023-01-09 11:29 UTC, YonatanKra commented on libs/components/src/lib/tab/README.md
> +## Members
Notice there are members that are not documented. Not here and not in the tests.
These are members that are exposed to the user and are in the [FAST documentation of tabs](https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation/src/tabs#fields) like `activetab`.

2023-01-09 11:29 UTC, YonatanKra requested changes
Notice my comments regarding missing APIs. Is this on purpose?

2023-01-09 11:33 UTC, olaf-k commented
There are two issues with the coverage:
1. Two paths not taken when `activeIndicatorRef?` is not defined, in `orientationChanged()` and `patchIndicatorStyleTransition()`. It seems that `activeIndicatorRef` is kept when `showActiveIndicator` is switched false (which is not gracefully handled by the component it seems.)
2. jsdom does not handle `getClientRects` (another limitation), you need to mock it.
```js
window.HTMLElement.prototype.getClientRects = function () {
    return [ { width: 10 } ] as unknown as DOMRectList;
}
```

2023-01-09 11:39 UTC, rinaok commented on libs/components/src/lib/tab/README.md
> +## Members
We are missing `hideActiveIndicator`. I think that `activetab` should not be in the docs

2023-01-09 11:41 UTC, rinaok commented on libs/components/src/lib/tab/README.md
> +## Members
But I'm not sure we want to expose `hideActiveIndicator` as well, @yinonov what do you think?

2023-01-09 11:42 UTC, olaf-k commented
> > > @YonatanKra Do you have any idea why the test is failing?
> > 
> > 
> > About the UT failure: you can't retrieve a custom CSS var, [it's a jsdom limitation](https://github.com/jsdom/cssstyle/issues/89#issuecomment-1316428531).
> 
> Oh. Is there a workaround?

you mean like using Playwright? 😁

2023-01-09 13:16 UTC, yinonov commented on libs/components/src/lib/tab/README.md
> +## Members
the fast version we use is still using `showActiveIndicator`. `hideActiveIndicator` is introduced in their alpha

2023-01-09 13:17 UTC, yinonov commented on libs/components/src/lib/tab/README.md
> +## Members
anyway, we don't want to expose it. correct

2023-01-09 13:54 UTC, YonatanKra commented
> > > > @YonatanKra Do you have any idea why the test is failing?
> > > 
> > > 
> > > About the UT failure: you can't retrieve a custom CSS var, [it's a jsdom limitation](https://github.com/jsdom/cssstyle/issues/89#issuecomment-1316428531).
> > 
> > 
> > Oh. Is there a workaround?
> 
> you mean like using Playwright? 😁

The problem with playwright is that it opens a new browser for every spec file.
It is slow and resource consuming (comes hand in hand).
That's what FAST is doing, and while working on the grid, I see a lot of issues with that (besides the fact their tests take a lot of time to run locally on my machine, with lots of flakiness).

2023-01-09 14:10 UTC, olaf-k commented
> The problem with playwright is that it opens a new browser for every spec file. It is slow and resource consuming (comes hand in hand). That's what FAST is doing, and while working on the grid, I see a lot of issues with that (besides the fact their tests take a lot of time to run locally on my machine, with lots of flakiness).

it's a tradeoff. by choosing DX over accuracy, we should be aware we'll have unexpected behaviors in our tests (which, in turn, impact DX). I sympathize with [the lack of watch mode](https://github.com/microsoft/playwright/issues/7035) which has been reported two years ago and have made [a pros & cons list of PW vs jsdom here](https://github.com/Vonage/vivid-3/issues/839).

2023-01-15 11:15 UTC, rinaok commented on libs/components/src/lib/tab/README.md
> +## Members
@yinonov the link is broken

2023-01-15 14:43 UTC, rachelbt commented on libs/components/src/lib/tabs/tabs.scss
> +		box-shadow: 1px 0 0 0 var(--vvd-color-neutral-300);
```suggestion
		box-shadow: 1px 0 0 0 var(#{constants.$vvd-color-neutral-300});
```

2023-01-15 14:44 UTC, rachelbt commented on libs/components/src/lib/tabs/tabs.scss
> +
```suggestion
@use "../../../../../dist/libs/tokens/scss/tokens.constants" as constants;

```

2023-01-15 20:43 UTC, rinaok approved these changes

2023-01-16 06:55 UTC, yinonov commented on libs/components/src/lib/tab/README.md
> +## Members
fixed

2023-01-16 06:58 UTC, yinonov reviewed
tab ui snapshots are broken

2023-01-16 12:00 UTC, rinaok approved these changes

2023-01-16 12:14 UTC, merged