feat(components): add radio group
Vonage/vivid-3 pull request #701
Opened 2022-09-26 16:31 UTC by olaf-k

2022-09-26 16:35 UTC, olaf-k commented
WIP, component needed to work with #696

2022-10-06 05:58 UTC, rachelbt commented on libs/components/src/lib/radio-group/radio-group.template.ts
> +		<span
```suggestion
		<div
```

2022-10-06 05:58 UTC, rachelbt commented on libs/components/src/lib/radio-group/radio-group.template.ts
> +		</span>
```suggestion
		</div>
```

2022-10-06 05:58 UTC, rachelbt commented on libs/components/src/lib/radio-group/radio-group.scss
>  	flex-wrap: wrap;
in the code foe the horizontal & vertical I suggest changing the column/row-gap to plain `gap: 8px` we need it when the wrap is on:
![image](https://user-images.githubusercontent.com/7512792/194225366-be2f68db-b7e2-4d20-8ff4-358e13d4ceac.png)

and for horizontal - there's no need for `flex-direction: row; this is the default behaviour of flex.

2022-10-20 12:41 UTC, yinonov requested changes

2022-10-20 12:41 UTC, yinonov commented on libs/components/src/lib/radio-group/README.md
> +    <vwc-radio label="1" value="1" checked></vwc-radio>
first show the default unchecked
```suggestion
    <vwc-radio label="1" value="1"></vwc-radio>
```

2022-10-20 12:41 UTC, yinonov commented on libs/components/src/lib/radio-group/radio-group.template.ts
> +			role="radiogroup"
the role is set on the base first element of the template but the complimenting attributes are set from within the class to the host itself

these paired aria attributes should probably be set on the same element
![image](https://user-images.githubusercontent.com/15140652/196950399-35ac93c2-e68e-4ad3-a3dd-72b340d66c7a.png)

not sure this makes any sense and what assistive technology actually reads it. can u ensure this is a valid practice or not?

2022-10-20 12:41 UTC, yinonov commented on libs/components/src/lib/radio-group/radio-group.template.ts
> +			role="radiogroup"
same goes for radio component
![image](https://user-images.githubusercontent.com/15140652/196951132-563622cd-fab6-4be9-bc93-109e5f588197.png)

2022-10-21 09:21 UTC, olaf-k commented on libs/components/src/lib/radio-group/radio-group.template.ts
> +			role="radiogroup"
I think we already talked about this, which is the reason for [the additional Axe test](https://github.com/Vonage/vivid-3/blob/3572b135e1a979937066235f692cbfaf8676388e/libs/components/src/lib/radio-group/radio-group.spec.ts#L138).

I ran a check with VoiceOver and the radio-group seemed to behave normally. (On another topic, the `readonly` state is very misleading.)

2022-10-24 08:40 UTC, YonatanKra commented on libs/components/src/lib/radio-group/radio-group.spec.ts
> +			expect(label).not.toBeNull();
I believe this is not needed, because the next line also makes sure of it. Right?

2022-10-24 08:40 UTC, YonatanKra commented on libs/components/src/lib/radio-group/radio-group.spec.ts
> +			expect(positioningRegion?.classList).toContain('horizontal');
Please move all expectations to the end.

2022-10-24 08:40 UTC, YonatanKra commented on libs/components/src/lib/radio-group/radio-group.spec.ts
> +			expect(radios.every(r => r.checked)).toBeFalsy();
Please set all expectation in the end of the `it`.

2022-10-24 08:40 UTC, YonatanKra commented on libs/components/src/lib/radio-group/radio-group.spec.ts
> +			expect(radios[2].getAttribute('tabindex')).toBe('-1');
All expects in the end of the `it`

2022-10-24 08:40 UTC, YonatanKra commented on libs/components/src/lib/radio-group/radio-group.spec.ts
> +			expect(element.value).toBe(radioToCheck.toString());
Mixing expectations with actions is not a good practice.
Please split them for the Action and Expectation.
You also have a Setup/Preparation phase here hiding inside the `keyboardCheck`.
So one has to read the whole function to understand what's going on instead of:
```
setupFocus(0);
hitKey(key);
await elementUpdated(element);
expect(checkedRadioValueBeforeKeyStroke).toBeFalsy();
expect(groupValueBeforeKeyStroke).toBeUndefined();
expect(radios[radioToCheck].checked).toBeTruthy();
expect(element.value).toBe(radioToCheck.toString());
```

2022-10-24 08:40 UTC, YonatanKra commented on libs/components/src/lib/radio-group/radio-group.spec.ts
> +		it('should loop', async () => {
Should loop over what? and do what? in what condition?

2022-10-24 08:53 UTC, olaf-k commented on libs/components/src/lib/radio-group/radio-group.spec.ts
> +			expect(element.value).toBe(radioToCheck.toString());
In your example, one has to understand what's going on in the additional functions you use too, so I'm not convinced by the gain in efficiency?

2022-10-24 08:56 UTC, YonatanKra commented on libs/components/src/lib/radio-group/radio-group.spec.ts
> +			expect(element.value).toBe(radioToCheck.toString());
I don't need to enter the functions to understand. I know what they are doing by their names.
For instance - `setupFocus` should be `setFocusOnElementWithValue(1)` or `setFocusOnRadioIndexed(0)`.
I can just read the function's name - I don't care about its implementation.
Same goes for `hitKey` - I don't care how it works. I just know it has the effect of hitting the key `key` :)

2022-10-27 07:20 UTC, yinonov commented on libs/components/src/lib/radio-group/radio-group.template.ts
> +			@focusout="${(x, c) => x.focusOutHandler(c.event as FocusEvent)}"
should [aria-orientation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-orientation) be included here as well?

it's missing in fast https://github.com/microsoft/fast/blob/2536c024febdf8a89300c257805a19a946f8039d/packages/web-components/fast-foundation/src/radio-group/radio-group.template.ts#L11-L17

intentional?

2022-10-27 07:23 UTC, yinonov commented on libs/components/src/lib/radio-group/radio-group.template.ts
> +			@focusout="${(x, c) => x.focusOutHandler(c.event as FocusEvent)}"
I think we should include it in our template. it is inherited to radio-group. probably defaults to horizontal

2022-10-27 07:34 UTC, olaf-k commented on libs/components/src/lib/radio-group/radio-group.template.ts
> +			@focusout="${(x, c) => x.focusOutHandler(c.event as FocusEvent)}"
yeah, it's a c/c from FAST, good catch.

2022-10-28 19:15 UTC, yinonov approved these changes

2022-10-29 09:41 UTC, merged