fix[avatar]: initials
Vonage/vivid-3 pull request #713
Opened 2022-09-29 13:22 UTC by rachelbt

2022-10-03 06:06 UTC, yinonov commented on libs/components/src/lib/avatar/avatar.spec.ts
> +		it('should not show the icon if name is set', async () => {
is there a test where the same _expect_ returns an instance?

2022-10-03 06:08 UTC, yinonov requested changes

2022-10-03 06:08 UTC, yinonov commented on libs/components/src/lib/avatar/avatar.template.ts
> +			${when( x => !x.name, renderIcon())}
then why render if no icon is set? or if node is assigned to slot?

2022-10-03 06:08 UTC, yinonov commented on libs/components/src/lib/avatar/partials/_mixins.scss
> +		font: var(#{$font-face});
no matter the avatar size, always the same font face?

2022-10-03 06:10 UTC, yinonov requested changes

2022-10-03 06:10 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +<hr>
indeterministic. can result in flaky ui test

2022-10-03 08:43 UTC, rachelbt commented on libs/components/src/lib/avatar/avatar.spec.ts
> +		it('should not show the icon if name is set', async () => {
there was a problem with the test. @YonatanKra [took it on him](https://github.com/Vonage/vivid-3/issues/721)

2022-10-03 08:54 UTC, rachelbt commented on libs/components/src/lib/avatar/avatar.template.ts
> +			${when( x => !x.name, renderIcon())}
because if there's no icon set - then the avatar is presenting its default view: icon of 'user-line'

2022-10-03 08:54 UTC, rachelbt commented on libs/components/src/lib/avatar/README.md
> +<hr>
then whats the best way to do?

2022-10-03 08:56 UTC, rachelbt commented on libs/components/src/lib/avatar/partials/_mixins.scss
> +		font: var(#{$font-face});
its a variable - it gets a font size in the scss:
```
&.density-condensed {
		@include mixins.get-density-properties(32px, #{constants.$vvd-font-base-condensed-bold});
	}
```

2022-10-03 23:45 UTC, yinonov commented on libs/components/src/lib/avatar/avatar.template.ts
> +			${when( x => !x.name, renderIcon())}
true. but anyway, if an image element is assigned, we don't need the icon. the slotted directive can assist verifying if an image was assigned and condition the icon

2022-10-03 23:45 UTC, yinonov commented on libs/components/src/lib/avatar/partials/_mixins.scss
> +		font: var(#{$font-face});
🤦‍♂️

2022-10-03 23:47 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +<hr>
either vwc-divider or nothing. whatever improves reading of code (nothing)

2022-10-13 10:44 UTC, YonatanKra approved these changes

2022-10-18 08:54 UTC, yinonov requested changes
last comment before approval

2022-10-18 08:54 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +<vwc-avatar density='extended' shape="pill" name="john doe"></vwc-avatar>
let's focus on each member and it's specific responsibility?
```suggestion
```

2022-10-18 12:13 UTC, rachelbt commented on libs/components/src/lib/avatar/README.md
> +<vwc-avatar density='extended' shape="pill" name="john doe"></vwc-avatar>
I think its important to see the sizes of the font as well of the icon changes due to "size/density" member

2022-10-18 14:00 UTC, yinonov commented on libs/components/src/lib/avatar/README.md
> +<vwc-avatar density='extended' shape="pill" name="john doe"></vwc-avatar>
so maybe u should say something about it. I, myself, didn't realize

2022-10-18 14:02 UTC, rachelbt commented on libs/components/src/lib/avatar/README.md
> +<vwc-avatar density='extended' shape="pill" name="john doe"></vwc-avatar>
like what?
Isn't the output is enough?
![image](https://user-images.githubusercontent.com/7512792/196451835-61dc9b8a-ee66-4da5-b3c4-fe65f50da99c.png)

2022-10-18 22:40 UTC, yinonov approved these changes

2022-10-19 05:35 UTC, merged