(size): change density to size
Vonage/vivid-3 pull request #726
Opened 2022-10-04 05:50 UTC by rachelbt

2022-10-12 07:20 UTC, yinonov commented
add this to the list of removals (enlarged number field)

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/15140652/195276176-423d29fb-31e3-4fcf-a218-f36a6ddece62.png">

2022-11-13 12:11 UTC, yinonov requested changes

2022-11-13 12:11 UTC, yinonov commented on change/@vonage-vivid-40f0613f-f6a4-4d06-b516-92c0b52da217.json
> +  "comment": "change densety to size and extended to expanded",
```suggestion
  "comment": "change density to size and extended to expanded",
```

2022-11-13 12:13 UTC, yinonov commented on libs/components/src/lib/enums.ts
>  export enum Density {
are we still using it?

2022-11-13 12:15 UTC, yinonov commented on libs/components/src/lib/icon/README.md
> +- Type: `'condensed'` | `'normal'` | `'expanded'`
Icon should be the same as progress ring. next PR?

2022-11-13 12:18 UTC, yinonov reviewed
few small comments

2022-11-13 12:50 UTC, rachelbt commented on libs/components/src/lib/icon/README.md
> +- Type: `'condensed'` | `'normal'` | `'expanded'`
Not sure it does. either way - that sounds like a different PR

2022-11-13 12:51 UTC, rachelbt commented on libs/components/src/lib/enums.ts
>  export enum Density {
no. you re right - we removed the density there. 
I'll remove it

2022-11-13 13:19 UTC, rachelbt commented on libs/components/src/lib/enums.ts
>  export enum Density {
removed

2022-11-13 14:04 UTC, yinonov approved these changes

2022-11-15 13:32 UTC, merged