chore(form-elements): form elements error message pattern
Vonage/vivid-3 pull request #745
Opened 2022-10-13 14:45 UTC by YonatanKra

2022-10-13 19:03 UTC, rachelbt reviewed
the scss of the error message can also be in the pattern so we can avoid duplicating the code?

2022-10-13 19:03 UTC, rachelbt commented on libs/components/src/shared/patterns/form-elements.ts
> +					<span class="error-message">${x => x.errorValidationMessage}</span>`)}
```suggestion
<div class="base">
					<${iconTag} class="icon" type="info-negative"></${iconTag}>
					<span class="message">${x => x.errorValidationMessage}</span>`)}
</div>
```
and I would add CSS:
```
.base {display: flex; row-gap: 8px; align-items: flex-start;}
.icon {flex-shrink: 0;}
```

2022-10-14 11:00 UTC, olaf-k requested changes

2022-10-18 13:41 UTC, olaf-k commented on libs/components/src/shared/patterns/form-elements.ts
> +				${when(x => x.errorValidationMessage, html<TextField>`
> In the same spirit of reuse, I'd remove the condition check `${when(x => x.errorValidationMessage` and leave it to the component to call the function (why a factory?) or not (thus making context a parameter).

I can live with the when in the helper until it's needed outside.

2022-10-19 14:03 UTC, yinonov commented
> the scss of the error message can also be in the pattern so we can avoid duplicating the code? Or is the pattern css-less?

it's css less, it supports a template & class members. for css we have scss mixins

2022-10-19 14:06 UTC, yinonov requested changes

2022-10-19 14:06 UTC, yinonov commented on libs/components/src/shared/patterns/error-message.scss
> +@use '../../../../../dist/libs/tokens/scss/constants' as constants;
hmm I'm not sure if we want this in patterns. we have a sass folder in shared where we maintain mixins
https://github.com/Vonage/vivid-3/blob/d2920294dad9dab5b6c053d2dd7bdf7b54c55f4a/libs/shared/src/lib/sass

2022-10-19 14:37 UTC, YonatanKra commented on libs/components/src/shared/patterns/error-message.scss
> +@use '../../../../../dist/libs/tokens/scss/constants' as constants;
This separates the design from the only place that's going to use it. It is not shared with other things. Why should it be outside the components/shared folder?
Maybe give every pattern its own folder?

2022-10-19 14:56 UTC, olaf-k approved these changes

2022-10-20 12:29 UTC, yinonov approved these changes

2022-10-20 12:29 UTC, merged