chore(docs): indicate avatar as experimental
Vonage/vivid-3 pull request #750
Opened 2022-10-18 08:58 UTC by yinonov

2022-10-23 12:10 UTC, rachelbt approved these changes
👍

2022-10-26 20:30 UTC, yinonov commented on apps/docs/_includes/navigation.njk
> +				{% if (item.status) == "alpha" %}🧪{% endif %}}"
```suggestion
				{% if (item.status) == "alpha" %}🧪{% endif %}"
```

2022-10-26 20:34 UTC, yinonov commented on apps/docs/_includes/navigation.njk
> +				{% if (item.status) == "alpha" %}🧪{% endif %}"
```suggestion
			text="{{ item.title | replace("-", " ") | capitalize }}{% if (item.status) == "alpha" %}🧪{% endif %}"
```

2022-10-27 06:32 UTC, rachelbt requested changes
the side navigation is broken :( 
![image](https://user-images.githubusercontent.com/7512792/198208545-7356c3c6-61dc-46e3-9380-2b3881afcab1.png)

2022-11-02 07:14 UTC, rachelbt submitted a review, later dismissed
YES!! 
Look s great and I love the status addition in the components.json, much more systematic! 👍

2022-11-02 08:47 UTC, olaf-k requested changes

2022-11-02 08:47 UTC, olaf-k commented on apps/docs/_includes/navigation.njk
> +			text="{{ item.title | replace("-", " ") | capitalize }} {% if (item.status) == "alpha" %}🧪{% endif %}"
`title="This component is experimental"` would help people wondering what the emoji means.

2022-11-02 08:47 UTC, olaf-k commented on apps/docs/_includes/navigation.njk
> +			text="{{ item.title | replace("-", " ") | capitalize }}	{% if (item.status) == "alpha" %}🧪{% endif %}"
(same remark)

2022-11-02 11:44 UTC, yinonov commented on apps/docs/_includes/navigation.njk
> +			text="{{ item.title | replace("-", " ") | capitalize }} {% if (item.status) == "alpha" %}🧪{% endif %}"
added 
![image](https://user-images.githubusercontent.com/15140652/199481593-a71eb0f4-a731-4f7c-acbc-502e447addf0.png)

2022-11-02 11:44 UTC, yinonov commented on apps/docs/_includes/navigation.njk
> +			text="{{ item.title | replace("-", " ") | capitalize }}	{% if (item.status) == "alpha" %}🧪{% endif %}"
add
![image](https://user-images.githubusercontent.com/15140652/199481638-29aebdbe-365b-4011-bf27-6b37296d78f3.png)

2022-11-02 11:45 UTC, yinonov commented on apps/docs/_includes/navigation.njk
> +			text="{{ item.title | replace("-", " ") | capitalize }} {% if (item.status) == "alpha" %}🧪{% endif %}"
it's more relevant to components at this point

2022-11-03 09:20 UTC, rinaok requested changes
<img width="1786" alt="Screenshot 2022-11-03 at 11 17 41" src="https://user-images.githubusercontent.com/10883919/199684611-bfa96f10-9a65-40e1-88ba-963a3a549c2d.png">

Why is the banner not full width?

2022-11-03 11:24 UTC, yinonov commented
> <img alt="Screenshot 2022-11-03 at 11 17 41" width="1786" src="https://user-images.githubusercontent.com/10883919/199684611-bfa96f10-9a65-40e1-88ba-963a3a549c2d.png">
> 
> Why is the banner not full width?

thanks, resolved

2022-11-03 12:02 UTC, rinaok requested changes
Something happened to the main page. It's not working.

2022-11-03 12:27 UTC, yinonov commented
> Something happened to the main page. It's not working.

thanks, resolved

2022-11-03 12:34 UTC, rinaok requested changes

2022-11-03 12:34 UTC, rinaok commented on apps/docs/pages/component-pages.njk
> +<vwc-banner class="banner" text="Alpha: this is an initial phase of component testing. expect breaking changes." connotation="warning"></vwc-banner>
```suggestion
<vwc-banner class="banner" text="Alpha: this is the initial phase of component testing. Expect breaking changes." connotation="warning"></vwc-banner>
```

2022-11-03 12:40 UTC, olaf-k reviewed
it looks like the banner covers the nav when resized horizontally. (happens on Chrome desktop but works well on iPhone.)
![image](https://user-images.githubusercontent.com/1153034/199722427-82ccef71-643a-46d7-b211-b0c6cc74224c.png)

2022-11-03 13:00 UTC, rinaok approved these changes

2022-11-03 13:03 UTC, yinonov commented
> it looks like the banner covers the nav when resized horizontally. (happens on Chrome desktop but works well on iPhone.) ![image](https://user-images.githubusercontent.com/1153034/199722427-82ccef71-643a-46d7-b211-b0c6cc74224c.png)

resolved

2022-11-03 13:10 UTC, olaf-k approved these changes

2022-11-03 17:12 UTC, merged