feat(popup): add light dismiss support
Vonage/vivid-3 pull request #765
Opened 2022-10-27 15:03 UTC by rinaok

- The light dismiss feature will be used in Popup as well in Select and Menu components.

- Light dismiss behaviors: most popups "light dismiss", in that the following will dismiss the popup: pressing the ESC key, invoking elsewhere in the document, invoking another popup (unless it is a child of the currently opened popup).	
	Read more: https://open-ui.org/components/popup.research

- Should be researched if the light dismiss should work also on resize / scroll.

- Should be checked: https://github.com/oddbird/popup-polyfill

2022-11-10 13:00 UTC, yinonov requested changes
due to the future support of popover, we might wanna remove any evidence of popup from the API collection. so remove its page. that way we only align with the naming popover introduces to browsers and under the hood we would eventually refactor any floating-UI / popup-polyfill to the native popover. open an issue to exclude popup from our site?

2022-11-10 13:03 UTC, yinonov commented on libs/components/src/lib/popup/popup.template.ts
> +    <!--the popup-wrapper is needed for alternating the inside of the popup and not it's shadow-->
possessive word
```suggestion
    <!--the popup-wrapper is needed for alternating the inside of the popup and not its shadow-->
```

2022-11-17 10:31 UTC, rinaok commented
@yinonov There is a new version 0.0.3 for the package. They changed it's name to be `popover-polyfill`.
Should we also change popup's name to popover?

2022-11-17 14:39 UTC, yinonov commented
> Member

yes. everyone else do https://carbondesignsystem.com/components/popover/usage/

2022-11-24 17:08 UTC, olaf-k commented
just a reminder to [make sure the tooltip benefits from this](https://github.com/Vonage/vivid-3/pull/829#discussion_r1031351356)

2022-11-28 11:57 UTC, rinaok commented
> > Member
> 
> yes. everyone else do [carbondesignsystem.com/components/popover/usage](https://carbondesignsystem.com/components/popover/usage/)

@yinonov I see that chrome still calls it pop-up, and it had a popover attribute https://developer.chrome.com/docs/web-platform/pop-up-api/

2022-11-28 11:59 UTC, rinaok commented
@yinonov The popover-polyfill still doesn't support in all light-dismiss behaviours. It doesb't suppoer ESC for example..

2022-11-28 12:00 UTC, rinaok commented on libs/components/src/lib/popup/README.md
> +Use the `popup` attribute to add Light dismiss behaviors.
@yinonov I see that chrome calls the element pop-up, and it has a popover attribute [developer.chrome.com/docs/web-platform/pop-up-api/popover-attribute](https://developer.chrome.com/docs/web-platform/pop-up-api/popover-attribute/)

2022-11-28 20:06 UTC, yinonov commented
> @yinonov The popover-polyfill still doesn't support in all light-dismiss behaviours. It doesb't suppoer ESC for example..

it don't matter. it will. we don't support any of the light dismiss methods

2022-11-28 22:01 UTC, rinaok commented
> > @yinonov The popover-polyfill still doesn't support in all light-dismiss behaviours. It doesb't suppoer ESC for example..
> 
> it don't matter. it will. we don't support any of the light dismiss methods

Ok, so I think the PR is good now, I only have this linting problem

2022-11-29 09:22 UTC, yinonov commented on libs/components/src/lib/popup/README.md
> +Use the `popup` attribute to add Light dismiss behaviors.
ok. doesn't make sense to do any changes at this point to our interface as that boat rocks

2022-12-20 12:16 UTC, yinonov commented on libs/components/src/lib/popup/README.md
> +- When `'auto'` the following will dismiss the popup: pressing the ESC key, keyboard-navigation, invoking elsewhere in the document, invoking another popup, etc.
```suggestion
- When `'auto'` the following will dismiss the popup: ~~pressing the ESC key~~, keyboard-navigation, invoking elsewhere in the document, invoking another popup, etc.
```

2022-12-20 12:29 UTC, yinonov requested changes

2022-12-20 12:29 UTC, yinonov commented on libs/components/src/lib/menu/menu.template.ts
> +				popover
test this

2022-12-20 12:29 UTC, yinonov commented on libs/components/src/lib/popup/README.md
> +- Type: `'auto'` | `'manual'`
decide whether we want to support (and test) `manual` choice, which means no-light-dismiss, OR
add `lightDismiss` property to popup custom element to support by default (or not default). keep in mind popup is now an implementation detail for underlying usage and will not reflect (formally) any of it's feature. it's like a constant alpha tagged custom element. as github readme files are still exposed in the repo, we should state in the top of popup readme that it is being used internally to enable components' popup ability

2022-12-20 12:47 UTC, rinaok commented
Waiting for https://github.com/oddbird/popover-polyfill/pull/49

2022-12-20 15:02 UTC, rinaok commented on libs/components/src/lib/popup/README.md
> +- Type: `'auto'` | `'manual'`
@yinonov  added manual test

2022-12-21 11:46 UTC, yinonov requested changes

2022-12-21 11:46 UTC, yinonov commented on libs/components/src/lib/popup/popup.ts
>  	override attributeChangedCallback(name: string, oldValue: string, newValue: string): void {
use `anchorChanged` & `openChanged` as in fast element convention

2022-12-21 11:46 UTC, yinonov commented on libs/components/src/lib/popup/popup.ts
> +	override connectedCallback(): void {
redundant

2022-12-21 11:46 UTC, yinonov commented on libs/components/src/lib/popup/definition.ts
> +import '@oddbird/popover-polyfill';
this still bugs me as it executes side effects from here, the component class file.

should we add the following code in a static method instead?
https://github.com/oddbird/popover-polyfill/blob/fe1958d5b7677a716a8c6b5172fceec83adba56b/src/index.ts#L1-L11

2022-12-21 11:46 UTC, yinonov requested changes
do action-group snapshot belong in this scope?

2022-12-21 12:28 UTC, rinaok commented
> do action-group snapshot belong in this scope?

It's not, here I created a separate PR for that: https://github.com/Vonage/vivid-3/pull/924

2022-12-21 12:30 UTC, rinaok commented on libs/components/src/lib/popup/definition.ts
> +import '@oddbird/popover-polyfill';
But if there will be a change, our tests will fail right?

2022-12-21 14:52 UTC, yinonov commented on libs/components/src/lib/popup/definition.ts
> +import '@oddbird/popover-polyfill';
no, it shouldn't. actually I'm doubting the benefit. @olaf-k @YonatanKra WDYT?

2022-12-21 15:43 UTC, olaf-k commented on libs/components/src/lib/popup/definition.ts
> +import '@oddbird/popover-polyfill';
what issue do you foresee running their code implicitly, as opposed to doing it ourselves? should we have more control over when `apply` is called? do we plan another implementation of `isSupported`? if the answer is no to both questions, I'm ok with the side-effect import.

2022-12-21 21:27 UTC, yinonov commented on libs/components/src/lib/popup/definition.ts
> +import '@oddbird/popover-polyfill';
Ok then

2022-12-25 15:10 UTC, yinonov approved these changes

2022-12-25 15:18 UTC, merged