refactor(tokens): locking down baseline size
Vonage/vivid-3 pull request #768
Opened 2022-10-30 11:03 UTC by yinonov

restrict allowed values for baseline size

2022-10-30 13:10 UTC, YonatanKra requested changes
Looks good. Much simpler. Added some comments regarding the tests.

2022-10-30 13:10 UTC, YonatanKra commented on libs/tokens/src/lib/transforms/font-size.spec.ts
> +	it('should match if is of type fontSizes', () => {
```suggestion
	it('should match if token is of type fontSizes', () => {
```

2022-10-30 13:10 UTC, YonatanKra commented on libs/tokens/src/lib/transforms/font-size.spec.ts
> +			...token,
I actually think it is much clearer if you just add `type: "fontSizes"` instead of adding the token here.

2022-10-30 13:10 UTC, YonatanKra commented on libs/tokens/src/lib/transforms/font-size.spec.ts
> +	it('should not match if not of type fontSizes', () => {
```suggestion
	it('should not match if token is not of type fontSizes', () => {
```

2022-10-30 13:10 UTC, YonatanKra commented on libs/tokens/src/lib/transforms/font-size.spec.ts
> +			...token
Can hard-code the token here for readability.

2022-10-30 15:02 UTC, yinonov commented on libs/tokens/src/lib/transforms/public-css-references.ts
> +import type { Named, Transform } from "style-dictionary";
Yes. Ideas for a better name?

2022-10-31 07:30 UTC, yinonov commented
should document public references. could these be autogenerated by tokens?

2022-10-31 07:49 UTC, YonatanKra commented on libs/tokens/src/lib/transforms/public-css-references.ts
> +import type { Named, Transform } from "style-dictionary";
Maybe be more clear these are css variables. For us it is clear but I had to get into the file to learn that. We want to avoid devs needing to get into a file to know what it's supposed to do/hold, no?

2022-10-31 09:30 UTC, YonatanKra submitted a review, later dismissed
LGTM. Just consider my final comment on the `it` description. Try not to use `not` :)

2022-10-31 09:30 UTC, YonatanKra commented on libs/tokens/src/lib/transforms/font-weight.spec.ts
> +	it('should not match if token is not of type fontWeights', () => {
```suggestion
	it('should return false if token is not of type fontWeights', () => {
```

2022-10-31 10:02 UTC, YonatanKra approved these changes

2022-10-31 10:03 UTC, merged