feat(switch): add the switch component
Vonage/vivid-3 pull request #785
Opened 2022-11-03 11:05 UTC by YonatanKra

2022-11-03 11:45 UTC, rachelbt requested changes
would like to see again - hope my additions were in place :)

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/switch.scss
> +	$appearances: filled ghost,
```suggestion
	$appearances: filled,
```
where are you using the ghost?

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/switch.scss
> +	height: 20px;
```suggestion
	inline-size: 36px;
	block-size: 20px;
	box-sizing: border-box;
```

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/switch.scss
> +		background-color: var(#{appearance.get-appearance-token(fill)});;
```suggestion
		background-color: var(#{appearance.get-appearance-token(fill)});
		border-color:  var(#{appearance.get-appearance-token(fill)});
```

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/switch.scss
> +}
```suggestion
.control:not(.disabled, [aria-checked="true"]) &{
    border: 1px solid var(constants.$vvd-color-neutral-500);
}
}
```

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/switch.scss
> +	border: 1px solid var(constants.$vvd-color-neutral-500);
```suggestion
```
moved it downward

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/switch.scss
> +	height: var(--checked-indicator-size);
```suggestion
	inline-size: var(--checked-indicator-size);
	block-size: var(--checked-indicator-size);
```

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/switch.scss
> +	margin-left: 8px;
should add typography to it

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/switch.scss
> +	margin-top: calc((20px - var(--checked-indicator-size)) / 2);
```suggestion
	margin-top: calc((18px - var(--checked-indicator-size)) / 2);
```
because I added box-sizing

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/switch.scss
> +		transform: translateX(20px);
```suggestion
		transform: translateX(18px);
```

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/README.md
> +    <vwc-switch connotation="alert"></vwc-switch>
```suggestion
    <vwc-switch connotation="primary" checked ></vwc-switch>
    <vwc-switch connotation="cta" checked ></vwc-switch>
    <vwc-switch connotation="alert" checked ></vwc-switch>
```
So people can see the colors :)

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/README.md
> +
I'm not sure name & value need a preview. It feels strange to me cause nothing is changed in the looks. maybe a JS preview is better

2022-11-03 11:45 UTC, rachelbt commented on libs/components/src/lib/switch/README.md
> +# switch
```suggestion
# Switch
```

2022-11-03 11:55 UTC, rachelbt submitted a review, later dismissed
one more - you are missing the hover state

2022-11-03 13:04 UTC, yinonov commented
wait for #634

2022-11-06 07:02 UTC, yinonov requested changes

2022-11-06 07:02 UTC, yinonov commented on libs/components/src/lib/switch/switch.ts
> +	@attr connotation?: string;
we subset enum

2022-11-06 07:02 UTC, yinonov commented on libs/components/src/lib/switch/switch.scss
> +	$connotations: accent cta alert,
I think there was a success connotation as well. what have we decided from a design perspective regarding CTA? or the connotations in general? did @ayalaBu find the change made by @jshenkman?

2022-11-06 09:22 UTC, AyalaBu commented on libs/components/src/lib/switch/switch.scss
> +	$connotations: accent cta alert,
@yinonov @YonatanKra 
I never touched the switch component, so the variants we have were created by Joella.
Right now it has 3 connotations: accent, cta & alert.
I don't think there is need to reduce the connotations amount in this component,
because from the UX point of view all of them may be needed.

2022-11-06 09:25 UTC, YonatanKra commented on libs/components/src/lib/switch/switch.scss
> +	$connotations: accent cta alert,
I'm working according to https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=8222%3A44607

2022-11-07 07:33 UTC, yinonov requested changes

2022-11-08 05:14 UTC, yinonov requested changes

2022-11-08 05:14 UTC, yinonov commented on libs/components/package.json
> -    "./listbox": "./listbox",
Listbox and switch are now missing

2022-11-08 05:14 UTC, yinonov commented on libs/components/src/lib/switch/README.md
> +    <vwc-switch checked></vwc-switch>
```suggestion
<vwc-switch checked></vwc-switch>
```

2022-11-08 05:14 UTC, yinonov commented on libs/components/src/lib/switch/README.md
> +    <vwc-switch disabled checked></vwc-switch>
```suggestion
<vwc-switch disabled></vwc-switch>
<vwc-switch disabled checked></vwc-switch>
```

2022-11-08 05:14 UTC, yinonov commented on libs/components/src/lib/switch/README.md
> +    <vwc-switch value="my-value"></vwc-switch>
Can u fix all following indentations?

2022-11-08 05:18 UTC, yinonov requested changes

2022-11-08 05:18 UTC, yinonov commented on libs/components/src/lib/switch/switch.template.ts
> +	<div class="switch">
Focus indicator is missing

2022-11-08 09:56 UTC, yinonov approved these changes

2022-11-08 14:49 UTC, yinonov approved these changes

2022-11-08 19:35 UTC, yinonov approved these changes

2022-11-08 19:36 UTC, merged