feat(docs): different color for code blocks
Vonage/vivid-3 pull request #790
Opened 2022-11-04 16:36 UTC by olaf-k

Maybe the font differences are too subtle, maybe I'm too old. A (slight) color shift may help distinguish code parts.
WDYT? (Also, not sure it's the proper place to do it?)

2022-11-05 07:36 UTC, yinonov requested changes

2022-11-05 07:36 UTC, yinonov commented on libs/styles/src/lib/core/typography.scss
> +		color: var(--vvd-color-neutral-600);
Colors to typefaces were not yet defined from a design perspective and this style file is meant for consumers use.
To style our docs use the docs app `main.css`

2022-11-05 11:30 UTC, yinonov requested changes

2022-11-05 11:30 UTC, yinonov commented on apps/docs/assets/styles/main.css
> +  color: var(--vvd-color-neutral-600);
See highlight js region at the bottom of the file

2022-11-05 11:33 UTC, olaf-k commented on apps/docs/assets/styles/main.css
> +  color: var(--vvd-color-neutral-600);
not sure what you mean? move it there or?

2022-11-05 18:34 UTC, yinonov commented on apps/docs/assets/styles/main.css
> +  color: var(--vvd-color-neutral-600);
what's the difference of when it's wrapped by anchor?

2022-11-05 18:47 UTC, yinonov commented on apps/docs/assets/styles/main.css
> +  color: var(--vvd-color-neutral-600);
even though these tags are a semantic family, they might have different  types of implementations. if we want to adopt a finite state for style, side effects should be avoided. this styles an implementation which isn't defined yet. style only what exist in the docs?

also notice that this style also applies to the code within highlight js. so the selector might need to be more specific 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/15140652/200136011-657d2819-5957-447f-8854-2fa24e70ff0b.png">

2022-11-07 10:14 UTC, olaf-k commented on apps/docs/assets/styles/main.css
> +  color: var(--vvd-color-neutral-600);
> what's the difference of when it's wrapped by anchor?

links styling should take precedence

2022-11-07 10:23 UTC, olaf-k commented on apps/docs/assets/styles/main.css
> +  color: var(--vvd-color-neutral-600);
> even though these tags are a semantic family, they might have different types of implementations. if we want to adopt a finite state for style, side effects should be avoided. **this styles an implementation which isn't defined yet**. style only what exist in the docs?
> 
> also notice that this style also applies to the code within highlight js. so the selector might need to be more specific <img alt="image" width="569" src="https://user-images.githubusercontent.com/15140652/200136011-657d2819-5957-447f-8854-2fa24e70ff0b.png">

not sure what you mean by the bold part.
the idea here is to make the semantic differences in the doc clearer. the difference between the proportional and the fixed-size fonts are subtle: enough to make you think something is not uniform in the text, not strong enough to highlight what this something is.
![image](https://user-images.githubusercontent.com/1153034/200286138-2137ce34-d260-4f70-8679-93c39321243f.png)
adding a color shift helps parsing the code examples faster
![image](https://user-images.githubusercontent.com/1153034/200286208-75b13aef-8d2a-4d9e-a2e6-8ef369f30a93.png)

and yes, it also impacts the default color in code blocks, this is a desirable side-effect (and adds consistency), but it can be removed if you think it's not useful.

2022-11-16 08:26 UTC, yinonov commented
consider https://github.com/Vonage/vivid-3/pull/766#issuecomment-1297015417

2023-03-22 14:59 UTC, closed without merging