feat(docs): add doc for public CSS references
Vonage/vivid-3 pull request #791
Opened 2022-11-04 17:03 UTC by olaf-k

Will close #770

2022-11-05 20:03 UTC, yinonov commented on docs/design/design-tokens.md
> +- --vvd-typography-headline
not?
```suggestion
`--vvd-typography-headline`
```

2022-11-05 20:11 UTC, yinonov requested changes

2022-11-05 20:11 UTC, yinonov commented on docs/design/design-tokens.md
> +- --vvd-typography-base-extended-code
sorted base to be first and dropping other code sizes. should consider removing their support so let's not expose for the time being
```suggestion
- --vvd-typography-base
- --vvd-typography-base-bold
- --vvd-typography-base-code
- --vvd-typography-base-condensed
- --vvd-typography-base-condensed-bold
- --vvd-typography-base-extended
- --vvd-typography-base-extended-bold
```

2022-11-05 20:11 UTC, yinonov commented on docs/design/design-tokens.md
> +<div style="font: var(--vvd-typography-base-extended-code)">base-extended-code</div>
sorted base to be first and dropping other code sizes. should consider removing their support so let's not expose for the time being
```suggestion
<div style="font: var(--vvd-typography-base)">base</div>
<div style="font: var(--vvd-typography-base-bold)">base-bold</div>
<div style="font: var(--vvd-typography-base-code)">base-code</div>
<div style="font: var(--vvd-typography-base-condensed)">base-condensed</div>
<div style="font: var(--vvd-typography-base-condensed-bold)">base-condensed-bold</div>
<div style="font: var(--vvd-typography-base-extended)">base-extended</div>
<div style="font: var(--vvd-typography-base-extended-bold)">base-extended-bold</div>
```

2022-11-05 20:24 UTC, yinonov requested changes

2022-11-05 20:24 UTC, yinonov commented on docs/design/design-tokens.md
> +    --vvd-font-family-monospace: Courier;
it's a pickle. we have no component to expose this change. so this could be confusing for readers to understand why it's present here

2022-11-05 20:24 UTC, yinonov commented on docs/design/design-tokens.md
> +
the reason this token is exposed is to enable authors to set typography to lean on relative units. maybe this is a right section to explain how that helps users expecting font sizing to follow their browser preference

2022-11-05 20:24 UTC, yinonov commented on docs/design/design-tokens.md
> +    --vvd-size-font-scale-base: 1.3rem;
`1.3rem` from what? to set this to be deterministic let's add `font-size: 1rem` to `:root` as well. it'll default to the UA 16px or to user's browser preference in settings
<img width="723" alt="image" src="https://user-images.githubusercontent.com/15140652/200139471-4ffe959c-15a0-44e0-bbe6-91f08a5cf078.png">

2022-11-07 13:41 UTC, olaf-k commented on docs/design/design-tokens.md
> +- --vvd-typography-headline
indeed!

2022-11-07 13:42 UTC, olaf-k commented on docs/design/design-tokens.md
> +- --vvd-typography-base-extended-code
yeah I changed the order because it felt more pleasing visually, but I'll remove that part anyway.

2022-11-07 13:50 UTC, olaf-k commented on docs/design/design-tokens.md
> +    --vvd-font-family-monospace: Courier;
for monospace?

2022-11-07 13:53 UTC, olaf-k commented on docs/design/design-tokens.md
> +
ok. the use I had in mind was for apps that provide controls to enlarge/shrink their text (without the use having to zoom).
if the main rationale is to say "as a user you can set a relative size" why don't we do it as a default?

2022-11-07 13:55 UTC, olaf-k commented on docs/design/design-tokens.md
> +    --vvd-size-font-scale-base: 1.3rem;
typography in CSS gives me headaches :)
it's 1.3rem from the default 16px mentioned above.

2022-11-10 11:00 UTC, yinonov commented on docs/design/design-tokens.md
> +
our root's base font size is 16px, body increments by 1 in the typography scale (major second). the variable should be applied on the root

2022-11-10 11:07 UTC, yinonov commented on docs/design/design-tokens.md
> +
I'm not sure the issue with zoom-in on 14px in controls should be addressed by that variable. u could set the base to a value larger than 16 and result in larger than 14 in controls.
BUT, there should probably be an alternate typography tokens file dedicated for mobile

2022-11-16 10:35 UTC, yinonov requested changes

2022-11-16 10:35 UTC, yinonov commented on docs/design/design-tokens.md
> +
it's now practiced in #836

2022-11-16 10:35 UTC, yinonov commented on docs/design/design-tokens.md
> +    --vvd-size-font-scale-base: 1.3rem;
see #836

2022-11-21 15:49 UTC, yinonov requested changes

2022-11-21 15:49 UTC, yinonov commented on docs/design/design-tokens.md
> +Aside from the [color-related tokens](/designs/color-palette), you may use these ones to tweak your application appearance.
```suggestion
Aside from the [color-related tokens](/designs/color-palette), you may use the following to customize your application appearance.
```

2022-11-21 15:55 UTC, yinonov requested changes

2022-11-21 15:55 UTC, yinonov commented on docs/design/design-tokens.md
> +- Type: `-1` | `0` | `1`
```suggestion
- Type: `-1` | `0` | `2`
```

2022-11-21 15:55 UTC, yinonov commented on docs/design/design-tokens.md
> +Use `--vvd-size-density` to modify the spacing and padding of widgets. Allowed values are `-1` (condensed), `0` (default) and `1` (expanded).
```suggestion
Use `--vvd-size-density` to modify the spacing and padding of widgets. Allowed values are `-1` (condensed), `0` (default), `1` and `2` (expanded).
```

2022-11-21 15:55 UTC, yinonov commented on docs/design/design-tokens.md
> +- Default monospace: `'Roboto Mono'`
should align with conventional docs where each members gets its own `type` and `default`

2022-11-21 15:55 UTC, yinonov commented on docs/design/design-tokens.md
> +Unless explicitely stated otherwise, Vonage products should use the brand font `Spezia`. This is explained [in this repo](https://github.com/Vonage/spezia-webfont-kit).
and spezia mono?

2022-11-21 15:58 UTC, yinonov requested changes

2022-11-21 15:58 UTC, yinonov commented on docs/design/design-tokens.md
> +Use `--vvd-size-font-scale-base` to define the base font size for the widgets.
there's no guideline explicitly defines tweaking it in widgets. there's no actual knowledge or constraints on where this should be applied

2022-11-21 15:58 UTC, yinonov commented on docs/design/design-tokens.md
> +When the `.vvd-root` class is set on the root element (i.e., `<html>`), the default font size is reset to the user-agent's one (generally `16px`)
that's not necessarily true. depends if application consumes the css core. actually I can't seem to understand whether this paragraph is correct

2022-11-22 08:13 UTC, yinonov submitted a review, later dismissed

2022-11-22 08:14 UTC, yinonov approved these changes

2022-11-22 08:27 UTC, merged