fix(docs): minor touch-ups
Vonage/vivid-3 pull request #792
Opened 2022-11-05 12:50 UTC by olaf-k

2022-11-05 19:57 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +<!-- -->
why not simply a line break?

2022-11-06 07:13 UTC, rachelbt commented on libs/components/src/lib/card/README.md
> +<!-- -->
it was a requested & designed  by @jshenkman:
https://vonage.slack.com/archives/C013F0YKH99/p1634197624060000

2022-11-07 08:40 UTC, olaf-k commented on libs/components/src/lib/card/README.md
> +<!-- -->
> why not simply a line break?
a new line in the middle of a list spaces items evenly
![image](https://user-images.githubusercontent.com/1153034/200264036-e259bd93-cca6-4ac2-8230-f0c434105b44.png)
to separate two contiguous lists, we could use two `<br>` or one comment, I chose the latter
![image](https://user-images.githubusercontent.com/1153034/200264302-cc4f8e5f-b3bb-4ee2-89a6-98ae45fe32f4.png)

2022-11-07 17:18 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +<!-- -->
Each variable should defined separately. And while at it, these are [css syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/syntax) types. Calling it a string do to css pre parsing should be wrong here. These are integers.

If already refactoring, can we align to css syntax?

2022-11-07 17:25 UTC, olaf-k commented on libs/components/src/lib/card/README.md
> +<!-- -->
sure

2022-11-08 13:34 UTC, yinonov requested changes

2022-11-08 13:34 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +- Type: `number`
it must be a whole number (not fractioned)
```suggestion
- Type: `integer`
```

2022-11-08 13:34 UTC, yinonov commented on libs/components/src/lib/card/README.md
> +- Type: `number`
```suggestion
- Type: `integer`
```

2022-11-08 13:34 UTC, yinonov commented on libs/components/src/lib/layout/README.md
>  - `--layout-grid-template-columns`
```suggestion
Control the grid-template-columns of the layout by setting `--layout-grid-template-columns`.

```

2022-11-08 16:50 UTC, yinonov approved these changes

2022-11-08 17:27 UTC, merged