feat(docs): default font - Monserat
Vonage/vivid-3 pull request #807
Opened 2022-11-08 16:06 UTC by rachelbt

2022-11-16 07:00 UTC, yinonov commented
denote https://github.com/Vonage/spezia-webfont-kit

2022-11-16 07:02 UTC, yinonov requested changes

2022-11-16 07:02 UTC, yinonov commented on apps/docs/assets/styles/iframe.css
> +@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700&display=swap');
document the need of this

2022-11-16 07:02 UTC, yinonov commented on apps/docs/assets/styles/iframe.css
> +	--vvd-font-family-upright: Montserrat;
no need. will be specified in tokens

2022-11-16 09:56 UTC, rachelbt commented on apps/docs/assets/styles/iframe.css
> +	--vvd-font-family-upright: Montserrat;
sure. but for preview we still need it until we change the token.
Leaving if till we choose a font for monospace as well...

2022-11-16 10:15 UTC, rachelbt commented
@yinonov tried using [fira-code font](https://fonts.google.com/specimen/Fira+Code?query=fira) but it didn't work good with Montserrat:
![image](https://user-images.githubusercontent.com/7512792/202152934-ce316ada-c470-4081-ba73-dccb36c3343f.png)

added [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono?query=roboto).

I'm wondering if its not bad for performance to load 2 fonts.
If we will choose to leave it with 2 fonts - I'll change  the import statement to include them both as Google-Fons provides.

2022-11-16 14:01 UTC, yinonov commented
> @yinonov tried using [fira-code font](https://fonts.google.com/specimen/Fira+Code?query=fira) but it didn't work good with Montserrat: ![image](https://user-images.githubusercontent.com/7512792/202152934-ce316ada-c470-4081-ba73-dccb36c3343f.png)
> 
> added [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono?query=roboto).
> 
> I'm wondering if its not bad for performance to load 2 fonts. If we will choose to leave it with 2 fonts - I'll change the import statement to include them both as Google-Fons provides.

fonts aren't fetched until actually used. therefore the FOUT. you should include them both in the css call to google fonts. notice in the network pane in dev-tools they won't load unless actually use in page

2022-11-22 16:44 UTC, yinonov requested changes

2022-11-22 16:44 UTC, yinonov commented on apps/docs/_layouts/base.njk
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400&display=swap" rel="stylesheet">
why are they split? can be reduced to a 1 call

2022-11-22 16:49 UTC, yinonov requested changes

2022-11-22 16:49 UTC, yinonov commented on apps/docs/assets/styles/iframe.css
> +@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500;600;700;800;900&display=swap');
do we need all these weights?

2022-11-22 16:50 UTC, yinonov approved these changes

2022-11-22 16:50 UTC, yinonov commented on apps/docs/assets/styles/main.css
> +	--vvd-font-family-monospace: Roboto Mono;
that's where we override font families to Spezia

2022-11-24 10:25 UTC, rachelbt commented
tokens for default font.
Basically I removed the `font-stretch` properties.

looks quit the same :)

![image](https://user-images.githubusercontent.com/7512792/203760413-81800b12-ccda-4d2d-b50e-509f0d222e00.png)


```
--vvd-typography-headline: 500  calc(var(--vvd-size-font-scale-base, 16px) * 4.125)/1.3333333333333333 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-subtitle: 500  calc(var(--vvd-size-font-scale-base, 16px) * 3.25)/1.3076923076923077 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-heading-1: 500  calc(var(--vvd-size-font-scale-base, 16px) * 2.5)/1.3 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-heading-2: 500  calc(var(--vvd-size-font-scale-base, 16px) * 2)/1.375 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-heading-3: 500  calc(var(--vvd-size-font-scale-base, 16px) * 1.625)/1.3846153846153846 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-heading-4: 500  calc(var(--vvd-size-font-scale-base, 16px) * 1.25)/1.4 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-base: 400  calc(var(--vvd-size-font-scale-base, 16px) * 0.875)/1.4285714285714286 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-base-bold: 600  calc(var(--vvd-size-font-scale-base, 16px) * 0.875)/1.4285714285714286 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-base-code: 400  calc(var(--vvd-size-font-scale-base, 16px) * 0.875)/1.4285714285714286 var(--vvd-font-family-monospace, Roboto Mono);
--vvd-typography-base-condensed: 400  calc(var(--vvd-size-font-scale-base, 16px) * 0.75)/1.3333333333333333 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-base-condensed-bold: 600  calc(var(--vvd-size-font-scale-base, 16px) * 0.75)/1.3333333333333333 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-base-condensed-code: 400  calc(var(--vvd-size-font-scale-base, 16px) * 0.75)/1.3333333333333333 var(--vvd-font-family-monospace, Roboto Mono);
--vvd-typography-base-extended: 400  calc(var(--vvd-size-font-scale-base, 16px))/1.5 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-base-extended-bold: 600  calc(var(--vvd-size-font-scale-base, 16px))/1.5 var(--vvd-font-family-upright, Montserrat);
--vvd-typography-base-extended-code: 400  calc(var(--vvd-size-font-scale-base, 16px))/1.5 var(--vvd-font-family-monospace, Roboto Mono);
```

2022-11-24 14:29 UTC, yinonov commented on apps/docs/_layouts/base.njk
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400&display=swap" rel="stylesheet">
we don't really need this, rather just document it

2022-11-24 14:29 UTC, yinonov commented on apps/docs/assets/styles/iframe.css
> +}
not actually needed

2022-11-24 14:34 UTC, yinonov requested changes
consider some of the comments are just a "note to self"

2022-11-24 14:34 UTC, yinonov commented on apps/docs/assets/styles/spezia.css
> +	--vvd-typography-base-extended-code: 400 ultra-condensed calc(var(--vvd-size-font-scale-base, 16px))/1.5 var(--vvd-font-family-monospace, SpeziaMonoCompleteVariable);
now on 2nd thought, if it's already a requirement to override tokens (due to stretch value), why should the font family be a public variable? it's half of a solution. requires a better API strategy

2022-12-10 17:44 UTC, yinonov requested changes

2022-12-10 17:44 UTC, yinonov commented on libs/components/README.md
> +<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&display=swap" rel="stylesheet">">
what about roboto?

2022-12-10 17:45 UTC, yinonov commented on libs/components/README.md
> +<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&display=swap" rel="stylesheet">">
oh not needed for button?

2022-12-10 17:47 UTC, yinonov requested changes

2022-12-10 17:47 UTC, yinonov commented on libs/components/README.md
> +### Fonts (Prerequisite) - Should we leave it for Vonage users?
explain how to import the font

2022-12-11 07:15 UTC, rachelbt commented on libs/components/README.md
> +<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&display=swap" rel="stylesheet">">
it is not needed for the button - but maybe its better we add it in the import statement so it will not be forgotten.

2022-12-11 11:14 UTC, yinonov commented on libs/components/README.md
> +<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&display=swap" rel="stylesheet">">
it can be imported when set in the query parameter together with `Montserrat` right?

2022-12-11 13:22 UTC, rachelbt commented on libs/components/README.md
> +<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&display=swap" rel="stylesheet">">
Yes - was working on it - didn't merged yet

2023-01-02 09:53 UTC, yinonov approved these changes

2023-01-02 09:54 UTC, merged