feat(docs): add scroll localStorage to side drawer
Vonage/vivid-3 pull request #813
Opened 2022-11-10 09:19 UTC by rinaok

2022-11-10 11:57 UTC, yinonov commented
> On Daily, @olaf-k mentioned the scrolling problem. [This is a solution I proposed not long ago](https://github.com/Vonage/vivid-3/pull/603/commits/39024ca8123702cfd874ea6f309868f7b38b21b5), Until we find a third party library for that, I think this can be the solution. What do you think? @yinonov

should it work on this PR recent deployment? it doesn't

2022-11-10 13:07 UTC, rinaok commented
> > On Daily, @olaf-k mentioned the scrolling problem. [This is a solution I proposed not long ago](https://github.com/Vonage/vivid-3/pull/603/commits/39024ca8123702cfd874ea6f309868f7b38b21b5), Until we find a third party library for that, I think this can be the solution. What do you think? @yinonov
> 
> should it work on this PR recent deployment? it doesn't

Yeah I know, it works locally but not in the deployment preview

2022-11-10 16:14 UTC, olaf-k requested changes

2022-11-10 16:14 UTC, olaf-k commented on apps/docs/assets/scripts/scroll-handler.js
> +		}, 1);
the only way I found to remove flakiness was to wait for the `aside` to be painted and have an actual height
```js
const setScrollFromLocalStorage = () => {
	const asideElement = getAsideElement();
	if (asideElement.offsetHeight > 0)
		asideElement.scrollTop = localStorage.getItem("scroll") ?? 0;
	else
		requestAnimationFrame(setScrollFromLocalStorage);
}
```

2022-11-11 05:30 UTC, yinonov commented
> > > On Daily, @olaf-k mentioned the scrolling problem. [This is a solution I proposed not long ago](https://github.com/Vonage/vivid-3/pull/603/commits/39024ca8123702cfd874ea6f309868f7b38b21b5), Until we find a third party library for that, I think this can be the solution. What do you think? @yinonov
> 
> > 
> 
> > should it work on this PR recent deployment? it doesn't
> 
> 
> 
> Yeah I know, it works locally but not in the deployment preview 

Sounds like a race condition

https://github.com/Vonage/vivid-3/pull/813#discussion_r1019344679

2022-11-13 13:08 UTC, rinaok commented on apps/docs/assets/scripts/scroll-handler.js
> +		}, 1);
@olaf-k thank you!!!

2022-11-13 13:10 UTC, rinaok commented on apps/docs/assets/scripts/scroll-handler.js
> +		getAsideElement().addEventListener('scroll', onScroll);
@olaf-k you mean outside of the whenDefined?

2022-11-14 09:17 UTC, olaf-k commented on apps/docs/assets/scripts/scroll-handler.js
> +		getAsideElement().addEventListener('scroll', onScroll);
no, I thought the handler did different things for window and aside, don't mind my comment.

2022-11-14 09:18 UTC, olaf-k approved these changes

2022-11-14 09:24 UTC, merged