feat(components): direction support for listbox
Vonage/vivid-3 pull request #817
Opened 2022-11-10 19:37 UTC by yinonov

this maneuver easily features a variant of listbox similar to the design [button-toggle-group](https://vivid.vonage.com/?path=/story/components-button-toggle-group--pill-shape) had. listbox, most likely, provides better semantics.

Disclaimer:

1. as block sizing could only be affected by the listbox child items, and as child items are, in practice, options, this may conflict. an option should not feature sizing. [density increment](https://vivid.deno.dev/designs/design-tokens#sizing) could be used instead

2. same goes for shape

- [x] add keydown handling for horizontal arrows interaction

This enablement can also be provided by a dedicated component or action group usage example.

should certainly be investigated to choose best role and whether keyboard handling is required and how

2022-11-13 08:29 UTC, rachelbt reviewed
so what if one wants to have a toogle-icon-buttons group?
I think that the shape is also needed...no?

2022-11-13 08:29 UTC, rachelbt commented on libs/components/src/lib/listbox/listbox.scss
> +	}
```suggestion

```
this is the default of flex you don't need to specify it

2022-11-13 13:43 UTC, yinonov commented on libs/components/src/lib/listbox/listbox.scss
> +	}
10x

2022-11-13 13:44 UTC, yinonov commented
> so what if one wants to have a toogle-icon-buttons group? I think that the shape is also needed...no?

that's an issue yeah

2022-11-13 15:21 UTC, yinonov commented
> so what if one wants to have a toogle-icon-buttons group? I think that the shape is also needed...no?

@rachelbt listbox can set styles on its child options
```css
border-radius: 24px;
overflow: hidden;
```

2022-11-24 07:35 UTC, yinonov commented
> > so what if one wants to have a toogle-icon-buttons group? I think that the shape is also needed...no?
> 
> @rachelbt listbox can set styles on its child options
> 
> ```css
> border-radius: 24px;
> overflow: hidden;
> ```
> 
> within a select, options will need to be sharpened. it's more of a reason to apply shaping style from the wrapper <img alt="image" width="198" src="https://user-images.githubusercontent.com/15140652/201595287-6e1c0e49-ace5-4d6a-b05d-44beedc99a65.png">

@rachelbt applied

2022-11-24 10:49 UTC, olaf-k requested changes
the change in orientation should update the keyboard handler: in the current deployment, changing a vertical listbox to a horizontal one leaves the up/down keys responsible for moving

2022-11-24 10:49 UTC, olaf-k commented on libs/components/src/lib/listbox/listbox.ts
> +		const key = e.key;
not needed

2022-11-24 10:49 UTC, olaf-k commented on libs/components/src/lib/listbox/README.md
> +When using shape - pay in mind setting the slotted elements with the same shape property.
"When using this property, remember to set to slotted elements to the same value."

didn't play with the code yet, but couldn't this be done from the listbox directly instead of leaving the responsibility to the user?

2022-11-24 10:49 UTC, olaf-k commented on libs/components/src/lib/listbox/README.md
> +Listbox displays list of [vwc-option](../../components/option) and allow users to select from them.
^allows

2022-11-26 19:59 UTC, yinonov commented
> there's something weird with the keyboard handlers: in the current deployment, changing a vertical listbox to a horizontal one leaves the up/down keys responsible for moving

it's the same for radio-group and it actually feels right. I wonder why horizontal arrow keydown don't trigger vertical navigation OOTB as well

2022-11-26 20:11 UTC, yinonov commented on libs/components/src/lib/listbox/README.md
> +Listbox displays list of [vwc-option](../../components/option) and allow users to select from them.
checked with a grammer checker. both versions seem to be satisfactory 🤷‍♂️

2022-11-26 20:11 UTC, yinonov commented on libs/components/src/lib/listbox/README.md
> +Listbox displays list of [vwc-option](../../components/option) and allow users to select from them.
```suggestion
Listbox displays a list of [vwc-option](../../components/option) and allow users to select from them.
```

2022-11-26 20:14 UTC, yinonov commented on libs/components/src/lib/listbox/README.md
> +When using shape - pay in mind setting the slotted elements with the same shape property.
no. it can easily be done by authors. component intervention is a last resort

2022-11-26 20:21 UTC, yinonov commented on libs/components/src/lib/listbox/README.md
> +When using shape - pay in mind setting the slotted elements with the same shape property.
actually, in this particular case, is IS done by the listbox

2022-11-26 20:26 UTC, yinonov commented on libs/components/src/lib/listbox/listbox.ts
> +		const key = e.key;
how did TS not catch that? 🤔

2022-11-27 11:15 UTC, olaf-k commented on libs/components/src/lib/listbox/README.md
> +Listbox displays list of [vwc-option](../../components/option) and allow users to select from them.
> checked with a grammer checker. both versions seem to be satisfactory 🤷‍♂️

^grammar 😁

2022-11-27 11:26 UTC, olaf-k commented
> it's the same for radio-group and it actually feels right. I wonder why horizontal arrow keydown don't trigger vertical navigation OOTB as well

`radio-group` doesn't update its keyboard handler on direction change and uses up/down along with left/right indifferently.
the current behavior of `listbox` does not feel right (try to add `direction="horizontal"` in the first doc example)

2022-11-27 16:28 UTC, yinonov commented on libs/components/src/lib/listbox/README.md
> +Listbox displays list of [vwc-option](../../components/option) and allow users to select from them.
I'll have to trust you on that one

2022-11-27 16:28 UTC, yinonov commented on libs/components/src/lib/listbox/README.md
> +Listbox displays a list of [vwc-option](../../components/option) and allow users to select from them.
```suggestion
Listbox displays a list of [vwc-option](../../components/option) and allows users to select from them.
```

2023-03-22 14:25 UTC, closed without merging

2023-03-22 14:25 UTC, acelletti commented
Moved to [VIV-863 - Investigate direction support for listbox](https://jira.vonage.com/browse/VIV-863)