feat(docs): adopt `@microsoft/api-extractor` & `@custom-elements-manifest/analyzer`
Vonage/vivid-3 pull request #821
Opened 2022-11-13 13:11 UTC by k-paxian

- Generate `customElements` manifest
- Generate vivid components api model

2022-11-13 13:22 UTC, yinonov reviewed
@k-paxian thanks! better starting point than #818

2022-11-13 13:22 UTC, yinonov commented on libs/components/project.json
> +        "commands": [
@YonatanKra should run these commands pre-packaging step

2022-11-13 13:22 UTC, yinonov commented on libs/components/project.json
> +          "api-extractor run -c ./libs/components/api-extractor.json"
should evaluate as we do not follow TSDoc guidelines completely

2022-11-13 13:23 UTC, yinonov commented on .github/workflows/_publish-package.yml
> +          npx nx run components:gen
should this be ran manually or a "prestart" implementation in project.json

2022-11-13 13:25 UTC, yinonov commented on cem.config.mjs
> +    ]
following steps, create plugin to render code block within comments. eventually READMEs should be autogenerated

2022-11-13 13:38 UTC, k-paxian commented on libs/components/project.json
> +          "api-extractor run -c ./libs/components/api-extractor.json"
no worries, there is a config ignoring inconsistency for now, it can be un-ignored gradually later
![image](https://user-images.githubusercontent.com/18071010/201524660-b58c6aea-49d4-4510-b5ee-ea67ae976231.png)

2022-11-13 13:40 UTC, k-paxian commented on .github/workflows/_publish-package.yml
> +          npx nx run components:gen
it's more like `prepublish` action and for now the only spot for publishing is in the workflow area 🤷

2022-11-13 14:02 UTC, k-paxian commented on libs/components/project.json
> +        "commands": [
these needs to be run anywhere after the build process, since api-extractor relying on `index.d.ts` produced during the build

2022-11-16 21:29 UTC, yinonov requested changes

2022-11-16 21:42 UTC, yinonov commented on README.md
> +##### Built With [Typescript](https://www.typescriptlang.org), [Fast](https://fast.design), [Sass](https://sass-lang.com) and ❤️
good one

2022-11-16 21:42 UTC, yinonov commented on .npmrc
> +package-lock=false
how does it affect installations?

2022-11-16 21:44 UTC, yinonov commented on package.json
> +		"rollup-plugin-postcss": "^4.0.2",
why? I vaguely recall it was removed intentionally. need it here?

2022-11-17 07:19 UTC, yinonov requested changes

2022-11-17 07:19 UTC, yinonov commented on libs/components/project.json
> +    "gen": {
maybe more explicit?

```suggestion
    "generateMeta": {
```

2022-11-17 21:05 UTC, k-paxian commented on libs/components/src/index.ts
> +export * from './lib/enums';
while specifying the attributes we are using string literals for certain values like 
![image](https://user-images.githubusercontent.com/18071010/202558895-04c1743f-bd86-499c-ba2a-e5359623c065.png)

But we would like to use const references there like
```jsx
import { Connotation, Layout } from '@vonage/vivid-react'

          <VwcButton
            connotation={Connotation.CTA}
            layout={Layout.Outlined}
          />
```

2022-11-17 21:12 UTC, k-paxian commented on .npmrc
> +package-lock=false
controversial one, we usually use yarn to install packages, just to have both `yarn.lock` & `package.lock` side by side looks a bit odd, even worse, yarn is making use of `package.lock` if it exists. Don't mind to discard this change if you feel it's not useful.

2022-11-17 21:15 UTC, k-paxian commented on package.json
> +		"rollup-plugin-postcss": "^4.0.2",
I don't remember exactly, but at some point during the `build` script run on a windows box it desperately asks for this dependency 🤷 worth checking at least why is it happening?

2022-11-17 21:16 UTC, k-paxian commented on libs/components/project.json
> +          "cem analyze --config cem.config.mjs",
yes, works fine by me on a windows machine

2022-11-17 21:17 UTC, k-paxian commented on package.json
> +		"rollup-plugin-postcss": "^4.0.2",
if it shouldn't be there feel free to discard it

2022-11-17 21:42 UTC, yinonov commented on .npmrc
> +package-lock=false
if it doesn't have any affect on the result of generated files of this scope's target, let's revert this one.
you may have a point here but I recall having trouble with packages not aligning to semver in the past, can extract it this to another tiny PR?

2022-11-18 07:45 UTC, yinonov commented on libs/components/src/index.ts
> +export * from './lib/enums';
sure - we thought of refactoring to const be there was no such requirement until now.

- [ ] refactor enums to consts
- [ ] export enums / consts subset types
- [ ] remove [libs/components/src/index.ts](https://github.com/Vonage/vivid-3/pull/821/files/cdc7a88ad75cbaf307dffaf02e8a4e70ef246f4b#diff-9068f8a41f226453682b9874c9951a886671b0552e4d8baf2447404f1091d6b9) once done

2022-11-18 07:46 UTC, yinonov commented on libs/components/src/index.ts
> +export * from './lib/enums';
Vonage/vivid-3#844

2022-11-18 08:12 UTC, yinonov submitted a review, later dismissed

2022-11-18 08:13 UTC, yinonov commented
can you please run `npx bachball change` to generate change file?

2022-11-18 12:30 UTC, yinonov approved these changes

2022-11-18 12:38 UTC, merged