feat(components): combobox new component
Vonage/vivid-3 pull request #825
Opened 2022-11-13 22:14 UTC by yinonov

Closes #824

2022-12-12 21:24 UTC, yinonov commented on libs/components/src/lib/option/option.scss
> -	border-radius: 6px;
requested by design?

2022-12-12 21:26 UTC, yinonov commented on libs/components/src/lib/combobox/ui.test.ts
> +
set the viewport width to not waste extra space and a large image

2022-12-13 10:59 UTC, rinaok commented on libs/components/src/lib/option/option.scss
> -	border-radius: 6px;
@yinonov IDK... It is your change: https://github.com/Vonage/vivid-3/pull/825/commits/418d54dbe942418ac7a935e76efba7b6bc3a87f4
I can remove it if not needed.

2022-12-13 14:47 UTC, rinaok commented on libs/components/src/lib/combobox/combobox.scss
> +}
@rachelbt How I make the popup be the same width as the combobox?

2022-12-13 14:56 UTC, rinaok commented on libs/components/src/lib/combobox/combobox.scss
> +	--_popup-width: 209px;
@rachelbt Tried that but it didn't work, that's why I put 209px

2022-12-13 16:16 UTC, rachelbt commented on libs/components/src/lib/popup/popup.scss
> +		position: absolute;
```suggestion
		position: absolute;
		inline-size: var(#{variables.$popup-width}
```

2022-12-13 16:17 UTC, rachelbt commented on libs/components/src/lib/combobox/combobox.scss
> +
```suggestion
:host {
  position: relative;
  }
```

2022-12-13 16:59 UTC, rinaok commented
> Closes #824
> 
> * [x]  add support for popup width (or more specifically its assigned node)
> * [ ]  enable text field icon trailing, or compose a dedicated text field with alternate style (can be customized in element definition). or just use plain input in template

@yinonov Are you sure we need icon inside the combobox? I think that chevron is enough .

2022-12-15 19:21 UTC, yinonov commented on libs/components/src/lib/combobox/README.md
> +- Type: `'inline'` | `'list'` | `'both'`
good fix. should we be adding `none`? https://github.com/microsoft/fast/tree/6ebb5ec7bdb7666f49ddc524bc56f70a2e8aa574/packages/web-components/fast-foundation/src/combobox#variables

2022-12-18 14:00 UTC, rachelbt reviewed
when opening the listbox - should the user navigate with the up & down arrows?

2022-12-18 14:19 UTC, rinaok commented
> when opening the listbox - shouldn't the user navigate with the up & down arrows?

@rachelbt Yes I know, I'm working on it

2022-12-18 14:55 UTC, rinaok commented
> > when opening the listbox - shouldn't the user navigate with the up & down arrows?
> 
> @rachelbt Yes I know, I'm working on it

@rachelbt It's working now

2022-12-18 15:37 UTC, yinonov commented on libs/components/src/lib/combobox/README.md
> +- Type: `'inline'` | `'list'` | `'both'`
It's a native spec. not our call

2022-12-18 15:45 UTC, rinaok approved these changes

2022-12-19 10:55 UTC, yinonov reviewed
how does triggering the focus on an option work? on `keypress`? would it help to delegate focus in popup definition? so that focus on host will automatically decide which option to focus on (instead of manual)

2022-12-19 11:33 UTC, rinaok commented
> how does triggering the focus on an option work? on `keypress`? would it help to delegate focus in popup definition? so that focus on host will automatically decide which option to focus on (instead of manual)

@yinonov You want us to remove all Fast's key handlers from the combobox template and that the popup will handle it?

2022-12-19 13:05 UTC, yinonov commented
> rs from the combobox template and that the po

no! so it's a hindered knowledge to this scope? handled by fast? I'd still add tests to it. WDYT?

2022-12-19 13:11 UTC, rinaok commented
> 

@yinonov Yes, all the behaviour is handled by Fast

2022-12-19 13:12 UTC, yinonov reviewed
why does the `open` section rendered snippet autofocus? I didn't see any explicit code for it (it might be intentional. just making sure)

<img width="805" alt="image" src="https://user-images.githubusercontent.com/15140652/208433777-c2fecd78-5a5c-46f2-b442-b42ee3e2852a.png">

2022-12-19 13:21 UTC, yinonov commented on change/@vonage-vivid-8865978f-8468-4691-a216-12a13c91a92f.json
> +{
is this redundant?

2022-12-19 13:23 UTC, yinonov commented on libs/components/src/lib/combobox/README.md
> +### Option
it should be `default`. as in
https://github.com/Vonage/vivid-3/blob/9bafb96d81556e9cff522046acd2ca166da29b01/libs/components/src/lib/menu/README.md#L78-L81

2022-12-19 13:38 UTC, rinaok commented on libs/components/src/lib/combobox/README.md
> +### Option
@yinonov updated but we need to update it also in listbox readme

2022-12-19 14:09 UTC, olaf-k requested changes

2022-12-19 14:09 UTC, olaf-k commented on libs/components/src/lib/combobox/README.md
> +</vwc-combobox>
this example does not demonstrate the `value` usage.
```suggestion
<vwc-combobox value="First Option">
 <vwc-option text="First Option"></vwc-option>
 <vwc-option text="Second Option"></vwc-option>
</vwc-combobox>
```

also, and this is beyond the scope of your PR, but why are `option` text and value the same thing? they should be be two separate props/attrs

2022-12-19 14:24 UTC, olaf-k commented
clicking on the combobox button opens the list of options, but clicking again does not close it.

2022-12-19 14:28 UTC, olaf-k commented
if you have a page with a combobox followed by a listbox, the combobox list appears under the listbox when opened:
![chrome_DdqtA2DSml](https://user-images.githubusercontent.com/1153034/208448192-74ed0cff-9f4f-4397-a239-a422224fbfc6.gif)

2022-12-19 18:31 UTC, yinonov commented on libs/components/src/lib/combobox/README.md
> +</vwc-combobox>
I think options here should have a matching value. Don't they?

2022-12-19 18:33 UTC, yinonov commented
U mean it doesn't go on top? Top-layer access issue. Referenced in our docs in multiple caveat sections

2022-12-20 08:05 UTC, olaf-k commented on libs/components/src/lib/combobox/README.md
> +</vwc-combobox>
> I think options here should have a matching value. Don't they?

the FAST and native implementations both distinguish the displayed text from the form value, I was expecting our `option` to behave in the same manner.

2022-12-20 08:10 UTC, yinonov commented on libs/components/src/lib/combobox/README.md
> +</vwc-combobox>
of course. sorry, didn't catch ur previous comment. I mean combobox value should match an option value

2022-12-20 09:08 UTC, rachelbt commented on libs/components/src/lib/popup/partials/variables.scss
> +$popup-width: --popup-width;
```suggestion
.popup {
	$popup-width: --_popup-width;
	#{$popup-width}: 50%;
}
```

2022-12-20 09:30 UTC, rachelbt commented on libs/components/src/lib/combobox/combobox.scss
> +	--popup-width: 100%;
```suggestion
	$popup-width: --_popup-width;
	#{$popup-width}: 100%;
```

2022-12-20 09:30 UTC, rachelbt commented on libs/components/src/lib/popup/partials/variables.scss
> +$popup-width: --popup-width;
```suggestion
$popup-width: --_popup-width;
```

2022-12-20 10:13 UTC, rinaok commented
> 

@olaf-k @yinonov It's the same behaviour as in FAST https://explore.fast.design/components/fast-combobox, do you think it's a bug?

2022-12-20 13:03 UTC, olaf-k commented
> @olaf-k @yinonov It's the same behaviour as in FAST [explore.fast.design/components/fast-combobox](https://explore.fast.design/components/fast-combobox), do you think it's a bug?

good point, I checked and [they already have an issue on their side about it](https://github.com/microsoft/fast/issues/5721).

2022-12-20 13:11 UTC, yinonov commented
> why does the `open` section rendered snippet autofocus? I didn't see any explicit code for it (it might be intentional. just making sure)
> 
> <img alt="image" width="805" src="https://user-images.githubusercontent.com/15140652/208433777-c2fecd78-5a5c-46f2-b442-b42ee3e2852a.png">

https://github.com/microsoft/fast/blob/6ebb5ec7bdb7666f49ddc524bc56f70a2e8aa574/packages/web-components/fast-foundation/src/combobox/combobox.ts#L336-L352

2022-12-20 13:17 UTC, rinaok commented
> U mean it doesn't go on top? Top-layer access issue. Referenced in our docs in multiple caveat sections (e.g. [tooltip#caveat](https://vivid.deno.dev/components/tooltip#caveat)). perhaps a similar caveat mention should be added for combobox

@yinonov Added Caveat

2022-12-20 13:17 UTC, rinaok approved these changes

2022-12-20 13:20 UTC, rinaok submitted a review, later dismissed

2022-12-20 13:32 UTC, olaf-k commented on libs/components/src/lib/combobox/README.md
> +A common practice used in apps / frameworks to promote a Combobox component to top other elements z-axis, is to utilise a service that dynamically appends a Combobox component to the end of the body
hmm. this probably is a valid advice for modal components that appear on their own but this is hardly applicable to form components such as the combobox. I'm ok to leave the widget as it is until someone complains but we need to be prepared for another solution than "dynamically append it to body".

2022-12-20 13:39 UTC, olaf-k requested changes
I'll open an issue for this option.value thingy.

2022-12-20 13:42 UTC, rinaok commented on libs/components/src/lib/combobox/README.md
> +A common practice used in apps / frameworks to promote a Combobox component to top other elements z-axis, is to utilise a service that dynamically appends a Combobox component to the end of the body
ok

2022-12-20 13:44 UTC, rinaok submitted a review, later dismissed

2022-12-20 14:11 UTC, olaf-k approved these changes
can you put back the rest of the disclaimer?

```
## Caveat

Document elements display precedence is formed by the imaginary z-axis [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context), commonly by order of which elements are rendered and special properties (e.g. _z-index_).
Combobox component is a low level element, unaware of its document context, but is, in most cases, required to overlay on top of all elements.
```

2022-12-20 15:06 UTC, rinaok approved these changes

2022-12-21 11:52 UTC, yinonov commented on libs/components/src/lib/combobox/combobox.scss
> +	$popup-width: --_popup-width;
how did `--_popup-width` pass stylelint? it should have thrown an error exception.

extract to, and import from `partials/_variables.scss`

2022-12-21 11:54 UTC, yinonov commented on libs/components/src/lib/combobox/ui.test.ts
> +
@rinaok

2022-12-21 14:13 UTC, rinaok commented on libs/components/src/lib/combobox/combobox.scss
> +	$popup-width: --_popup-width;
done

2022-12-21 14:15 UTC, rinaok commented on libs/components/src/lib/combobox/combobox.scss
> +	$popup-width: --_popup-width;
@rachelbt @yinonov I think that we should add default value for popup-width inside popup css, right?

<img width="599" alt="Screenshot 2022-12-21 at 16 15 14" src="https://user-images.githubusercontent.com/10883919/208925861-36af351a-774d-4d3b-b215-04a73806222b.png">

2022-12-21 14:22 UTC, yinonov commented on libs/components/src/lib/combobox/combobox.scss
> +	#{popup-variables.$popup-width}: 100%;
can u explain this again? where is this variable used?

2022-12-21 14:44 UTC, rinaok commented on libs/components/src/lib/combobox/combobox.scss
> +	#{popup-variables.$popup-width}: 100%;
@yinonov When popup is strategy="absolute"

2022-12-21 14:57 UTC, yinonov commented on libs/components/src/lib/combobox/combobox.scss
> +	#{popup-variables.$popup-width}: 100%;
and?

2022-12-21 15:20 UTC, yinonov commented on libs/components/src/lib/combobox/combobox.scss
> +	#{popup-variables.$popup-width}: 100%;
never mind followed the code

2022-12-21 15:52 UTC, rinaok approved these changes

2022-12-27 08:22 UTC, olaf-k commented on libs/components/src/lib/combobox/combobox.template.ts
> +		  ${x => x.label}
mixed spaces with tabs here and in `comboboxTemplate` (should've been caught by linter though?)

2022-12-27 14:11 UTC, yinonov commented on libs/components/src/lib/combobox/combobox.template.ts
> +		  ${x => x.label}
something's off with eslint

2023-01-05 11:26 UTC, merged