refactor(tooltip): disable manual handling of open state
Vonage/vivid-3 pull request #829
Opened 2022-11-14 16:33 UTC by rinaok

2022-11-14 23:50 UTC, yinonov requested changes

2022-11-14 23:50 UTC, yinonov commented on libs/components/src/lib/popup/popup.ts
> +	get anchorElement(): Element | null | undefined {
why? then this accessor might as well be a property and be assigned to the actual element

2022-11-14 23:50 UTC, yinonov commented on libs/components/src/lib/tooltip/README.md
should explain what triggers the tooltip, and why (by recommended pattern) -

> A tooltip is a popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it. It typically appears after a small delay and disappears when Escape is pressed or on mouse out.

https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/

2022-11-14 23:50 UTC, yinonov commented on libs/components/src/lib/tooltip/tooltip.template.ts
>  import { html } from '@microsoft/fast-element';
no real change in this file, can be reduced from the PR

2022-11-14 23:56 UTC, yinonov reviewed
we should go over microsoft/fast#6468

2022-11-15 11:22 UTC, rinaok commented on libs/components/src/lib/tooltip/tooltip.template.ts
>  import { html } from '@microsoft/fast-element';
moved the role inside

2022-11-15 16:04 UTC, yinonov commented on libs/components/src/lib/tooltip/README.md
> +The tooltip shoul be placed on interactive controls (things that can be hovered or focusable) such as: button, checkbox, input text.
```suggestion
The tooltip should be placed on interactive controls (things that can be hovered or focusable) such as: button, checkbox, input text.
```

2022-11-15 16:25 UTC, yinonov requested changes
fast mentioned something regarding control over delay via css. what's our delay now?

2022-11-15 16:25 UTC, yinonov commented on libs/components/src/lib/tooltip/README.md
> +A tooltip is a popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it. It typically appears after a small delay and disappears when
```suggestion
A tooltip is a popup that displays informative message, description or explanation related to an element receiving keyboard focus or when the mouse hovers over it. It typically appears after a small delay and disappears when Escape is pressed or on mouse out. 
```

2022-11-15 16:25 UTC, yinonov commented on libs/components/src/lib/tooltip/README.md
> +The tooltip should be referenced through the use of aria-describedby. The aria-describedby attribute is on the anchor element, not on the tooltip. It should be the same as tooltip's id. To change ari
are we planning to feature this? if so, why document as instructions?

2022-11-15 16:25 UTC, yinonov commented on libs/components/src/lib/tooltip/README.md
> +The tooltip shoul be placed on interactive controls (things that can be hovered or focusable) such as: button, checkbox, input text.
```suggestion
The tooltip should be placed on interactive controls, elements that can be hovered over or focusable (e.g. button, checkbox, input text etc'.).
```

2022-11-15 16:25 UTC, yinonov commented on libs/components/src/lib/tooltip/README.md
> +The tooltip is a description and therefor, the tooltip itself can not be interactive or focusable and contains only text.
first describe the text as we do in other component.

next paragraph should note -

> Because the tooltip itself never receives focus and is not in the tabbing order, a tooltip can not contain interactive elements like links, inputs, or buttons

_[mdn](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role#description)_

2022-11-16 09:40 UTC, rinaok commented on libs/components/src/lib/tooltip/README.md
> +The tooltip should be referenced through the use of aria-describedby. The aria-describedby attribute is on the anchor element, not on the tooltip. It should be the same as tooltip's id. To change ari
So you mean that the user should not know about it at all?

2022-11-16 16:12 UTC, rinaok commented
> fast mentioned something regarding control over delay via css. what's our delay now?

We don't have a delay. They remove it because they now control tooltip transitions via CSS.

I added 
`.open {
		transition: visibility 0s 0s linear, opacity 50ms 0.5s linear;
		opacity: 1;
		visibility: visible;
	}

	&:not(.open) {
		transition: visibility 0s 0.5s, opacity 50ms linear;
		opacity: 0;
		visibility: hidden;
	}`
	
	what do you think?

2022-11-17 07:44 UTC, yinonov requested changes

2022-11-17 07:44 UTC, yinonov commented on libs/components/src/lib/tooltip/README.md
> +A tooltip is a popup that displays informative message, description or explanation related to an element receiving keyboard focus or when the mouse hovers over it. It typically appears after a small
```suggestion
A tooltip displays additional, non-essential, informative message, description or explanation to a focusable element upon hover or focus. It typically appears after a short delay and disappears when `Escape` key is pressed, element looses focus or hovered off. 
```

2022-11-17 07:46 UTC, yinonov reviewed
shouldn't the visual regression fail?

2022-11-17 07:50 UTC, yinonov requested changes

2022-11-17 07:50 UTC, yinonov commented on libs/components/src/lib/tooltip/README.md
> +  <vwc-button id="button" icon="help-line" shape="pill"></vwc-button>
this shouldn't be a button as it doesn't trigger any action.
it can be a plain icon with `tabindex="0"` and `aria-describedby`.

this is more of a toggletip implememtation. perhaps it's better to avoid this use-case and resolve to actual controls (button, text-field etc')

2022-11-17 07:52 UTC, yinonov commented
> > fast mentioned something regarding control over delay via css. what's our delay now?
> 
> @yinonov We don't have a delay. Fast removed it because they now control tooltip transitions via CSS.
> 
> I added it like fast:
> 
> ```
> .open {
> 		opacity: 1;
> 		transition: visibility 0s 0s linear, opacity 50ms 0.5s linear;
> 		visibility: visible;
> 	}
> 
> 	&:not(.open) {
> 		opacity: 0;
> 		transition: visibility 0s 0.5s, opacity 50ms linear;
> 		visibility: hidden;
> 	}
> ```
> 
> ```
> what do you think?
> ```

yes that's good to reflect. we might want a default value here? maybe a css variable to control the duration? or better off, no default but a usage example of adding it via css (as you did)

2022-11-17 09:14 UTC, rinaok commented
> 

you mean that we should remove it from our css, and let the user add it?

2022-11-17 09:16 UTC, rinaok commented
> shouldn't the visual regression fail?

why?

2022-11-17 09:20 UTC, rinaok commented on libs/components/src/lib/tooltip/README.md
> +  <vwc-button id="button" icon="help-line" shape="pill"></vwc-button>
"The tooltip can be placed on interactive controls (things that can be hovered or focusable) such as: button, checkbox, input text." 
What is the problem with the button? You can't place it on an icon.

2022-11-17 10:09 UTC, rinaok commented
> > > fast mentioned something regarding control over delay via css. what's our delay now?
> > 
> > 
> > @yinonov We don't have a delay. Fast removed it because they now control tooltip transitions via CSS.
> > I added it like fast:
> > ```
> > .open {
> > 		opacity: 1;
> > 		transition: visibility 0s 0s linear, opacity 50ms 0.5s linear;
> > 		visibility: visible;
> > 	}
> > 
> > 	&:not(.open) {
> > 		opacity: 0;
> > 		transition: visibility 0s 0.5s, opacity 50ms linear;
> > 		visibility: hidden;
> > 	}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > what do you think?
> > ```
> 
> yes that's good to reflect. we might want a default value here? maybe a css variable to control the duration? or better off, no default but a usage example of adding it via css (as you did)

I think that the user should not control on the transition at all.

2022-11-17 10:11 UTC, rinaok commented on libs/components/src/lib/popup/popup.scss
> -	}
@yinonov For the tooltip's transition to work, I had to remove the `display:none` from the popup. What do you think about it?

2022-11-17 20:31 UTC, yinonov commented on libs/components/src/lib/tooltip/README.md
> +  <vwc-button id="button" icon="help-line" shape="pill"></vwc-button>
but this is a pointless button. button triggers action on click. what does this one trigger?

2022-11-20 11:59 UTC, rinaok commented on libs/components/src/lib/tooltip/README.md
> +  <vwc-button id="button" icon="help-line" shape="pill"></vwc-button>
@yinonov Do you want to remove this usage example?

2022-11-20 13:14 UTC, yinonov commented on libs/components/src/lib/tooltip/README.md
> +  <vwc-button id="button" icon="help-line" shape="pill"></vwc-button>
I think it is best

2022-11-20 15:12 UTC, yinonov commented on libs/components/src/lib/popup/popup.scss
> -	}
Can u elaborate?

2022-11-21 08:57 UTC, rinaok commented on libs/components/src/lib/popup/popup.scss
> -	}
@yinonov If the popup has the display:none when not open. We can't see the transition.

2022-11-22 09:54 UTC, yinonov commented on libs/components/src/lib/popup/popup.scss
> -	}
this might affect SR reading content which is supposedly doesn't display, thus shouldn't be read by any ATs

2022-11-22 09:55 UTC, olaf-k requested changes

2022-11-22 09:55 UTC, olaf-k commented on libs/components/src/lib/tooltip/README.md
> +A tooltip displays additional, non-essential, informative message, description or explanation to a focusable element upon hover or focus. It typically appears after a short delay and disappears when
`element loses focus or hover state.`

2022-11-22 09:55 UTC, olaf-k commented on libs/components/src/lib/tooltip/README.md
> +The tooltip should be placed on interactive controls, elements that can be hovered over or focusable (e.g. button, checkbox, input text etc'.).
(e.g., button, checkbox, input text, etc.).

2022-11-22 09:55 UTC, olaf-k commented on libs/components/src/lib/tooltip/tooltip.ts
> +		this.id = 'tooltip';
this means that several tooltips on the same page will share the same `id`!

2022-11-22 12:26 UTC, rinaok commented on libs/components/src/lib/popup/popup.ts
> +		if (!this.open || !this.anchorEl) {
it's protected not public

2022-11-22 12:28 UTC, rinaok commented on libs/components/src/lib/popup/popup.scss
> -	}
I'm not sure I understood. The tooltip is visible false, isn't it affect SR reading content as well?

2022-11-22 16:22 UTC, olaf-k requested changes
I don't think setting the `aria-describedby` dynamically to the anchor was a bad strategy, maybe just using unique ids?

2022-11-22 16:22 UTC, olaf-k commented on libs/components/src/lib/tooltip/tooltip.template.ts
> +  <div class="tooltip" role="tooltip" inert>
`inert` is an issue here as it "makes the browser "ignore" user input events for the element, including focus events and events from assistive technologies" ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert))
which means that `aria-describedby` will not take the inert element into account (confirmed by a quick test with NVDA and VoiceOver)

2022-11-22 16:25 UTC, olaf-k commented on libs/components/src/lib/tooltip/tooltip.template.ts
> +  <div class="tooltip" role="tooltip" inert>
(this is less important, but apparently `role=tooltip` seems to be useless from what I read: screen readers just ignore it)

2022-11-24 10:05 UTC, rinaok commented on libs/components/src/lib/tooltip/tooltip.template.ts
> +  <div class="tooltip" role="tooltip" inert>
@olaf-k @yinonov I removed the inert from this PR, we have a separate PR for that: https://github.com/Vonage/vivid-3/pull/827

2022-11-24 10:35 UTC, olaf-k requested changes

2022-11-24 10:35 UTC, olaf-k commented on libs/components/src/lib/tooltip/README.md
> +A tooltip displays additional, non-essential, informative message, description or explanation to a focusable element upon hover or focus. It typically appears after a short delay and disappears when
remove `typically` since we're talking specifically about this implementation
+
it actually only disappears on Esc when it is focused, not when it is hovered, is it the wanted behavior?

2022-11-24 17:05 UTC, olaf-k commented on libs/components/src/lib/tooltip/README.md
> +A tooltip displays additional, non-essential, informative message, description or explanation to a focusable element upon hover or focus. It typically appears after a short delay and disappears when
sure, it makes sense to track the behavior there, but the current doc should reflect the current behavior

2022-11-24 17:11 UTC, rinaok commented
@olaf-k @yinonov 

What do you think? Can we merge the pr?

2022-11-25 08:59 UTC, olaf-k commented
> @olaf-k @yinonov
> 
> What do you think? Can we merge the pr?

I'm ok with the PR as it is, but we'll have to dedicate some time going over the widgets behavior when using a screen reader.
as it is (without `describedby`) the tooltip is not read when the button is focused. out of this particular scope though.

2022-11-25 08:59 UTC, olaf-k approved these changes

2022-11-25 10:31 UTC, olaf-k requested changes

2022-11-25 10:31 UTC, olaf-k commented on libs/components/src/lib/tooltip/tooltip.template.ts
>  <vwc-popup class="${getClasses}" arrow alternate
better to use `context.tagFor` than hardcode references to other widgets

2022-11-25 14:54 UTC, olaf-k approved these changes

2022-11-27 13:36 UTC, merged