perf(components): action group role as group
Vonage/vivid-3 pull request #837
Opened 2022-11-16 10:51 UTC by yinonov

see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/group_role

2022-11-21 14:39 UTC, rachelbt commented
_The group role should be used to form a logical collection of items with related functionality_

it seems right to add the role="group" but it may be problematic since we do not know what our consumers are using the action group for.

however we have this:
_The group role should not be used for major perceivable sections of a page. If a section is significant enough that it should be included in the page's table of contents, use the region role or a standard [landmark role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#landmark_roles)._

I'm wondering whether we should add it in the component or suggest adding it with a usage example in the docs.

2022-11-21 16:24 UTC, yinonov commented
> _The group role should be used to form a logical collection of items with related functionality_
> 
> it seems right to add the role="group" but it may be problematic since we do not know what our consumers are using the action group for.
> 
> however we have this: _The group role should not be used for major perceivable sections of a page. If a section is significant enough that it should be included in the page's table of contents, use the region role or a standard [landmark role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#landmark_roles)._
> 
> I'm wondering whether we should add it in the component or suggest adding it with a usage example in the docs.

it can be set by default and be opt-out or even allow author-custom role (where future toolbar might require). it should be documented

2023-03-30 11:37 UTC, rachelbt reviewed
look look great!
Left on comment

2023-03-30 11:37 UTC, rachelbt commented on libs/components/src/lib/action-group/README.md
> +<vwc-action-group role="radiogroup" aria-label="Text Alignment">
👍

2023-03-30 11:37 UTC, rachelbt commented on libs/components/src/lib/action-group/action-group.ts
> +	@attr() role: string | undefined;
is there a way to restrict it to rote types?

2023-03-30 12:03 UTC, olaf-k requested changes

2023-03-30 12:03 UTC, olaf-k commented on libs/components/src/lib/action-group/action-group.template.ts
> +	aria-label="${x => x.ariaLabel}">
if you want the `aria-label` to be updated when it changes on the host, you need to declare it as an `@attr` otherwise it'll just keep the initial value.

2023-03-30 14:35 UTC, olaf-k approved these changes

2023-03-30 14:37 UTC, merged