fix(components): remove hardcoded tags
Vonage/vivid-3 pull request #862
Opened 2022-11-25 14:50 UTC by olaf-k

necessary if we want to be prefix-agnostic

2022-11-25 16:41 UTC, yinonov commented
Bravo!

2022-11-25 16:43 UTC, yinonov requested changes

2022-11-25 16:43 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +				${when(x => !x.open, html`<${iconTag} type='chevron-down-solid'></${iconTag}>`)}
Might as well replace with the `affix` pattern

2022-11-25 17:52 UTC, olaf-k commented
TODO: address CSS too
![image](https://user-images.githubusercontent.com/1153034/204035734-1b171d50-4607-4a01-b004-e2240db9ee81.png)

2022-12-06 07:15 UTC, rachelbt reviewed
👍

2022-12-06 07:15 UTC, rachelbt commented on libs/components/src/lib/accordion-item/accordion-item.scss
>  			margin-inline-start: 16px;
we actually do not need this at all - this is not a slot... 
we can keep only this:
`margin-inline-start: 16px;`
no need the `display: flex` at all :)

2022-12-07 21:44 UTC, yinonov requested changes

2022-12-07 21:44 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +
reason for 2 elements is to eagerly load both icons. even if 1 isn't used initially

2022-12-07 21:44 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +	/* eslint-disable @typescript-eslint/indent */
why?

2022-12-07 21:44 UTC, yinonov commented on libs/components/src/lib/accordion/accordion.scss
> +::slotted(:not(:only-of-type)) {
hmm anything then? should we create an issue to propagate role to host as in other widgets?

2022-12-08 09:32 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +	/* eslint-disable @typescript-eslint/indent */
because eslint's idea of how the template should be indented makes it less readable.

2022-12-08 09:36 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.scss
> +::slotted(:not(:only-of-type)) {
yes, I thought about it, but accordion-items don't have particular roles. ours are buttons, but I tried to stay generic.
I'm open to suggestions!

2022-12-13 09:13 UTC, yinonov requested changes

2022-12-13 09:13 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +	/* eslint-disable @typescript-eslint/indent */
this is a local patch and problem will persist in other templates. maybe less relevant to this scope?

2022-12-13 09:15 UTC, yinonov requested changes

2022-12-13 09:15 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +
`<vwc-icon name="chevron-up-solid">` already fetches the svg file from CDN

2022-12-13 12:12 UTC, olaf-k commented
@yinonov eslint exception removed + svg preloading in #909

2022-12-13 13:15 UTC, yinonov approved these changes

2022-12-13 13:28 UTC, merged