fix(jsdocs): solve all lint warnings in project
Vonage/vivid-3 pull request #869
Opened 2022-11-29 15:46 UTC by rinaok

2022-11-30 10:38 UTC, yinonov requested changes
please await #861 as this is a major change applying many files

2022-11-30 10:41 UTC, yinonov requested changes
some of the ommited decorators like accessors (e.g. `@public`) are TSDoc related. we might need to go over them all and fix due to #818

2022-12-05 11:48 UTC, rinaok commented
> please await #861 as this is a major change applying many files

@yinonov Now after #861 is merged, can we merge this?

2022-12-05 16:32 UTC, yinonov commented
> > please await #861 as this is a major change applying many files
> 
> @yinonov Now after #861 is merged, can we merge this?

it requires a very thorough review still. the pain point with this symptom relates to https://github.com/Vonage/vivid-3/pull/110#issuecomment-1006352237

the optimal solution is, if tsdoc-lint was to enforce comments, to remove jsdoc-lint and use the tsdoc-lint instead

2022-12-05 17:22 UTC, rinaok commented
> > > please await #861 as this is a major change applying many files
> > 
> > 
> > @yinonov Now after #861 is merged, can we merge this?
> 
> it requires a very thorough review still. the pain point with this symptom relates to [#110 (comment)](https://github.com/Vonage/vivid-3/pull/110#issuecomment-1006352237)
> 
> the optimal solution is, if tsdoc-lint was to enforce comments, to remove jsdoc-lint and use the tsdoc-lint instead

@yinonov But you said that we should avoid at this point from tsdoc https://github.com/Vonage/vivid-3/pull/110#issuecomment-1006352237

2022-12-06 05:36 UTC, yinonov commented
Because of lint technical limitation not enforcing necessary comments. But if u already went through and added all, we can reconsider tsdoc lint.
It will do more, now that api-extractor generate meta data

2022-12-16 11:19 UTC, yinonov commented
let's try to revive #110

2022-12-19 09:38 UTC, rinaok commented
> let's try to revive #110

@yinonov merged https://github.com/Vonage/vivid-3/pull/110

2022-12-21 09:50 UTC, YonatanKra commented on libs/components/src/lib/breadcrumb/ui.test.ts
> + */
```suggestion
/**
 *
 *
 * @returns (): Promise<void>;
 */
```

2022-12-21 09:52 UTC, YonatanKra reviewed
I think we can exempt test files (`.spec|test.ts`) from tsdoc linting rule.
What do you think @olaf-k ?

2022-12-21 12:23 UTC, yinonov submitted a review, later dismissed
As #110 expected to now redfine eslint rules, it might outdate the changes of this PR.

what worries me is the fact we are not that acquainted with [TSDoc](https://tsdoc.org) and how to use it to its extent

the general idea to automate and improve our workflow is to have comments populating to READMEs and from there to docs website

for web components interfaces, TSDoc lacks some features, of where `custom-elements-manifests` come into play.

1st, let's make 1, single component as perfect POC, have its doc generated automatically.

going over lots of files to fix without a solid understanding the result will probably buy us more debts

2022-12-21 14:23 UTC, olaf-k commented
> I think we can exempt test files (`.spec|test.ts`) from tsdoc linting rule. What do you think @olaf-k ?

my gut feeling would be "yes please!" or at least keep only rules that prevent readability issues (weird capitalization, mix tab/space, this sort of stuff)

2022-12-21 14:24 UTC, yinonov commented
> > I think we can exempt test files (`.spec|test.ts`) from tsdoc linting rule. What do you think @olaf-k ?
> 
> my gut feeling would be "yes please!" or at least keep only rules that prevent readability issues (weird capitalization, mix tab/space, this sort of stuff)

aware of any such preceding practice?

2022-12-21 15:37 UTC, olaf-k commented
> aware of any such preceding practice?

following our chat: it makes sense to keep some formatting rules to keep the code clean and readable for team members and minimize commit noise, while removing strict rules (e.g., no empty functions) for test files.

2022-12-26 10:33 UTC, olaf-k requested changes
Note that the default linting target uses nx's `run-many` to check all projects [and thus skips warnings](https://github.com/nrwl/nx/issues/9638#issuecomment-1118568347).

To get the warnings displayed you must either add `--verbose` to the linting target command or simple run it project by project (e.g., `npx nx lint components`).

At the time of writing, there are still 400+ warning messages from the components project, repeating ones from tsdoc complaining about jsdoc formatting.

2022-12-26 10:45 UTC, rinaok commented
> Note that the default linting target uses nx's `run-many` to check all projects [and thus skips warnings](https://github.com/nrwl/nx/issues/9638#issuecomment-1118568347).
> 
> To get the warnings displayed you must either add `--verbose` to the linting target command or simple run it project by project (e.g., `npx nx lint components`).
> 
> At the time of writing, there are still 400+ warning messages from the components project, repeating ones from tsdoc complaining about jsdoc formatting.

@olaf-k good catch!

2022-12-26 11:39 UTC, olaf-k approved these changes
Seeing the diff, there's a bunch of comments that could use some cleanup, but that's beyond the scope of this PR.

2023-03-22 14:45 UTC, closed without merging