feat(components): override default prefix api
Vonage/vivid-3 pull request #890
Opened 2022-12-06 08:47 UTC by yinonov

- [x] ~~only `index.js` exists in the badge folder. need to split it into index.js and definition.js~~
- [x] definition now don't export by default. should have rollup export it by default
- [x] rename definition export. instead of `badgeDefinition` to just `badge`
- [x] don't export anything from base class to be exposed outside the library (like the actual Badge class)
- [x] remove https://github.com/Vonage/vivid-3/blob/8799fee84fdf3291180dd840e881f1c287eaa186/libs/components/src/shared/design-system/index.ts#L4-L5
- [x] remove https://github.com/Vonage/vivid-3/blob/8799fee84fdf3291180dd840e881f1c287eaa186/libs/components/src/shared/design-system/index.ts#L12
- [x] document new feature
- [x] allow (and document) the following interface

```js
import { register } from '@vonage/vivid';
import { badge, button, ... } from '@vonage/vivid';

register('vvd', badge, button, ...);
```

<hr>

~~an approach simpler to manage will revert back to using side effect imports. instead of `import.meta.url` we expose a setter for the prefix to override globally, prior to components import.~~

~~in a react app this is ordered by calling the setter from `index.js`~~

![image](https://user-images.githubusercontent.com/15140652/205988208-3553381e-b857-412f-8388-e145bbf7cb59.png)

~~and `import()` of custom element registration from react components~~
~~dynamic import is required for the prefix override call to kick in before registration fires~~

![image](https://user-images.githubusercontent.com/15140652/205989532-603e8d51-8b4b-485a-91a8-6ee1d9e331fa.png)

~~no significant difference shown in bundled assets~~

2022-12-07 19:03 UTC, YonatanKra requested changes
Tests? ;)

2022-12-13 13:54 UTC, YonatanKra requested changes
The component generation template should be updated. Let me make my attempt at it.

2022-12-13 13:54 UTC, YonatanKra commented on libs/components/src/shared/design-system/index.spec.ts
> +describe('design system', () => {
![image](https://user-images.githubusercontent.com/6459899/207347630-28909744-a2c8-40cd-ab19-900fece1be28.png)

2022-12-13 14:47 UTC, olaf-k commented on libs/components/src/shared/design-system/index.ts
> +export const registerFactorial = (...args: any[]) => (prefix = defaultPrefix) => designSystem.withPrefix(prefix).register(...args);
Unless I'm missing something, there is no need to destructure your arrays (creating copies) every time?
```suggestion
export const registerFactorial = (args: any[]) => (prefix = defaultPrefix) => designSystem.withPrefix(prefix).register(args);
```
and in every definition file, just call `export const registerSomething = registerFactorial(somethingElements);`

2022-12-13 15:16 UTC, YonatanKra commented on libs/components/README.md
> +one of the pros of this approach is that, although custom elements are registered under different namespaces, [npm packages version range handling](https://docs.npmjs.com/cli/v7/configuring-npm/packa
Yea. I don't understand what `versions saving` means.

2022-12-13 15:37 UTC, yinonov commented on libs/components/src/shared/design-system/index.ts
> +export const registerFactorial = (...args: any[]) => (prefix = defaultPrefix) => designSystem.withPrefix(prefix).register(...args);
It accepts parameters not array. Did u try?

2022-12-13 16:41 UTC, yinonov commented on libs/nx-vivid/src/generators/component/files/definition.ts__tmpl__
> +export const vivid<%= className %> = <%= className %>.compose<FoundationElementDefinition>({
class name here should be camel cased
```suggestion
export const <%= className %> = <%= className %>.compose<FoundationElementDefinition>({
```

2022-12-13 16:41 UTC, yinonov commented on libs/nx-vivid/src/generators/component/files/definition.ts__tmpl__
> +export const <%= camelCasedName %>Elements = [vivid<%= className %>];
here too
```suggestion
export const <%= camelCasedName %>Elements = [<%= className %>];
```

2022-12-13 16:46 UTC, yinonov commented on libs/components/README.md
> +one of the pros of this approach is that, although custom elements are registered under different namespaces, [npm packages version range handling](https://docs.npmjs.com/cli/v7/configuring-npm/packa
what's the correct term for when npm resolute to the same version even if 2 dependencies point to different versions. to avoid bloating the bindle size

2022-12-13 17:47 UTC, olaf-k commented on libs/components/src/shared/design-system/index.ts
> +export const registerFactorial = (...args: any[]) => (prefix = defaultPrefix) => designSystem.withPrefix(prefix).register(...args);
oops, you're right, suggestion updated.

2022-12-13 17:55 UTC, olaf-k commented on libs/components/README.md
> +one of the pros of this approach is that, although custom elements are registered under different namespaces, [npm packages version range handling](https://docs.npmjs.com/cli/v7/configuring-npm/packa
an error? 😁

(are you thinking of `npm dedupe`?)

2022-12-13 19:52 UTC, yinonov commented on libs/components/README.md
> +one of the pros of this approach is that, although custom elements are registered under different namespaces, [npm packages version range handling](https://docs.npmjs.com/cli/v7/configuring-npm/packa
Yes. I'll rephrase

2022-12-13 19:54 UTC, yinonov commented on libs/components/src/shared/design-system/index.ts
> +export const registerFactorial = (...args: any[]) => (prefix = defaultPrefix) => designSystem.withPrefix(prefix).register(...args);
The new suggestion will assign only the 1st argument to `args`

2022-12-14 06:45 UTC, YonatanKra submitted a review, later dismissed
LGTM

2022-12-14 08:59 UTC, olaf-k commented on libs/components/src/shared/design-system/index.ts
> +export const registerFactorial = (...args: any[]) => (prefix = defaultPrefix) => designSystem.withPrefix(prefix).register(...args);
in definition.ts files:
```js
export const widgetElements = [widget, ...iconElements, ...focusElements];
```
`widgetElements` is an **array**, that you pass to `registerFactorial`:
```js
export const registerWidget = registerFactorial(widgetElements);
```
thus, in the shared util file:
```js
export const registerFactorial = (args: any[]) => (prefix = defaultPrefix) => designSystem.withPrefix(prefix).register(...args);
```
`registerFactorial` is defined as a function accepting an **array**, which is later spread since register accepts 1..n arguments.

your original code defines `registerFactorial` as a function with 1..n arguments (using the spread operator), which forces you to spread each `widgetElements` when calling it instead of simply passing its reference as I suggest.

2022-12-14 10:38 UTC, yinonov commented on libs/components/src/shared/design-system/index.ts
> +export const registerFactorial = (...args: any[]) => (prefix = defaultPrefix) => designSystem.withPrefix(prefix).register(...args);
thanks! commited

2022-12-14 10:45 UTC, olaf-k submitted a review, later dismissed
👍

2022-12-14 10:47 UTC, YonatanKra submitted a review, later dismissed
LGTM. Exciting :)

2022-12-14 16:31 UTC, merged