fix(dialog): horizontal positioned icon
Vonage/vivid-3 pull request #891
Opened 2022-12-06 10:01 UTC by rachelbt

2022-12-06 19:24 UTC, yinonov requested changes

2022-12-06 19:24 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.scss
> +			row-gap: 24px;
can this be set to a derivative already? (as discussed this week regarding dense gaps)

2022-12-06 19:24 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.scss
> +			column-gap: 8px;
same here

2022-12-06 19:24 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +Use the `horizontal-icon` attribute to set the dialog's icon horizontal to dialog text
thinking more on the line of `icon-placement="top | inline"`. WDYT?

2022-12-06 19:24 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.template.ts
> +							<div class="headline-wrapper ">
```suggestion
							<div class="headline-wrapper">
```

2022-12-07 06:50 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.scss
> +			row-gap: 24px;
good thinking! will change

2022-12-07 06:51 UTC, rachelbt commented on libs/components/src/lib/dialog/README.md
> +Use the `horizontal-icon` attribute to set the dialog's icon horizontal to dialog text
thought about it, I guess its more correct to do this.

2022-12-07 07:29 UTC, rachelbt commented on libs/components/src/lib/dialog/README.md
> +Use the `horizontal-icon` attribute to set the dialog's icon horizontal to dialog text
changed

2022-12-08 04:44 UTC, yinonov requested changes

2022-12-08 04:44 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +- Type: `top` | `left`
Might be `right` in `rtl`. Resolve to logical?

2022-12-12 08:09 UTC, yinonov requested changes

2022-12-12 08:09 UTC, yinonov commented on libs/components/src/lib/dialog/README.md
> +Use the `icon-placement` attribute to set the dialog's icon horizontal to dialog text
not clear

2022-12-12 08:12 UTC, yinonov requested changes

2022-12-12 08:27 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.ts
> +type IconPlacement = 'top' | 'start';
how about:
```suggestion
type IconPlacement = 'block-start' | 'inline-start';
```
?

2022-12-12 10:24 UTC, rachelbt commented on change/@vonage-vivid-f7860a27-4ee9-4ca0-9f5c-f42d945e5647.json
> +  "comment": "dialog horizontal icon",
```suggestion
  "comment": "dialog icon placement side option added",
```

2022-12-12 10:43 UTC, yinonov approved these changes

2022-12-12 11:23 UTC, merged