feat(component): use affix pattern
Vonage/vivid-3 pull request #915
Opened 2022-12-14 19:33 UTC by rachelbt

2022-12-19 12:31 UTC, olaf-k requested changes

2022-12-19 12:31 UTC, olaf-k commented on libs/components/src/shared/patterns/affix.ts
> +			<style>${messageStyles}</style>
the style should probably be inlined or be made more generic rather than injecting `<styles>`.

2022-12-19 12:31 UTC, olaf-k commented on libs/components/src/shared/patterns/affix.scss
> +	line-height: var(#{$icon-line-height}, 1);
the class name is an optional parameter of the function returned by `affixIconTemplateFactory`, it may not always be `icon`

2022-12-20 08:23 UTC, rachelbt commented on libs/components/src/lib/avatar/avatar.spec.ts
> -			expect(avatarDefinition()).toBeInstanceOf(FoundationElementRegistry);
It may be removed by me when I merged from main...
@YonatanKra mind looking?

2022-12-20 08:27 UTC, rachelbt commented on libs/components/src/shared/patterns/affix.scss
> +	line-height: var(#{$icon-line-height}, 1);
oh - I missed the part that its not have to be icon class....
Do you think it should be line an inline style?
```<span style="line-height: var(--_icon-line-height, 1);" class="${className ? className : 'icon'}"><${iconTag} :name="${() => icon}"></${iconTag}></span>```

2022-12-20 09:21 UTC, olaf-k commented on libs/components/src/shared/patterns/affix.scss
> +	line-height: var(#{$icon-line-height}, 1);
you're the CSS wizard! 😁
I'm guessing there's a nicer way to do it but it would involve refactoring accordion-item and having the proper CSS injected when you use the affix helper, soooo... that's definitely faster.

2022-12-20 18:17 UTC, yinonov commented on libs/components/src/lib/avatar/avatar.spec.ts
>  		it('should be initialized as a vwc-avatar', async () => {
```suggestion
		it('should be initialized as a vwc-avatar', async () => {
			expect(avatarDefinition()).toBeInstanceOf(FoundationElementRegistry);
```

2022-12-21 07:45 UTC, rachelbt commented on libs/components/src/shared/patterns/affix.ts
> +			<style>${messageStyles}</style>
on second thought - this is what we do in the form-element pattern...

2022-12-21 07:48 UTC, rachelbt commented on libs/components/src/shared/patterns/affix.scss
> +	line-height: var(#{$icon-line-height}, 1);
it actually has nothing with css wizarding... its about the class names or options
@yinonov WDYS? should we add the stile inline?

2022-12-29 14:50 UTC, yinonov commented on libs/components/src/shared/patterns/affix.scss
> +	line-height: var(#{$icon-line-height}, 1);
inline style won't scale as it is limited when it comes to dynamic permutations

2023-01-02 09:55 UTC, YonatanKra commented on libs/components/src/lib/dialog/dialog.scss
> +				> * {
Oh?

2023-01-02 10:22 UTC, rachelbt commented on libs/components/src/shared/patterns/affix.scss
> +	line-height: var(#{$icon-line-height}, 1);
that means that anyone who is using the affix icon or the form pattern will have to remember adding the import of the css. right?

2023-01-02 10:39 UTC, YonatanKra submitted a review, later dismissed
LGTM

2023-01-03 08:34 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.scss
> +				> * {
by default its `vertical-align: sub; `but here we need top. Cant target `vwc-icon` so * is the option to use :)

2023-01-11 09:52 UTC, yinonov requested changes

2023-01-11 09:52 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.scss
> +			}
relate?

2023-01-11 09:52 UTC, yinonov commented on libs/components/src/lib/option/option.scss
> -	padding-block: 10px;
relates?

2023-01-11 10:11 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.scss
> +			}
yes :) 
without it the icon doesn't sit as it was.
It was aligned because the line-height was wrong. now that it is fixed - thin is needed :)

2023-01-11 10:13 UTC, rachelbt commented on libs/components/src/lib/option/option.scss
> -	padding-block: 10px;
In a way, yes.  I noticed that this made the option be more than 40px when only one line + icon in it.

2023-01-11 10:15 UTC, rachelbt commented on libs/components/src/shared/patterns/affix.scss
> +	line-height: var(#{$icon-line-height}, 1);
as was decided in a talk with @yinonov:
I've inserted the style as inline - until [this will be tended](https://github.com/Vonage/vivid-3/issues/950)

2023-01-11 11:05 UTC, rachelbt commented
In a second thought we decided to stop and think.
Not all places that use icon need the affix. Maybe we need an icon pattern?
More style is related to affix pattern.
Will be decided later.
Line height:1 will be added to the style of each component where is needed.

2023-01-11 11:26 UTC, olaf-k commented on libs/components/src/shared/patterns/affix.ts
> +			<!-- Using inline style until the affix + form elements will be created as scss mixin (vivid-3/issues/950)-->
this will be outputted in the markup. should be moved as a JS comment before the `return` line.

2023-03-05 12:46 UTC, rachelbt commented
was solved differently in here:
https://github.com/Vonage/vivid-3/pull/951

2023-03-05 12:46 UTC, closed without merging