fix(components): export foundation element registry
Vonage/vivid-3 pull request #916
Opened 2022-12-14 20:20 UTC by yinonov

- [ ] add tests to ensure elements definitions and design system reference are exported

2022-12-15 17:44 UTC, yinonov commented on change/@vonage-vivid-c57b0cba-e40d-4f8c-984c-b885be0c7b6c.json
> +  "comment": "rewrite component definition",
```suggestion
  "comment": "export component definition and design system",
```

2022-12-15 17:45 UTC, yinonov commented on change/@vonage-nx-vivid-987f3d5d-1355-4160-82c2-e29335e54634.json
> +  "comment": "align with public exports",
```suggestion
  "comment": "rewrite component definition",
```

2022-12-16 09:23 UTC, olaf-k requested changes

2022-12-16 09:23 UTC, olaf-k commented on libs/components/src/lib/number-field/definition.ts
> +export const numberFieldElement = [numberFieldDefinition(), ...buttonRegistries, ...dividerRegistries];
```suggestion
export const numberFieldRegistries = [numberFieldDefinition(), ...buttonRegistries, ...dividerRegistries];
```

2022-12-16 09:23 UTC, olaf-k commented on libs/components/src/lib/number-field/number-field.spec.ts
> +	 */
to be removed

2022-12-16 09:23 UTC, olaf-k commented on libs/components/src/lib/number-field/number-field.spec.ts
> +	 */
to be removed

2022-12-16 09:23 UTC, olaf-k commented on libs/components/src/lib/number-field/number-field.spec.ts
> +			 */
to be removed

2022-12-16 09:23 UTC, olaf-k commented on libs/components/src/lib/number-field/number-field.spec.ts
> +			 */
to be removed

2022-12-16 09:23 UTC, olaf-k commented on libs/components/src/shared/design-system/index.spec.ts
> +		const elementsDefintions = [badgeDefinition(), iconDefinition()];
all over this file: `s/elementsDefintions/elementsDefinitions`

2022-12-16 09:23 UTC, olaf-k commented on libs/nx-vivid/src/generators/component/files/__fileName__.spec.ts__tmpl__
> +			expect((<%= className %>)Definition()).toBeInstanceOf(FoundationElementRegistry);
needs `import { FoundationElementRegistry } from '@microsoft/fast-foundation';` then

2022-12-16 10:38 UTC, yinonov commented on libs/components/src/shared/design-system/index.spec.ts
> +		const elementsDefintions = [badgeDefinition(), iconDefinition()];
what?

2022-12-16 10:39 UTC, yinonov commented on libs/components/src/lib/number-field/number-field.spec.ts
> +			 */
```suggestion
```

2022-12-16 10:44 UTC, olaf-k commented on libs/components/src/shared/design-system/index.spec.ts
> +		const elementsDefintions = [badgeDefinition(), iconDefinition()];
small typo: `elementsDefintions` should be searched/replaced by `elementsDefinitions` (note the additional `i`)

2022-12-16 11:05 UTC, olaf-k approved these changes

2022-12-16 11:20 UTC, merged