feat(components): FAST-based Accordion
Vonage/vivid-3 pull request #930
Opened 2022-12-28 17:55 UTC by olaf-k

WIP, do not get to hung up on the code which is not finished (especially the CSS).

Breaking API changes, due to inheritance:
- Accordion: `multi` (boolean attr/prop) changed to `expand-mode` which can be either `multi` or `single` (default).
- AccordionItem: `open` (attr/prop) becomes `expanded`.
- AccordionItem: `headingLevel` (prop) becomes `headinglevel` (note the difference in capitalization), accepts values 1—6 (2—6 before) and defaults to 2 (3 before).

Behavior change:
- AccordionItem: has a `leading` attr/prop to set the indicator at the start (as in Figma).
- Accordion: when `expand-mode` is set to `single`, one item must remain opened at all times (i.e., you can't close all items, this is how the FAST component works).

Markup has changed, notably to get rid of the `<h>` tag and embed everything in a button for AccordionItem. This might change though. I kept `headinglevel` (reflected as `aria-level`) even though I don't get why it would be considered as it's in the shadow DOM.

Tests must be updated. This hasn't been done yet, either to annoy @YonatanKra or because I haven't had time to update them.

2022-12-28 20:30 UTC, yinonov commented
what about `open` property? changes to `expand`?

2022-12-28 20:41 UTC, yinonov commented
- heading level gets picked up by the a11y tree even when inside shadow root.
- it's pretty convenient to use an actual heading tag dynamically with the fast-element. so why not use it
- I think in terms of looks - icon, indicator, leading / trailing, accordion item has already been shaped according to requests so let's keep `No-Indicator`, `Meta`, `Icon`, `Icon-Trailing`

2022-12-29 10:59 UTC, olaf-k commented
> * heading level gets picked up by the a11y tree even when inside shadow root.
> * it's pretty convenient to use an actual heading tag dynamically with the fast-element. so why not use it

There might be a misunderstanding here: the heading level *still exists*, only it is assumed by the button's `aria-level`. It's just the unnecessary `<hx>` tag that went away. FAST does something similar (they put `aria-level` on a div, their markup is different).

> * I think in terms of looks - icon, indicator, leading / trailing, accordion item has already been shaped according to requests so let's keep `No-Indicator`, `Meta`, `Icon`, `Icon-Trailing`

I can remove `leading`, no worries, but isn't Figma also a result of users requests?

2022-12-29 14:37 UTC, olaf-k commented
Note to self:
- `aria-disabled` is not reset when `expand-mode` changes from `single` to `multi` (FAST bug?)

2023-01-12 09:26 UTC, rachelbt commented on libs/components/src/lib/accordion/accordion.scss
> -
why did you moved this to be as bottom border on the accordion-item?

2023-01-12 10:04 UTC, YonatanKra requested changes
Finished accordion-item.
More after lunch :)

2023-01-12 10:04 UTC, YonatanKra commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +		it('should set icon', async () => {
```suggestion
		it('should render icon when icon is set', async () => {
```

2023-01-12 10:04 UTC, YonatanKra commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +	/* eslint-disable @typescript-eslint/indent */
What? Why the eslint-disable?

2023-01-12 11:11 UTC, olaf-k commented
> Finished accordion-item. More after lunch :)

haven't read your comments yet but please note that I did not write the tests. I merely updated their syntax to deal with the new prop names (e.g., `open` > `expanded`) and assumed that they were already reviewed for the existing accordion.

2023-01-12 11:16 UTC, YonatanKra requested changes

2023-01-12 11:16 UTC, YonatanKra commented on libs/components/src/lib/accordion/accordion.spec.ts
> +			// expect(accordionItem1.expanded).toBeFalsy();
What is the FAST issue?

2023-01-12 11:16 UTC, YonatanKra commented on libs/components/src/lib/accordion/accordion.spec.ts
> +			expect(accordionItem2.expanded).toBeTruthy();
Here I must insist on the AAA pattern. It is pretty hard to follow what's happening at a glance.

2023-01-12 11:16 UTC, YonatanKra commented on libs/components/src/lib/accordion/accordion.spec.ts
> +			expect(accordionItem2.expanded).toBeFalsy();
Same AAA comment here as well.

2023-01-12 11:16 UTC, YonatanKra commented on libs/components/src/shared/patterns/affix.ts
> +		? html`<span class="${'icon'}"><${iconTag} :name="${() => icon}"></${iconTag}></span>`
![image](https://user-images.githubusercontent.com/6459899/212052861-d89038e5-ee7c-4249-b369-66a58b9a9ab3.png)

2023-01-12 13:21 UTC, YonatanKra commented
> > Finished accordion-item. More after lunch :)
> 
> haven't read your comments yet but please note that I did not write the tests. I merely updated their syntax to deal with the new prop names (e.g., `open` > `expanded`) and assumed that they were already reviewed for the existing accordion.

IMO, that's the problem with code that's not following standards.
Ppl copy-paste or learn not-so-good habits ;)

2023-01-23 10:24 UTC, olaf-k commented on libs/components/src/lib/accordion-item/README.md
> +- Default: `2`
yes, these values come directly from the FAST component and I thought the differences were small enough to warrant extra code to override them.
if you think it is important I can add that code though.

2023-01-23 10:26 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.scss
> +	border-bottom: 1px solid var(#{constants.$vvd-color-neutral-200});
reasons to move the border to the item instead of the parent:
1. simpler parent css
2. same as FAST
3. same as [our Figma](https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19073%3A77179&t=0wbeVDNWnTtxFTHy-0)
@AyalaBu opinion?

2023-01-23 10:26 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.scss
> -
[see my other comment](https://github.com/Vonage/vivid-3/pull/930#discussion_r1083876783)

2023-01-23 10:27 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.scss
> +h1, h2, h3, h4, h5, h6 {
👍 will do

2023-01-23 10:27 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.scss
> +button {
but that's just one element here though?

2023-01-23 10:28 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.scss
> +	:where(h1, h2, h3, h4, h5, h6):has(> button > .icon:nth-child(2)) + & {
it does work (see the doc's icon example part).
but you're right about support (even FF, such a pity). I'll find another way!

2023-01-23 10:29 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.scss
> -		color: var(#{constants.$vvd-color-neutral-600});
our Figma disagrees.
@AyalaBu should the accordion-item icons have a different color?

2023-01-23 13:16 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.template.ts
> +	/* eslint-disable @typescript-eslint/indent */
eslint struggles with the markup/code mix inside our template strings.
how it looks now:
![image](https://user-images.githubusercontent.com/1153034/214048612-ab1835e1-dc42-4c92-a8c4-51ab553afac5.png)
how it looks when eslint is satisfied:
![image](https://user-images.githubusercontent.com/1153034/214048728-a6813504-ca35-49bb-a5f7-a32806d8c763.png)

I believe linters should not impair readability, but if feel strongly in favor of eslint, I can reformat and remove the directive.

2023-01-23 13:36 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			element.shadowRoot?.querySelector('button')?.click();
made the code clearer

2023-01-23 13:37 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.spec.ts
> +			// expect(accordionItem1.expanded).toBeFalsy();
clarified

2023-01-23 13:39 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.spec.ts
> +			expect(accordionItem2.expanded).toBeTruthy();
just to reiterate: those tests were already approved, I just updated the API calls.

I also have no trouble reading them. I added comments to make it easier to parse quickly. I'm happy to commit any suggestion you have if that's not enough.

2023-01-23 13:39 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.spec.ts
> +			expect(accordionItem2.expanded).toBeFalsy();
same reply as above

2023-01-23 13:40 UTC, olaf-k commented on libs/components/src/shared/patterns/affix.ts
> +		? html`<span class="${'icon'}"><${iconTag} :name="${() => icon}"></${iconTag}></span>`
I actually removed a functionality I introduced myself 😁

2023-01-23 14:06 UTC, rachelbt commented on libs/components/src/lib/accordion-item/accordion-item.scss
> -		color: var(#{constants.$vvd-color-neutral-600});
the icon color change was part of design alignment:
[see this PR](https://github.com/Vonage/vivid-3/pull/802/files)

2023-01-23 17:03 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.scss
> +button {
I trust you!

2023-01-23 17:05 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.scss
> -		color: var(#{constants.$vvd-color-neutral-600});
did I forgot a conversation I was part of? maybe. MAYBE.

2023-01-24 06:54 UTC, YonatanKra commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(itemHeaderButton.querySelector(':nth-child(2)')?.classList).not.toContain('icon');
Caching the item would make this code much simpler.
`const headerButtonIconWrapper itemHeaderButton.querySelector(':nth-child(2)')`;
And use it in the 3 times it is used below.

2023-01-24 06:55 UTC, YonatanKra commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(itemHeaderButton.querySelector(':last-child > vwc-icon')?.getAttribute('name')).toBe('chevron-down-solid');
Same goes with this long query regarding caching it for later use and clarity.

2023-01-24 06:56 UTC, YonatanKra commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(element.shadowRoot?.querySelector(':first-child')?.tagName).toEqual('H2');
Long query that repeats itself. Should have its own variable

2023-01-24 06:59 UTC, YonatanKra commented on libs/components/src/lib/accordion/accordion.spec.ts
> +		it.skip('should only allow one accordion items open at a time', async () => {
Thing is, right now it has an API we expose with the bug.
So... we either document what we want and fix it, or we document how it works right now.
This is the current API (with the bug):
```
it('should allow only one accordion item expanded when set to "single"', async () => {
			element.expandmode = 'single';
			accordionItem1.expanded = true;

			accordionItem1.expanded = true;
			accordionItem2.dispatchEvent(new Event('change'));
			await elementUpdated(element);

			expect(accordionItem1.expanded).toBeFalsy();
			expect(accordionItem2.expanded).toBeTruthy();
		});
```
And, of course, add another test to show that just changing the `expand` prop works differently right now.

The other option would be to fix the bug on our end and when they fix it on their end, remove our fix.

2023-01-24 07:01 UTC, YonatanKra commented on libs/components/src/lib/accordion/accordion.spec.ts
> +			accordionItem2.expanded = true;
This can be simplified IMO:
```
		it('should allow expansions of multiple accordion items when set to "multi"', async () => {
			element.expandmode = 'multi';
			accordionItem1.expanded = true;

			accordionItem2.expanded = true;
			accordionItem2.dispatchEvent(new Event('change'));
			await elementUpdated(element);

			expect(accordionItem1.expanded).toBeTruthy();
			expect(accordionItem2.expanded).toBeTruthy();
		});
		```

2023-01-24 08:27 UTC, YonatanKra commented
Another general remark - this is not a refactor; it is a breaking change :)
Refactor is when you change the code without any change to the API.

2023-01-24 10:01 UTC, yinonov commented
> Another general remark - this is not a refactor; it is a breaking change :)
> 
> Refactor is when you change the code without any change to the API.

By convention any type can be a breaking change

https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-both--and-breaking-change-footer

2023-01-24 10:12 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(itemHeaderButton.querySelector(':nth-child(2)')?.classList).not.toContain('icon');
you can't do that since what we're testing here is that the icon is properly inserted in the DOM, making `:nth-child(2)` a different element after you set the prop.
I've rewritten the test to make that clearer though.

2023-01-24 10:12 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(itemHeaderButton.querySelector(':last-child > vwc-icon')?.getAttribute('name')).toBe('chevron-down-solid');
same as above: the element changes. made the code more explicit.

2023-01-24 10:12 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(element.shadowRoot?.querySelector(':first-child')?.tagName).toEqual('H2');
different DOM elements again

2023-01-24 10:13 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.spec.ts
> +		it.skip('should only allow one accordion items open at a time', async () => {
this is unnecessary throwaway work. the bug is known, documented here and awaiting fix (PR is on its way).

2023-01-24 10:17 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.spec.ts
> +			accordionItem2.expanded = true;
soooo, your simplified version is just going back to the original test that [you deemed not readable enough](https://github.com/Vonage/vivid-3/pull/930#discussion_r1067997389) (albeit without the initial `expect`s)
I've left it as is.

2023-01-24 10:17 UTC, olaf-k commented
> Another general remark - this is not a refactor; it is a breaking change :) Refactor is when you change the code without any change to the API.

you'll need to take it up to @yinonov 😁
![image](https://user-images.githubusercontent.com/1153034/214266212-b01753c5-fc9b-43b5-a9df-ae9e502f37d7.png)

2023-01-24 11:27 UTC, YonatanKra commented
> > Another general remark - this is not a refactor; it is a breaking change :)
> > Refactor is when you change the code without any change to the API.
> 
> By convention (if we were to align with conventional commits), any type can be a breaking change
> 
> https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-both--and-breaking-change-footer

@yinonov 

Let's clear out definitions: 
Refactoring is defined by a change in code that does not change its functionality. This change, by changing how the component works is by definition not a refactor. 

A breaking change means a change in the API. By changing the API (open => expanded) we exhibit a breaking change.

2023-01-24 12:38 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.spec.ts
> +			accordionItem2.expanded = true;
> Note that changing element.expandmode = 'multi';  to element.expandmode = 'single'; the test is still passing, hence the test itself is wrong.

the test is fine. the fact that the accordion allows multiple children to be open programmatically while in single mode is still the result of [the bug mentioned earlier](https://github.com/microsoft/fast/issues/6585). 

> The test I suggest fails on single and passes on multi :)

it shouldn't.

2023-01-26 13:22 UTC, YonatanKra submitted a review, later dismissed

2023-01-26 14:46 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(indicatorExistsOnInit).toBeDefined();
`indicatorExistsOnInit` is a boolean, it is *always* defined.

2023-01-26 14:46 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(isClosedAfterSecondClick).toBeFalsy();
how this is supposed to be improve readability over
```
	itemHeaderButton.click();
	expect(element.expanded).toBeTruthy();
	itemHeaderButton.click();
	expect(element.expanded).toBeFalsy();
```
is beyond me.

2023-01-26 14:46 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.spec.ts
> +	}
how is
```
toggleAccordionItem(someItem);
```
preferable to
```
someItem.expandbutton.click();
```
?

2023-01-26 14:46 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.spec.ts
> +	it('should set aria-disabled on active item', async function () {
```suggestion
	it('should set aria-disabled on active item in single mode', async function () {
		element.expandmode = 'single';
```

2023-01-26 14:46 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.spec.ts
> +			return [anotherAccordionItem1, anotherAccordionItem2];
no need to return an array if you're only using the second item

2023-01-26 18:45 UTC, yinonov requested changes

2023-01-26 18:45 UTC, yinonov commented on change/@vonage-vivid-6061f3db-b114-4a23-a457-642b1fec705e.json
> +{
no longer required

2023-01-26 19:24 UTC, YonatanKra commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(indicatorExistsOnInit).toBeDefined();
Nice catch. I left the old test :)
Thanks!

2023-01-26 19:35 UTC, YonatanKra commented on libs/components/src/lib/accordion/accordion.spec.ts
> +	}
It is an implementation detail that can change if we change `accordion-item`'s API at any point in time.
As a reader, you are not interested in the implementation detail, but in the flow itself. If you really want, see what the function is doing.

2023-01-26 19:45 UTC, YonatanKra commented on libs/components/src/lib/accordion-item/accordion-item.spec.ts
> +			expect(isClosedAfterSecondClick).toBeFalsy();
A matter of standardization. 

`Arrange, Act, Assert`

But a very good point. I pointed it out in my article - this `it` was testing two things (expand + close). I split them into two `it`s.

2023-01-26 20:09 UTC, yinonov requested changes

2023-01-26 20:09 UTC, yinonov commented on libs/components/src/lib/accordion-item/accordion-item.scss
> +	border-bottom: 1px solid var(#{constants.$vvd-color-neutral-200});
implementation struggles shouldn't not affect style preference, of which `only-of-type` shouldn't set a border to itself.
How complicated is it to set such style from the accordion container?

2023-01-27 11:03 UTC, olaf-k commented on libs/components/src/lib/accordion-item/accordion-item.scss
> +	border-bottom: 1px solid var(#{constants.$vvd-color-neutral-200});
> implementation struggles shouldn't not affect style preference, of which `only-of-type` shouldn't set a border to itself. How complicated is it to set such style from the accordion container?

it is not a struggle nor is it complicated. it is a matter of consistency: with our Figma file, with FAST, and with the code (as a pure container, the parent does not style anything).

2023-01-27 11:13 UTC, olaf-k reviewed
> implementation struggles shouldn't not affect style preference, of which only-of-type shouldn't set a border to itself.
How complicated is it to set such style from the accordion container?

see [my points here](https://github.com/Vonage/vivid-3/pull/930#discussion_r1088833178).

what is the added value of putting back the border in the parent?

2023-01-27 11:20 UTC, olaf-k commented on libs/components/src/lib/accordion/accordion.spec.ts
> +	}
this does not improve readability.
details are important in tests and "toggle the item", because there are several ways of toggle said item, gives me less information than "click on the item's expand button".

2023-01-27 12:38 UTC, yinonov approved these changes

2023-01-27 12:41 UTC, merged