[dialog]: adding subtitle
Vonage/vivid-3 pull request #934
Opened 2023-01-05 08:28 UTC by rachelbt

2023-01-05 08:42 UTC, olaf-k commented on libs/components/src/lib/dialog/README.md
> +  subtitle="this is an example of the dialog with stooted buttons inside footer">
I'm guessing `slotted`?

2023-01-05 08:44 UTC, rachelbt commented on libs/components/src/lib/dialog/README.md
> +  subtitle="this is an example of the dialog with stooted buttons inside footer">
you caught me :) :)

2023-01-05 09:37 UTC, olaf-k commented on libs/components/src/lib/dialog/dialog.template.ts
> +								<div class="headline-text">
maybe wrap the `div` in a `when(x.headline || x.subtitle)` to skip its rendering when none of them are set

2023-01-05 10:34 UTC, rachelbt commented on libs/components/src/lib/dialog/ui.test.ts
> +test.only('should show the component', async ({ page }: { page: Page }) => {
:scream: shame on me!!

2023-01-08 10:48 UTC, yinonov requested changes

2023-01-08 10:48 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.scss
> +			column-gap: calc(#{size.$vvd-size-condensed} / 2);
doesn't scale
in default density it changes the value from 8 to 16
in `-1` density it changes 4 to 14

that's a wild card

2023-01-08 10:49 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.scss
> +	}
what's that?

2023-01-08 10:52 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.scss
> +			column-gap: calc(#{size.$vvd-size-condensed} / 2);
so no dividing but subtraction yes?

2023-01-08 10:52 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.scss
> +	}
style for the headline text wrapper that contains the headline + subtitle

2023-01-08 10:53 UTC, yinonov requested changes

2023-01-08 10:53 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.scss
> +	gap: 12px;
this raises a question whether it was authored by design. doesn't relate to this scope. can we extract?

2023-01-08 10:53 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.template.ts
> +								${when(x => x.headline || x.subtitle, headlineText())}
why not make them independent from 1 another? can't this be resolved with easily via css?

2023-01-08 10:54 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.template.ts
> +								${when(x => x.headline || x.subtitle, headlineText())}
they are independent - but if none of them is inserted by the consumer - no wrapper div is generated

2023-01-08 10:55 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.scss
> +	gap: 12px;
this is a fix - originally didn't give the right gap....

2023-01-08 11:09 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.template.ts
> +								${when(x => x.headline || x.subtitle, headlineText())}
how complicated would it be to concede the wrapper in favor of a grid?

2023-01-08 11:11 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.template.ts
> +								${when(x => x.headline || x.subtitle, headlineText())}
I considered it but there are too many options that flex is a much better and fluid one, even though we are "paying" with another wrapper

2023-01-08 11:12 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.scss
> +			column-gap: calc(#{size.$vvd-size-condensed} / 2);
subtraction scales with design unit. gap should still be researched later on for whether it should be fluid. but this is yet to be standardized

2023-01-08 11:15 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.scss
> +			column-gap: calc(#{size.$vvd-size-condensed} / 2);
so should I use definite unit (8px) or leave it as it is?

2023-01-10 11:36 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.template.ts
> +								${when(x => x.headline || x.subtitle, headlineText())}
@yinonov  - I changed the html structure of header, remover 2 wrappers, used `grid`

2023-01-10 15:06 UTC, yinonov approved these changes

2023-01-11 06:32 UTC, merged