feat(data-grid): port data grid component from fast
Vonage/vivid-3 pull request #947
Opened 2023-01-10 11:16 UTC by YonatanKra

2023-01-10 22:42 UTC, yinonov requested changes

2023-01-10 22:42 UTC, yinonov commented on apps/docs/_data/components.json
> +		"markdown": "./libs/components/src/lib/data-grid/README.md",
```suggestion
		"status": "alpha",
		"markdown": "./libs/components/src/lib/data-grid/README.md",
```

2023-01-11 22:03 UTC, yinonov requested changes

2023-01-11 22:03 UTC, yinonov commented on libs/components/src/lib/data-grid/README.md
> +```
is this the correct snippet? there's no `rowItemTemplate`

2023-01-11 22:03 UTC, yinonov commented on libs/components/src/lib/data-grid/README.md
> +```
correct snippet? there's no `cellItemTemplate`

2023-01-15 15:22 UTC, yinonov requested changes

2023-01-15 15:22 UTC, yinonov commented on libs/components/src/lib/data-grid/README.md
> +### noTabbing
why not simply `tabindex="-1"`?

2023-01-15 15:27 UTC, yinonov requested changes
I tend to start reviewing from reading spec from the readme representation. It's hard when the docs aren't clear. I can obviously try reading unit test instead but consumers will first try docs

2023-01-15 15:27 UTC, yinonov commented on libs/components/src/lib/data-grid/README.md
> +Use `generate-header"` for data gris deader
```suggestion
Use `generate-header"` for data grid deader
```

2023-01-15 15:27 UTC, yinonov commented on libs/components/src/lib/data-grid/README.md
> +# data-grid
documentation must be more elaborative, I can hardly understand what the members stand for

2023-01-15 15:27 UTC, yinonov commented on libs/components/src/lib/data-grid/README.md
> +The column definitions of the grid
which is?

2023-01-28 05:57 UTC, YonatanKra commented on libs/components/src/lib/data-grid/README.md
> +### noTabbing
It has a more complex behavior internally IMO.

2023-01-28 20:40 UTC, yinonov commented on libs/components/src/lib/data-grid/README.md
> +- Default: `default`
I know this comes from extending _**fast**_ but this is a very strange API. default it the fallback of set of available values. it should not by an option on its own

2023-01-28 21:10 UTC, yinonov commented
notice vonage/vivid#1371

2023-02-01 07:17 UTC, YonatanKra commented on libs/components/src/lib/data-grid/README.md
> +- Default: `default`
Default = show the header
Sticky = show a sticky header
none = do not show the header
Do you want to change the `default` value?

2023-02-01 09:23 UTC, yinonov approved these changes

2023-02-01 09:25 UTC, merged