docs(icon): add px to icon docs
Vonage/vivid-3 pull request #948
Opened 2023-01-10 12:44 UTC by rinaok

2023-01-10 13:12 UTC, olaf-k approved these changes
👍

2023-01-10 13:15 UTC, olaf-k commented on libs/components/src/lib/icon/README.md
> +<vwc-icon name="close-line" size="-6"></vwc-icon>16px
shouldn't the measurements be in `em`?

2023-01-10 13:17 UTC, olaf-k requested changes

2023-01-10 13:17 UTC, olaf-k commented on libs/components/src/lib/icon/README.md
> +<vwc-icon name="close-line" size="-6"></vwc-icon>16px
shouldn't the measurements be in `em`?

2023-01-10 13:26 UTC, rinaok commented on libs/components/src/lib/icon/README.md
> +<vwc-icon name="close-line" size="-6"></vwc-icon>16px
yes, it's just to help users to compare it with figma

2023-01-10 13:33 UTC, olaf-k commented on libs/components/src/lib/icon/README.md
> +<vwc-icon name="close-line" size="-6"></vwc-icon>16px
answering to myself: they are `px` indeed (so the README should be updated) but their actual size depend on the `--vvd-size-density` value.
![image](https://user-images.githubusercontent.com/1153034/211564965-c4f5d6cb-b4c1-43ca-8254-db403a8ee541.png)

2023-01-10 13:43 UTC, rachelbt commented on libs/components/src/lib/icon/README.md
> +<vwc-icon name="close-line" size="-6"></vwc-icon>16px
I think that there are 2 issues here:
1. under size we have `Default: '1em' (inherits font-size)` but I'm not sure that this is clear enough that this is set if theres not size member that is being added.
2.  our consumers are looking for an icon that is 24px width and do not know which `size` is it. @rinaok tried to solve that. but, @olaf-k you are right - if one changer the `vvd-size-density` than the px units are changing....

2023-01-10 13:52 UTC, olaf-k commented on libs/components/src/lib/icon/README.md
> +<vwc-icon name="close-line" size="-6"></vwc-icon>16px
> 1. under size we have `Default: '1em' (inherits font-size)` but I'm not sure that this is clear enough that this is set if theres not size member that is being added.
indeed. I first thought it was a mistake since `$vvd-size-normal` was not set at 1em, but had to look at the code to understand this was not the default.

2023-01-10 15:33 UTC, rinaok commented on libs/components/src/lib/icon/README.md
> +<vwc-icon name="close-line" size="-6"></vwc-icon>16px
@olaf-k @rachelbt Do you have any suggestions on how to help users understand the right size for their project? I find it very confusing.

2023-01-10 15:51 UTC, olaf-k commented on libs/components/src/lib/icon/README.md
> +<vwc-icon name="close-line" size="-6"></vwc-icon>16px
I'd change the README to read:

Use the `size` attribute/property to set the icon's size. Note that changing `--vvd-size-density` will affect the chosen size (the example below shows the size in `px` for the default `--vvd-size-density` value).

- Type: `-6` | `-5` | `-4` | `-3` | `-2` | `-1` | `0` | `1` | `2` | `3` | `4` | `5`
- Default: `undefined` (the icon dimensions will default to `1em`×`1em`)

2023-01-10 16:05 UTC, rinaok commented on libs/components/src/lib/icon/README.md
> +<vwc-icon name="close-line" size="-6"></vwc-icon>16px
updated

2023-01-10 16:18 UTC, olaf-k commented on libs/components/src/lib/icon/README.md
> +Note that changing `--vvd-size-density` will affect the chosen size (the example below shows the size in px for the its default value).
```suggestion
Note that changing `--vvd-size-density` will affect the chosen size (the example below shows the size in px for its default value).
```
(the joys of copy/pasting ;)

2023-01-10 22:40 UTC, yinonov requested changes

2023-01-10 22:40 UTC, yinonov commented on libs/components/src/lib/icon/README.md
> +<vwc-icon name="close-line" size="5"></vwc-icon>60px
what if we scale up / down? size units won't be correct

https://github.com/Vonage/vivid-3/blob/36329cba95612d974f0c03055a7cee0031fe002e/docs/design/design-tokens.md#L133-L140

2023-01-11 09:03 UTC, rinaok commented on libs/components/src/lib/icon/README.md
> +<vwc-icon name="close-line" size="5"></vwc-icon>60px
@yinonov See Olaf's comment

2023-01-11 10:52 UTC, olaf-k approved these changes

2023-01-11 12:34 UTC, merged