fix(note): no icon option
Vonage/vivid-3 pull request #949
Opened 2023-01-10 13:13 UTC by rachelbt

2023-01-10 14:21 UTC, yinonov requested changes

2023-01-10 14:21 UTC, yinonov commented on libs/components/src/lib/note/README.md
> +### No-icon
how about `icon="false | null | undefined"`?

2023-01-10 14:32 UTC, rachelbt commented on libs/components/src/lib/note/README.md
> +### No-icon
instead of a new member?

2023-01-11 11:56 UTC, rachelbt commented on change/@vonage-vivid-50cc6185-d6dd-4292-a82a-5530d8954408.json
> +  "comment": "note no-icon option",
```suggestion
  "comment": "remove default connotation based icon",
```

2023-01-11 13:59 UTC, YonatanKra commented on libs/components/src/lib/note/note.spec.ts
> +	});
![image](https://user-images.githubusercontent.com/6459899/211825019-39210471-bdba-4be5-beff-24b153072390.png)

2023-01-11 14:00 UTC, YonatanKra commented on libs/components/src/lib/note/note.spec.ts
> +	it('should not render icon when no icon member is set', async function () {
```suggestion
	it(`Should remove the icon when "no-icon" is set`, async function () {
```

2023-01-11 14:14 UTC, rachelbt commented on libs/components/src/lib/note/note.spec.ts
> +	});
mastering the  art of copy-paste from other components :)

2023-01-11 14:15 UTC, rachelbt commented on libs/components/src/lib/note/note.spec.ts
> +	it('should not render icon when no icon member is set', async function () {
no - there's no "no-icon" attribute.
If consumer do not add icon then there's no icon

2023-01-11 14:47 UTC, yinonov commented on libs/components/src/lib/note/note.ts
> +
```suggestion
```

2023-01-11 15:05 UTC, rachelbt commented on libs/components/src/lib/note/ui.test.ts
> +	page.setViewportSize({ width: 900, height: 840 });
```suggestion
	page.setViewportSize({ width: 900, height: 720 });
```

2023-01-11 15:32 UTC, yinonov submitted a review, later dismissed

2023-01-11 21:38 UTC, yinonov approved these changes

2023-01-12 07:19 UTC, yinonov approved these changes

2023-01-12 07:20 UTC, merged