chore(docs): add link to text input spec
Vonage/vivid-3 pull request #963
Opened 2023-01-17 15:12 UTC by YonatanKra

2023-01-17 15:38 UTC, rachelbt commented on libs/components/src/lib/text-field/README.md
> +While `text-field` follows [the W3C specifictation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text), note that the text field does not support `type="number"`. For this there is
While `text-field` follows [the W3C specifictation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text), note that the text field does not support `type="number"`. For this there is the `number-field` component.
```suggestion
While `text-field` follows [the W3C specifictation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text), note that the text field does not support `type="number"`. For this there is the [`number-field`](https://vivid.deno.dev/components/number-field) component.
```

2023-01-17 15:44 UTC, rachelbt submitted a review, later dismissed
LGTM

2023-01-17 17:28 UTC, yinonov requested changes

2023-01-17 17:28 UTC, yinonov commented on libs/components/src/lib/text-field/README.md
> +While `text-field` follows [the W3C specifictation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), these are valid types:
```suggestion
While `text-field` follows [the W3C specifictation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), the following are the only, formally, supported types:
```

2023-01-17 17:55 UTC, rinaok approved these changes

2023-01-17 19:39 UTC, yinonov requested changes

2023-01-18 07:43 UTC, yinonov approved these changes

2023-02-26 10:37 UTC, rinaok approved these changes

2023-02-28 12:52 UTC, merged