fix(documentation): getting started guide
Vonage/vivid-3 pull request #968
Opened 2023-01-20 06:42 UTC by rachelbt

2023-01-20 14:31 UTC, yinonov requested changes

2023-01-20 14:31 UTC, yinonov commented on docs/getting-statred/instalation.md
> +
Precede with intro, i.e. "This guide will help you get up and running with vivid"

2023-01-20 14:55 UTC, yinonov requested changes
Name of the file should be installation (it's instalation now)

2023-01-20 14:58 UTC, yinonov requested changes

2023-01-20 14:58 UTC, yinonov commented on docs/getting-statred/instalation.md
> +# Getting Started with Vivid@next
Name of the file is installation. Title says "_getting started with vivid@next_". It's not in full parity

2023-01-20 14:58 UTC, yinonov commented on docs/getting-statred/instalation.md
> +If you do not have a vivid@2.x installed - you can move on to **[install vivid-next]**(#install-vivid@next)
If the focus of this doc is installation (or getting started), then this should come later. 1st show the simplest usage

2023-01-20 15:00 UTC, yinonov commented on docs/getting-statred/instalation.md
> +```
```suggestion
```json
```

2023-01-20 15:00 UTC, yinonov commented on docs/getting-statred/instalation.md
> +```
```suggestion
```json
```

2023-01-22 07:47 UTC, rachelbt commented on docs/getting-statred/instalation.md
> +If you do not have a vivid@2.x installed - you can move on to **[install vivid-next]**(#install-vivid@next)
moved the pre-installation to the end

2023-01-23 07:43 UTC, yinonov requested changes

2023-01-23 07:43 UTC, yinonov commented on docs/getting-statred/getting-started.md
> +Step-by-step instructions for setting up vivid@next
```suggestion
A step-by-step instructions for getting up and running with vivid@next
```

2023-01-30 10:03 UTC, yinonov requested changes

2023-01-30 12:08 UTC, rachelbt commented on docs/getting-statred/getting-started.md
> +```
why?

2023-01-30 14:18 UTC, olaf-k reviewed
typo in the path
![image](https://user-images.githubusercontent.com/1153034/215502037-d646bc15-bfe1-4fb0-b3e5-8e9cffd58c2d.png)

2023-01-30 14:18 UTC, olaf-k commented on docs/getting-statred/getting-started.md
> +Add tokens to your app.
maybe "choose a *theme* to include" (or something) might make more sense to users who don't necessarily know what *tokens* are?

2023-01-30 14:35 UTC, olaf-k commented on docs/getting-statred/getting-started.md
> +@import "~@vonage/vivid/styles/tokens/theme-dark.css";
the path should be the one to `node_modules` as for SCSS.
the `~` is not standard, it's only a facility offered by some build tools.

2023-01-30 14:39 UTC, olaf-k commented on docs/getting-statred/getting-started.md
> +<link rel="stylesheet" href="/assets/styles/tokens/theme-light.css" media="all">
this should also target the `node_modules` folder

2023-01-30 14:43 UTC, olaf-k commented on docs/getting-statred/getting-started.md
> +	--vvd-typography-base-extended-bold: 600 ultra-condensed calc(var(--vvd-size-font-scale-base, 16px))/1.5 SpeziaCompleteVariableUpright;
maybe one or two simpler examples would make this part less intimidating? 😨

2023-01-30 14:46 UTC, olaf-k commented on docs/getting-statred/getting-started.md
> +You can also add it to any wrapping element if you would like to scope the styles to only a certain part of your application.
this part is so important that I would put it in its own section before the font explanation, WDYT?

2023-01-31 20:38 UTC, yinonov requested changes

2023-01-31 20:38 UTC, yinonov commented on docs/getting-statred/getting-started.md
> +This is a step-by-step instructions for setting up vivid@3 and up.
singular
```suggestion
This is a step-by-step instruction for setting up vivid@3 and up.
```

2023-01-31 21:10 UTC, yinonov requested changes

2023-01-31 21:10 UTC, yinonov commented on docs/getting-statred/getting-started.md
> +Go to this repo:
To obtain the _Spezia_ webfont kit, go to this repository:

2023-01-31 21:10 UTC, yinonov commented on docs/getting-statred/getting-started.md
> +Download and add the Spezia font to your app.
Download the font and add it to your project.

2023-01-31 21:10 UTC, yinonov commented on docs/getting-statred/getting-started.md
> +Make sure you add it in the correct path as in the css file (or change the path in the css below):
```suggestion
Make sure it is added to the correct path as indicated in the CSS file (or update the path in the CSS below).
```

2023-01-31 21:10 UTC, yinonov commented on docs/getting-statred/getting-started.md
> +Note - the`@import` needs to be declared at the top of the css file.
```suggestion
Note: The `@font-face` declaration must be placed at the top of the CSS file.
```

2023-01-31 21:10 UTC, yinonov commented on docs/getting-statred/getting-started.md
> +	--vvd-typography-base-extended-bold: 600 ultra-condensed calc(var(--vvd-size-font-scale-base, 16px))/1.5 SpeziaCompleteVariableUpright;
generally this could be avoided by simply referring to the https://github.com/vonage/spezia-webfont-kit repo. it's a generous initiative by vivid team which everyone are bound to by brand.
we don't want to be infamous for it

2023-02-01 10:24 UTC, rachelbt commented on docs/getting-statred/getting-started.md
> +	--vvd-typography-base-extended-bold: 600 ultra-condensed calc(var(--vvd-size-font-scale-base, 16px))/1.5 SpeziaCompleteVariableUpright;
So I'll leaving it as it is

2023-02-01 10:32 UTC, rachelbt commented on docs/getting-statred/getting-started.md
> +You can also add it to any wrapping element if you would like to scope the styles to only a certain part of your application.
I moved it after typography but gave it a heading to make it more noticeable

2023-02-15 09:48 UTC, yinonov commented
handled in #939

2023-02-15 09:48 UTC, closed without merging