fix(dialog): min inline size variable
Vonage/vivid-3 pull request #971
Opened 2023-01-22 09:20 UTC by rachelbt

2023-01-22 10:47 UTC, yinonov requested changes

2023-01-22 10:47 UTC, yinonov commented on change/@vonage-vivid-818f9abb-f12b-459f-8b72-8f5abd2be869.json
> +  "comment": "fix(dialog): min-inline-size variable",
```suggestion
  "comment": "fix(dialog): max-inline-size variable",
```

2023-01-23 06:45 UTC, rachelbt commented on change/@vonage-vivid-818f9abb-f12b-459f-8b72-8f5abd2be869.json
> +  "comment": "fix(dialog): min-inline-size variable",
```suggestion
  "comment": "fix(dialog): max-inline-size variable and dialog scream color",
```

2023-01-23 07:23 UTC, yinonov requested changes

2023-01-23 07:23 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.scss
> +		}
use https://github.com/Vonage/vivid-3/blob/main/libs/shared/src/lib/sass/mixins/scrim.scss#L9

2023-01-23 07:50 UTC, rachelbt commented on libs/components/src/lib/dialog/dialog.scss
> +		}
it doesn't work (tried...)
_It does not inherit from any element and is not inherited from. No restrictions are made on what properties apply to this pseudo-element either._

https://fullscreen.spec.whatwg.org/#::backdrop-pseudo-element

also in SO question:
https://stackoverflow.com/questions/58818299/css-variables-not-working-in-dialogbackdrop/63322762#63322762

I think the use of currentColor is working well here.
I know its kind of redundant code but for now there's no other option for setting the `::backdrop` color

2023-01-23 13:32 UTC, yinonov commented on libs/components/src/lib/dialog/dialog.scss
> +		}
I see. then change the mixin

2023-01-23 18:29 UTC, yinonov approved these changes

2023-01-24 06:43 UTC, merged