Feat(Tree): add component
Vonage/vivid-3 pull request #987
Opened 2023-01-29 16:53 UTC by rinaok

Tree View

A tree view widget presents a hierarchical list. Any item in the hierarchy may have child items, and items that have children may be expanded or collapsed to show or hide the children. For example, in a file system navigator that uses a tree view to display folders and files, an item representing a folder can be expanded to reveal the contents of the folder, which may be files, folders, or both.

Structure

The vwc-tree-view should have a role=”tree”.

The vwc-tree-view-item should have a role=”treeitem”.
Each parent node contains or owns an element with role group.

2023-02-07 14:00 UTC, rinaok commented
@AyalaBu Should the `selected` state look like in option:

![Screenshot 2023-02-07 at 15 59 05](https://user-images.githubusercontent.com/10883919/217265424-64c60267-eb88-4774-b6f9-77f2a757de3d.png)

Or like in tabs:
![Screenshot 2023-02-07 at 15 59 39](https://user-images.githubusercontent.com/10883919/217265569-6d0b6c4f-b23b-4799-b0d3-7528bde35be6.png)

In Fast it looks like this:
![Screenshot 2023-02-07 at 16 00 14](https://user-images.githubusercontent.com/10883919/217265698-38ab6d23-2375-4106-bc9e-d9dcef05e10b.png)

2023-02-07 14:01 UTC, rinaok commented
@AyalaBu How should the chevron look like?
I used `chevron-right-solid` and rotated it in 45 degrees.

2023-02-07 15:53 UTC, AyalaBu commented
@rinaok 
I looked into the issue you presented here,
and I saw a bit different behavior.

Based on these examples you can use the chevrons we have in store:
https://mui.com/material-ui/react-tree-view/

https://w3c.github.io/aria-practices/examples/treeview/treeview-navigation.html

But also there is this example:
https://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1a.html

I think in a situation like this you can use a "+" and a "-" icons.

2023-02-13 14:49 UTC, olaf-k commented on libs/components/src/lib/tree-item/tree-item.scss
> +	padding-inline: 60px;
I don't know if it's the wanted effect but this adds padding on both side, making the subitems shrink fast and not right-aligned.
![image](https://user-images.githubusercontent.com/1153034/218489897-1cd5df5a-9a79-4daa-97b5-715046ce28f7.png)

maybe `padding-inline-start` would be preferable?

2023-02-13 14:52 UTC, rinaok commented on libs/components/src/lib/tree-item/tree-item.scss
> +	padding-inline: 60px;
Yeah actually you are right, only the text should be with padding like this:

![Screenshot 2023-02-13 at 16 52 37](https://user-images.githubusercontent.com/10883919/218490967-c601dd83-cc08-4a81-acb5-aa8b89a8208a.png)

2023-02-13 14:53 UTC, rinaok commented on libs/components/src/lib/tree-item/tree-item.scss
> +	padding-inline: 60px;
@olaf-k Can you suggest  it as a change?

2023-02-13 15:13 UTC, olaf-k commented on libs/components/src/lib/tree-view/tree-view.scss
> +	position: relative;
is this needed?

2023-02-13 15:14 UTC, olaf-k commented on libs/components/src/lib/tree-item/tree-item.scss
> +	position: relative;
is this needed?

2023-02-13 15:33 UTC, olaf-k commented on libs/components/src/lib/tree-item/tree-item.scss
> +	padding-inline: 60px;
```suggestion
	padding-inline-start: 48px;
```
(I also updated the value to align the start of the child at the end of the parent's expand/collapse indicator)

2023-02-13 16:10 UTC, olaf-k requested changes

2023-02-13 16:10 UTC, olaf-k commented on libs/components/src/lib/tree-item/tree-item.spec.ts
> +		it('should not expand when keydown arrow left', async () => {
there's a bunch of keys for which it shouldn't expand 😁
it might be more interesting that it expands/collapses when the proper keys are used?

2023-02-13 16:13 UTC, olaf-k commented on libs/components/src/lib/tree-item/tree-item.spec.ts
> +		it('should not expand when keydown arrow left', async () => {
speaking of key navigation: using right/left apparently also navigates inside a tree item. is it the wanted behavior? I'm asking because the FAST component doesn't do that.

2023-02-13 16:14 UTC, rinaok commented on libs/components/src/lib/tree-item/tree-item.scss
> +	position: relative;
probably not

2023-02-13 16:37 UTC, rinaok commented on libs/components/src/lib/tree-item/tree-item.spec.ts
> +		it('should not expand when keydown arrow left', async () => {
@olaf-k You can expand and close the tree view by using right/left. but not navigate up and down. It's the same as in FAST

2023-02-13 16:39 UTC, rinaok commented on libs/components/src/lib/tree-item/tree-item.spec.ts
> +		it('should not expand when keydown arrow left', async () => {
@olaf-k removed the test. There is a test which tests it: "should expand when click"

2023-02-13 18:16 UTC, olaf-k commented on libs/components/src/lib/tree-item/tree-item.spec.ts
> +		it('should not expand when keydown arrow left', async () => {
> @olaf-k You can expand and close the tree view by using right/left. but not navigate up and down. It's the same as in FAST

it's not the same: you *can* navigate with the right/left keys. go to the [tree item slot example](https://vivid-n0yyyx55rys0.deno.dev/components/tree-item#item) and focus on Tree item 1. you can use the right key to open the first item then use it again to move down (and the left key to move up).

> @olaf-k removed the test. There is a test which tests it: "should expand when click". I tried to check if it expands with the keys but I failed to do it :(

Jest can be a pain sometimes. I'll see if I can help tomorrow.

2023-02-14 10:07 UTC, olaf-k commented on libs/components/src/lib/tree-view/tree-view.spec.ts
> +			</vwc-tree-view>`
```suggestion
			`<${COMPONENT_TAG}>
				<vwc-tree-item id="item1"></vwc-tree-item>
				<vwc-tree-item id="item2"></vwc-tree-item>
			</${COMPONENT_TAG}>`
```
maybe your test issues come from here? you were testing treeItem1/2 as `tree-item`s when they were `tree-view`s.

2023-02-14 10:17 UTC, olaf-k commented on libs/components/src/lib/tree-view/tree-view.spec.ts
> +			</vwc-tree-view>`
(you will also need to update the dependencies)

2023-02-14 12:06 UTC, olaf-k commented
@rinaok I took the liberty to fix your tests import and added an example of key testing in `tree-item.spec.ts`

2023-02-16 13:07 UTC, yinonov submitted a review, later dismissed

2023-02-16 15:40 UTC, yinonov approved these changes

2023-02-16 15:41 UTC, yinonov approved these changes

2023-02-19 09:12 UTC, merged