docs(badge): add changes
Vonage/vivid-3 pull request #99
Opened 2022-01-02 15:51 UTC by rinaok

2022-01-03 06:50 UTC, rachelbt submitted a review, later dismissed

2022-01-03 08:40 UTC, yinonov requested changes

2022-01-03 08:40 UTC, yinonov commented on src/components/badge/README.md
> +Badges can contain icons. Icons can be placed to the left or to the right side of the text.
```suggestion
Badge text can be affixed by a decorative icon, either by its start or end. 
```

2022-01-03 09:22 UTC, yinonov requested changes
We should rephrase the technical writing.
some examples can be seen [here](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/button/button.ts)

2022-01-04 07:46 UTC, yinonov approved these changes

2022-01-04 07:46 UTC, yinonov commented
simplified the type category

2022-01-04 08:27 UTC, merged